### ISSUE TITLE
[X_Objecttype] wordt [X_Objecttypegroep]  op basis van "HoofdobjecttypeID"

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#10]
In de tabel X_Objecttypegroepen staat de kolom, "HoofdobjecttypeID". Waar dit van toepassing is, wordt de groep vervangen door de corresponderende record uit 'X_Objecttype'.

Zodoende hoeven we niet de single name aan te passen. De record 'Informatiemodel' wordt verder wel opgenomen als klasse. Want de onderliggende klassen (die niet samenvallen met een objecttypegroep nemen we gewoon op. 'Hulpobjecten' blijft ook over (die we dan wel gewoon als Class aanmaken)

**Comment by redmer** [comment]
Beantwoord in #7
