### ISSUE TITLE
Ongebruikte prefixdefinities in eind-TTL

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#100]
https://github.com/Stichting-CROW/imbor/blob/8db0a7c957a3c519b12cdbe4b6f0125b12e530dd/data/transformaties/000%20Namespaces.ttl#L22

**Comment by RiX012** [comment]
Niet gebruikt:
adms
gwsw
nen3610
imgeo
dc

ook nog graph. Maar die heb ik even laten staan omdat dit nog handig kan worden...
