### ISSUE TITLE
Bij Boom type Boomstam toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1000]
Bij Boom type Boomstam toevoegen

**Comment by WisseDQ** [comment]
Wat wordt hier bedoelt met een boomstam? Is dat een stobbe?

**Comment by wjtmollema** [comment]
**Verwerking**
Het type 'Staand dood hout' is toegevoegd als type van Boom. De term 'Boomstam' is reeds in gebruik voor een objecttype.  

**Motivatie**
'Staand dood hout' is een term die een Boom aanduidt die op een hogere hoogte is geveld dan een Stobbe en voor ecologische doeleinden in de openbare ruimte is achtergebleven.
