### ISSUE TITLE
Luchthoogte toevoegen bij de klasse Holle leiding

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1001]
Luchthoogte als attribuut bij alle Holle leidingen:. Dit is de afstand tussen het vloeistofpeil en de BOB onder van de leiding. Dit gegeven wordt geregistreerd om te bepalen of leidingen ‘verdronken’ zijn. Het kan zijn dat je dit ziet als dynamisch gegeven, maar het komt ook niet voor in GWSW.

**Comment by MarinusVonhof** [comment]
Dit aanpassingsvoorstel is bij RIONED geregistreerd onder nr 1239.
Op 2 november 2023 volgt beoordeling door de werkgroep GWSW-Basis en daarna volgt publicatie van de uitslag op https://data.gwsw.nl/ .
