### ISSUE TITLE
Bij Rioolput type regelput toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1002]
Rioolput: type: Regelput. Een specifiek soort put die in relatie tot verbonden onderdelen in het stelsel het waterniveau regelt.

**Comment by wjtmollema** [comment]
Volgens RIONED zijn er twee soorten Regelput: `Stuwput` en `Overstortput`, beiden zijn aanwezig in IMBOR 2022. https://www.riool.net/regelput

**Comment by wjtmollema** [comment]
@RiX012 Zoals ik het zie hoort `Regelput` dus niet toegevoegd te worden omdat `Stuwput` en `Overstortput` al opgenomen zijn; hierdoor kan de issue gesloten worden.
