### ISSUE TITLE
Beschoeiing kunststof en kunststof schotten en ontbreken verankering

### ISSUE THREAD

**Issue by RobKoningDenW** [Stichting-CROW/imbor#1003]
Een collega van mij heeft problemen met waar zaken onder te plaatsen.
Kunt u me helpen met onderstaande vragen?

Ik loop tegen de volgende problemen aan bij de IMBOR 2022:

Beschoeiing:
Probleem: Een kunststof schot (ROWat of KLP) past niet in de definities van verschijningsvormen:

afbeelding

Betuining: Een houten omheining van een oeverzijde om het onderwatertalud te beschermen (dus geen kunststof).
Het zijn geen matten, palen of planken
Wiepenbeschoeiing: Een beschoeiing die gemaakt is van bundels samengebonden takken

Kortom, een kunststof schot past hier niet in. 

Verankering

Bij ‘Damwand’ ontbreekt ‘type verankering’, terwijl dit bij Beschoeiing wel aanwezig is. 

afbeelding 2

afbeelding 3

Derhalve loop ik tegen wat complicaties op bij het conversie-proces.
![Melding 00105626 - bijlage 1](https://user-images.githubusercontent.com/112395633/187195154-3e8fc9ea-bfd5-4e2f-83f0-580cdfa073c9.png)
![Melding 00105626 - bijlage 2](https://user-images.githubusercontent.com/112395633/187195178-ae90d29e-c11d-4c34-b840-53ec83087a42.png)
![Melding 00105626 - bijlage 3](https://user-images.githubusercontent.com/112395633/187195190-960d48a4-a1b0-4be3-9dbb-8ce2a871f956.png)

**Comment by RiX012** [comment]
Dank voor uw vraag. 

Wat betreft het Kunststof schot. Dit is is op te lossen om het Type Plankenbeschouiing te gebruiken, met het materiaal Kunststof.

Wat betreft de verankering. Voor de volgende versie kunnen we typeverankering toevoegen als attribuut van het objecttype Damwand.

**Comment by wjtmollema** [comment]
**Verwerking**
Het attribuut 'type verankering' is toegevoegd aan de klasse 'Damwand.' Het nieuwe enumeratietype 'DamwandTypeVerankering' bevat dezelfde domeinwaarden als 'BeschoeiingTypeVerankering.'

**Motivatie**
Het attribuut is een waardevolle toevoeging bij de klasse 'Damwand.' Deze melding is tevens ontvangen in de gemeenten Deventer en Dijk en Waard.
