### ISSUE TITLE
Bij informatiebord zijn type en type gedetailleerd niet zichtbaar in de database

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1004]
Bij informatiebord zijn type en type gedetailleerd niet zichtbaar in de database

**Comment by wjtmollema** [comment]
**Verwerking**
Dit betreft een fout in de tabel imborKern_EnumeratiesDomeinwaarden. De bovenliggende waarde voor alle domeinwaarden van 'InformatiebordType' zijn aangepast van Informatieverkeersbord naar van 'Informatieverkeersbord' naar 'Informatiebord' in de tabel imborKern_EnumeratiesDomeinwaarden.

**Motivatie**
De aard van de wijziging is een correctie van een fout die aanwezig was in de publicatieversie.
