### ISSUE TITLE
Bij informatieobject Monument-informatie is het ja/nee veld Monument overbodig

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1005]
*Bij informatieobject Monument-informatie is het ja/nee veld Monument overbodig

**Comment by wjtmollema** [comment]
**Verwerking**
Het attribuut 'monument' is komen te vervallen als attribuut bij de klasse 'Monument-informatie' en derhalve als IMBOR-attribuut.

**Motivatie**
Het toepassen van het informatieobject 'Monument-informatie' maakt het gebruik van 'monument' redundant.
