### ISSUE TITLE
Bij informatieobject Monument-informatie het attribuut startdatum toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1006]
Bij informatieobject Monument-informatie het attribuut startdatum toevoegen

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Kijkend naar de data-indeling van het Rijksmonumentenregister, beschouw bijvoorbeeld [deze](https://monumentenregister.cultureelerfgoed.nl/monumenten/1) registergegevens van een monumentaal woonhuis, wordt er niet gesproken over `startdatum` maar over `Inschrijving register`. Aangezien `startdatum` als attribuut nog niet tot IMBOR 2022 behoort en het semantisch gezien een generieke term is, is het voorstel om `datum inschrijving register`, `inschrijving register` of `datum monumentenregister` op te nemen bij `Monument-informatie.`

Zo wordt namelijk voorkomen wat het geval is voor `registratiedatum`: een attribuut dat aangeduid wordt door een zeer algemene term, maar dankzij het selectieve behoren tot de klasse `Soortnaam groenobject` een specifieke definitie heeft gekregen: "Datum waarop het objecttype geregistreerd wordt of een soortnaam toegevoegd wordt aan de lijst van soortnamen." Ook hier kan een wijziging worden voorgesteld:
- Aanpassen van de term `registratiedatum` naar `datum registratie soortnaam`;
- Aanpassen van de definitie naar: "Datum waarop een soortnaam toegevoegd wordt aan de lijst van soortnamen."

**Comment by wjtmollema** [comment]
Daar ben ik het mee eens. Ik stel voor deze issue te sluiten en `registratiedatum` op te nemen in #1075 . Iets als `datum monumentenregister` heeft wel een andere betekenis dan `tijdstipRegistratie`.

**Comment by RiX012** [comment]
Ok goed idee. Zodra je `registratiedatum` hebt opgenomen kan deze gesloten worden.
