### ISSUE TITLE
Hilversum: bij uithouder attribuut diameter toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1007]
Hilversum: bij uithouder attribuut diameter toevoegen

**Comment by wjtmollema** [comment]
**Verwerking**
Het attribuut 'diameter' is toegevoegd aan de klasse 'Uithouder' met als eenheid mm.

**Motivatie**
Uithouders hebben een diameter die van belang is om te registreren. De gemeente Hilversum is hiervan een praktijkvoorbeeld.
