### ISSUE TITLE
Hilversum: Ombouw van een ondergrondse kast als objecttype toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1008]
Ombouw van een ondergrondse kast als objecttype toevoegen

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- Het toevoegen van een `ObjectType` `Kastombouw` als `subKlasseVan` `Bouwwerk`. 
- Het toevoegen van het attribuut `boven- of ondergronds` aan `Kastombouw`.
- Het toevoegen van het attribuut `zichtbaar` (gelijk een `subKlasseVan` `Scheiding`)  of `bovengronds zichtbaar` (gelijk de klasse `Put`).
