### ISSUE TITLE
Hilversum: haaientand als synoniem toevoegen bij type van een wegmarkering

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1009]
Hilversum: haaientand als synoniem toevoegen bij type van een wegmarkering

**Comment by wjtmollema** [comment]
**Verwerking**
In de tabel imborVoc_Termen heeft de term ‘Driehoeksmarkeringen’ het synoniem ‘Haaientanden’ gekregen.

**Motivatie**
'Driehoeksmarkeringen' is een type gedetailleerd van 'Wegmarkering' met als bovenliggende waarde 'Dwarsmarkering.' 'Haaientanden' is een term die in het dagelijks taalgebruik wordt aangewend om het voorkomen van dit type gedetailleerd aan te duiden.
