### ISSUE TITLE
Versiereferentie ook voor vastewaardelijsten en groeperingen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#101]
https://github.com/Stichting-CROW/imbor/blob/a2e22bafd2bb3e48491aa6cdabc417f81c3a81bf/data/transformaties/930%20Versieinformatie.rq#L48

alles met `imbor/def/`

**Comment by RiX012** [comment]
@redmer Laat me weten als je deze definitieve lijst hebt. Want volgens mij staat dit als enige nog in de weg voor publicatie
