### ISSUE TITLE
Eigenaar kent geen waarde Ministerie; Eigenaar gedetailleerd kent wel waarden Ministerie van ... etc.

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1010]
Attributen Beheerder en Beheerder gedetailleerd aan de ene kant en Eigenaar en Eigenaar gedetailleerd lijken veel op elkaar.
Dat er verschillen zijn is natuurlijk mogelijk.

Wat ik opmerkelijk vind is dit;
- Beheerder heeft o.a. domeinwaarde Ministerie
- Beheerder gedetailleerd heeft een viertal domeinwaarden Ministerie van ...
- er is een relatie tussen de waarde Ministerie en Ministerie van ... tussen beide attributen

- Eigenaar kent geen domeinwaarde Ministerie (kan ik inkomen, als een ministerie nooit eigenaar is)
- Maar waarom zijn er dan wel domeinwaarden Ministerie van ... te vinden in Eigenaar gedetailleerd?

Ofwel laat die ministerie-domeinwaarden weg uit Eigenaar gedetailleerd, ofwel voeg Ministerie toe aan Eigenaar. Zoals het nu is is het verwarrend.

**Comment by wjtmollema** [comment]
**Verwerking**
De term ‘Ministerie’ is toegevoegd als domeinwaarde binnen het enumeratietype ‘BeheerdObjectEigenaar’ in imborKern_EnumeratiesDomeinwaarden.

**Motivatie**
De melder wijst terecht op de inconsistentie tussen 'BeheerdObjectEigenaar’ en 'BeheerdObjectBeheerder’ wat betreft de domeinwaarde 'Ministerie.' De inconsistentie is bij deze gerectificeerd.
