### ISSUE TITLE
Vraag: relatie tussen objecttype Wijk en attribuut wijknaam

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1011]
Vraag/onduidelijkheid.
Is er een relatie beschreven in het imbor 2022 model tussen attribuut wijknaam en objecttype Wijk?
Zo ja, uit welk attribuut bij objecttype Wijk hoort dan de wijknaam vandaan te komen?
Zelfde geldt eigenlijk ook voor allerlei van dit soort objecten, bijv. Buurt, Provincie, etc.

**Comment by RiX012** [comment]
Dit is een discutabel punt. Er is momenteel geen expliciete relatie. Alleen soms wordt er gesteld dat deze 'Waarde automatische gegenereerd' zou kunnen worden. We reserveren in het aankomende softwareleveranciers overleg tijd om dit te bespreken.

**Comment by RiX012** [comment]
@wjtmollema ik denk dat deze issue gemergd kan worden met #1101, toch?

**Comment by wjtmollema** [comment]
Ja dat klopt helemaal. Ik stel voor om deze issue te sluiten. De melder opteert in die issue ook al voor een bepaalde oplossing.

**Comment by wjtmollema** [comment]
Er wordt om toestemming verzocht deze issue te sluiten.

**Comment by RiX012** [comment]
Wordt verder behandeld in #1101
