### ISSUE TITLE
Semantische relatie 'heeft deel' tussen bijv. Asfaltverharding en specifiek Wegmarkering zou 0-N moeten zijn

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1012]
Semantische relatie 'heeft deel' tussen Asfaltverharding, Band, etc. en Wegmarkering is nu 0-1, maar zou 0-N moeten zijn.
Attributen type, type gedetailleerd etc. geven duidelijk weer dat het om één specifiek stukje wegmarkering gaat. En dus zou je meerdere wegmarkeringen kwijt moeten kunnen op één Asfaltverharding.

**Comment by RiX012** [comment]
Goed punt, nemen we mee

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- Wijzigen `Asfaltverharding :: heeftDeel :: Wegmarkering` van `0 op 1 relatie` naar `0 op N relatie`;
- Aanpassen van `Asfaltverharding :: heeftDeel :: Armatuur` naar `Asfaltverharding :: heeftDeel :: Actieve wegmarkering` en van `0 op 1 relatie` naar `0 op N relatie`.
