### ISSUE TITLE
Dubbeling in functies: "transport van oppervlaktewater" versus "transporteren van oppervlaktewater"

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1013]
Deze twee functies zijn in feite hetzelfde er kan er een uit.

**Comment by wjtmollema** [comment]
**Verwerking**
De term 'Transporteren van oppervlaktewater' is verwijderd. De term 'Transport van oppervlaktewater' is ontleend aan GWSW en blijft gehandhaafd.

**Motivatie**
Melder wijst terecht op de aanwezigheid van een overbodige functie. Derhalve is de overbodige functie komen te vervallen.
