### ISSUE TITLE
Informatieobject Oplever-informatie heeft geen relaties

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#1014]
**Beschrijf de bug**
In de versie van 2020 van IMBOR zag je de attributen van de klasse aanschaf-informatie bij allerlei objecten voorkomen. 
Nu is het informatieobject oplever-informatie nergens aan gelinked deze heeft dus geen sematische relaties.
Is dat bewust zo?

**Om te reproduceren**
Stappen om te reproduceren.
1. Ga naar
2. Klik op

**Je verwachtte**
Een beknopte, heldere beschrijving van wat je verwachtte dat zou gebeuren.

**Versie of uitgave van IMBOR**
- Versie: 2022.01

**Meer context**
Als je nog meer context kwijt wil.

**Comment by RiX012** [comment]
Aanschaf-informatie is een `InformatieObject` welke met de relatie `isBeschrevenDoor` is vastgelegd voor de abstracte klasse `Constructie` alle directe en indirecte subklassen daarvan krijgen dus de relatie naar Aanschaf-informatie mee. 
Deze vorm van overerving is nog niet verwerkt in de ontologie verkenner van IMBOR op docs.crow.nl/onto-verkenner/imbor. Maar wel reeds zichtbaar in de Access database

**Comment by WisseDQ** [comment]
Oke maar de attributen van de aanschafinformatie komen niet naar voren als je het objecttype bekijkt dat onder constructie valt bijvoorbeeld: https://docs.crow.nl/onto-verkenner/imbor/#/view?uri=https%3A%2F%2Fdata.crow.nl%2Fimbor%2Fdef%2F28f47317-7dd0-4210-9165-e1ef902ae66d

Of interpreteer ik dat verkeerd?

**Comment by RiX012** [comment]
De attributen van aanschafinformatie komen bij het informatieobject aanschafinformatie voor. En het informatieobject aanschafinformatie ligt met een semantische relatie aan constructie (en alles daaronder).

De relatie ligt dus volgt `Objecttype` `isBeschrevenDoor` `InformatieObject` `heeftAttribuut` `Attribuut`

**Comment by WisseDQ** [comment]
@RiX012 Een fout gemaakt ik de melding over welk informatieobject het gaat. 
Ik bedoelde hier eigenlijk Oplever-informatie.

**Comment by RiX012** [comment]
> @RiX012 Een fout gemaakt ik de melding over welk informatieobject het gaat. Ik bedoelde hier eigenlijk Oplever-informatie.

Ahhh ja daar heb je een punt @JochemMollema, dit lijkt inderdaad een inconsistentie te zijn?

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Het toevoegen van relaties voor `Oplever-informatie` voor die `ObjectTypen` die ook binnen de relatiescope van `Installatie-informatie` en `Aanschaf-informatie` vallen. Oftewel: voor de leden van de klasse `ReëelObject`.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
