### ISSUE TITLE
Drietal attributen met vaste domeinwaardenlijst hebben geen domeinwaarden

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1017]
Drie attributen zijn gelinkt aan alleen objecttype 37 Boom:
- 520	"boomhoogteklasse eindbeeld"
- 521	"kroondiameterklasse eindbeeld"
- 1033	"opkroonhoogteklasse beoogd"

Alle drie zijn het enumeraties, d.w.z. ze hebben vaste domeinwaarden.
Echter, Ga je zoeken op welke domeinwaarden dit moeten zijn, dan komt er niets uit.
enumeratietypen 2438, 3890 en 3891 leveren niets op in imborkern_enumeratiesdomeinwaarden.

ofwel er moeten nieuwe domeinwaarden bedacht worden voor die atttributen, ofwel bestaande domeinwaarden gekoppeld worden aan de enumeratietypen horende bij die attributen.

**Comment by RiX012** [comment]
Dank voor het opmerken. Dit is inderdaad zo in de formulieren van Access. De domeinwaarden zijn er echter wel in de achterliggende tabellen volgens mij.
@JochemMollema Kun jij dit reproduceren?

**Comment by GreenpointAdviesPN** [comment]
Wij gebruiken de Access formulieren niet, maar de tabellen uit Access zelf. Dus kijk het even goed na inderdaad. Dank.

**Comment by wjtmollema** [comment]
**Verwerking**
In de tabel imborKern_EnumeratiesDomeinwaarden worden in het veld 'Enumeratietype' de combinaties van klasse, attribuut en enumeratietype uit imborKern_K_KlassenAttributen weergegeven. Doordat de attributen 'boomhoogteklasse eindbeeld,' 'kroondiameterklasse eindbeeld' en 'opkroonhoogteklasse beoogd' gebruik maakten van dezelfde enumeratietypes als hun tegenhangers 'boomhoogteklasse actueel,' 'kroondiameterklasse actueel' en 'opkroonhoogteklasse actueel' waren alleen de KlasseAttribuutID's van die laatste drie opgenomen. Dit leidt tot de volgende wijziging:

Enumeratielijst op basis van KlasseAtrribuutID toegevoegd in imborKern_EnumeratiesDomeinwaarden voor:
- opkroonhoogteklasse beoogd;
- kroondiameterklasse eindbeeld;
- boomhoogteklasse eindbeeld.

**Motivatie**
Melder wees terecht op een inconsistentie in de toewijzing van domeinwaarden aan attributen. Deze fout is gerectificeerd.
