### ISSUE TITLE
Bereikbaarheid en Bereikbaarheid gedetailleerd op attribuutniveau gekoppeld maar op domeinwaardeniveau niet

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1018]
Bereikbaarheid (attr 410) en Bereikbaarheid gedetailleerd (attr 333) zijn aan elkaar gekoppeld middels de "imborkern_attributen" tabel. Echter, in "imborkern_enumeratiesdomeinwaarden" is geen enkele domeinwaarde van Bereikbaarheid gedetailleerd gekoppeld aan een domeinwaarde van Bereikbaarheid.

Oplossing: ofwel de koppeling tussen de attributen verbreken, ofwel imborkern_enumeratiesdomeinwaarden bovenliggendewaarde aanvullen. Laatste heeft onze voorkeur.

**Comment by wjtmollema** [comment]
**Verwerking**
Als bovenliggende waarde in imborKern_EnumeratiesDomeinwaarden is 'Bereikbaarheid met beperkingen' toegevoegd bij de domeinwaarden van 'Bereikbaarheid-InformatieBereikbaarheidGedetailleerd.'

**Motivatie**
De melder wijst terecht op het onbenut laten van de koppeling van de waarden van de enumeratietypes 'Bereikbaarheid-informatieBereikbaarheid' en 'Bereikbaarheid-InformatieBereikbaarheidGedetailleerd.'
