### ISSUE TITLE
algemene sh:PropertyShape ook voor nta8035:QuanitityValue toepasselijk maken

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#102]
https://github.com/Stichting-CROW/imbor/blob/8db0a7c957a3c519b12cdbe4b6f0125b12e530dd/data/imbor.shapes.ttl#L195

nu alleen via `sh:path`, moet ook nog via `rdf:list`.

**Comment by RiX012** [comment]
@redmer hoever ben je hiermee?

**Comment by redmer** [comment]
Dit is klaar en geïmplementeerd in #112. Dat voegt een shape toe dat d.m.v. `sh:or` controleert of een `sh:PropertyShape` voldoet aan of het directe model (simpel) via `sh:path`, of het indirecte model (`nta8035:QuantityValue`) via `sh:path ( XXX rdf:value ) `.
