### ISSUE TITLE
Gemeente Haarlem: Toevoegen objecttype Vlaggenmastput

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1028]
**Melding**
De gemeente Haarlem registreert putten die als houder voor Vlaggenmasten fungeren. Het grootste deel van het jaar staat er echter geen Vlaggenmast in de put. 

**Verwerking**
- 'Vlaggenmastput' toegevoegd aan imborVoc_Termen.
- 'Vlaggenmastput' toegevoegd aan imborKern_Klassen en imborKern_Klassenindeling en imborKern_K_KlassenChildParent onder de klasse 'Straatmeubilair.'

**Motivatie**
De toevoeging van de gemeente Haarlem leidt tot een betere objecttypedekking voor IMBOR.

**Comment by RiX012** [comment]
Is het niet een `type` van `Put`?

**Comment by wjtmollema** [comment]
De term 'put' is hier van toepassing in de zin van 'een pijpvormige uitholling in een oppervlak,' maar niet als een onderdeel van de ondergrondse infrastructuur, wat de klasse Put wel impliceert. Het is een objecttype met een inrichtende rol en als zodanig zouden de attributen van de klasse Put hier onzinnig zijn, maar de attributen van Straatmeubilair zinnig.

**Comment by RiX012** [comment]
Fair enough! Helder!

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
