### ISSUE TITLE
Gemeente Utrecht: Registratie voltage bij klasse Kabel

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1038]
**Melding**
De gemeente Utrecht wil voltages registreren bij Elektriciteitskabels. Als zodanig is dat vanwege het ontbreken van dit attribuut onder de klasse 'Kabel' in IMBOR 2022 niet mogelijk.

**Verwerking**
'voltage' bij de klasse Kabel toegevoegd in de tabel imborKern_K_KlassenAttributen

**Motivatie**
Op een Kabel is in werkelijkheid een bepaald voltage van toepassing en IMBOR 2022 bevat reeds het attribuut 'voltage.' Als zodanig is de uitdrukkingskracht van IMBOR vergroot.

**Comment by RiX012** [comment]
Welke 'voltage' betreft het hier? Wat er op staat, het maximum? Piekspanning. Wordt dit in de definitie (en wellicht de label) helder?

**Comment by wjtmollema** [comment]
De definitie van het attribuut voltage is die zoals die in IMBOR 2022 gehanteerd wordt: "Spanning uitgedrukt in volt." Hierin wordt niet gesproken over piekspanning. 

In de praktijkvoorbeelden van Utrecht gaat het om de spanning die normaliter op de Elektriciteitskabel staat (zie ook de types van Voedingskabel: Laagspanningskabel [230-400V]; Middenspanningskabel [0,4-30 kV]; en Hoogspanningskabel [36-220 kV]). In het praktijkvoorbeeld van Haarlem (issue #1026) gaat het om een Container in het laagspanningsbereik.

**Comment by RiX012** [comment]
Ok. Als voldoende duidelijk is dat het hier gaat om het 'normale' voltage en een normale situatie lijkt het me prima. 
Maar er bekruipt me een gevoel dat het hier gaat om (op termijn) een registratie van een meer dynamisch gegeven

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
