### ISSUE TITLE
Gemeente Almelo: attribuut ‘model’ toevoegen aan klasse Put

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1043]
**Melding**
De gemeente Almelo verzoekt het toeschrijven van het attribuut 'model' aan de klasse Put voor het registreren van modelgegevens van bijv. Drainageputten.

**Verwerking**
In imborKern_K_KlassenAttributen is 'model' toegevoegd aan de klasse Put.

**Motivatie**
Een Put kan in werkelijkheid een instantie van een bepaald model zijn en IMBOR 2022 bevat reeds het attribuut 'model.' Als zodanig is de uitdrukkingskracht van IMBOR vergroot.

**Comment by wjtmollema** [comment]
Betreft de alternatieven die je voorstelt, denk ik niet dat 'modelomschrijving' geschikt is, omdat een _best practice_ voor het gebruik van dit attribuut is om de modelnamen te gebruiken die een fabrikant of leverancier ook hanteert, niet om als organisatie zelf een omschrijving te bedenken. 'Model-informatie' daarentegen zou de indruk wekken dat het om een informatieobject gaat, wat een andere aanpassing aan het model zou vereisen. 

Zelf ben ik een voorstander van 'modelnaam,' in de lijn met de attributen objectnaam, buurtnaam etc. De term modelnaam impliceert dat de domeinwaarde refereert naar een bepaald model voor het objecttype.

**Comment by RiX012** [comment]
Goed punt. `modelnaam` vind ik prima. Maar vallen daar dan ook 'nummers' onder? Anders zou `modellabel` passen

**Comment by wjtmollema** [comment]
Onder een `modelnaam` valt gebruikelijk een combinatie van tekens die mogelijk nummers bevat. Voor louter nummers bestaat natuurlijk al het attribuut `typenummer` en voor organisatiespecifieke gevallen `objectnummer`.

Voorbeeld van een `modelnaam` van een Speeltoestel: 

Vrijbuiter - Vrijstaande glijbaan RVS H1.27 SOL.030.363, 

waarbij het mogelijk is 'SOL.030.363' binnen `modelnaam` op te nemen of binnen `typenummer`. 

Het voorbeeld waar de Drainageput in Almelo betrekking op heeft is de volgende:
`modelnaam` :: Tegra 800 PP Smart Drain Put ZW

**Comment by RiX012** [comment]
Duidelijk!

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
