### ISSUE TITLE
Gemeente Amsterdam: Toevoegen objecttype Paneel als subKlasseVan Kunstwerk

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1046]
**Melding**
Op de gemeentelijke busstations van Amsterdam bestaan er Panelen die als zelfstandige Kunstwerken fungeren.

**Verwerking**
- Paneel toegevoegd aan imborVoc_Termen.
- Paneel toegevoegd aan imborKern_Klassen. Paneel toegevoegd aan de klasse Kunstwerk in imborKern_Klassenindeling en imborKern_K_KlassenChildParent.

**Motivatie**
Door het objecttype Paneel toe te voegen wordt de uitdrukkingskracht van IMBOR vergroot.

**Comment by wjtmollema** [comment]
Ik neem de generieke opmerking in acht.

Definitie Paneel: "Een verticale scheiding bestaande uit een raamwerk met meerdere componenten dat een gedeelte van de openbare ruimte opdeelt."

**Comment by RiX012** [comment]
Prima!
