### ISSUE TITLE
Gemeente Utrecht: toevoegen objecttype Busstation als subKlasseVan de klasse Virtuele ruimte

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1049]
**Melding**
De gemeente Amsterdam merkt op dat Busstation als instantie van de klasse Virtuele ruimte ontbreekt.

**Verwerking**
- Busstation toegevoegd aan imborVoc_Termen.
- Busstation toegevoegd aan imborKern_Klassen. Busstation toegevoegd aan de klasse Virtuele ruimte in imborKern_Klassenindeling en imborKern_K_KlassenChildParent.

**Motivatie**
Door het objecttype Busstation toe te voegen wordt de uitdrukkingskracht van IMBOR vergroot.

**Comment by RiX012** [comment]
Ik wil graag kijken of alles rondom een "... station" nu consistent gemodelleerd is. Dit lijkt een ongeschreven modelleerregel dat een station geen object is maar een gebied, maar wat valt daar dan onder?

**Comment by wjtmollema** [comment]
Op dit moment zou het gaan om de volgende objecttypes:
- Busstation (`subKlasseVan Virtuele ruimte`)
- Meetstation (`subKlasseVan Sensor`)
- Snellaadstation (`subKlasseVan Virtuele ruimte`)
- Tankstation (`subKlasseVan Virtuele ruimte`)
- Vuilwaterinnamestation (`subKlasseVan Installatie`)
- Weerstation (`subKlasseVan Sensor`)

Strikt genomen gaat je vraag dus over Busstation, Tankstation en Snellaadstation. Intuïtief beschouwd kunnen hier verschillende dingen over gezegd worden:

- Busstation: Geen IMGeo-object. Het lijkt me aan de gemeente zelf waar het Busstation begint en eindigt. Op een bepaald moment gaat de openbare weg over in een busbaan/vertakking voor openbaar vervoer naar een Busstation. 
- Tankstation: synoniem van Benzinestation, wat een `IMGeo-FunctioneelGebied` is. De IMBOR-begrenzing van Tankstation volgt dus de IMGeo-begrenzing. Een Tankstation heeft echter een kadastrale begrenzing, want er is een eigenaar van de grond (partiulier, provincie, gemeente, Rijkswaterstaat etc.). Logischerwijs volgt de begrenzing de kadastrale grens, met exclusie van de weg.
- Snellaadstation: Geen IMGeo-object. Kan een onderdeel uitmaken van een Tankstation, maar dat is niet noodzakelijk. Volgens de Rijksdienst voor Ondernemend Nederland is een Snellaadstation een 'laadlocatie' waarvan zij de begrenzing omschrijven als: "Een locatie met een of meer laadstations met daarbij behorende laadplekken/laad-parkeervakken."  Hier is de term 'laadstation' synoniem aan `Oplaadpaal`. Het Snellaadstation is dus een vlakobject dat alle tot die locatie behorende laadparkeervakken en oplaadpalen omvat.

**Comment by RiX012** [comment]
> Strikt genomen gaat je vraag dus over Busstation, Tankstation en Snellaadstation.

Ja klopt inderdaad.

Zouden deze drie dan allemaal passen als subklasse van `Verkeerskundig functionele zone`

**Comment by wjtmollema** [comment]
Ja, die passen mijns inziens in die indeling.

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
