### ISSUE TITLE
objecttypes aantal komt niet overeen

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#105]
Vandaag begonnen met de IMBOR2020-08 versie te analyseren om te kijken welke impact deze heeft. Het eerste wat ik doe is het vergelijken van aantallen, geeft het aan de voorkant dezelfde hoeveelheden als aan de achterkant en diagonaal.

Ik constateer hierin verschillen…

Als ik de objecttypes controleer die ik onder de objecttypegroepen optel dan kom ik op het aantal van 328 terwijl in overzicht objecttype het totaal zie dan kom ik op 339. Zonder nu zelf het helemaal door te spitten (zoek de verschillen!!) hoop ik van jullie hiervoor een verklaring te ontvangen.

Bij  IMBOR algemeen zie  ik registratieve gebieden staan bij Objecttypegroep. Deze komt niet voor in het rijtje bij de Objecttypegroep overzicht.  Dit is niet consequent. Mogelijk dat dit de verklaring ook is voor het verschil bij bovenstaand punt.

>>	Wordt de Objecttypegroep registratieve gebieden toegevoegd aan de verzameling van Objecttypegroepen ?

**Comment by JochemMollema** [comment]
Vervallen objecten zijn ook in de lijst met objecten zichtbaar. Opgelost in versie 2021. In 2020-08 337 objecttypes en 2 vervallen.
