### ISSUE TITLE
startGeldigheid en eindGeldigheid uit NEN3610 overnemen in IMBOR

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1051]
Er is behoefte aan twee tijdlijnen, zoals beschreven in NEN3610, om naast je registratie ook de levensloop van het fysieke object buiten bij te houden. Er zijn situaties waarin je Vooraf of achteraf wilt registreren, terwijl het object fysiek nog niet of niet meer aanwezig is.
Vandaar het voorstel de attributen startGeldigheid en eindGeldigheid, conform NEN3610, op te nemen in IMBOR náást tijdstipRegistratie en eindRegistratie.

**Comment by RiX012** [comment]
Makkelijkste manier zou zijn om het gehele 'Temporele aspecten model' uit de NEN3610 volledige en consistent door te voeren binnen IMBOR. Inclusief een uitleg/beschrijving in de ReSpec 
Wellicht icm #997

**Comment by GreenpointAdviesPN** [comment]
Bij nader inzien voldoet de omschrijving van de tijdlijn Geldigheid niet aan de wens om de periode tussen de beheerfase en de registratie te overbruggen. De beoogde periode gaat vaak over de periode waarin een object nog niet geplaatst is in de buitenruimte en dus fysiek nog niet bestaat óf het object al wel bestaat in realiteit, maar nog niet in de scope van BOR valt. In beide gevallen hoort deze registratie dan nog niet in IMBOR, mijns inziens. We gaan dit dus in onze beheersoftware opnemen bovenop IMBOR.

 Ik zou dit verzoek dan ook willen intrekken.

**Comment by RiX012** [comment]
@GreenpointAdviesPN We gaan jou situatie voorleggen aan de beheerders van de NEN3610 en vragen wat hier precies de manier voor zou moeten zijn en of de NEN3610 dit wel of niet zou moeten kunnen dekken.

**Comment by GreenpointAdviesPN** [comment]
De use case is als volgt:
Een boombeheerder heeft een boom in het beheersysteem staan. Deze bestaat ook echt in de buitenruimte. Opgegeven moment sterft de boom af en wordt deze verwijderd omdat dit gevaar oplevert. Omdat er nog juridische zaken lopen of nazorg is zoals bijvoorbeeld de stobbe wegfrezen, wil de beheerder nog beschikken en kunnen registreren op het record in de registratie. Daarnaast plant de beheerder een herplant in op dezelfde plek. Die nieuwe boom zal over bijv. 2 weken geplant worden. Hij wil dit nu alvast registreren (i.e. een nieuw record), zodat deze boom mee komt in overzichten voor werkzaamheden aan bomen voor komend jaar.
Je hebt dan in de werkelijkheid een stobbe staan op de plek waar de boom stond. Je hebt dan in de registratie. twee records staan met objecttype Boom. één met een beheerfase startend in de nabije toekomst, de ander met een beheerfase eindigend in de nabije toekomst. Maar geen van beide zijn in werkelijkheid meer een Boom zoals beschreven volgens de definitie.
Kortom naast tijdstipRegistratie en eindRegistratie wil je ook beginWerkelijkObject en eindWerkelijkObject of iets dergelijks kunnen registreren.

**Comment by wjtmollema** [comment]
@RiX012 Het is een noemenswaardig gegeven dat in IMBOR 2022 `beginGeldigheid` en `eindGeldigheid` alleen bij de klasse `Faunaverblijfplaats` zijn opgenomen met definities conform de betekenis in NEN3610. Zou dit een bug zijn, of is hier een specifieke aanleiding voor geweest?

**Comment by RiX012** [comment]
> @RiX012 Het is een noemenswaardig gegeven dat in IMBOR 2022 `beginGeldigheid` en `eindGeldigheid` alleen bij de klasse `Faunaverblijfplaats` zijn opgenomen met definities conform de betekenis in NEN3610. Zou dit een bug zijn, of is hier een specifieke aanleiding voor geweest?

Dat constateerde ik ook. Het waarom zou ik niet weten, wel dat dit dus niet afdoende lijkt.

**Comment by RiX012** [comment]
> > @RiX012 Het is een noemenswaardig gegeven dat in IMBOR 2022 `beginGeldigheid` en `eindGeldigheid` alleen bij de klasse `Faunaverblijfplaats` zijn opgenomen met definities conform de betekenis in NEN3610. Zou dit een bug zijn, of is hier een specifieke aanleiding voor geweest?
> 
> Dat constateerde ik ook. Het waarom zou ik niet weten, wel dat dit dus niet afdoende lijkt.

Dit lijkt een bug te zijn, waarbij de relatie waarschijnlijk naar `FysiekObject` had moeten liggen ipv `Faunaverblijfplaats`

**Comment by wjtmollema** [comment]
Er wordt verzocht deze issue te sluiten en om de definitieve conclusies te presenteren onder #1075.

**Comment by RiX012** [comment]
Eens.
