### ISSUE TITLE
Unafact: Toevoegen van 'mobiele' waterkering zoals die voorkomt in Kampen en gelijksoortige risicogebieden voor overstroming.

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1052]
**Melding**
O.a. in de stad Kampen worden zogeheten 'mobiele' waterkeringen gebruikt in geval van een risico op overstroming. Het gaat om het opbouwen van een waterkeringsconstructie uit metalen palen en schotten in geval van overstromingsgevaar. De locaties waar de mobiele waterkering wordt toegevoegd zijn vooraf bekend en kunnen sterk verschillen: langs een kade, het sluiten van een onderdoorgang, het afschermen van een woning of het ophogen van een bestaande waterkering aan de kade. Als zodanig kan het met de huidige types van het objecttype `Waterkering` niet worden uitgedrukt, omdat deze een permanent karakter hebben.

**Voorgestelde verwerking**
- Optie 1 (**lage impact**:) Het toevoegen van de nieuwe term `Mobiele waterkering` aan `WaterkeringType`. Hiermee wordt een bestaand objecttype benut. Belangrijk is wel aan te geven dat de `Waterkering` `tijdelijk` is (toevoegen `tijdelijk` als attribuut van de klasse `Waterkering`).
- Optie 2 (**meer impact dan optie 1**): Het toevoegen van `Mobiele waterkering` als nieuw objecttype. Hiermee is het niet nodig om `tijdelijk` als attribuut van de klasse `Waterkering` toe te voegen, want dit kan ofwel onderdeel uitmaken van de klasse `Mobiele waterkering`, ofwel worden opgenomen in de definitie van `Mobiele waterkering`, zodat het attribuut niet nodig is vanwege redundantie. 

**Motivatie**
Het kunnen registreren van deze locaties kunnen zeer belangrijk zijn voor risicogemeenten en -waterschappen (denk ook aan wat er in Limburg is gebeurd in 2021). Het is daarbij belangrijk onderscheid te kunnen maken tussen permanente en tijdelijke waterkeringen.

**Comment by RiX012** [comment]
Optie 2 lijkt me logisch. 
Daarnaast de opmerking dat het attribuut `tijdelijk`  wellicht nader bekeken moet vanwege het modelleren van de temporele aspecten uit de NEN3610

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld.
