### ISSUE TITLE
Wegnummer bij alle objecten

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1054]
Wij zijn als provincie Groningen voorzichtig bezig om het IMBOR te gebruiken. Die is wat ons betreft goed bruikbaar en erg volledig, maar we missen één attribuut dat we voor alle objecten nodig hebben. 

Als provincie leggen we van elk object vast langs welke weg zich bevindt. Daarom is het voor ons nodig om (bijvoorbeeld onder Gebiedsindeling (overgeërfd)) het attribuut ‘Wegnummer’ in het IMBOR te hebben. Graag hoor ik of dit mogelijk is.

**Comment by RiX012** [comment]
Ik denk dat dit geometrische afgeleid zou moeten worden. `wegnummer` zou eigenlijk alleen als attributen van een `Weg` geregistreerd hoeven worden. 
@JochemMollema met welke reden is dit nu verwerkt?

**Comment by wjtmollema** [comment]
In IMBOR 2022 is de registratie van `wegnummer` louter bij `Weg` niet het geval.

Ter illustratie hieronder een overzicht van de klassen waartoe het attribuut `wegnummer` nu behoort:
- `Aquaduct`
- `Beweegbare brug`
- `Ecoduct`
- `Flyover`
- `Geluidsscherm`'
- `Kademuur`
- `Luchtscherm`
- `Onderdoorgang`
- `Tunnel`
- `Vaste brug`
- `Verharding`
- `Viaduct`
- `Weg`
- `Wegas`
- `Wegvak`



</body>

</html>
