### ISSUE TITLE
Gemeente Amsterdam: Uitbreiding IMBOR-materialenpaspoort met de fasering van materialen

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1055]
**Melding**
De gemeente Amsterdam ziet een meerwaarde voor het registreren van de fasering van gebruikte materialen binnen IMBOR. Dit betekent het aangeven als gegeven van een vorm van `Materie` die van toepassing is bij een objecttype in welke fase van gebruik het verkeert. Door de gemeente voorgestelde waarden voor de fasering zijn:
- Fase 0 = nieuw materiaal
- Fase 1 = voor de eerste keer hergebruikt
- Enz.

**Voorgestelde verwerking**
De voorgestelde verwerking is de toevoeging van een attribuut `materiefase` aan de klasse `Materie`. Voor een `subKlasseVan` `Materie` kan vervolgens aangegeven worden voor een bepaald `gewicht`, `volume` en `percentage` in welke `materiefase` die hoeveelheid verkeert.

**Motivatie**
Voor het registreren van informatie die kan bijdragen aan een datagestuurde circulaire economie van de materie in de openbare ruimte is dit een waardevolle toevoeging aan het huidige materialenpaspoort van IMBOR, omdat het IMBOR-gebruikers in staat stelt de duurzaamheid van hun assets te waarderen en te traceren.

**Comment by RiX012** [comment]
Op zich een prima oplossing voor nu. Ik denk wel dat materie en materialenpaspoorten nog een keer een overhaul krijgen in IMBOR. Met name als we gaan samenwerken met Madaster.

**Comment by wjtmollema** [comment]
Tot de presentatie van een nader tegenargument wordt deze issue op de bovenstaande wijze in IMBOR 2023 verwerkt. 

@RiX012 Het heroverwegen van het materialenpaspoort zou in dat licht niet meer dan logisch zijn.
