### ISSUE TITLE
Domeinwaarde 8120 "Organisatiespecifieke domeinwaarden" verwijderen

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1056]
De domeinwaarde 8120 "Organisatiespecifieke domeinwaarden" is eigenlijk geen domeinwaarde, maar een soort aanwijzing dat het attribuut voorzien dient te worden door de organisatie/software leverancier met eigen domeinwaarden.

Ik stel voor dat deze waarde verwijderd wordt als domeinwaarde en dat eventueel in de toelichting bij de attributen waarop dit van toepassing is aan te geven dat je de domeinwaarden zelf kunt bepalen.

**Comment by RiX012** [comment]
Daar ben ik het eigenlijk wel mee eens. Dit zou ook alleen moeten gelden voor `Enumeraties` en niet voor `Suggestielijsten`. 
@wjtmollema Wellicht zouden we dat eens uit moeten zoeken en een passage opnemen in de techdoc.

**Comment by wjtmollema** [comment]
**Suggestie**
De oplossing zou hier kunnen zijn om de `enumeratietypes` uit imborKern_EnumeratiesDomeinwaarden te verwijderen als het een attribuut van het type `referentie` betreft. 

Vervolgens kan er in imborKern_Attributen een onderscheid gemaakt worden in het gegeven `Datatype`. In `TypeAttribuut` wordt namelijk onderscheid gemaakt tussen `Enumeratie` en `Referentie`. In navolging hiervan kan de waarde `N.v.t. waarden in lijst` uit `Datatype` die nu geldt voor zowel `Enumeratie` en `Referentie` louter van toepassing op `Enumeratie` gemaakt worden. De term `Organisatiespecifieke domeinwaardenlijst` kan tenslotte gebruikt worden als `Datatype` voor de attributen van het type `Referentie` .

Als zodanig is het als metagegeven opgenomen, maar niet in imborKern_EnumeratiesDomeinwaarden. Overigens is dit geen letterlijke **suggestie** voor een passage https://docs.crow.nl/imbor/techdoc/

**Comment by RiX012** [comment]
Organisatie specifieke waarde (als domeinwaarde) zou uit het model moeten.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Uitvoering van de **Suggestie** uit het bovenstaande bericht:

> **Suggestie** De oplossing zou hier kunnen zijn om de `enumeratietypes` uit imborKern_EnumeratiesDomeinwaarden te verwijderen als het een attribuut van het `TypeAttribuut` `Referentie` betreft.
> 
> Vervolgens kan er in imborKern_Attributen een onderscheid gemaakt worden in het gegeven `Datatype`. In `TypeAttribuut` wordt namelijk onderscheid gemaakt tussen `Enumeratie` en `Referentie`. In navolging hiervan kan de waarde `N.v.t. waarden in lijst` uit `Datatype` die nu geldt voor zowel `Enumeratie` en `Referentie` louter van toepassing op `Enumeratie` gemaakt worden. De term `Organisatiespecifieke domeinwaardenlijst` kan tenslotte gebruikt worden als `Datatype` voor de attributen van het type `Referentie` .
> 
> Als zodanig is het als metagegeven opgenomen, maar niet in imborKern_EnumeratiesDomeinwaarden. Overigens is dit geen letterlijke **suggestie** voor een passage https://docs.crow.nl/imbor/techdoc/

**Comment by wjtmollema** [comment]
Uitgevoerd zoals voorgesteld. Nieuw label aangemaakt voor `Presentatie wijziging aan softwareleveranciers`.
