### ISSUE TITLE
Gemeente Deventer: toevoegen van Mof als zelfstandig objecttype

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1058]
**Melding**
De gemeente Deventer registreert moffen als zelfstandige knooppunten in het rioleringsnetwerk. Dit is niet congruent met de manier waarop IMBOR 2022 over 'moffen' spreekt, namelijk als `verbindingstype` van de klasse `Holle leiding`. Dit doet IMBOR-riolering in navolging van [GWSW](https://data.gwsw.nl/?menu_item=individuals&item=../../def/1.5.2/Basis/DubbeleSteekmof). De gemeente Deventer stelt echter voor de mof als zelfstandig objecttype op te laten nemen in IMBOR.

**Verwerking**
Het honoreren van het verzoek van de gemeente kan op meerdere manieren ingevuld worden:
- Optie 1: **Opname van `Mof` als objecttype en verbindingstype wordt vervangen door een semantische relatie.**  Bij het toevoegen van `Mof` als zelfstandig objecttype worden de domeinwaarden van `verbindingstype` `Mof/Spie` en `Dubbele steekmof` redundant. Deze termen zouden domeinwaarden worden van het enumeratietype `MofType`. Dit heeft consequenties voor GWSW omdat IMBOR hierdoor af zou wijken van `Verbindingstype (coll)`. Daarnaast ontstaat de wens om voor `Mof` als objecttype ook een afstemming te hebben met GWSW. De redundantie is het gevolg van het feit dat de relatie `Mof :: Holle leiding` op een algemenere manier uitgedrukt kan worden, namelijk met behulp van de semantische relatie `isVerbondenMet`.
- Optie 2: **Opname van `Mof` als objecttype en verbindingstype blijft gehandhaafd.** Bij het toevoegen van `Mof` als zelfstandig objecttype kan de redundantie ook genegeerd worden om niet te tornen aan de afstemming met `Verbindingstype (coll)`. Hierdoor wordt het een keuze voor de IMBOR-gebruiker om (i) `Mof :: isVerbondenMet :: Holle leiding` ofwel (ii) `Holle leiding :: verbindingstype` te gebruiken. Het gevolg van deze optie echter is dat (i) geen afstemming heeft met GWSW, maar wel binnen haar domein valt.

Een derde optie is om het verzoek van de gemeente niet te honoreren, wat IMBOR ongewijzigd zou laten en derhalve ook geen consequenties zou hebben voor de afstemming met GWSW.

**Motivatie**
De motivatie is gedeeltelijk afkomstig uit hoe een mof haar intrede doet in de ontwerpfase van de objectlevenscyclus. In NLCS 5.0 worden moffen als zelfstandig symbool gebruikt, bijvoorbeeld als de laagnaam `ET_HULP_MOF`.

**Comment by MarinusVonhof** [comment]
Dit aanpassingsvoorstel is bij RIONED geregistreerd onder nr 1243.
Op 2 november 2023 volgt beoordeling door de werkgroep GWSW-Basis en daarna volgt publicatie van de uitslag op https://data.gwsw.nl/ .
