### ISSUE TITLE
Registratie-informatie en Inwinning-informatie verder toepassen

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1059]
Ingebracht door @GreenpointAdviesPN:
Ik zie dat in IMBOR de  `InformatieObjecten` `Registratie-informatie` en `Inwinning-informatie` alleen toegepast worden op de subklassen van `FysiekObject` en op `Materie`. Dat betekend dat dit niet toegepast wordt op `Functie` (als activiteit) en  `InformatieObject`. Dat lijkt me wel wenselijk en met name dan op alle `InformatieObject`en (behalve wellicht Registratie- en Inwinning-informatie zelf).
Daarmee zou je namelijk een sluitend verhaal kunnen maken m.b.t. de mutatiehistorie van een object en al zijn relaties.

Ik kan me voorstellen dat dat nu niet gedaan is, omdat 'Registratie- en Inwinning-informatie' ook `InformatieObject`en zijn en je daarmee een oneindige loop van meta over meta, over meta, over meta, etc. kunt krijgen. Aan de andere kant kun je in de semantische relaties tabel regelen dat dat niet gebeurd.
Waarom is er voor gekozen om geen meta van `InformatieObject` en `Functie` vast te leggen, terwijl je de attributen daarvan wel kunt muteren?

**Comment by RiX012** [comment]
> Daarmee zou je namelijk een sluitend verhaal kunnen maken m.b.t. de mutatiehistorie van een object en al zijn relaties
Ja daar heb je inderdaad wel een punt

Omdat de attributen op deze twee klassen met name gaan over de attributen van het object is het ook logisch om zoiets te kunnen doen. 
@JochemMollema Het lijkt ook hier logisch om de klassen `Registratie-informatie` en `Inwinning-informatie` nog meer op te lijnen met de bronnen waarop ze gebaseerd zijn (o.a. NEN3610) en dan deze consistenter toe te passen, niet?

**Comment by JochemMollema** [comment]
Ik ga hier mee aan de slag en zal proberen beide informatieobjecten verder op te lijnen.

**Comment by wjtmollema** [comment]
Er wordt verzocht deze issue te sluiten en om de definitieve conclusies te presenteren onder https://github.com/Stichting-CROW/imbor/issues/1075.

**Comment by RiX012** [comment]
> Er wordt verzocht deze issue te sluiten en om de definitieve conclusies te presenteren onder #1075.

Eens.
