### ISSUE TITLE
beheerder -eigenaar ministerie

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#106]
Waarom wordt ministerie niet als  type eigenaar/beheerder (algemeen) opgenomen en de specifieke niet in type beheerder / eigenaar plus?

Anders kunnen we de provincies en gemeente ook wel als zodanig opnemen. 

"
Ministerie   van Landbouw, Natuur en Voedselkwaliteit opgenomen in tabellen   REF_TypeEigenaar en REF_TypeBeheerder In tabel X_AttributenDomeinwaarden   Ministerie van Landbouw, Natuur en Voedselkwaliteit toegevoegd voor   TypeEigenaar en TypeBeheerder
--

**Comment by JochemMollema** [comment]
IMBOR-team: het voorstel wordt gevolgd. Ministerie komt in de vaste lijsten terug voor beheerder en eigenaar de afzonderlijke ministeries verhuizen naar de suggestielijsten beheerder gedetailleerd en eigenaar gedetailleerd.
