### ISSUE TITLE
Gemeente Haarlem: toevoegen van Kaartlezer als objecttype of als attribuut

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1060]
**Melding**
De gemeente Haarlem registreert bij diverse objecttypes of er kaartlezers aan verbonden of op bevestigd zijn. Voorbeelden van bestaande IMBOR-objecttypes met (geïntegreerde) kaartlezers zijn: `Container`, `Poller`, `Betaalautomaat`, `Parkeerautomaat`, `Slagboominstallatie`, `Meldpaal`, `Toegangshekinstallatie`.

**Voorgestelde verwerking**
Voor de verwerking zijn er meerdere opties mogelijk, waarvan de een meer impact heeft dan de ander (waarbij impact gemeten wordt aan de hand van het aantal wijzigingen.
- Optie 1 **lagere impact**: De toevoeging van het objecttype `Kaartlezer` als `subKlasseVan` `Sensor`. `Kaartlezer` kan vervolgens met de semantische relatie `isVerbondenMet` aan andere objecttypes gerelateerd worden.
- Optie 2  **hogere impact**: De toevoeging van het attribuut `kaartlezer` bij verscheidene klassen (zie **Melding**). Het 'hebben van een kaartlezer als onderdeel' wordt als zodanig een attribuut.

**Motivatie**
Het is overduidelijk dat kaartlezers deel uitmaken van de openbare ruimte. Het zijn technische onderdelen van een groter installatiecomplex, maar het is voorstelbaar dat er nut is bij de registratie zoals de gemeente Haarlem die heeft ingericht. Daarom is het gewenst dat IMBOR die registratie faciliteert door het op te nemen binnen de standaard.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld in optie 1.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
