### ISSUE TITLE
Gemeente Utrecht: het toevoegen van het attribuut cultuurhistorisch waardevol bij Planten

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1061]
**Melding**
In samenwerking met de gemeente Utrecht is geconstateerd dat tegen logische verwachtingen in de domeinwaarde `Stinsenbeplanting` van het attribuut `cultuurhistorisch waardevol` niet van toepassing is voor `Planten`. Om de `Stinsenbeplanting` in de gemeente wel te kunnen modelleren als `Planten` wordt verzocht `cultuurhistorisch waardevol` toe te voegen bij `Planten`.

**Voorgestelde verwerking**
Voor de verwerking wordt het volgende voorgesteld:
- Het toevoegen van `cultuurhistorisch waardevol` aan de klasse `Planten`;
- Het toevoegen van het enumeratietype `PlantenCultuurhistorischWaardevol` met als domeinwaarde `Stinsenbeplanting`.

**Motivatie**
Wanneer men de definitie van `Stinsenbeplanting` beschouwt ("Stinsenplant (of stinzenplant) is een in Nederland en Duitsland gangbare benaming voor een groep planten die van oorsprong in een regio alleen als ingevoerde sierplantensoort voorkwam in landgoederen, boerenhoven, pastorietuinen en dergelijke, en zich daar handhaafden of verwilderd zijn."), dan wordt het duidelijk dat het onzinnig is om het objecttype `Planten` deze omschrijving te ontzeggen.

**Comment by JochemMollema** [comment]
@RiX012  deze issue kan gesloten worden, zie uitwerking #1379
