### ISSUE TITLE
Gemeente Utrecht: verzoek om het attribuut 'onderhoudsregime' toe te voegen aan de klasse 'Groenobject'

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1062]
**Melding**
De gemeente Utrecht ziet een toegevoegde waarde in het gebruiken van het attribuut `onderhoudsregime` bij de objecttypes die tot de klasse `Groenobject` behoren. In IMBOR 2022 is `onderhoudsregime` een exclusief attribuut van de klasse `Kunstwerk`. Het heeft als definitie: "Onderhoudsregime waarbinnen het beheerobject valt." Binnen `onderhoudsregime` zou de gemeente aanduidingen van onderhoudsvormen voor `Groenobject`en op kunnen nemen.
 
**Voorgestelde verwerking**
- Het toevoegen van `onderhoudsregime`  aan de klasse `Groenobject` in imborKern_KlassenAttributen.

**Motivatie**
De definitie van `onderhoudsregime`  ("Onderhoudsregime waarbinnen het beheerobject valt.") is voldoende breed voor de voorgestelde toewijzing.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
