### ISSUE TITLE
Unafact: Vleermuiskast op twee plekken in de type-indeling van Faunaverblijfplaats opgenomen

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1070]
**Melding**
De term `Vleermuiskast` komt op twee plaatsen terug in de type-indeling van `Faunaverblijfplaats`. Dit is een fout in de indeling, omdat de invullingen van `type extra gedetailleerd` m.b.t. `Vleermuiskast` logischerwijs ook die waarde als bovenliggende waarde moeten hebben. Dit is nu niet het geval (zie afbeelding). Echter is dit niet het enige probleem: boven `Nestkast voor zoogdieren` (`type gedetailleerd`) is er in de type-indeling nog maar een niveau over. `Vleermuiskast` kan daar niet ingevoegd worden.

**Voorgestelde verwerking**
- `Vleermuiskast` vervalt bij `FaunaverblijfplaatsType`;
- `FaunaverblijfplaatsTypeGedetailleerd` en `FaunaverblijfplaatsTypeExtraGedetailleerd` blijven gehandhaafd.

![image](https://user-images.githubusercontent.com/90725038/208097820-3305c520-b48d-4776-a9a5-1e809f2d99a3.png)

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
