### ISSUE TITLE
Gemeente Almelo: toevoegen 'voedselrijkdom bodem' aan klasse Begroeiing

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1072]
**Melding**
Uit afstemming tussen de gemeente Almelo en een groenaannemer is gebleken dat het relevant voor het bepalen van IMBOR-objecttypes van `Begroeiing` en types van `Gras- en kruidachtigen` wat de voedselrijkdom van de onderliggende bodem is.

**Voorgestelde verwerking**
- Toevoegen `voedselrijkdom bodem` aan de klasse `Begroeiing`;
- Toevoegen `BegroeiingVoedselrijkdomBodem` met als domeinwaarden `Voedselarm` (syn. `Oligotroof`), `Matig voedselrijk` (syn. `Mesotroof`), `Voedselrijk` (syn. `Eutroof`) en `Overmatig voedselrijk` (syn. `Hypertroof`).

**Motivatie**
Het toevoegen van dit attribuut maakt IMBOR aantrekkelijker voor ecologie en natuurontwikkeling. Daarnaast ziet men bij de gemeente Almelo dat voedselrijkheid ook een verborgen parameter is voor het classificeren van `type`, `biotooptype` en `graslandfase` bij een objecttype zoals `Gras- en kruidachtigen`.

**Comment by RiX012** [comment]
Wellicht attribuut generieker benoemen door alleen `voedselrijkdom` te gebruiken

**Comment by JochemMollema** [comment]
Na overleg is besloten dat dit gegeven bij de klasse Bodem hoort. Door het toekennen van de voorgestelde attributen wordt Bodem een objecttype.

Attribuut voedselrijkdom toegevoegd aan Bodem met de domeinwaarden:
Voedselarm (syn. Oligotroof), Matig voedselrijk (syn. Mesotroof), Voedselrijk (syn. Eutroof) en Overmatig voedselrijk (syn. Hypertroof).

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
