### ISSUE TITLE
Unafact: Uitbreiding IMBOR-modellering Bomenrij

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1073]
**Melding**
`Bomenrij` als objecttype is tot stand gekomen in IMBOR 2022 op basis van afstemming met de Samenhangende Objectenregistratie (SOR). Op basis van ervaringen in de praktijk blijkt echter dat voor nuttig gebruik van dit objecttype een aantal attribuutgegevens gerelateerd aan de `Boom` ontbreken voor het beheren van bomen in een rij als een objecttype. Dit spiegelt de huidige modellering van `Bosplantsoen` en `Bos`, waar ook attributen m.b.t. bomenbeheer zijn opgenomen die simultaan van toepassing zijn op alle bomen binnen die vlakobjecten. 

In het geval van `Bomenrij` gaat het om de volgende attributen:
- `boomveiligheidscontrole`
- `boomveiligheidsklasse`
- `herplantplicht`

**Voorgestelde verwerking**
- Toevoegen van `boomveiligheidscontrole` aan de klasse `Bomenrij`;
- Toevoegen van `boomveiligheidsklasse` aan de klasse `Bomenrij`;
- Toevoegen van `herplantplicht` aan de klasse `Bomenrij`.

**Motivatie**
Net zoals `Bosplantsoen` en `Bos` bevat `Bomenrij` bomen, waarvoor een zorgplicht geldt en de bovenstaande attributen zeer belangrijk zijn.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
