### ISSUE TITLE
BGT 1.2: Kunstwerkdeel: type: Hoogspanningsmast kan niet uitgedrukt worden in IMBOR 2022

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1076]
**Melding**
Het `BGT-ObjectType` `Kunstwerkdeel: type: Hoogspanningsmast` is geen onderdeel van IMBOR. Dit is een mankement in de uitwisseling van IMBOR en IMGeo. [Hoogspanningsmast](https://geonovum.github.io/IMGeo-objectenhandboek/kunstwerkdeel?highlight=hoogspannin#hoogspanningsmast) behoort immers tot het [verplichte](https://docs.geostandaarden.nl/imgeo/catalogus/bgt/#hoogspanningsmast) deel van BGT|IMGeo.

**Voorgestelde verwerking**
- Toevoegen van het `IMBOR-ObjectType` `Hoogspanningsmast` als `subKlasseVan` `Kunstwerk`.

**Motivatie**
IMBOR streeft een uitwisseling met BGT|IMGeo na die compleet en consistent is. Om dat doel te behalen is deze toevoeging benodigd.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
