### ISSUE TITLE
Gemeente Deventer: toevoegen 'lensdiameter' bij Verkeerslantaarn

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1078]
**Melding**
De gemeente Deventer merkt op dat bij `Verkeerslantaarn` er geen attribuut beschikbaar is voor het registreren van de diameter van de behuizing voor de lichtbronnen van de `Verkeerslantaarn`. Deze diameter wordt de `lensdiameter` genoemd.

**Voorgestelde verwerking**
- Toevoegen van het attribuut `lensdiameter` - met de eenheid `mm` - aan de klasse `Verkeerslantaarn`.

**Motivatie**
De gemeente Deventer geeft aan dat er verschillende lensdiameters van toepassing zijn en dat het relevant is voor het plannen van een vervanging van de `Lichtbron` uit de `Verkeerslantaarn` om te weten wat de exacte `lensdiameter` moet zijn. Dit attribuut vervult een functie gelijk die van `masttopdiameter` bij de klasse `Paal`.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
