### ISSUE TITLE
Gemeente Deventer: IMBOR Laadinfrastructuur

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1079]
**Melding**
De gemeente Deventer heeft een tweeledig uitbreidingsvoorstel gedaan voor `ObjectType`n die onderdeel uitmaken van de laadinfrastructuur in de openbare ruimte.
1. Binnen de gemeente is er een elektronisch aangedreven veerverbinding over de IJssel. Aan beide wallen zijn er magnetische laadpunten aangebracht die de veerpont 'aantikt' bij het bereiken van de overliggende wal. Het idee is om dit object onder te brengen bij `Laadpunt`.
2. Het onderbrengen van 'Deelautoparkeervak' bij `Parkeervoorziening`. Er komen in de gemeente steeds meer elektrische deelauto's beschikbaar die ook vanuit beleidswege vaste parkeervakken toegewezen krijgen voor het parkeren tijdens inactiviteit van de deelauto.

**Voorgestelde verwerking**
1. Het toevoegen van `Magnetisch laadpunt voor veerponten` aan `LaadpuntType`;
2. Het toevoegen van `Deelautoparkeervak` aan `ParkeervoorzieningType`.

**Motivatie**
Om bruikbaar te blijven voor een zich snel ontwikkelende openbare ruimte is het belangrijk dat IMBOR dergelijke vernieuwende objecttyperingen snel adapteert teneinde hun structurele registratie te accommoderen.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
