### ISSUE TITLE
Unafact: redundantie jaar renovatie bij Gebouw vanwege Onderhoud-informatie

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1081]
**Melding**
`jaar renovatie` is zowel bij de klasse `Gebouw` als bij de klasse `Onderhoud-informatie` opgenomen. De eerste opname is redundant vanwege de mogelijkheid de volgende relatie te leggen: `Gebouw :: isBeschrevenDoor :: Onderhoud-informatie :: heeftAttribuut :: jaar renovatie`.

**Voorgestelde verwerking**
`jaar renovatie` laten vervallen bij de klasse `Gebouw`.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
