### ISSUE TITLE
Gemeente Tilburg: het objecttype Groeiplaats

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1083]
**Melding**
De gemeente Tilburg constateert diverse zaken gerelateerd aan het `ObjectType` `Groeiplaats`:
1. `Groeiplaats` is niet opgenomen binnen de vakdisciplines Ecologie en Groen in imborKern_K_VakdisciplinesObjecttypen.
2. `Groeiplaats` heeft geen semantische relatie met het `InformatieObject` `Soortnaam groenobject`.

**Voorgestelde verwerking**
1. `Groeiplaats` toevoegen binnen de vakdisciplines Ecologie en Groen in imborKern_K_VakdisciplinesObjecttypen.
2. Toevoegen van `Groeiplaats` `isBeschrevenDoor` `InformatieObject` `Soortnaam groenobject` aan imborKern_K_ObjecttypenSemantischeRelaties.

**Motivatie**
`Groeiplaats` is inderdaad gerelateerd aan Groen en Ecologie (check (1)). `Groeiplaats` gaat volgens de definitie inderdaad over een bepaalde plantensoort (check (2)).

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.

**Comment by wjtmollema** [comment]
Er wordt om toestemming verzocht deze issue te sluiten

**Comment by JochemMollema** [comment]
Bij deze issue hoort nog wel een naamswijziging. Groeiplaats is gewijzigd in Plantensoortlocatie en het objecttype Groeiplaatsinrichting is hernoemd in Groeiplaats.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
