### ISSUE TITLE
Gemeente Tilburg: registratie van een 'leemlaag' bij een Watervlakte :: type :: Poel

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1087]
**Melding**
De gemeente Tilburg constateert dat het niet mogelijk is om te registreren dat een `Poel` als bodem een kunstmatige `Leemlaag` heeft.

**Voorgestelde verwerking**
Bij de constructie van een `Poel` kan een `Leemlaag` als een soort constructielaag worden aangebracht als bodem. Voor de registratie denkt men hierdoor dadelijk aan het toevoegen van `Leemlaag` aan `ConstructielaagConstructielaagsoort`. Echter zijn de beschikbare `ObjectType`n hiervoor niet geschikt: zowel `Constructielaag verhardingsobject` en `Constructielaag groenobject` gaan niet over 'constructielaag _waterobject_'. Deze `ObjectType`n zijn gescheiden vanwege de toekenning van bepaalde attributen aan `Constructielaag verhardingsobject` en niet aan `Constructielaag groenobject`.

 Dit wijst op twee opties voor verwerking:
- Het opheffen van het onderscheid tussen  `Constructielaag verhardingsobject` en `Constructielaag groenobject`. Het terugbrengen van beide `ObjectType`n tot `Constructielaag` en het toevoegen van `Leemlaag` aan `ConstructielaagConstructielaagsoort`.
- Het toevoegen van `Constructielaag waterobject` als `subKlasseVan` `Constructielaag`. Het toevoegen van `Leemlaag` aan `ConstructielaagConstructielaagsoort`.

**Comment by RiX012** [comment]
Waarom kan er bij `Constructielaag groenobject` niet `Leemlaag` worden toegevoegd?

**Comment by wjtmollema** [comment]
Natuurlijk kan dat, en als je het onderscheid tussen de constructielagen niet zou opheffen dan zou dit ook gebeuren door het toevoegen van `Leemlaag` aan `ConstructielaagConstructielaagsoort`.

Echter zie ik bij het toepassen van `Constructielaag verhardingsobject` en `Constructielaag groenobject` dat of het een constructielaag van een groenobject of van een verhardingsobject is een _relationeel_ gegeven is. Oftewel:

- `Constructielaag :: is verbonden met :: <<subklasse van Groenobject>>`
- `Constructielaag :: is verbonden met :: <<subklasse van Verharding>>`

Een relationeel gegeven wordt hier in de typering van een `ObjectType` gebakken. Het is nu juist de vraag of dat wel wenselijk is.

**Comment by wjtmollema** [comment]
Er wordt nogmaals voorgesteld om een enkel objecttype `Constructielaag` te gaan hanteren, zoals voorgesteld in https://github.com/Stichting-CROW/imbor/issues/1087#issue-1584343467:

Het opheffen van het onderscheid tussen `Constructielaag verhardingsobject` en `Constructielaag groenobject`. Het terugbrengen van beide ObjectTypen tot `Constructielaag` en het toevoegen van `Leemlaag` aan `ConstructielaagConstructielaagsoort`.

**Comment by JochemMollema** [comment]
Voorstel voor 1 objecttype Constructielaag is een goed voorstel,  maar vanwege impact eerst samen bespreken.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
