### ISSUE TITLE
Gemeente Tilburg: Heroverweging semantische relaties met materialen

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1088]
**Melding**
De gemeente Tilburg constateert onzinnige combinaties in de semantische relaties van `ObjectType`n met `Materie`. Als voorbeeld worden de relaties van `Slot` genoemd.

**Voorgestelde verwerking**
Heroverweging van de opgenomen semantische relaties met materialen. Er zijn tenminste twee opties:
1. Het bepalen van principes op basis waarvan een semantische relatie tussen een `ObjectType` en een vorm `Materie` in IMBOR moet worden opgenomen.
2. Het doornemen van de huidige invulling van imborKern_K_ObjecttypenSemantischeRelaties en het laten vervallen van de onzinnige combinaties.

Discussie binnen het IMBOR-team moet uitwijzen welke optie te prefereren valt.

**Comment by wjtmollema** [comment]
**Analyse**
Een eerste analyse levert reeds circa 90 problematische semantische relaties op. Aanpassing van deze semantische relaties in de werkversie behoeft accordering van het IMBOR-team.
[20240426_Analyse GitHub #1088.xlsx](https://github.com/Stichting-CROW/imbor/files/11331528/20240426_Analyse.GitHub.1088.xlsx)

**Comment by RiX012** [comment]
Wordt gemerged met #1192
