### ISSUE TITLE
Eenheid "Reeks" is geen echte eenheid

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1091]
De eenheid "Reeks" met vocabulairid 14502, is geen echte eenheid. Deze wordt alleen gebruikt als eenheid voor relatievehoogteligging uit de BGT. Het woord "relatief" geeft eigenlijk al aan dat dit een waarde is zonder meetbare eenheid.
Wat mij betreft mag deze "eenheid" komen te vervallen en mag attribuut "relatievehoogteligging" in IMBOR eenheidsloos worden.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
De melder maakt een geldig punt betreft de pseudo-eenheid `Reeks`.
Wanneer echter de Basisregistratie Grootschalige Topografie Gegegevenscatalogus BGT 1.2 wordt geraadpleegd bij '[relatieveHoogteligging](https://docs.geostandaarden.nl/imgeo/catalogus/bgt/#relatievehoogteligging)', dan ziet men dat het `Waardetype attribuut` (het equivalent van `Datatype` uit IMBOR) daar `Integer` is. In IMBOR wordt `xsd:decimal` gebruikt, maar https://docs.geostandaarden.nl/imgeo/catalogus/bgt/#niveauaanduidingen-per-object sluit expliciet decimale waarden uit. Echter is `xsd:positiveInteger` geen adequate vervanger, omdat `relatieveHoogteligging` negatieve waarden toestaat. Het voorstel is daarom om het tot nog toe ongebruikte `Datatype` `xsd:Integer` hiervoor in IMBOR op te nemen.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
