### ISSUE TITLE
De Eenheid 'Integer' is niet juist

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1092]
De Eenheid 'Integer' is niet juist. Deze zou moeten vervallen

**Comment by wjtmollema** [comment]
**Corollarium**
In samenhang met issue #1091 moet bij al deze gevallen bekeken worden of niet eerder `xsd:integer` dan `xsd:positiveInteger` van toepassing moet zijn.

**Comment by wjtmollema** [comment]
**Uitwerking**
Bij de volgende combinaties van `Klasse` en `Attribuut` is `Integer` de eenheid. Bij elke combinatie is aangegeven of het `Datatype` `xsd:integer` of `xsd:positiveInteger` moet zijn.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Klasse | Attribuut | Eenheid | Datatype | Gewenst   datatype | Motivatie
-- | -- | -- | -- | -- | --
Armatuur | aantal   connectoren | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Asfaltverharding | aantal   deklagen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Compartiment | aantal   i.e. bedrijven | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Vrijverval rioolleiding | aantal   i.e. bedrijven | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Rioolput | aantal   i.e. bedrijven | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Waterbeheergebied | aantal   i.e. per woning | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Compartiment | aantal   i.e. recreatie | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Vrijverval rioolleiding | aantal   i.e. recreatie | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Rioolput | aantal   i.e. recreatie | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Laadplein | aantal   laadpalen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Lichtbron | aantal   leds | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Gras- en kruidachtigen | aantal   obstakels | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Planten | aantal   obstakels | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Asfaltverharding | aantal   onderlagen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Overbrugging | aantal   overspanningen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Geluidsscherm | aantal   panelen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Hek | aantal   panelen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Parkeervoorziening | aantal   parkeerplaatsen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Fietsparkeervoorziening | aantal   parkeerplaatsen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Speeltoestel | aantal   plaatsen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Zitelement | aantal   planken | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Gemaal | aantal   pompen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Rijbaan | aantal   rijstroken | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Kast | aantal   sloten | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Tunnel | aantal   tunnelbuizen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Asfaltverharding | aantal   tussenlagen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Compartiment | aantal   woningen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Rioolput | aantal   woningen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Vrijverval rioolleiding | aantal   woningen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Aansluitvoorziening | aantal   zekeringen | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Haag | aantal   zijden | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Lichtbron | branduren | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Verkeersintensiteit-informatie | capaciteit | Integer | xsd:decimal | xsd:decimal | Datatype is correct.
Lichtbron | CRI | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Sluis doorvaart | doorvaartnummer | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Soortnaam groenobject | hoeveelheid | Integer | xsd:decimal | xsd:decimal | Datatype is correct.
Speelterrein | inspectievolgorde | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Constructielaag | laagnummer | Integer | xsd:positiveInteger | xsd:integer | Datatype is   incorrect. Negatieve waarden kunnen gebruikt worden worden voor ondergrondse   lagen van gebouwen.
Bouwlaag | laagnummer | Integer | xsd:positiveInteger | xsd:integer | Datatype is   incorrect. Negatieve waarden kunnen gebruikt worden worden voor ondergrondse   lagen van gebouwen.
Ruimte | laagnummer | Integer | xsd:positiveInteger | xsd:integer | Datatype is   incorrect. Negatieve waarden kunnen gebruikt worden worden voor ondergrondse   lagen van gebouwen.
Gebouwzone | laagnummer | Integer | xsd:positiveInteger | xsd:integer | Datatype is   incorrect. Negatieve waarden kunnen gebruikt worden worden voor ondergrondse   lagen van gebouwen.
Boom | leeftijd | Integer | xsd:duration | xsd:positiveInteger  | De eenheid integer had hier een functie omdat xsd:duration niet noodzakelijkerwijs een integernotatie heeft.
Onderhoud-informatie | levensduur | Integer | xsd:decimal | xsd:decimal | Datatype is correct.
Kast | meternummer | Integer | xsd:positiveInteger | xsd:positiveInteger | Datatype is correct.
Opening kunstwerk | nummer   opening | Integer | xsd:decimal | xsd:decimal | Datatype is correct.
Onderhoud-informatie | technische   levensduur | Integer | xsd:decimal | xsd:decimal | Datatype is correct.



</body>

</html>

Dientengevolge kan de eenheid vervallen. Bovenstaande wijzigingen m.b.t. laagnummer worden doorgevoerd.

**Comment by RiX012** [comment]
> @RiX012 De enige vraag aan jou die rest, is of `jaar` toegevoegd zou moeten worden als `Eenheid`. Dit heeft geen consequenties voor alle attributen die een jaartal moeten vastleggen, zoals `jaar van aanleg` omdat bijv. `2023` niet de eenheid `jaar` heeft - dat zou '2023 jaar' betekenen - maar van het `Datatype` `xsd:gYear` is.

Waarom zou het dan nodig zijn? Ik vind het op zich prima, maar dan moet het ook in de mappingen tabellen naar QUDT aangevuld worden.

**Comment by wjtmollema** [comment]
Dit is eventueel nodig omdat een andere maat om een tijdsduur in op te delen ook tot de collectie `Eenheid` behoort: `uur`.

**Comment by RiX012** [comment]
OK doen dan!

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld:
-`jaar` toegevoegd aan de collectie `Eenheid` en toegeschreven aan: `technische levensduur`
-`jaar` in `refModel_Mapping` de `externeSpecificatie` `QUDT object :: Time :: Year` gegeven, ten behoeve waarvan `Year` is gedefinieerd in `refModel_Domeinwaarden` conform [http://qudt.org/vocab/unit/YR](http://qudt.org/vocab/unit/YR#)

**Comment by RiX012** [comment]
Verwerken zoals besproken.

**Comment by wjtmollema** [comment]
Verwerkt zoals besproken. Er wordt verzocht om toestemming om de issue te sluiten.

**Comment by RiX012** [comment]
- `Integer` is geen `Eenheid`
- Voor alle voorkomens is het `Datatype` en de `Eenheid` gecheckt

Mogelijke impact:
- Wijziging in eenheden en datatypen zorgen voor transformaties
