### ISSUE TITLE
Gemeente Amersfoort: Fietssluis toevoegen als typering onder hek

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#1094]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Niet opgenomen in IMBOR is: Fietssluis, Gemeente Amersfoort zou dit graag apart willen registreren.
![image](https://user-images.githubusercontent.com/80532038/222179110-6f38c765-8e47-464a-8524-91ea208a4ef6.png)
Kan onder objecttype hek vallen,

**Beschrijf de oplossing die je voor je ziet**
Toevoegen als type of type detail onder hek anders uitleggen hoe dit geregistreerd kan worden in IMBOR.

**Wat voor alternatieven heb je overwogen?*
Als buishek opnemen met een specifiek model. 

**Meer context**

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Op dit moment wordt in IMBOR de 'Fietssluis' - als constructie bestaande uit twee `ObjectType`n `Hek` - niet onder die naam onderscheiden. Beide `Hek`ken afzonderlijk kunnen reeds gemodelleerd worden m.b.v. van het `type` van `Hek` `Geleidehek`. Zie de definitie:

> Hek van gebogen (enkele) buis met dwarsstang voor stabiliteit, toegepast bij voetgangerssluis, scheiding van voetpaden en rijbanen.

Tegemoetkomend aan de gemeente Amersfoort de definitie als volgt gewijzigd worden om de (toegegeven) veel voorkomende toepassing van de fietssluis te incorporeren:

> Hek van gebogen (enkele) buis met dwarsstang voor stabiliteit, toegepast bij een fiets- of voetgangerssluis en scheidingen van voetpaden en rijbanen.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.

**Comment by wjtmollema** [comment]
Er wordt om toestemming verzocht deze issue te sluiten.
