### ISSUE TITLE
NEN3610 laatste versie van URI's gebruiken in IMBOR

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1095]
De NEN3610 is gepubliceerd als ontologie. Te raadplegen voorlopen op:
https://github.com/Geonovum/nen3610-werkomgeving/blob/main/model/respec/nen3610-2022-model.md

Hiermee komen nieuwe een aangepaste URI's ter beschikking die we in IMBOR moeten gaan doorvoeren.

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
@RiX012 De NEN 3610-klassen zijn geen onderdeel van de mappingtabel. Ik stel voor om `URI` als gegeven van een term toe te voegen aan imborVoc_Termen, waarbij ofwel de IMBOR-URI (zoals in de ontologie-verkenner), ofwel een URI uit een ander model wordt opgenomen naast de reeds gebruikte GUIDs. De IMBOR-URI's zijn nu geen onderdeel van de Access-publicatie.

**Comment by wjtmollema** [comment]
Excuus, het was mijn bedoeling aan te geven dat de URI's strikt genomen niet binnen de scope van IMBOR 2022 zelf vallen, maar _binnen de aansluiting met andere modellen_, waarbij de URI's niet direct in `refModel_Mapping` zijn opgenomen. Uiteraard kunnen ze in `refModel_Objecttypen` overgenomen worden.

**Comment by wjtmollema** [comment]
De volgende termen in `refModel_Objecttypen` die een provisorische NEN 3610 URI toegewezen hadden gekregen, komen in de definitieve publicatie niet terug:
- `Kering`
- `Ondertunneling`
- `Overbrugging`

Deze hebben dit waarschijnlijk ongerechtvaardigd toegewezen gekregen, want `Kering` is een SOR-verbijzondering van `NEN3610:FunctioneleRuimte` en `Ondertunneling` en `Overbrugging` zijn SOR-verbijzonderingen van `NEN3610:Kunstwerk`.

**Comment by wjtmollema** [comment]
**Addendum**
De online publicatie van het semantisch model introduceert een aantal veranderingen in schrijfwijze van NEN 3610-termen. IMBOR volgt de schrijfwijzen uit de PDF-publicatie van de norm. T.z.t. wordt de correcte schrijfwijze geverifieerd bij de auteurs van de NEN 3610. De hypothese met betrekking tot de verschillen in schrijfwijzen wat betreft het weglaten van spaties, verbindingstekens en trema's in de online publicatie is dat dit te wijten is aan het verbeteren van de machineleesbaarheid van de termen.

Hieronder wordt een overzicht gegeven van de schrijfwijzen en of ze worden doorgevoerd in IMBOR.
- `Functionele ruimte` → `FunctioneleRuimte`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Geo-object` → `GeoObject`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Geografische ruimte` → `GeografischeRuimte`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Juridische ruimte` → `JuridischeRuimte`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Reëel object` → `ReeelObject`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Registratieve ruimte` → `RegistratieveRuimte`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Virtuele ruimte` → `VirtueleRuimte`: IMBOR voert deze verandering in schrijfwijze tot nader order niet door.
- `Waterruimte` → `Waterverplaatsingsruimte`: In de PDF-publicatie heette dit al  `Waterverplaatsingsruimte`; dit was dus een fout in IMBOR.
- `Water` →  `Oppervlaktewater`: IMBOR volgt deze terminologische verandering op. Binnen de PDF-publicatie is de NEN 3610 inconsistent wat betreft het toepassen van de ene of de andere term (definities zijn identiek). Dit is waarschijnlijk een simpele tekstuele fout.

**Comment by wjtmollema** [comment]
@RiX012 is het inmiddels duidelijk of de bovenstaande zaken doorgevoerd moeten worden, d.w.z. volgen we in benaming van de klassen de online publicatie van het semantische model van de NEN 3610: 2022 of het officiële document?

**Comment by RiX012** [comment]
Zoals je in [issuecomment-1502931054](https://github.com/Stichting-CROW/imbor/issues/1095#issuecomment-1502931054) aangegeven hebt mag je deze verwerken. De benaming maakt ook niet zo heel veel uit. Het gaat met name om de persistente URI.
