### ISSUE TITLE
Foutje in Opkroonhoogteklasse bomen?

### ISSUE THREAD

**Issue by HarroVerhoeven** [Stichting-CROW/imbor#1097]
28 februari 2023 14:33

Beste CROW,

Wij zijn op dit moment bezig met het implementeren van IMBOR voor wat betreft onze bomendata. Dat gaat op zich prima, maar bij het attribuut ‘opkroonhoogteklasse beoogd’ heb ik denk ik een foutje ontdekt.

Als keuzelijst staat daar namelijk het volgende:

Bereikt
Niet van toepassing
Niet van toepassing (te vellen boom)
Nog niet bereikt
Onbereikbaar, overschrijding stam: kroon 1:1
Onbereikbaar, snoei-ingreep ongewenst
Onbereikbaar, snoei-ingreep onverantwoord

Dat is hetzelfde lijstje als ‘opkroonhoogteklasse actueel’, terwijl ik hier een lijst met opkroonhoogteklasses verwacht.

Kunnen jullie hier even naar kijken?

Met vriendelijke groet,

Pieter Jan Karsijns
Geodata-specialist
Team Areaalbeheer

Werkdagen op: ma di do vr

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Strikt genomen is wat hier het probleem is besproken in #1017. De enumeratielijst `BoomOpkroonhoogteklasse` die wordt geciteerd is niet gekoppeld aan `opkroonhoogteklasse beoogd`.

Op basis van de definitie van `opkroonhoogteklasse beoogd` ("Takvrije stam ‘eindbeeld’.") is de verwachting van dhr. Karsijns opkroonhoogteklasses te zien te krijgen logisch. `opkroonhoogteklasse beoogd` dient daarom het `Enumeratietype` `BoomTakvrijeStam` toegewezen te krijgen. Maar voordat dit doorgevoerd kan worden, is het nodig de semantische overlap met `takvrije stam` op het gebied van hun definities te verhelpen.

**Comment by wjtmollema** [comment]
Deze issue komt te vervallen omdat `opkroonhoogteklasse beoogd` is gewijzigd i.r.t. de afstemming met het Handboek Bomen op dit specifieke punt in #1133 .
