### ISSUE TITLE
UNAFACT: afmetingen Compartiment wel in GWSW, maar niet in IMBOR

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1098]
**Melding**
Zie bijgevoegde afbeelding.
![image](https://user-images.githubusercontent.com/90725038/225855604-5a1c5c89-76bc-4516-a0e6-68e751cf5c9f.png)
**Voorgestelde verwerking**
GWSW volgen en `lengte` en `breedte` toevoegen aan de klasse `Compartiment`.

**Comment by wjtmollema** [comment]
**Addendum**
Aansluitend hierop is een check uitgevoerd op de attributen die in GWSW bij relevante objecten zijn opgenomen t.o.v. hoe dit gespiegeld is in IMBOR 2022.

De voorlopige resultaten staan hieronder:
- `opvangcapaciteit` moet toegevoegd worden aan `Slibafscheider`;
- `opvangcapaciteit` moet toegevoegd worden aan `Aansluitput`;
- `sleutelnummer` moet toegevoegd worden aan `Slot`;
- `vorm` moet toegevoegd worden aan `Stroomprofiel`;
- `dikte` moet toegevoegd worden aan `Overstortdrempel`;
- `dikte` en `stromingsrichting` moeten toegevoegd worden aan `Stuwmuur`;

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.

**Comment by WisseDQ** [comment]
Hoe staat het met de gebiedsgrenzen van een compartiment die in GWSW zijn verwerkt. compartimentoriëntatie. Hoe word deze in IMBOR verwerkt? Nu klopt dit niet. Een nieuw issue aanmaken?

**Comment by RiX012** [comment]
> compartimentoriëntatie

@wjtmollema wil je deze eens nakijken in onze laatste werkversie?

**Comment by wjtmollema** [comment]
**Situatie IMBOR 2022**
`Compartimentoriëntatie` komt **niet** voor in de collectie `Topologisch element`
**Situatie werkversie IMBOR 2024**
Zie hiervoor ook de uitwerking in https://github.com/Stichting-CROW/imbor/issues/997#issuecomment-1500300563
In IMBOR 2024 wordt `Compartimentoriëntatie` toegevoegd als `type` van `RioleringNode`, een klasse die de NEN 3610-klasse `Netwerk::Node` implementeert. Er is voor deze uitwerking gekozen omdat de GWSW-aanduiding de volgende is:
`Topologisch element --> Representatie fysiek object --> Knooppunt --> Compartimentoriëntatie`.

In GWSW geldt dat `Compartimentoriëntatie` 'is een kenmerk van' `Compartiment`; dit vertaalt zich naar de NEN 3610 implementatie in IMBOR als: `Compartimentoriëntatie` `isInTopomodel` `Compartiment` en de inverse `Compartiment` `isInNetwerkmodel` `Compartimentoriëntatie`
