### ISSUE TITLE
notatie Jaar versus Datum

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#110]
Binnen het IMBOR model  (2020-08 aangehouden), maar ook relevant voor 2020-01 zijn er veel tegenstrijdigheden als het gaat hoe de attribuutwaarden nu daadwerkelijk moet worden aangehouden.
Hierbij is ook het document 'N1590 Dictionary_IMBOR_2020-08.docx' meegenomen om te kijken welke waarden moet worden aangehouden.
Hierbij uitgegaan dat Jaar ook daadwerkelijk als jaar- numeriek - vrij invoerveld(YYYY) moet worden weergegeven.
In de N1590 Dictionary_IMBOR_2020-08.docx, dan worden veel van de ‘Jaren’ ook als Datumveld aangemerkt i.p.v. “Long Integer”

D = Datumveld / L = Long Integer
Jaar van Aanleg                               D                           
Plantjaar                                           alleen als omschrijving
Bouwjaar                                          L
Theoretisch eindjaar                       D
PraktischEindjaar                            D
JaarRenovatie                                 L /D
JaarUitgevoerdOnderhoud             D
JaarVervanging                               D
Productiejaar                                   L
Kiemjaar                                           D                                          
JaarConserveren                             L/D
JaarVanInspectie                            L
JaarVanKeuring                               L
JaarHerinrichting                            D
BaggerdiktePeiljaar                        L
BaggervolumePeiljaar                    L
Bemonsteringsjaar                         L
Peiljaar                                           L
VerwachtBaggerjaar                      L
Prognosejaar                                 L
JaarReparatie                                 L

Het document 'N1590..."en de  IMBOR accesdatabase 2020-08 spreken op dit punt elkaar dus tegen.

Ander punt is dat veel "jaren" niet relevant zijn voor IMBOR als het gaat om  inventarisatie gegevens omdat dit dynamische gegevens zijn die gegenereerd worden vanuit inspecties of planningsresultaten.  Hierbij is een datum logischer omdat het vaak om berekende waarden gaat. Hierbij zou dan dus de attribuutveld benaming aangepast moeten worden om de uniformiteit en duidelijkheid te vergroten.

Als we kijken naar de velden binnen het IMBOR model (access database) komen de attribuutveld omschrijvingen niet overeen met de definitie ( Bij beheerobject Jaar van Aanleg wordt inde definitie aangegeven dat het ook de plaatsingsdatum kan worden gebruikt : "Jaar waarin het beheerobject is aangelegd of aangeplant (kan ook voor de plaatsingsdatum gebruikt worden)."

**Comment by JochemMollema** [comment]
IMBOR team:  Alle   jaren zijn nu numeriek, geen datumvelden. Jaren zijn bij  verschillende klassen  opgenomen en liggen in het grijze gebied   tussen vaste en dynamische gegevens, maar moeten uiteindelijk allemaal   gestructureerd worden.
--
