### ISSUE TITLE
Gemeente Almelo: Aanpassing IMBOR Bordcodes E08a, E08b, E08c o.b.v. wijziging RVV

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1100]
**Melding**
De gemeente Almelo attendeert het CROW op de volgende wijziging in wetgeving rondom de bordcodes:
![image](https://user-images.githubusercontent.com/90725038/226897054-040c9280-13c1-47cf-ac17-85d1b17efd5e.png)

**Voorgestelde verwerking**
- Definities van de benoemde bordcodes conform RVV maken;
- Verder doorletteren om de bestaande E08b en E08c nog te kunnen registreren (in acht genomen dat E08a nu E08b wordt).

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld

**Comment by wjtmollema** [comment]
**Aanvulling op de definitieve verwerking**

- `E08b` wisselt met `E08e`; en `E08e` wordt `E08a`;
- `E08c` wordt overgenomen en huidige `E08c` wordt `E08q`.
