### ISSUE TITLE
Afleidbare attributen zo veel mogelijk consistent uit IMBOR verwijderen

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1101]
Veel huidige attributen zijn afleidbaar door GIS acties of afleidingen op basis van externe datasets. Om IMBOR klein en zuiver te houden wordt bekeken deze zo veel mogelijk te elimineren. Het gaat bijvoorbeeld om `gebiedstype`, `grondsoort`, `wijk`, `buurt`, etc. 

Dit issue behandeld daarmee ook: #803 #1011 #999 #991 #1054 #914

**Comment by wjtmollema** [comment]
**Addendum**
Hieronder is een werkoverzicht opgenomen van de klassen en attributen die genomineerd zijn voor de wijziging die deze issue voorstelt. Per combinatie van klasse en attribuut is aangegeven wat de reden tot nominatie is.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Klasse | Attribuut | Nominatie-overweging
-- | -- | --
Bouwwerk | bag-identificatie | Het opnemen van de   objectidentificatie uit de Basisregistratie Adressen en Gebouwen (BAG) is   strikt genomen het herhalen van externe informatie binnen IMBOR. Dit gegeven   heeft wel een duidelijke functie, namelijk het koppelen van objecten die in   twee, normaliter gescheiden, registraties voorkomen. Omtrent dit gegeven mag   daarom niet zonder reflectie tot vervallen besloten worden. Dit is een bespreekgeval.
Gebouw | bag-identificatie | Ibid.
Kast | bag-identificatie | Ibid.
Kunstwerk | bag-identificatie | Ibid.
Leiding | beginpunt | Samen met `eindpunt` is   dit attribuut de enige 'foreign key' die IMBOR sinds de introductie van de   semantische relatie binnen een objectklasse heeft opgenomen. Dit is   inconsistent met de wijze waarop er in IMBOR gemodelleerd wordt. Het beginpunt   van een leiding kan uitgedrukt worden m.b.v. de semantische relatie `Leiding   :: is verbonden met :: [Object]`. Er kan als tegenwerping worden aangevoerd   dat als zodanig de semantiek van een 'beginpunt' verloren gaat. Als reactie   kan men stellen dat de stromingsrichting bepaalt welk object het beginpunt en   welk object het eindpunt van een Leiding is. Op dit moment is dat geen   sluitend tegenargument omdat het attribuut `stromingsrichting` niet beschikbaar   is voor leidingen. Daarnaast is dit een attribuut dat door leveranciers en   gebruikers als essentieel wordt ervaren. Ook vanwege de relatie met GWSW is   dit een bespreekgeval met een hoge impact.
Beheerd object | beheergebied | Dit gegeven is   redundant wanneer `Beheergebied` als `ObjectType` wordt geïntroduceerd en er   sprake is van de semantische relatie `Beheergebied :: bevat :: [Object]`.
Geo-object | bronhouder | Het opnemen van de   identificatie van de bronhouder uit de LV BGT is het herhalen van externe   informatie in IMBOR.
Gebiedsindeling | buurtnaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Buurt :: bevat ::   [Object]`.
ReëelObject | conversie-id | Het opnemen van de   identificatie van een object uit een non-IMBOR registratie is eigenlijk het   opnemen van externe informatie in IMBOR. Het is een gegeven dat duidelijk een   praktische meerwaarde heeft, namelijk in de vorm van historie, gebruiksgemak   etc. Echter is de introductie van een veld met een identificatiecode in elke   applicatie zo geregeld, dus de vraag die hier beantwoord moet worden is:   hoort dit in IMBOR?
RuimtelijkGebied | conversie-id | Ibid.
Leiding | eindpunt | Samen met `beginpunt` is   dit attribuut de enige 'foreign key' die IMBOR sinds de introductie van de   semantische relatie binnen een objectklasse heeft opgenomen. Dit is   inconsistent met de wijze waarop er in IMBOR gemodelleerd wordt. Het beginpunt   van een leiding kan uitgedrukt worden m.b.v. de semantische relatie `Leiding   :: is verbonden met :: [Object]`. Er kan als tegenwerping worden aangevoerd   dat als zodanig de semantiek van een 'beginpunt' verloren gaat. Als reactie   kan men stellen dat de stromingsrichting bepaalt welk object het beginpunt en   welk object het eindpunt van een Leiding is. Op dit moment is dat geen   sluitend tegenargument omdat het attribuut stromingsrichting niet beschikbaar   is voor leidingen. Daarnaast is dit een attribuut dat door leveranciers en   gebruikers als essentieel wordt ervaren. Ook vanwege de relatie met GWSW is   dit een bespreekgeval met een hoge impact.
Gebiedsindeling | gebiedstype | Dit gegeven is   redundant bij het gebruik van de semantische relatie   `Natuurgebied/Werkgebied/Centrumgebied/Woongebied/Recreatiegebied (etc.) ::   bevat :: [Object]`.
Gebiedsindeling | gemeentenaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Gemeente :: bevat ::   [Object]`.
Woonplaats | gemeentenaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Gemeente :: bevat ::   [Object]`.
Begroeiing | grondsoortnaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Grondsoort :: bevat ::   [Object]`.
Bouwwerk | grondsoortnaam | Ibid.
Gebouw | grondsoortnaam | Ibid.
Holle leiding | grondsoortnaam | Ibid.
Kunstwerk | grondsoortnaam | Ibid.
Put | grondsoortnaam | Ibid.
Verharding | grondsoortnaam | Ibid.
Gebiedsindeling | ligging | Dit gegeven is   redundant wanneer `Bebouwde komgrens` als `ObjectType` wordt geïntroduceerd en er   sprake is van de semantische relatie `Bebouwde komgrens :: bevat :: [Object]`.
Geo-object | lv-publicatiedatum | Het opnemen van de   datum van opname van een object de LV BGT is het herhalen van externe   informatie in IMBOR.
Gebiedsindeling | openbare ruimtenaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Openbare ruimte :: bevat   :: [Object]`.
Gebiedsindeling | postcode | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Postcode :: bevat ::   [Object]`.
Gemeente | provincienaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Provincie :: bevat ::   [Object]`.
Gebiedsindeling | stadsdeel of kern | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Bebouwingskern :: bevat   :: [Object]`.
Bak | standplaats | Het opnemen van   standplaats is het tot attribuut transformeren van een unieke relatie die   beter met een semantische relatie uitgedrukt kan worden. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Bak]`.
Boom | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Boom`.
Fietssnelheidsindicator | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Fietssnelheidsindicator`.
Klimplant | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Klimplant`.
Paalconstructie | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Paalconstructie]`.
Scheiding | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Scheiding]`.
Solitaire   plant | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Solitaire plant`.
Straatmeubilair | standplaats | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Straatmeubilair]`.
Bak | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Bak]`.
Boom | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Boom`.
Fietssnelheidsindicator | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Fietssnelheidsindicator`.
Klimplant | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Klimplant`.
Paalconstructie | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Paalconstructie]`.
Scheiding | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Scheiding]`.
Solitaire   plant | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   Solitaire plant`.
Straatmeubilair | standplaats   gedetailleerd | Ibid. In dit geval:   `Elementenverharding/Gras- en kruidachtigen/Watervlakte (etc.) :: bevat ::   [ObjectType subKlasseVan Straatmeubilair]`.
Verkeersbord | verkeerszone | Dit is een   bespreekgeval dat lijkt op wegcategorie duurzaam veilig. Volgens   Verkeerskundig adviesbureau Ronnico heeft het meerwaarde dit bij het bord te   registreren. Echter zou het met de volgende semantische relatie uitgedrukt   kunnen worden: `Verkeerszone :: bevat :: Verkeersbord`.
Gebiedsindeling | waterschapnaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Waterschap :: bevat ::   [Object]`.
Verharding | wegcategorie duurzaam veilig | Dit is een bespreekgeval. Via vlakkenovererving zou dit   gegeven van een `Weg` overgerfd kunnen worden. De toeschrijving aan `Wegas` is   logisch vanwege de constructie van het wegennetwerk uit `Wegas` en `Wegknoop`.   Een `Weg` is een geometrische vlakrepresentatie van een `Wegas` of een `Wegknoop`.   Echter kan het logischerwijs niet zo zijn dat `Wegas :: bevat :: [ObjectType   subKlasseVan Verharding]` zoals `Weg :: bevat :: [ObjectType subKlasseVan   Verharding]` wel logisch is. Er kan dus    voor gekozen worden om `wegcategorie duurzaam veilig` op te nemen als   attribuut van `Weg` of om een andere oplossing te bedenken.
Verkeersbord | wegcategorie duurzaam veilig | Ibid.
Wegas | wegcategorie duurzaam veilig | Ibid.
Verharding | wegcategorie duurzaam veilig gedetailleerd | Ibid.
Verkeersbord | wegcategorie duurzaam veilig gedetailleerd | Ibid.
Wegas | wegcategorie duurzaam veilig gedetailleerd | Ibid.
Aquaduct | wegnummer | De opname van dit gegeven is   redundant, omdat de overerving via een semantische relatie met `Weg` plaats kan   vinden.
Beweegbare   brug | wegnummer | Ibid.
Ecoduct | wegnummer | Ibid.
Flyover | wegnummer | Ibid.
Geluidsscherm | wegnummer | Ibid.
Kademuur | wegnummer | Ibid.
Luchtscherm | wegnummer | Ibid.
Onderdoorgang | wegnummer | Ibid.
Tunnel | wegnummer | Ibid.
Vaste brug | wegnummer | Ibid.
Verharding | wegnummer | Ibid.
Viaduct | wegnummer | Ibid.
Weg | wegnummer | Ibid.
Wegas | wegnummer | Ibid.
Wegvak | wegnummer | Ibid.
Verharding | wegvaknummer | De opname van dit gegeven is   redundant, omdat de overerving via een semantische relatie met `Wegvak` plaats   kan vinden.
Buurt | wijknaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Wijk :: bevat :: Buurt`.
Gebiedsindeling | wijknaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Wijk :: bevat ::   [Object]`.
Bebouwingskern | woonplaatsnaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Woonplaats :: bevat ::   Bebouwingskern`.
Gebiedsindeling | woonplaatsnaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Woonplaats :: bevat ::   [Object]`.
Wijk | woonplaatsnaam | Dit gegeven is   redundant bij het gebruik van de semantische relatie `Woonplaats :: bevat ::   Wijk`.



</body>

</html>

**Comment by wjtmollema** [comment]
**Addendum**
**Bespreekpunt 1: bag-identificatie** : Sleutelvelden zijn wel belangrijk voor de aansluiting met andere modellen, maar is dit benodigd binnen IMBOR?  `bag-identificatie` verdwijnt als attribuut maar wordt meegenomen in de ontwikkeling van een generieke oplossing om objecten uit verschillende registraties aan elkaar te verbinden. BAG, BGT, IMGeo: externe modellen waarvoor beschreven moet worden wat de relaties zijn. Op het niveau van de verwijzingen tussen representaties uit verschillende registraties van hetzelfde object, is onderkend dat dit buiten de scope van IMBOR valt.

**Bespreekpunt 2 Gebiedsindeling**:  Het streven is de attributen uit de klasse te gaan uitdrukken met semantische relaties. Voordelen: objecten kunnen in werkelijkheid in meerdere openbare ruimtes liggen; als zodanig worden **intersecties** van objecten mogelijk gemaakt (denk aan een `Park` dat intersecties heeft met meerdere `Openbare ruimte` begrenzingen. Daarnaast is het expressievermogen van semantische relaties groter. Echter is het zo dat bij veel gemeenten er meer polygonen moeten worden vervaardigd voor het realiseren van de semantische relaties die lopen van uniek object tot uniek object: voor `Wijk`, `Buurt`, `Woonplaats`, `Gemeente`, `Waterschap`, `Provincie` etc. is er geen probleem, omdat deze begrenzingen algemeen beschikbaar zijn. Begrenzingen van openbare ruimtes en komgrenzen worden een probleem omdat deze vaak nog niet aanwezig zijn; wel zou de BAG voor de eerstgenoemden een bron kunnen zijn. Voor de problematische gevallen is een overgangssituatie mogelijk die (i) wel de implementatie van de semantische relatie omvat; maar (ii) (bijvoorbeeld) werkt met geometrieloze objecten totdat de begrenzingen als IMBOR-objecten zijn opgenomen. 

Conclusie voor **Bespreekpunten 1 & 2**: Doorvoeren in werkversie en presenteren aan de softwareleveranciers.

**Comment by RiX012** [comment]
@GreenpointAdviesPN ik denk dat met deze passage uit [#issuecomment-155114492](https://github.com/Stichting-CROW/imbor/issues/1101#issuecomment-1551144922) toch eigenlijk voldoen aan jouw terechte zorg?
>Bespreekpunt 2 Gebiedsindeling: Het streven is de attributen uit de klasse te gaan uitdrukken met semantische relaties. 
>...
>Voor de problematische gevallen is een overgangssituatie mogelijk die (i) wel de implementatie van de semantische relatie omvat; maar (ii) (bijvoorbeeld) werkt met geometrieloze objecten totdat de begrenzingen als IMBOR-objecten zijn opgenomen.

We stellen daarmee eigenlijk dat de gebieden _wel_ op zich staande objecten zijn. Maar dat er _niet_ persé een geometrie aan vast zit. Dit lijkt me technisch haalbaar en wanneer er later wel een geometrie is kan dit zo worden toegevoegd.
@wjtmollema we zullen dan trouwens ook de multipliciteit van geometrie bij deze gebieden moeten aanpassen.

**Comment by GreenpointAdviesPN** [comment]
Ik snap de theorie nu, maar het gebruik van het model wordt er minder praktisch van op dit vlak, denk ik.
Hoe zit het eigenlijk met exporteren? Is er al een voorbeeld en of een validator i.o.d.?

**Comment by RiX012** [comment]
> Ik snap de theorie nu, maar het gebruik van het model wordt er minder praktisch van op dit vlak, denk ik.

Ik begrijp wat je bedoelt, maar ik denk: Ja en Nee. Ja op de conventionele manier misschien een beetje geredeneerd vanuit tabellen. Nee, want op de manier waarop wij (en de rest van de sector) onze modellen gaan inrichten wordt het consistenter. 

We hebben geen uitwisselformaat als je dat bedoelt. Het beste wat we tot nu toe aanbieden is dit: https://docs.crow.nl/imbor/uitwisseling_rdf/. Hier zit ook een mogelijkheid tot validatie bij.

**Comment by wjtmollema** [comment]
**Wat staat er hiervan nog open?**

- `grondsoortnaam`
- `standplaats` & `standplaats gedetailleerd` --> welke semantische relatie moet dit worden? `is verbonden met` of een nieuwe (`heeft als standplaats`)?
- `beginpunt` & `eindpunt`: zo laten conform afspraak met GWSW
- `bronhouder` --> redundant want als het relevant is, zit dit als voorvoegsel in `domein`
- `conversie-id` --> Wordt veel gebruikt; wellicht handhaven?
- `lv-publicatiedatum` --> voorstel om dit te verwijderen. Dit is een BGT-gegeven en wordt nu bij _alle_ geo-objecten vastgelegd, d.w.z., het levert veel lege ruimte op.
- `relatie` --> voorstel om dit te handhaven.
- `verkeerszone` --> voorstel om dit te handhaven totdat de werkgroep Borden operationeel is.
- `wegcategorie duurzaam veilig` & `wegcategorie duurzaam veilig gedetailleerd` --> bespreekgeval. Wat vinden de CROW-experts die dit bedacht hebben?
- `wegnummer` --> Eigenlijk het `objectnummer` van een `Weg`.
- `wegvaknummer` --> Eigenlijk het `objectnummer` van een `Wegvak`.

**Comment by wjtmollema** [comment]
De keuzes die in de uitwerking van dit onderwerp zijn gemaakt, zijn geleid door het idee dat IMBOR 2022 in de modellering nog onvoldoende geconformeerd was aan de NEN 2660-2. Vele IMBOR-attributen behelzen namelijk (ruimtelijke) relaties tussen verschillende `Objecten` (bijv. tussen `Ruimtelijke gebieden` en `Reële objecten`). Dit issue diende het oppakken en wegwerken van al deze gevallen. In de gevallen dat er al een Objecttype bestaat zodat een relatie met dat objecttype de eigenschap kan vervangen, vervalt het attribuut simpelweg. In andere gevallen zijn er objecttypes toegevoegd om de vervanging van eigenschap door semantische relatie mogelijk te maken.

Finale wijzigingen:
a.	Het laten vervallen van het attribuut ‘`grondsoortnaam`’ wordt doorgevoerd. Dit kan volledig vervangen worden door de volgende expressie: `Grondsoort :: bevat :: ReëelObject`. 
b.	Het attribuut ‘`relatie`’ (toegepast bij `Kast` en `Oplaadpaal`) wordt hernoemd naar ‘`aansluitingsrol`’.
c.	`lv-publicatiedatum` en `bronhouder` vervallen.
d.	Alleen het geval ‘`standplaats / standplaats gedetailleerd`’ wordt nog onderzocht. Het is hier namelijk de vraag of er een unieke semantische relatie geïntroduceerd moet worden, alleen voor dit gegeven.
e.	`beginpunt, eindpunt, conversie-id, verkeerszone, wegcategorie duurzaam veilig en wegcategorie duurzaam veilig gedetailleerd, wegnummer` en `wegvaknummer` blijven behouden, omdat het niet te verwachten is dat deze attributen op een duurzame manier vervangen kunnen worden door semantische relaties tussen bestaande objecten.

**Comment by RiX012** [comment]
> e. `beginpunt, eindpunt,`

Kan dit door de NODE en LINK relatie niet weg?

> `wegnummer` en `wegvaknummer`

Dit wordt waarschijnlijk opgepakt wanneer we aan de slag gaan met de WEGINFRA-OTL

> d. Alleen het geval ‘`standplaats / standplaats gedetailleerd`’ wordt nog onderzocht. Het is hier namelijk de vraag of er een unieke semantische relatie geïntroduceerd moet worden, alleen voor dit gegeven.

Als dit een uniek geval is, klinkt het logischer om hier een vrij attribuut voor te blijven gebruiken.

**Comment by wjtmollema** [comment]
1. Goed punt. Dit is een bespreekgeval, o.a. met RIONED. De enige plek waar dit gebruikt is bij de klasse `Leiding`. Als dit verplaatst wordt, is voor het registreren van de richting van de leiding altijd een topologische representatie nodig. Ik vind het lastig te overzien wat hiervan de consequenties zijn. Als besloten wordt sowieso GWSW te volgen voor IMBOR Stedelijk Water, dan gaan deze attributen niet vervallen.
2. Oké. 
3. Het huidige attribuut vertoont mankementen, namelijk dat (1) een Enumeratielijst ontbreekt en (2) dat de eigenschap dynamisch is, maar niet dynamisch gemodelleerd is, denk aan een Boom die in Onverhard staat, maar vervolgens wordt dit vlak gewijzigd naar Gras- en kruidachtigen en dat moet afzonderlijk gemuteerd worden bij de Boom. Bespreken in volgende IMBOR-teamssessie @RiX012 @JochemMollema

**Comment by wjtmollema** [comment]
1. Reactie: Nieuwe issue voor hermodellering van `beginpunt` en `eindpunt` als subproperty van `is verbonden met`
2. Reactie: Laten zoals het is.
3. Reactie: Nieuwe issue voor het openen van de discussie over de hermodellering van `standplaats` als subproperty van `is verbonden met`

**Comment by wjtmollema** [comment]
Al deze zaken zijn verwerkt en de nieuwe issues zijn geopend. @RiX012 Wat mij betreft kan de issues dus gesloten worden.

**Comment by wjtmollema** [comment]
#1305 
#1306

**Comment by RiX012** [comment]
Mogelijke impact:

1. Veel attributen weg
2. Meer geometrieën nodig
3. Beheersystemen moeten dit inregelen
