### ISSUE TITLE
Gebruiksfunctie Klimboom zit fout in het model

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1102]
Gebruiksfunctie Klimboom zit fout in het model

**Comment by wjtmollema** [comment]
**Verwerking**
De fout zit hem in de distributie van `Klimboom` over de `...Gebruiksfunctie` `Enumeratietype`s. Op dit moment komt `Klimboom` voor bij:

```
- BouwlandGebruiksfunctie
- RietlandGebruiksfunctie
```
Dit is incorrect. `Klimboom` zou enkel moeten voorkomen als domeinwaarde van `Boom`. Er wordt voorgesteld bovenstaande fouten te verwijderen uit imborKern_EnumeratiesDomeinwaarden en `Klimboom` op te nemen binnen `Functie` als '`Faciliteren van klimmen`' zodat de volgende relatie van toepassing kan zijn: `Boom :: voertUit :: Faciliteren van klimmen`

**Comment by RiX012** [comment]
Prima

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
