### ISSUE TITLE
BoomBoomhoogteklasse - waarden zitten er twee keer in

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1103]
BoomBoomhoogteklasse - waarden zitten er twee keer in

**Comment by wjtmollema** [comment]
**Constatering**
Deze fout is veroorzaakt door het verhelpen van het probleem van #1017 die op 30-11-2022 verwerkt is in de werkversie.

Het probleem is dat in de huidige Access-query die domeinwaarden van enumeraties weergeeft in de query die domeinwaarden van attributen toont, niet goed om kan gaan met het meervoudige gebruik van een enumeratiedomeinwaarde door twee attributen. Aangezien in imborKern_K_KlassenAttributen het `Enumeratietype` van `BoomBoomhoogteklasse` wel bij de juiste attributen benoemd staat, is dit een Access-bug, maar geen modelleringsfout. De IMBOR online viewer van IMBOR 2022 heeft dit probleem dan ook niet voor `BoomBoomhoogteklasse`. Zie [link](https://docs.crow.nl/onto-verkenner/imbor/?#/view?uri=https%3A%2F%2Fdata.crow.nl%2Fimbor%2Fdef%2F97834ad8-6f73-4e17-8455-1f1b9487e9cd).

De dubbeling in de werkversie is verholpen, derhalve kan deze issue gesloten worden.
