### ISSUE TITLE
UNAFACT: Het objecttype Bodem is een verkeerde implementatie van NEN3610: Bodem

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1105]
**Constatering**
Het `ObjectType` `Bodem` zou eigenlijk geen `ObjectType` mogen zijn; het komt eigenlijk overeen met de [`NEN 3610-klasse:Bodem`](https://github.com/Geonovum/nen3610-werkomgeving/blob/main/model/respec/nen3610-2022-model.md#bodem-bodem). Dit is een abstracte klasse en een `subKlasseVan` `ReeelObject` zoals ook `Begroeiing`, `Constructie` en `Oppervlaktewater` dat zijn. Los van dat dit zowel binnen NEN 3610, SOR als IMBOR het diepste niveau is in de vertakking van `ReeelObject`, is het nog niet zinnig om `Bodem` te instantiëren als `ObjectType`. Immers, gezien de definitie ("Bovenste deel van de aarde, exclusief oppervlaktewater.") zou dit een vreemd object opleveren. Het is gezien de definitie ook onlogisch dat dit nu een `subKlasseVan` `Beheerd object` is.

De toelichting bij `Bodem` op pagina 64 van NEN 3610 verklaart waarom de klasse bestaat: 

> Bodem verwijst naar een typering en/of benoeming van het aardoppervlak, waarbij de bodem doorloopt onder het oppervlaktewater. Bodem omvat ook de daaronder liggende bodemmaterialen met indelingen die kunnen verschillen per vakgebied zoals bodemkunde, geohydrologie en geomorfologie.

Deze toelichting geeft te denken of `IMBOR-ObjectType Grondsoort` niet een `subKlasseVan` `Bodem` zou moeten zijn in plaats van louter een `subKlasseVan` `Geo-object`, zoals nu het geval is.

**Voorgestelde verwerking**
- Het laten vervallen van het `ObjectType` `Bodem`, oftewel het aanpassen van `Bodem` van `ObjectType` naar `Klasse`;
- Het maken van `Grondsoort` tot  `subKlasseVan` `Bodem`.

**Comment by RiX012** [comment]
De tweede optie doorvoeren. `Grondsoort` als subklasse van `nen3610:Bodem`. Dit is ook conform de toelichting die staat bij de NEN3610:2022.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Er wordt toestemming gevraagd om de issue te sluiten.
