### ISSUE TITLE
Gemeente Altena: toevoegen attribuut Jaar van oorsprong bij objecttype Weg

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1106]
Gemeente Altena: toevoegen attribuut Jaar van oorsprong bij objecttype Weg

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- `jaar van ontstaan` of `ontstaansjaar` als attribuut toevoegen (Rijkswaterstaat spreek bijvoorbeeld over het _ontstaan_ van een `Weg` i.p.v. over de _oorsprong_ van een `Weg`.
- Het toevoegen van `jaar van ontstaan` of `ontstaansjaar` aan de klasse `Weg`. 
- Overwegen of `jaar van ontstaan` of `ontstaansjaar` nog bij andere `Virtuele ruimte`s toegevoegd moet worden of in het algemeen bij `Virtuele ruimte` als tegenhanger van `jaar van aanleg` bij `Reëel Object`.

**Comment by wjtmollema** [comment]
**Conclusie**
`jaar van ontstaan` wordt toegevoegd op het niveau van `Virtuele ruimte` omdat hier in meer gevallen een gebruikssituatie voor is (denk aan `Hondenbeleidsgebied`, `Sportveld`, `Speelterrein` e.d.).

Verwerkt zoals voorgesteld.

**Comment by wjtmollema** [comment]
Er wordt om toestemming verzocht deze issue te sluiten.

**Comment by RiX012** [comment]
Deze toch nog even even bespreken ihkv tijdlijnen

**Comment by wjtmollema** [comment]
**Bespreekpunt**
Dezelfde conclusie als bij `jaar van aanleg` zou m.i. gelden.

**Comment by wjtmollema** [comment]
In https://github.com/Stichting-CROW/imbor/issues/1075 wordt `jaar van aanleg` gevrijwaard van vervallen omdat het nuttig is vanwege het gemak dat het gebruikers oplevert. Het hier voorgestelde attribuut `jaar van oorsprong` zou een gebruiker van `Ruimtelijke gebieden` eenzelfde gebruiksgemak opleveren.

**Comment by RiX012** [comment]
Ik zou liever zien dat er een attribuutsoort gemaakt wordt die voor beiden geldt.

**Comment by wjtmollema** [comment]
**Voorstel**
Een attribuut `jaar constitutie` (of een synoniem daarvan) voor de klasse `FysiekObject`

**Comment by RiX012** [comment]
@wjtmollema  doorvoeren, pushen en close

**Comment by wjtmollema** [comment]
Post hoc kanttekening: op deze manier beschikt `Materie` ook over `jaar constitutie`. 'Is dat een probleem?' moeten we ons afvragen.

**Comment by RiX012** [comment]
> Post hoc kanttekening: op deze manier beschikt `Materie` ook over `jaar constitutie`. 'Is dat een probleem?' moeten we ons afvragen.

Nee vind ik geen probleem. Zeker niet als multipliciteit 0:1 is

**Comment by wjtmollema** [comment]
Dan kan deze issue bij deze gesloten worden.

**Comment by RiX012** [comment]
Overlap met #1321

**Comment by JochemMollema** [comment]
@RiX012 : deze issue kan gesloten worden.
