### ISSUE TITLE
Afstemming met Handboek Bomen: Bepaling minimale dataset

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1109]
**Melding**
Op basis van de met het Norminstituut besproken afstemming tussen IMBOR en het Handboek Bomen wordt de minimale dataset gebaseerd op het Handboek Bomen 2022 bepaald.

**Resultaat**
In de onderstaande tabel wordt de minimale dataset weergegeven. De onderstaande tabel is onderhevig aan **werk in uitvoering**.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

ObjectType | attribuut | Minimale dataset | Herkomst attribuut
-- | -- | -- | --
`Boom` | `objectnummer` | Ja | IMBOR 2022
`Boom` | `jaar van aanleg` | Ja | IMBOR 2022
`Boom`  | `beheerder` | Ja | IMBOR 2022
`Boom`  | `eigenaar` | Ja | IMBOR 2022
`Boom`  | `controlefrequentie BVC` | Ja | Hernoeming van `controlefequentie` specifiek voor `Boom` vanwege afstemming met Handboek Bomen, zie #1111 
`Boom`  | `onderhoudsfrequentie` | Ja | IMBOR 2022, maar zie #1114 
`Boom`  | `soortnaam` | Ja | IMBOR 2022
`Boom`  | `boombeleidsstatus` | Ja | IMBOR 2022, maar zie #1117 
`Boom`  | `beoogde omloop boom`| Ja | IMBOR 2022, maar zie #1065 
`Boom`  | `bomenstructuur` | Ja | Hernoeming van `boomgroep` vanwege afstemming met Handboek Bomen, zie #1119
`Boom`  | `boomhoogteklasse actueel` | Ja | IMBOR 2022, zie #1125
`Boom`  | `boomhoogteklasse eindbeeld` | Ja | IMBOR 2022, zie #1125
`Boom`  | `beoogde opkroonhoogte` | Ja | Herziening van `opkroonhoogteklasse beoogd` vanwege afstemming met Handboek Bomen, zie #1133
`Boom`  | `stamdiameterklasse` | Ja | IMBOR 2022, maar zie #1135 
`Boom`  | `vereiste vrije doorgang` | Ja | Herziening van `takvrije zone [primair/secundair]` en `vrije doorrijhoogteklasse [primair/secundair]` vanwege afstemming met Handboek Bomen, zie #1136 en #1137
`Boom`  | `type` | Ja | IMBOR 2022, maar zie #1139

</body>

</html>

**Comment by JochemMollema** [comment]
Er is een nieuwe versie van de minimale dataset afgestemd op handboek bomen versie 2022.
