### ISSUE TITLE
Boomspiegel - Weginrichtingsobjecten

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#111]
In de versie 2018-2 was de boomspiegel bij Weginrichtingsobjecten opgenomen. In 2020-01 is deze blijkbaar komen te vervallen en nog niet terug gekomen in 2020-08.
Nu wordt de boomspiegel nog wel bij Boom als attribuut opgenomen maar via een koppeling o.b.v. een GUID.
Waar moet deze worden opgehaald als deze niet meer beschikbaar is binnen het model ?
![Weginrichtingsobjecten - groep](https://user-images.githubusercontent.com/40396592/96421495-22995300-11f7-11eb-988a-0a77af5360b0.png)
![Boomspiegel attribuut - GUID](https://user-images.githubusercontent.com/40396592/96421514-2927ca80-11f7-11eb-9f40-45d120cc3570.png)

**Comment by JochemMollema** [comment]
Attribuut   met GUID voor Boomspiegel komt te vervallen, koppeling met objecten via   semantische relaties.
--
