### ISSUE TITLE
Graag Haaientand(en) toevoegen als synoniem van een voorwaarschuwingsdriehoek

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1126]
Graag Haaientand(en) toevoegen als synoniem van een voorwaarschuwingsdriehoek

**Comment by wjtmollema** [comment]
**Constatering**
De term `Driehoeksmarkeringen` heeft op dit moment al als synoniem `Haaientanden` volgens de verwerking van #1009. 

Met de `Voorwaarschuwingsdriehoek: bibeko/bubeko/fietspad` wordt een enkele driehoek van variabele grootte bedoeld, zie hieronder:
![image](https://user-images.githubusercontent.com/90725038/230549940-f39f14ac-d740-4ee4-adce-017574c9def0.png)

Het lijkt hier niet te gaan om een markering die in de volksmond een 'haaientand' wordt genoemd.
