### ISSUE TITLE
object begin- en eindtijd

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#113]
In het IMBOR model worden de attribuut namen in alle gevallen met een hoofdletter opgenomen met uitzondering van objectBeginTijd en objectEindTijd. We kunnen niet achterhalen of dit bewust is, maar gezien we in de markt geconfronteerd worden met opmerking dat  termen niet conform IMBOR zijn is de vraag of dit een uitzondering is of een typefout.

Als het geen type fout is reist de vraag waarom de andere attribuutnamen niet op dezelfde manier zijn opgenomen.

Als het wel een  typefout, dan graag aanpassen t.b.v. de uniformiteit en het voorkomen van  discussies. 

Note: Als de reden is dat deze overeen kan komen met de BGT registratie, dan hoort deze bij het attribuut "vak" bgt, als het puur om de begin - eindtijd van het beheerobject gaat, dan zal het ook met een hoofdletter moeten beginnen.

![Attribuut beheerobject begin - eind tijd](https://user-images.githubusercontent.com/40396592/97594178-b098e900-1a02-11eb-8be3-374ee2754179.png)

**Comment by JochemMollema** [comment]
Teksten   aangepast ook voor andere BGT attributen
--

**Comment by JochemMollema** [comment]
Voor de attributen wordt een eenduidige naamgeving toegepast in IMBOR 2021

**Comment by RiX012** [comment]
Het gaat om de NEN2660 Labels richtlijn, want de identifier is de GUID string (codering dus).

Dus attributen en relaties lowercase met spaties: “aangemaakt door” en “is verbonden met” 
De rest ‘gewoon’ NL taal: “Drijvende oever” en “Niet van toepassing"
