### ISSUE TITLE
Kleur meubilair dubbel

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#114]
In de access db staat bij objecttypegroep de kleur er dubbel in
![Meubilair - kleur dubbel](https://user-images.githubusercontent.com/40396592/98551236-5ff47c00-229d-11eb-9139-c33c9fd65431.png)

**Comment by JochemMollema** [comment]
Hoi Redmer, deze is aangepast in de werkversie.

Kleur bij Meubilair als 1 op N blijft staan, tweede attribuut met kleur vervallen. Aangepast in de tabel X_ObjecttypesAttributen.\

Groet,

Jochem

Van: Redmer Kronemeijer <notifications@github.com>
Verzonden: maandag 16 november 2020 12:42
Aan: Stichting-CROW/imbor <imbor@noreply.github.com>
CC: Jochem Mollema <jochem@inarea.nl>; Assign <assign@noreply.github.com>
Onderwerp: Re: [Stichting-CROW/imbor] Kleur meubilair dubbel (#114)


Assigned #114<https://github.com/Stichting-CROW/imbor/issues/114> to @JochemMollema<https://github.com/JochemMollema>.

**Comment by JochemMollema** [comment]
Kleur   met 1 op N bij Klasse Meubilair.
--
