### ISSUE TITLE
Maastricht: afvalobjecten

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1142]
Graag controleren of de volgende "Afvalobjecten" in IMBOR verwerkt zijn:

- Milieuperron
- Milieupark
- Afvalbrengstation
- Milieustraat

Toevoegen bij type afval: Luiers en incontinentiemateriaal

Borden milieuzone

**Comment by wjtmollema** [comment]
**Controle**

- Milieuperron: Niet in werkversie IMBOR 2023.
- Milieupark: Niet in werkversie IMBOR 2023.
- Afvalbrengstation: `Verzamelplaats :: type :: Inzamelpunt` heeft als synoniem `Afvalaanbiedlocatie`. Dit heeft overeenkomsten met een Afvalbrengstation, maar binnen een Afvalbrengstation zijn er meerdere Inzamelpunten. Dit zit dus nog niet letterlijk in de werkversie IMBOR 2023. 
- Milieustraat: Niet in werkversie IMBOR 2023.
- type afval: Luiers en incontinentiemateriaal: Aanwezig als de domeinwaarde van `Luiers` van `AfvalbakTypeAfval` en `ContainerTypeAfval`.
- Borden milieuzone: De borden `C22a` en `C22b` voor de start en het einde van een milieuzone zijn aanwezig. Zie onderstaande afbeelding. 
![image](https://user-images.githubusercontent.com/90725038/232400365-823a4cf6-9218-4e8b-9960-5a11e4b4a8dc.png)

Echter gaat het bij de nieuwe bebording voor milieuzones om de volgende borden, die nog niet in de werkversie IMBOR 2023 opgenomen zijn (zie https://www.milieuzones.nl/verkeersbord-en-onderborden): 
![image](https://user-images.githubusercontent.com/90725038/232400526-74b48329-5069-4088-ab4f-619d953d7c9f.png)
![image](https://user-images.githubusercontent.com/90725038/232400710-2770a854-ca4b-4d98-92d3-2e9ac5753e06.png)
![image](https://user-images.githubusercontent.com/90725038/232400782-1ddcc307-25f2-45c5-8d71-c5d911d04005.png)

**Voorgestelde verwerking gewenste toevoeging**

- `Millieuperron`: Bij de introductie van een `ObjectType` `Afvalscheidingslocatie` kan het `Milieuperron` bij `AfvalscheidingslocatieType` worden ondergebracht. Een `Verzamelplaats` kan aanwezig zijn binnen een `Afvalscheidingslocatie`.
- `Milieupark`:  `Milieupark` kan bij `AfvalscheidingslocatieType` worden ondergebracht.
- `Afvalbrengstation`: `Afvalbrengstation` kan bij `AfvalscheidingslocatieType` worden ondergebracht.
- `Milieustraat`: `Milieustraat` als synoniem van  `Afvalbrengstation` worden beschouwd.
- `type afval :: Luiers en incontinentiemateriaal`: Term `Luiers` wijzigen naar `Luiers en incontinentiemateriaal`.
- Borden milieuzone: Het toevoegen van de volgende zes bordcodes: `C22a-1`, `C22a-2`, `C22a-4`, `C22a-5`, `C22a-6`, `C22a-7`, `C22a-8` en `C22a-9`. Deze codes moeten echter gecontroleerd worden door bevoegde experts.

**Comment by wjtmollema** [comment]
**Tussentijdse terugkoppeling**
Verwerkt zoals voorgesteld excl. de voorgestelde toevoegingen voor het `Verkeersbord`. Er wordt voorgesteld dit aan een expertgroep voor te leggen.

**Openstaand voorstel**

**Comment by JochemMollema** [comment]
De voorgestelde uitwerking gaat over het toevoegen van 9 nieuwe onderborden:
Term
C22a1
C22a2
C22a3
C22a4
C22a5
C22a7
C22a8
C22a9

**Comment by JochemMollema** [comment]
@RiX012 deze isue kan gesloten worden.
