### ISSUE TITLE
Maastricht: registratie Geveltuinen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1143]
Maastricht: registratie Geveltuinen

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Geveltuinen kunnen voorkomen als verschillende soorten `Begroeiing`. Dit moet geïntegreerd worden in de huidige indeling van verschijningsvormen. Het voorstel is om `Geveltuin` op te nemen als `gebruiksfunctie` bij `Struiken`, `Planten` en `Gras- en kruidachtigen`.

**Comment by wjtmollema** [comment]
**Conclusie**
Er is gekozen voor het toevoegen van het `ObjectType` `Geveltuin` als subklasse van `Vegetatieobject`. Dit is dezelfde modellering als is toegepast voor `Gevelgroen`. Dit is als zodanig verwerkt.

**Comment by wjtmollema** [comment]
Er wordt om toestemming verzocht deze issue te sluiten.
