### ISSUE TITLE
Almere: bespreken of Wadi een objecttype moet worden i.p.v. een functie

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1144]
Almere: bespreken of Wadi een objecttype moet worden i.p.v. een functie

**Comment by wjtmollema** [comment]
**Addendum**
Bij `Gras- en kruidachtigen` zijn attributen zoals `uitstroomniveau`, `bergend vermogen` etc. opgenomen. Er wordt voorgesteld dit te verplaatsen naar `Regenwaterbuffer`. Idem voor de subklassen van `Verharding` waarbij dit van toepassing is.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Of `Wadi` ook dient te vervallen als `gebruiksfunctie` moet blijken uit #878.
