### ISSUE TITLE
Almere: vastleggen van de berging van water in/onder een weg

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1145]
Almere: vastleggen van de berging van water in/onder een weg

**Comment by wjtmollema** [comment]
**Constatering**

- Er moet besproken worden of dit niet al afgevangen is met het `ObjectType` `Bergingsbassin`;
- Los van die conclusie kan er overwogen worden om aan een `ObjectType` van de klasse `Verharding` de `gebruiksfunctie` `Ondergrondse waterberging` toe te kennen.

**Comment by wjtmollema** [comment]
![image](https://user-images.githubusercontent.com/90725038/232417053-9661136f-e91f-4944-bd73-d7d8be7ef55e.png)

**Comment by MarinusVonhof** [comment]
Dit aanpassingsvoorstel is bij RIONED geregistreerd onder nr 1384.
Op 2 november 2023 volgt beoordeling door de werkgroep GWSW-Basis en daarna volgt publicatie van de uitslag op https://data.gwsw.nl/ .
