### ISSUE TITLE
Toevoegen talud- en drempelmarkeringen

### ISSUE THREAD

**Issue by JortSmit** [Stichting-CROW/imbor#1146]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
In IMBOR lijken talud- en drempelmarkeringen te ontbreken in het onderdeel 'Wegmarkeringen'. Zou je deze toegevoegd kunnen worden?

**Beschrijf de oplossing die je voor je ziet**
Een toevoeging van talud- en/of drempelmarkeringen in IMBOR. 

**Wat voor alternatieven heb je overwogen?*
Niet van toepassing

**Comment by RiX012** [comment]
Dank voor de input, we delen dit toe aan de subgroep Wegmarkeringen

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gealloceerd naar https://github.com/Stichting-CROW/imbor/issues/1095. Derhalve wordt deze issue gesloten.
