### ISSUE TITLE
Beschoeiing en Plantenbak hebben synoniem dat gelijk is aan de term

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1147]
In de imborvoc_termen heeft het objecttype "Beschoeiing" een synoniem dat exact hetzelfde is. Dit synoniem kan eruit.
Het zelfde geldt voor "Plantenbak".

**Comment by wjtmollema** [comment]
Dank voor het melden.

**Verwerking**
Beide synoniemen zijn verwijderd uit de werkversie van IMBOR 2023.
