### ISSUE TITLE
UNAFACT: Duiker, Hevel en Sifon zijn zowel Kunstwerk als Leiding

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1148]
**Melding**
De `ObjectType`n `Duiker`,  `Hevel` en `Sifon` zijn in de werkversie `subKlassenVan` zowel `Kunstwerk` als `Leiding`. Dit is zo omdat deze `ObjectType`n op het raakvlak van Civiele constructies met Riolering bestaan en gegevens van de attributen uit beide klassen van in de praktijk toepassing zijn.

Dit levert echter problemen op voor de attributen `vorm` en `zettingsgevoeligheid`. Deze attributen worden namelijk door `Duiker`,  `Hevel` en `Sifon` geërfd van zowel `Kunstwerk` als `Leiding`. Dit is in tegenspraak met [modelleerregel 3.11](https://docs.crow.nl/imbor/modelleerregels/#relatie-tussen-een-klasse-en-een-attribuut-is-1-1-r0020), wanneer hieruit wordt afgeleid dat _als_ dit voor klasse geldt dat dit dan ook geldig is voor `ObjectType`.

**Voorgestelde verwerking**
Er zijn meerdere oplossingen mogelijk:

1. Aangezien de klasse `Leiding` meer onderscheidende attributen toekent dan `Kunstwerk`, kan er voor gekozen worden `Duiker`,  `Hevel` en `Sifon` exclusief tot `Leiding` te laten behoren, waarbij een selectie van de benodigde attributen uit `Kunstwerk` aan de klassen van de `ObjectType`n zelf worden toegewezen.
2. `vorm` en `zettingsgevoeligheid` kunnen hoger in de klassenhiërarchie worden geplaatst, namelijk bij deze gedeelde moederklasse van `Kunstwerk` en `Leiding`: `Constructie`.
3. Er wordt een modelleerpatroon geintroduceerd die dubbele overerving voorkomt door de dubbele attributen te laten samenvallen door een 'hoofdsuperklasse' aan te wijze op een bepaald niveau van overerving (in dit geval niveau 8).

Optie 1 geniet de voorkeur, omdat optie 2 van grote impact is op alle `subKlassenVan` `Constructie`. Er bestaan namelijk `EnumeratieType`s voor `vorm` binnen de `subKlassenVan` `Constructie` die zijn geïntroduceerd op basis van semantiek. Optie 3 is elegant, maar omslachtig omdat het hier om een uitzondering gaat i.p.v. om een breder probleem.

**Comment by RiX012** [comment]
Het lijkt me prima om optie 1 uit te voeren. 
Ik zie echter in de AccessDB dat meervoudig overerven van attributen vaker voorkomt. Bij Duiker wordt lengte ook dubbel overgeërfd, maar met verschillende eenheden. Dit moet voorkomen worden.

**Comment by wjtmollema** [comment]
**Actie IMBOR-team:** 
Ofwel #994 terugdraaien en wachten tot Duiker, Hevel en Sifon compleet conform GWSW gemodelleerd gaan worden, ofwel het bovenstaande voorlopig doorvoeren voor 2024 release en later door Expertgroepen Stedelijk Water en Civiele constructies laten evalueren. Deze dubbele overerving mag uiteraard niet uitgebracht worden.

**Comment by wjtmollema** [comment]
**Addendum**

Voor `Duiker` wordt het een en ander opgelost bij de integratie met GWSW. Omdat `Sifon` en `Hevel` niet in GWSW voorkomen, worden zij door IMBOR tot subklasse van Holle leiding gemaakt. 

Deze objecttypen krijgen de volgende attributen toegekend op objecttypeniveau:
- `kilometrering begin` (vanwege `Ondertunneling`)
- `kilometrering begin` (vanwege `Ondertunneling`)
- `anti-graffiti voorziening` (vanwege `Kunstwerk`)
- `component` (vanwege `Kunstwerk`)
- `gewicht` (vanwege `Kunstwerk`)
- `locatieaanduiding` (vanwege `Kunstwerk`)
- `onderhoudsregime` (vanwege `Kunstwerk`)
- `oppervlakte` (vanwege `Kunstwerk`)
- `oriëntatie` (vanwege `Kunstwerk`)
- `type afsluiting` (vanwege `Kunstwerk`)

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.

**Comment by wjtmollema** [comment]
Er wordt voorgesteld om deze issue te sluiten.
