### ISSUE TITLE
Waterobject - BGT FysiekVoorkomen dubbel

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#115]
Zowel bij het beheerobject als waterobject (objecttypegroep) komt de BGT Fysiekvoorkomen dubbel voor...

![BGT Fysiek Voorkomen waterobject- dubbel](https://user-images.githubusercontent.com/40396592/98559772-52dc8a80-22a7-11eb-80a5-51d89f9d0c58.png)

**Comment by ernst63** [comment]
Komt ook bij Groenobject voor

**Comment by JochemMollema** [comment]
Bij Waterobject, Groenobject en Terreindeel kan BGTFysiekVoorkomen vervallen, overerving vindt plaats via Beheerobject.

BGTFysiekVoorkomen als attribuut op vervallen gezet bij Waterobject, Terreindeel, Verhardingsobject en Groenobject in de tabel X_ObjecttypeAttributen.
