### ISSUE TITLE
Enumeraties voor attribuut Cultuurhistorisch waardevol controleren

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1150]
Enumeraties voor attribuut Cultuurhistorisch waardevol controleren: niet alle waarden zijn representatief. Voorbeeld: Grafheuvels komen in Gelderland vooral in het Bos voor.

**Comment by wjtmollema** [comment]
**Constatering**
IMBOR-team: Uitwerken als `InformatieObject` (werknaam) `Cultuurhistorische waarde`

**Comment by JochemMollema** [comment]
@RiX012  deze issue kan gesloten worden, zie uitwerking #1379
