### ISSUE TITLE
Houtsingel als synoniem opnemen van Houtwal. Definitie hierop aanpassen.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1151]
Houtsingel als synoniem opnemen van Houtwal. Definitie hierop aanpassen.

**Comment by wjtmollema** [comment]
**Constatering**
Wikipedia geeft de volgende omschrijving van een Houtsingel:

> Een houtsingel, boomsingel of kortweg singel (in Nederland) of een houtkant (in Vlaanderen) is een brede strook met bomen en struiken als afscheiding tussen weilanden en akkers en ook wel langs beken en waterlopen. Een houtsingel is een lijnvormig landschapselement van 4 tot 20 meter breed en minimum 25 meter lang. Houtsingels lijken veel op [houtwallen](https://nl.wikipedia.org/wiki/Houtwal). Bij een houtwal is er sprake van een opgeworpen wal, waar de beplanting op staat.

Hier wordt Houtwal niet als synoniem van Houtsingel gezien. Houtsingel lijkt eerder een synoniem van Bomenrij te zijn.

Vergelijk de IMGeo-definitie van Houtwal:
> Terreindeel zijnde een afscheiding met beperkte breedte en beplant met bomen of struiken. (Bron: definities.geostandaarden.nl)

En vergelijk ook de SOR-definitie van Bomenrij:
> Opgaande rijvormige begroeiing van bomen zonder ondergroei van struiken.

De laatst geciteerde definitie maakt duidelijk dat een Houtsingel geen synoniem is van Bomenrij. Maar het is eveneens duidelijk dat niet elke Houtwal ook een Houtsingel genoemd kan worden. 

**Voorgestelde verwerking**
- `Houtsingel` toevoegen als domeinwaarde aan `imborVoc_Termen`;
- `type` toevoegen aan `Houtwal` en `HoutwalType` toevoegen als `EnumeratieType` aan `imborVoc_Termen`;
- `Houtsingel` toevoegen aan `HoutwalType`

**Comment by JochemMollema** [comment]
Domeinwaard Houtsingel toegevoegd als verschijningsvorm van een Houtwal.
Enumeratie HoutwalVerschijningsvorm toevoegd.
Domeinwaarde Houtsingel toegevoegd aan de enumeratie HoutwalVerschijningsvorm
Verschijningsvorm als attribuut vastgelegd bij Klasse Houtwal

@RiX012 deze issue kan gesloten worden.
