### ISSUE TITLE
Struikelsteen als type van een Herdenkingsdocument met synoniem Stolperstein registeren

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1152]
Struikelsteen als type van een Herdenkingsdocument met synoniem Stolperstein registeren

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- De domeinwaarde `Struikelsteen` wordt toegevoegd met als synoniem `Stolperstein`;
- `Struikelsteen` wordt toegevoegd aan `HerdenkingsmonumentType`

**Comment by wjtmollema** [comment]
**Conclusie IMBOR-team**
De verschijningsvorm wordt toegevoegd.
