### ISSUE TITLE
Gemeente Maastricht: Aanvullende typeringen van Kunstobject en Herdenkingsmonument

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1153]
**Melding**
In de gemeente Maastricht en de zuidelijke Nederlanden zijn er een aantal veelvoorkomende verschijningsvormen van `Kunstobject` en `Herdenkingsmonument` die nog niet in IMBOR zijn opgenomen. Daarnaast wordt er voorgesteld een verschijningsvorm van 'stadspoort' in IMBOR op te nemen.

_Kunstobject_
- Mariabeeld

_Herdenkingsmonument_
- Kanon
- Kruisbeeld

**Voorgestelde verwerking**
_Kunstobject_
- Er wordt voorgesteld om `Mariabeeld` **niet** als domeinwaarde toe te voegen; dit lijkt namelijk op een te sterke vermenging van functie en voorkomen. Het kan uitgedrukt worden met behulp van het vrije veld van `objectnaam`: `Kunstobject :: type :: Vrijstaand beeld :: objectnaam :: Mariabeeld.`

_Herdenkingsmonument_
- Er wordt voorgesteld om `Kanon` (of generieker: `Artillerie-object`) als domeinwaarde toe te voegen aan` imbor_Voc_Termen`. Vervolgens kan de domeinwaarde toegevoegd worden aan `HerdenkingsmonumentTypeGedetailleerd` met als bovenliggende waarde `Oorlogsmonument` in `imborKern_EnumeratiesDomeinwaarden`. Hiervoor moet `Herdenkingsmonument` het attribuut `type gedetailleerd` toegekend krijgen.
- Er wordt voorgesteld om `Kruisbeeld` als domeinwaarde toe te voegen aan` imbor_Voc_Termen`. Vervolgens kan de domeinwaarde toegevoegd worden aan `HerdenkingsmonumentType` in `imborKern_EnumeratiesDomeinwaarden`.

_Stadspoort_
- Er wordt voorgesteld om `Stadspoort` of `Vestingpoort` als domeinwaarde toe te voegen aan` imbor_Voc_Termen`. Vervolgens kan de domeinwaarde toegevoegd worden aan `GebouwTypeGedetailleerd` met als bovenliggende waarde `Vestingsgebouw` in `imborKern_EnumeratiesDomeinwaarden`.

**Comment by wjtmollema** [comment]
**Conclusies IMBOR-team**

- Het niet uitbreiden van `Kunstobject` is geaccordeerd;
- De overwegingen m.b.t. `Herdenkingsmonument` vragen om een afweging met een hogere impact (zie impactverhoging naar 2);
- `Stadspoort` (met als synoniem `Vestingpoort`) kan zoals voorgesteld worden toegevoegd.

**Comment by JochemMollema** [comment]
De bovenstaande punten zijn verwerkt. 
@RiX012 : deze issue kan gesloten worden
