### ISSUE TITLE
Drijflijn - waterobject of waterinrichtingsobject / scheiding

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#116]
Naar onze mening is een drijflijn meer een object dat in de objecttypegroep IMBOR Waterinrichtingsobject of bij IMBOR Scheidingen moeten worden opgenomen i.p.v. IMBOR Waterobject

**Comment by JochemMollema** [comment]
Correct, is al eerder geconstateerd en aangepast. Drijflijn moet als waterinrichtingsobject verwerkt worden.

**Comment by JochemMollema** [comment]
Aangepast in IMBOR 2021
