### ISSUE TITLE
In de markeringen IMBOR wordt de bajonetpijl 2 maal genoemd. 

### ISSUE THREAD

**Issue by HarroVerhoeven** [Stichting-CROW/imbor#117]
(Vraag ingediend door Stefan van Gerwen, SvGerwen@brabant.nl)

Kan dit of moet dat anders zijn? Of is dit voor een pijl links en een pijl rechts?
![Bajonetpijl](https://user-images.githubusercontent.com/65553494/99517129-4e8f2c00-298f-11eb-9e71-2bc846476749.jpg)

**Comment by wjtmollema** [comment]
Deze **bug** is reeds verholpen in de release van IMBOR 2022. De huidige versie van de Access-database bevat `Bajonetpijl` nog maar 1 keer vanwege het eenmalige voorkomen in imborKern_EnumeratiesDomeinwaarden.
