### ISSUE TITLE
GitHub procedure uitleggen t.b.v. softwareleveranciers en hun klanten

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1172]
In het software leveranciers overleg van 7 juni 2023 werd aangegeven dat het waarde zou hebben als vanuit het IMBOR team aangegeven zou worden hoe de IMBOR GitHub omgeving gebruikt zou moeten worden. 

Hier wordt onder andere mee bedoeld:
- Positie van de GitHub omgeving duidelijk maken
- Uitleggen hoe het werkt
    - Instructie hoe men iets moet registreren
    - Wat CROW daar verwacht binnen te krijgen, o.a.
           - Conversie problemen
           - Verzoek tot aanvullingen
           - Vragen t.b.v. verduidelijking
           - Bugs
- Procedure uitleggen hoe wij het behandelen
    - Prioritering uitleggen

**Comment by JHLJoosten** [comment]
Hi @RiX012 en @EJvandekamp , Ik heb bovenstaande tekst voorlopig opgenomen in het concept beheerplan als bijlage. Ik vind het een duidelijke tekst die goed is om niet alleen software leveranciers maar ook gebruikers een richting te geven hoe ze bij kunnen dragen aan IMBOR ontwikkeling. 
Als jullie vinden dat het een aparte pagina verdiend dan kan dat altijd denk ik.
Verder ben ik nog nieuwsgierig naar wat er nu mee gedaan wordt met de tekst in het kader van communicatie naar buiten. Lijkt me zinvol om de "community" groter te maken door hierover te communiceren. (tenzij we daar nu nog niet op zitten te wachten uiteraard)

**Comment by RiX012** [comment]
@EJvandekamp deze heb jij verspreid onder de leveranciers toch?

**Comment by JHLJoosten** [comment]
@EJvandekamp , Is deze verspreid onder de software leveranciers?
Ik kan me voorstellen dat we in het in algemene zin delen met de gemeenschap zodat we ook gebruikers naar GitHub kunnen trekken.
Hoe zie jij dat @RiX012 @JochemMollema

**Comment by EJvandekamp** [comment]
@JHLJoosten, deze uitleg is n.a.v. van het laatste overleg met de Klankbordgroep Softwareleveranciers op 04-10-2023 verspreidt onder de softwareleveranciers. Was een onderdeel van het verslag. 

M.b.t. het andere punt. Lijkt me goed om dit zo breed mogelijk te verspreiden onder de gebruikers.

**Comment by JHLJoosten** [comment]
@EJvandekamp, Laten we morgen ook even kijken hoe we dit gaan doen. Want iedereen mailen lijkt me wat omslachtig.
In principe staat de handleiding on-line in het concept beheerplan. Alleen dat is nu nog niet openbaar.
Anders kunnen we er op een andere wijze ruchtbaarheid aan geven misschien. @RiX012 @JochemMollema ?

**Comment by JochemMollema** [comment]
Bij de softwareleveranciers die nu ons overleg zitten, is Github wel bekend. Het is meer een kwestie van het willen gebruiken.

Groet,

Jochem

Van: JHLJoosten ***@***.***>
Verzonden: maandag 8 januari 2024 16:16
Aan: Stichting-CROW/imbor ***@***.***>
CC: Jochem Mollema ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Stichting-CROW/imbor] GitHub procedure uitleggen t.b.v. softwareleveranciers en hun klanten (Issue #1172)


@EJvandekamp<https://github.com/EJvandekamp>, Laten we morgen ook even kijken hoe we dit gaan doen. Want iedereen mailen lijkt me wat omslachtig.
In principe staat de handleiding on-line in het concept beheerplan. Alleen dat is nu nog niet openbaar.
Anders kunnen we er op een andere wijze ruchtbaarheid aan geven misschien. @RiX012<https://github.com/RiX012> @JochemMollema<https://github.com/JochemMollema> ?

**Comment by JHLJoosten** [comment]
@RiX012 en ik kunnen dat in de overleggen met de software leveranciers wel gaan benadrukken!
