### ISSUE TITLE
UNAFACT: buurtcode, wijkcode, provinciecode, waterschapcode etc. redundant in het kader van objectnummer

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1176]
**Melding**
Alle subklassen van `Registratief gebied` hebben het attribuut `objectnummer` voor het registreren van organisatiespecifieke nummers. `buurtcode, wijkcode, provinciecode, waterschapcode etc.` bestaan nu zij aan zij met `objectnummer`. Deze attributen hebben in IMBOR hun intrede gedaan omdat ze in de SOR opgenomen zouden worden (zie bijv. https://docs.geostandaarden.nl/disgeo/emso/#buurt). 

Uit dit gegeven komen twee vragen voort:

- Is het gebruik van `buurtcode, wijkcode, provinciecode, waterschapcode etc.` redundant als `objectnummer` hier ook voor beschikbaar is? Of is het nuttig om een CBS-code naast een organisatiespecifieke code te gebruiken?
- In het licht van de herziening van `Gebiedsindeling` die is voorgesteld in https://github.com/Stichting-CROW/imbor/issues/1101 zijn de codes/namen van de bovenliggende `Registratief gebied`en (bijv. `wijknaam` bij `Buurt` en `woonplaatsnaam` bij `Wijk`) in ieder geval redundant.

**Voorgestelde verwerking**
Het laten vervallen van `buurtcode, wijkcode, provinciecode, waterschapcode etc.` omdat de CBS-code in principe de wenselijke invulling is van `objectnummer` en het onwenselijk is om speciaal voor de `Registratief gebied`en die codes te behouden, waarmee deze objecttypes niet alleen afwijken van andere `Virtuele ruimte`s, maar ook van alle `Reële objecten`.

**Comment by wjtmollema** [comment]
**Bespreekpunt**
-Is er sprake van _ongewenste_ redundantie? Zo ja, issue doorvoeren. Zo nee, dan is het complementair en kan de issue gesloten worden.

**Comment by wjtmollema** [comment]
**Motivatie van ongewenste redundantie**
Het bijhouden van de code-attributen naast het reeds beschikbare `objectnummer` is ongewenst, omdat wat hier wenselijk is om in te vullen voor beiden hetzelfde is (namelijk de cbs-code). Het registreren van de cbs-code in `objectnummer` is als het ware een beste praktijk. Deze redundantie is niet bruikbaar, maar neemt 'ruimte' in het model in zonder daar wat aan toe te voegen.

@RiX012 Ondersteun jij de conclusie dat deze attributen kunnen vervallen omdat deze redundantie ongewenst is?

**Comment by RiX012** [comment]
> @RiX012 Ondersteun jij de conclusie dat deze attributen kunnen vervallen omdat deze redundantie ongewenst is?

Yes helemaal mee eens.

**Comment by wjtmollema** [comment]
Issue is verwerkt zoals voorgesteld in https://github.com/Stichting-CROW/imbor/issues/1176#issue-1765618132.

@RiX012 Deze issue kan gesloten worden.
