### ISSUE TITLE
UNAFACT: draagkrachtig een niveau laten zakken naar Gras- en kruidachtigen

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1179]
**Melding**
Het attribuut `draagkrachtig` is nu opgenomen op het niveau van `Groenobject`. Echter is de doelstelling van dit gegeven om te bepalen of er bijv. een voertuig op het object zou kunnen parkeren. Parkeren op `Gras- en kruidachtigen` valt voor te stellen, maar op `Planten`, `Bos`, `Bosplantsoen` etc. lijkt met niet de bedoeling. 

Er wordt derhalve voorgesteld `draagkrachtig` te verplaatsen van `Groenobject` naar `Gras- en kruidachtigen`.

**Voorgestelde verwerking**
Beoordeling door de werkgroep Groen.

**Comment by JochemMollema** [comment]
Draagkrachtig is als attribuut alleen nog maar van toepassing bij Gras- en kruidachtigen. Als attribuut verwijderd bij Planten.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
