### ISSUE TITLE
‘Type gedetailleerd’ van de dwars- en lengtemarkering: wat zijn precies brede en smalle strepen

### ISSUE THREAD

**Issue by HarroVerhoeven** [Stichting-CROW/imbor#118]
(Vraag ingediend door Stefan van Gerwen, SvGerwen@brabant.nl)

Ik wil weten wat exact wordt verstaan onder smal en breed. Wat zijn daarvan de maten. Wat valt onder smal en wat onder breed? Moet dit niet in IMBOR nader worden gespecificeerd?

**Comment by RiX012** [comment]
> Mijns inziens moet er nader overleg komen over de gehele modellering van `Wegmarkering`, ook vanwege het gebruik van afwijkend gemodelleerde attributen zoals `markering toepassing` (i.p.v. bijvoorbeeld `gebruiksfunctie`).

Yep, mee eens. Werk voor een Werkgroep

**Comment by wjtmollema** [comment]
Door de voorstellen vanuit de Provincie Noord-Brabant zoals die zijn uitgewerkt in #1195, worden de kwalitatieve termen 'smal' en 'breed' zoals die voorkomen in de verschijningsvormen die in de bovenstaande berichten zijn opgesomd, niet meer gebruikt in typeringen van `Wegmarkering`. `breedte` en `markeringsbreedte` zijn in dit geval de overgebleven eigenschappen van  `Wegmarkering` waarmee 'smal' en 'breed' kwantitatief uitgedrukt kunnen worden.

In lijn met de afhandeling van andere (ver)ouder(d)e Wegmarkeringen-issues wordt deze issue gesloten en voor de definitieve verwerking van de kwestie wordt verwezen naar #1195.
