### ISSUE TITLE
UNAFACT: zijn de bedieningsgegevens bij Tunnelventilatie en Vuilwaterinnamestation zinnig?

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1181]
**Melding**
Bij analyse van alle Enumeratietypen voor `<<klasse>>TypeBediening` en `<<klasse>>Communicatieprotocol` komen een aantal combinaties voor die wellicht onzinnig zijn.

Het gaat voornamelijk om:

- `Tunnelventilatie`
- `Vuilwaterinnamestation`

**Voorgestelde verwerking**
Onderzoeken of deze combinaties zinnig zijn; zo niet, dan laten vervallen.

**Comment by JochemMollema** [comment]
De wijze waarop een apparaat aangestuurd wordt, kan nu met een informatieobject Communicatie-informatie ondervangen worden. Deze issue is daarmee niet meer relevant.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
