### ISSUE TITLE
UNAFACT: Is bij Asfaltverharding de voeg wel van toepassing? 

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1183]
**Melding**
`Asfaltverharding` heeft drie attributen voor het vastleggen van informatie over voegen:

1. `voeg`: "Aanduiding van het type voeg. Naad of opening tussen twee aansluitende gedeelten van een of meer constructies."
2. `soort voeg`: "Aanduiding voor het soort voeg (plaatsing) in het Verhardingsobject."
3. `voegvulling`: "Aanduiding van het type voegvulling."

Maar zijn dit wel zinnige gegevens om te registreren bij `Asfaltverharding`?

**Voorgestelde verwerking**
Voorleggen aan de werkgroep Wegen.

**Comment by JochemMollema** [comment]
Google meldt dat de combinatie voeg en asfaltverharding wel mogelijk is. Attributen blijven gehandhaafd.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
