### ISSUE TITLE
Definitie van GM_MultiPoint klopt niet

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1186]
In de imborvoc_termen staat als definitie bij GM_MultiPoint: "Klasse zonder attributen voor het vastleggen van de geometrische verschijningsvorm: multilijn.". Dat laatste woord moet natuurlijk "multipunt" zijn.

**Comment by wjtmollema** [comment]
Bedankt voor het delen van de constatering. 

**Voorgestelde verwerking**
De definitie van `GM_MultiPoint` wijzigt naar:

> Klasse zonder attributen voor het vastleggen van de geometrische verschijningsvorm: multipunt.

@RiX012 is dit akkoord?

**Comment by RiX012** [comment]
Ja goeie. Doorvoeren inderdaad. Dank @GreenpointAdviesPN
