### ISSUE TITLE
Informatieverlies in ACCES-database.

### ISSUE THREAD

**Issue by jplender** [Stichting-CROW/imbor#1187]
Als ik de ACCES-database lees bemerk ik informatie-verlies als gevolg van data-uitwisseling. Dat is waarschijnlijk het gevolg van het gebruik van een verkeerd data-type.  

Een voorbeeld van informatie-verlies vindt ik in de tabel imborVoc_Termen: kolom 'toelichting': en dan de term: 'ballustrade'. Dit veld bevat een afgebroken zin.

Het aantal tekens in deze kolom mag maximaal 255 zijn. Een groter aantal tekens leidt tot verkeerde of onvolledige informatie. 

**Om te reproduceren**
Stappen om te reproduceren.
1. Ga IMBOR, de tabel imborVoc_Termen: kolom 'toelichting': en dan de term: 'ballustrade'. Dit veld bevat een afgebroken zin.

**Je verwachtte**
Volledige en beknopte informatie in een logische zin die eindigt met en punt.

**Versie of uitgave van IMBOR**
- Versie: 2022

**Meer context**
Ik wordt graag op de hoogte gehouden van uw keus. Er is ongetwijfeld een vergroting van dit data-type mogelijk, maar geef er de voorkeur aan dat de definitie of toelichting niet groter is dan 255 tekens.

**Comment by RiX012** [comment]
Dank voor het melden! Er ontbreken inderdaad gegevens.
@wjtmollema kun jij controleren of dit inderdaad een mismatch is tussen het maximaal aantal tekens in Access en de bron van waaruit dit gekopieerd is?

**Comment by wjtmollema** [comment]
@RiX012 Ik kan bevestigen dat er sprake is van 'afgebroken' tekst in het veld `Toelichting`. Het gegevenstype van het veld is echter wel `Lange tekst`, dus aan de tekenbeperking ligt het niet. Het gaat door de bank genomen om termen die al voor IMBOR 2022 tot de IMBOR-termen behoorden. Dit informatieverlies zal vermoedelijk in de periode 2018-2021 zijn ontstaan. 

Het IMBOR-team heeft in beeld om welke instanties van `Toelichting` het gaat en zal deze gevallen corrigeren.

**Comment by wjtmollema** [comment]
**Addendum**
Excavatiewerkzaamheden in vorige versies wijst uit dat een aantal van deze afgebroken gevallen in IMBOR 2020-08 nog compleet waren.
