### ISSUE TITLE
Gemeente Den Haag: Laadinfrastructuur: toevoegen meterinformatie aan Oplaadpaal

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1188]
**Melding**
De gemeente Den Haag stelt voor meterinformatie toe te voegen aan de attributenverzameling die aan het `ObjectType` `Oplaadpaal` wordt toegeschreven. Het gaat om twee aspecten:

- Nummer van de aangesloten meter; dit is reeds onderdeel van IMBOR als het attribuut `meternummer` bij de klasse `Kast`.
- Modelnaam van de aangesloten meter. Dit is nog _geen_ onderdeel van IMBOR.
- `ean-code`. Dit is reeds onderdeel van IMBOR.

**Voorgestelde verwerking**

- Het toevoegen van het attribuut `metermodelnaam` aan IMBOR en het toekennen van dit attribuut aan zowel `Oplaadpaal` als `Kast` (consistentie-overweging);
- Het toekennen van het attribuut `meternummer` aan de klasse `Oplaadpaal`.
- Het toekennen van het attribuut `ean-code` aan de klasse `Oplaadpaal`.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.

**Comment by wjtmollema** [comment]
Er wordt om toestemming verzocht om deze issue te sluiten.

**Comment by RiX012** [comment]
Ik twijfel aan het introduceren van `metermodelnaam` . Is het niet logischer hier een meer generieke oplossing voor te verzinnen?

**Comment by wjtmollema** [comment]
**Bespreekpunt**
Objecttype, attribuut of informatieobject?

**Comment by wjtmollema** [comment]
**Addendum**
Gemeente Den Haag beargumenteert dat er een keuze gemaakt moet kunnen worden tussen het registreren van louter een `Oplaadpaal` en het registreren van een combinatie van `Oplaadpaal` en een of meer `Laadpunt`en.

Hiervoor zouden de volgende attributen ook beschikbaar moeten worden bij `Oplaadpaal`:

```
- firmwareversie
- protocolversie 
- type besturing
- communicatieprotocol
- ean-code
- evse-id
```
Er wordt voorgesteld om hier een `Informatieobject` voor te ontwikkelen, waarbij tevens beoordeeld moet worden welke andere attributen hier aan toegevoegd zouden moeten worden en of dit in een en hetzelfde `Informatieobject` past, of dat er meerdere `Informatieobject`en voor aan te pas moeten komen.

**Comment by wjtmollema** [comment]
Het Informatieobject `Communicatie-informatie` wordt voorgesteld, met het volgende attributenprofiel:

```
- firmwareversie
- protocolversie 
- type besturing
- communicatieprotocol
- ean-code
- evse-id
```
Dit zou leiden tot een grote opschoning in imborKern_KlassenAttributen, omdat alle bovenstaande attributen kunnen vervallen bij de klassen waar die nu geregistreerd staan. Voor al die klassen wordt ter vervanging een `isBeschrevenDoor`-relatie met `Communicatie-informatie` geïntroduceerd.

@RiX012 Als jij akkoord bent met deze hermodellering - die overigens in lijn is met overige informatieobjecten zoals Installatie-informatie, Oplever-informatie etc. - dan wordt het doorgevoerd.

**Comment by wjtmollema** [comment]
@RiX012 Verwerkt zoals voorgesteld. Kardinaliteit is 0:1 geworden. Deze issue kan gesloten worden.
