### ISSUE TITLE
Materiaal van borden

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1190]
Waar vind ik het materiaal van een bord? Hoe is deze relatie te maken?

**Comment by RiX012** [comment]
@StefanvanGerwen 

Dit kan door de consistOf relatie.
In de IMBOR viewer kun je naar [Verkeersbord](https://docs.crow.nl/onto-verkenner/imbor/#/view?uri=https%3A%2F%2Fdata.crow.nl%2Fimbor%2Fdef%2F26dc09f6-c4aa-4b7e-8d0f-1a8fd4fec85d) gaan en vervolgens naar het tabblad 'Relaties'. Daar zie je de voorgedefinieerde relaties.

Zie deze screenshot:
![image](https://github.com/Stichting-CROW/imbor/assets/56293445/4d33f6bb-04fa-4c84-ae8e-9b7661a6b559)

**Comment by JochemMollema** [comment]
@RiX012 deze issie kan gesloten worden.
