### ISSUE TITLE
Verwijzen naar de on-line werkversie van BOMOS

### ISSUE THREAD

**Issue by JHLJoosten** [Stichting-CROW/imbor#1191]
In de documentatie wordt de verwijzing gedaan naar twee PDF documenten.
Wellicht kunnen we beter de on-line versie van BOMOS hanteren als meest actuele?
https://gitdocumentatie.logius.nl/publicatie/bomos/fundament/

**Comment by RiX012** [comment]
Lijkt me een goeie ja!

**Comment by JHLJoosten** [comment]
Ik sluit het issue
