### ISSUE TITLE
Definitie geleiderail

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1198]
**Issue toelichten**
Klopt de definitie van geleiderail:
Stalen, lintvormige geleideconstructie samengesteld uit planken, afstandhouders diagonalen en palen of stijlen.
Dit begint met Stalen...., nu zijn er varianten uitgevoerd in hout. Wat later ook in de definitie beschreven wordt.
![image](https://github.com/Stichting-CROW/imbor/assets/32089055/177bc66a-796d-4e71-962e-b7fd6c71ce4d)

**Eventueel een verbetervoorstel of eigen inzicht**
Indien mogelijk Stalen weglaten:
Lintvormige geleideconstructie samengesteld uit planken, afstandhouders diagonalen en palen of stijlen.

**Comment by wjtmollema** [comment]
Bedankt voor het melden van de inconsistentie in de definitie. De definitie zal conform het voorstel worden aangepast.
