### ISSUE TITLE
Gemeente Venray: hoogzit toevoegen

### ISSUE THREAD

**Issue by gvoorhorst** [Stichting-CROW/imbor#1200]
In de gemeentebossen hebben we diverse hoogzitten geplaatst tbv de jagers. 

We willen de locatie bijhouden. Op dit moment heb ik dit als Zitelement - Bank - Speciale bank. 

Voor mijn gevoel voldoet dit niet. 

Mijn voorstel zou zijn als volgt: 
Of: 
- Bij Zitelement type hoogzit toevoegen
- Bij Faunameubilair type hoogzit toevoegen

**Comment by wjtmollema** [comment]
Beste melder, bedankt voor uw inbreng.

**Analyse**
In lijn met de bevinding van de melder kan de verschijningsvorm `Hoogzit` nog niet uitgedrukt worden m.b.v. `ZitelementType` of `ZitelementTypeGedetailleerd`.

**Voorgestelde verwerking**
Het toevoegen van `Hoogzit` aan `ZitelementType`.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Er wordt verzocht deze issue te sluiten.

**Comment by wjtmollema** [comment]
Er wordt verzocht deze issue te sluiten.
