### ISSUE TITLE
Gemeente Venray: Jeu de boules baan als sporttoestel

### ISSUE THREAD

**Issue by gvoorhorst** [Stichting-CROW/imbor#1201]
Bij objecttype Sporttoestel kan ik als "type sport" de optie "Jeu de boules" kiezen. 

Echter is er bij "type", "type gedetailleerd" of "type extra gedetailleerd" geen keuze voor een Jeu de boulesbaan of iets wat in die richting wijst. 

Graag "Jeu de boulesbaan" toevoegen als "type" onder objecttype Sporttoestel

**Comment by wjtmollema** [comment]
Beste melder, bedankt voor uw inbreng.

**Analyse**
`Jeu de Boules` is op dit moment een `type` van `Sportveld`. De [modelleerregels van IMBOR](https://docs.crow.nl/imbor/modelleerregels/#overlap-in-semantiek-moet-vermeden-worden-2-r0042) maken dat `Jeu de Boules` daarom geen `type` van een `Sporttoestel` mag zijn.

Er wordt terecht geconstateerd dat de combinatie van `Sporttoestel :: type sport` en de domeinwaarde `Jeu de Boules` op deze manier geen zinvol gebruik kent.

**Voorgestelde verwerking**
De domeinwaarde `Jeu de Boules` wordt verwijderd uit het enumeratietype `SporttoestelTypeSport`.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Er wordt verzocht deze issue te sluiten.

**Comment by wjtmollema** [comment]
Er wordt verzocht deze issue te sluiten.
