### ISSUE TITLE
Damwand en Beschoeiing als lijn opnemen

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1203]
De objecten Damwand en Beschoeiing worden nu standaard als vlak voorgesteld. Mijn voorstel is om dit standaard als curve op te nemen in IMBOR. Dan sluit het ook beter aan op BGT-IMGeo. Het gaat om objecten die behoorlijk smal zijn en waarbij de 2e dimensie eigenlijk niet boeit in beheer.

**Comment by RiX012** [comment]
Thanks, we nemen het mee in de volgende sessie!

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
De door Greenpoint Advies voorgestelde aanpassing van:

- `Damwand :: heeft begrenzing :: GM_Surface :: 1 op 1 relatie`
- `Beschoeiing :: heeft begrenzing :: GM_Surface :: 1 op 1 relatie`
- `Damwand :: heeft begrenzing :: GM_Curve :: 0 op 1 relatie`
- `Beschoeiing :: heeft begrenzing :: GM_Curve :: 0 op 1 relatie`

...naar:
- `Damwand :: heeft begrenzing :: GM_Surface :: 0 op 1 relatie`
- `Beschoeiing :: heeft begrenzing :: GM_Surface :: 0 op 1 relatie`
- `Damwand :: heeft begrenzing :: GM_Curve :: 1 op 1 relatie`
- `Beschoeiing :: heeft begrenzing :: GM_Curve :: 1 op 1 relatie`
...is in lijn met de eerste resultaten van de afstemming tussen NLCS 5.0 en IMBOR 2022 voor deze objecttypes. Ook binnen NLCS worden `Damwand` en `Beschoeiing` als lijnen weergegeven. Dit is tevens van toepassing op `Kademuur`.

Het voorstel is daarom om de bovenstaande wijziging door te voeren.

**Comment by RiX012** [comment]
Bespreken inderdaad. Ondervangen met alinea in Techdoc lijkt logisch.

**Comment by RiX012** [comment]
Dit issue wordt gesplitst. Het eerder (onderstaande) deel mag worden doorgevoerd en dan wordt de issue gesloten door @wjtmollema . De rest van het verhaal wordt verder behandeld in #1240 .

> **Voorgestelde verwerking** De door Greenpoint Advies voorgestelde aanpassing van:
> 
>     * `Damwand :: heeft begrenzing :: GM_Surface :: 1 op 1 relatie`
> 
>     * `Beschoeiing :: heeft begrenzing :: GM_Surface :: 1 op 1 relatie`
> 
>     * `Damwand :: heeft begrenzing :: GM_Curve :: 0 op 1 relatie`
> 
>     * `Beschoeiing :: heeft begrenzing :: GM_Curve :: 0 op 1 relatie`
> 
> 
> ...naar:
> 
>     * `Damwand :: heeft begrenzing :: GM_Surface :: 0 op 1 relatie`
> 
>     * `Beschoeiing :: heeft begrenzing :: GM_Surface :: 0 op 1 relatie`
> 
>     * `Damwand :: heeft begrenzing :: GM_Curve :: 1 op 1 relatie`
> 
>     * `Beschoeiing :: heeft begrenzing :: GM_Curve :: 1 op 1 relatie`
>       ...is in lijn met de eerste resultaten van de afstemming tussen NLCS 5.0 en IMBOR 2022 voor deze objecttypes. Ook binnen NLCS worden `Damwand` en `Beschoeiing` als lijnen weergegeven. Dit is tevens van toepassing op `Kademuur`.
> 
> 
> Het voorstel is daarom om de bovenstaande wijziging door te voeren.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
