### ISSUE TITLE
Materie Hout en Hardhout kunnen kiezen voor klasse Kunstwerk

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1204]
De klasse Kunstwerk heeft nu geen relatie met de materies Hout en Hardhout, terwijl bijv. een Beschoeiing een kunstwerk is. Beschoeiingen kunnen wel degelijk van hout of hardhout zijn.

**Comment by RiX012** [comment]
IMBOR limiteert niet welke relaties er tussen een fysiek object en een materie gelegd kunnen worden. We geven alleen 'voorstellen'. Het staat je zodoende vrij om een Beschoeiing van Hout of Hardhout te maken.

**Comment by wjtmollema** [comment]
@RiX012 Wellicht is het een goed idee om de eerste zin uit je bovenstaande antwoord (of een zin met een soortgelijke betekenis) onder https://docs.crow.nl/imbor/techdoc/#materie.

**Comment by RiX012** [comment]
> @RiX012 Wellicht is het een goed idee om de eerste zin uit je bovenstaande antwoord (of een zin met een soortgelijke betekenis) onder https://docs.crow.nl/imbor/techdoc/#materie.

Ja goeie. Ik heb een advisement erbij geplaats

**Comment by wjtmollema** [comment]
Er wordt voorgesteld om deze issue te sluiten.
