### ISSUE TITLE
IMBOR NEN2660 implementatie meer gelijk maken aan GWSW en SML

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1209]
- `nen2660:hasUnit` wordt vervangen door `qudt:unit`
- `nen2660:hasQuanitityKind` wordt vervangen door `qudt:hasQuanitityKind`
- `imbor:imborEenheid` komt te vervallen want het is simpeler om de huidige `skos:prefLabel` en `skos:definition` aan de `unit:` te hangen als extra annotatie
- Ook passen we de vermelding van imbor:GUID aan. Dit is 'gewoon' de `uri`

**Comment by wjtmollema** [comment]
- [ ] #1249 
- [ ] Access-database: Overal waar IMBORGUID gebruikt wordt, dit aanpassen naar URI
- [ ] Vervanging nen2660:hasUnit en vervanging nen2660:hasQuanitityKind in LD-modellering

**Comment by RiX012** [comment]
> * `imbor:imborEenheid` komt te vervallen want het is simpeler om de huidige `skos:prefLabel` en `skos:definition` aan de `unit:` te hangen als extra annotatie

Dit komt te vervallen wanneer #1249 is doorgevoerd.
