### ISSUE TITLE
Werken met Viual Studio Code aan documenten

### ISSUE THREAD

**Issue by JHLJoosten** [Stichting-CROW/imbor#1214]
Er is toch iets raars aan de hand met De hoofdstukken als ik de link open. Ook de afbeeldingen kreeg ik weer niet goed terug in de master. 
Hoofdstuk 5 bij mij is hoofdstuk 4 op de link hierboven. Terwijl de losse docs met de hoofdstuk nummering zouden moeten corresponderen?

**Comment by wjtmollema** [comment]
@JHLJoosten Verdient deze issue de status 'open' nog?

**Comment by JHLJoosten** [comment]
@wjtmollema , Geen urgent Issue, maar ik test het nog een keer en dan sluit ik hem af als het goed gaat.

**Comment by JHLJoosten** [comment]
Volgens mij werkt het weer!
