### ISSUE TITLE
Foutieve records in sematische relatie tussen IMBOR en IMGeo

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1215]
De volgende records uit refModel_Mapping zijn foutief:
5F0D1EDF-92AC-4997-8A2B-7F8D7E2D23D0
F740BB11-2854-4ECB-BFF3-40B8B9E68B75
D213A3D1-5DF8-4745-AD05-488D983548C8
81FC41FE-7609-4F18-99A3-11D34513E8B5

Hierbij zijn namelijk refattribuut1en refattribuut2 gelijk. In twee gevallen is de domeinwaarde ook gelijk en is refattribuut2 en refdomeinwaarde2 nit nodig. In de andere twee records klopt volgens mij het refattribuut2 niet en moet dat plus-fysiekvoorkomen zijn, respectievelijk bor-fysiekvoorkomen. 

15	"bgt-fysiekVoorkomen"	204	"half verhard"		15	"bgt-fysiekVoorkomen"	204	"half verhard"		=dubbeling
15	"bgt-fysiekVoorkomen"	314	"onverhard"		15	"bgt-fysiekVoorkomen"	316	"open grond"		->refattr2 is bor-f.v.k.
15	"bgt-fysiekVoorkomen"	314	"onverhard"		15	"bgt-fysiekVoorkomen"	567	"zand"			->refattr2 is plus-f.v.k.
15	"bgt-fysiekVoorkomen"	318	"open verharding"	15	"bgt-fysiekVoorkomen"	318	"open verharding"	=dubbeling

**Comment by wjtmollema** [comment]
Bedankt voor het aankaarten van de fouten. Ze zullen worden aangepast.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Mapping. Er wordt om toestemming verzocht deze issue te sluiten.
