### ISSUE TITLE
redomeinwaarde calamiteitendoorsteek (CADO) moet zijn calamiteitendoorsteek

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1216]
In refModel_Domeinwaarden wordt de IMGeo domeinwaarde "calamiteitendoorsteek (CADO)" gegeven. Echter, in BGT-IMGeo is dit "calamiteitendoorsteek", dus zonder de afkorting erachter. Graag gelijkstellen.

**Comment by wjtmollema** [comment]
Bedankt voor de melding. De fout zal worden aangepast.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Domeinwaarden. Er wordt om toestemming verzocht deze issue te sluiten.
