### ISSUE TITLE
Semantische relatie IMBOR-IMGeo voor Tunnel bevat onnodig attribuut1

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1217]
De semantische relatie met mappingguid EA82C89F-0742-42F1-B7DA-E421191E385B behelst de relatie tussen IMBOR Tunnel en IMGeo Tunneldeel. Daarbij wordt ook refattribuut1 bgt-type met refdomeinwaarde1 'tunneldeel' gesteld. Echter, deze domeinwaarde bestaat niet in IMGeo. Volgens mij is het niet nodig hier een refattribuut1 en refdomeinwaarde1 te gebruiken.

**Comment by wjtmollema** [comment]
Bedankt voor de melding. https://docs.geostandaarden.nl/imgeo/catalogus/bgt/#tunneldeel-0 wijst uit dat `Tunneldeel` inderdaad geen `bgt type` is maar juist een `bgt objecttype`.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Mapping. Er wordt om toestemming verzocht deze issue te sluiten.
