### ISSUE TITLE
Tekstuele fout in refModel_Domeinwaarden "GMS Kast" moet zijn "GMS kast"

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1218]
In de tabel refModel_Domeinwaarden staat de IMGeo domeinwaarde "GMS Kast". Echter, dit moet zijn "GMS kast". Kleine typefout, die wel consequenties heeft als je op tekstwaarden gaat koppelen. De meeste databasesystemen zijn hoofdlettergevoelig.
Refdomeinwaardeguid: A4999551-1E18-419E-B99D-5BFC36E4ABF4

**Comment by wjtmollema** [comment]
Bedankt voor het aankaarten van de fout. Dit zal worden aangepast.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Domeinwaarden. Er wordt om toestemming verzocht deze issue te sluiten.
