### ISSUE TITLE
Typefout refdomeinwaarde IMGeo "radardetector" moet zijn "radar detector"

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1219]
Refdomeinwaardeguid: DFAB6BCE-2DE1-4269-9D70-9B8A56742BD8
in tabel refModel_Domeinwaarden staat IMGeo domeinwaarde "radardetector", maar dit moet "radar detector" zijn.
Ook hier weer van belang bij tekstuele koppelingen.

**Comment by wjtmollema** [comment]
Bedankt voor het aankaarten van de ontbrekende spatie. Dit wordt aangepast.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Domeinwaarden. Er wordt om toestemming verzocht deze issue te sluiten.
