### ISSUE TITLE
refModel_Mapping verwijzing naar "open grond" als domeinwaarde bij "plus-fysiekVoorkomen" is foutief

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1220]
In de tabel refModel_Mapping wordt meermaals verwezen naar IMGeo-domeinwaarde "open grond" als zijnde een domeinwaarde van plus-fysiekVoorkomen, maar dat is niet correct. Dat moet zijn domeinwaarde van bor-fysiekVoorkomen.

**Comment by wjtmollema** [comment]
Bedankt voor het aankaarten van de fout. Dit zal worden aangepast.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Mapping. Er wordt om toestemming verzocht deze issue te sluiten.
