### ISSUE TITLE
refModel_Mapping verwijzing naar "betonelement" als zijnde plus-fysiekVoorkomen foutief

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1221]
In de tabel refModel_Mapping wordt meermaals verwezen naar IMGeo-domeinwaarde "betonelement" als zijnde een domeinwaarde van plus-fysiekVoorkomen, maar dat is niet correct. Dat moet zijn domeinwaarde van bor-fysiekVoorkomen denk ik, al kom ik deze domeinwaarde überhaupt nergens tegen in BGT IMGeo documentatie.

**Comment by wjtmollema** [comment]
Zie voor de IMGeo-domeinwaarde `beton element` https://docs.geostandaarden.nl/imgeo/catalogus/imgeo/#fysiekvoorkomenondersteunendwegdeelplus en https://docs.geostandaarden.nl/imgeo/catalogus/imgeo/#fysiekvoorkomenwegplus. 

Als er in refModel_Mapping `betonelement` zonder spatie staat, dan zal dit aangepast moeten worden.

**Comment by GreenpointAdviesPN** [comment]
ja klopt, het moet inderdaad beton element zijn. Dat had ik nog niet gezien. Dus "beton element" als domeinwaarde van plus-fysiekVoorkoomen is juist.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Domeinwaarden. Er wordt om toestemming verzocht deze issue te sluiten.
