### ISSUE TITLE
refModel_Mapping verwijzing naar "zwarte grond" als zijnde plus-fysiekVoorkomen is foutief

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1222]
In de tabel refModel_Mapping wordt meermaals verwezen naar IMGeo-domeinwaarde "zwarte grond" als zijnde een domeinwaarde van plus-fysiekVoorkomen, maar dat is niet correct. Dat moet zijn domeinwaarde van bor-fysiekVoorkomen denk ik, al kom ik deze domeinwaarde überhaupt nergens tegen in BGT IMGeo documentatie.

**Comment by wjtmollema** [comment]
Bedankt voor het aankaarten van de fout. De record zal worden aangepast.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld in refModel_Mapping. Er wordt om toestemming verzocht deze issue te sluiten.
