### ISSUE TITLE
In refModel_Mapping verwijzing naar objecttype Leiding uit verkeerde refinformatiemodel

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1224]
In refModel_Mapping staat een verwijzing naar refobjecttype Leiding uit het verkeerde informatiemodel. 
Betreft mappingguid: 6827ADF2-9328-4DF6-B8E1-60B4CB6E2DC6 
In die regel wordt een relatie beschreven tussen IMBOR en IMGeo, terwijl de refobjecttype uit NEN3610 komt.
Hier is sprake geweest van een verwisseling tussen refobjecttypeguid 799D2E7F-FBCA-4ECB-9106-C530DEEC1C62 (IMGeo Leiding) en FB463A8F-1DB0-4B6C-82CE-EC01DB26A21D (NEN3610 Leiding).

**Comment by wjtmollema** [comment]
De vraag die hier beantwoord moet worden, is waarom `imgeo:leiding` wordt gedefinieerd in refModel_Domeinwaarden terwijl de term 'leiding' niet wordt gebruikt in IMGeo, noch in de BGT.

Voorstel:

1. Vervangen van `imgeo:Leiding` door `nen3610:leiding` op alle plekken dat de eerstgenoemde gebruikt wordt; zodat
2. `imgeo:Leiding` kan vervallen in refModel_Domeinwaarden.

**Comment by GreenpointAdviesPN** [comment]
Er is al een record in refModel_mapping waarin de relatie imbor:leiding - nen3610:leiding gelegd is. Dat is mappingguid 4D016BC7-CD83-4EAB-9735-1F01DBE55AE2. Dus ik denk dat alleen de imgeo:Leiding records verwijderd hoeven te worden.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Er wordt toestemming verzocht deze issue te sluiten.
