### ISSUE TITLE
Verwerken Datamodel Handboek Bomen in 'IMBOR2024 Bomen'

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1225]
Nu de samenwerking tussen het Norminstituut Bomen (als kennispartner bomen) en het CROW is geformaliseerd is de weg vrij om de data van het ‘datamodel Handboek Bomen | IMBOR Bomen 2024’ te verwerken. Dit is invulling van de beslissing genomen in #1210.
 
Er is een spreadsheet met een actueel overzicht (versie 2023-11-02) van de attributen en domeinwaarden zoals die op hoofdlijnen eerder met elkaar zijn besproken t.b.v. het datamodel Handboek Bomen | IMBOR Bomen 2024. Een eerste aanzet hiervan is gedaan in #1109.

Daarnaast is er nog een document (versie 2023-11-02) met verschillende relevante aandachtspunten en opmerkingen.

Overlap moet gecheckt worden met: #300 #302 #1119 #1121 #1127 #1151

**Comment by wjtmollema** [comment]
@JochemMollema Na jouw controle (en die van het Norminstituut?) kan dit issue gesloten worden. Een opvallend gegeven is in ieder geval dat sommige attributen als achtervoegsel '... boom' hebben gekregen en anderen ' (boom)'. Dit kan gelijkgetrokken worden neem ik aan.
