### ISSUE TITLE
Toevoegen aan markeringsbreedte van de waarden 0,50m en 0,70m ivm breedte driehoeksmarkeringen

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1227]
De driehoeksmarkeringen worden in 2 breedtes aangebracht, 50cm binnen de bebouwde kom en 70cm buiten de bebouwde kom.

Graag toevoegen aan markeringsbreedte de waarden:
0,50
0,70

**Comment by wjtmollema** [comment]
Bedankt voor de melding. [Hier ](https://github.com/Stichting-CROW/imbor/issues/1195#issuecomment-1660415979) wordt reeds voorgesteld de waarden `0,50` en `0,60` toe te voegen. Daar zal ook `0,70` benoemd worden.

**Comment by wjtmollema** [comment]
Melding wordt gesloten omdat het project voor de hermodellering van `imbor:Wegmarkering` is afgerond.
