### ISSUE TITLE
Boomvoorzieningen

### ISSUE THREAD

**Issue by gvoorhorst** [Stichting-CROW/imbor#1228]
Op dit moment zijn boomvoorzieningen een attribuut met meerdere domeinwaarden, behorende bij Objecttype Boom. 

Dit heeft beperkingen: een boom is een puntobject, terwijl bijvoorbeeld wortelwering en wortelgeleiding ook als lijn wordt toegepast langs verharding. Voor het toepassen van bomengrond of boomkratten zou een vlakgeometrie juist handig zijn. In deze zin zou een objecttype Boomvoorziening een oplossing kunnen zijn, met diverse typen gedetailleerd. 

Wordt daar in de volgende versie van de IMBOR standaard daar rekening mee gehouden? Eventueel in samenhang met de integratie van handboek bomen?

Het liefst werken we volledig volgens het IMBOR model namelijk.

**Comment by wjtmollema** [comment]
Voor de aangegeven behoefte bomengrond of boomkratten zelfstandig te registreren is in de huidige versie van IMBOR het objecttype `Groeiplaatsinrichting` beschikbaar. Voor wortelwering en wortelgeleiding is dit niet het geval. Tot nu toe is dat laatste ook nog niet voortgekomen uit de voorbereidingen van de integratie van het Handboek Bomen met IMBOR. 

@JochemMollema dit lijkt me nog een bespreekpunt met het Norminstituut Bomen.

**Comment by wjtmollema** [comment]
@JochemMollema Wat is hier de status van?

**Comment by wjtmollema** [comment]
Conform Handboek Bomen in huidig versie van IMBOR Development. @RiX012 Deze issue kan gesloten worden. Akkoord?
