### ISSUE TITLE
Gemeente Hoorn: Belijning en Wegmarkering op Speelterrein

### ISSUE THREAD

**Issue by JHLJoosten** [Stichting-CROW/imbor#1231]
Op speelterreinen worden nu ook vaak een verkeerparcours aangelegd maar hoe gaan we daarin in ImBor mee om? Wat voor type of type gedetailleerd geven we daaraan?
Verharding bij verharding. Doen we de belijning bij wegmarkering? Maar daar ontbreekt plus-type waar je dan weer het kenmerk speelvoorziening kan aangeven.
 
Ook worden er dan van die kleine paaltjes met verkeersborden geplaats. Hier hetzelfde probleem welke type of type gedetailleerd gebruiken we.
 
   
 
Met vriendelijke groet,

Nico van Caspel

![image](https://github.com/Stichting-CROW/imbor/assets/135842056/77faf034-e02a-4ad4-8aa5-09d526fc6504)
![image](https://github.com/Stichting-CROW/imbor/assets/135842056/c2384f76-f273-4c81-a678-a0f0686c9dfc)
![image](https://github.com/Stichting-CROW/imbor/assets/135842056/24526e8c-0057-4366-9f09-72b2348132b4)

 

Nieuwe Steen 1 | postbus 603 | 1620 AR Hoorn
T 0229 252200 | E [gemeente@hoorn.nl](mailto:gemeente@hoorn.nl) | [www.hoorn.nl]

**Comment by wjtmollema** [comment]
**Acties**
-Beoordelen of voor de verkeersbordpaaltjes `Speeltoestel :: type :: Sociaal spel` volstaat. Zo niet, dan zou een betere typering toegevoegd moeten worden.
-Beoordelen of de belijning gezien moet worden als:

1. `Wegmarkering`, maar dan zouden adequate typeringen moeten worden toegevoegd;
2. `Veldbelijning`, maar dan moet dit een Constructie worden en in definitie opgerekt worden van exclusief sportvelden naar inclusie voor Speelterrein.
3. `Speeltoestel :: type :: Behendigheidstoestel :: type gedetailleerd :: Pleinplakker`, maar dan en slechts dan als opties (1) en (2) definitief worden verworpen EN het object in aanlegvorm ook overeenkomt met een `Pleinplakker`.
4. `Speeltoestel :: type :: <<N.t.b.>>`. Deze optie moet overwogen worden als optie (3) ook niet volstaat.

**Comment by wjtmollema** [comment]
**Addendum**
Optie (1) komt te vervallen, vanwege de hermodellering van `Wegmarkering`.

Voor de belijning wordt voorgesteld om van `Veldbelijning` een `Constructie` te maken en de definitie te verwijden (keuze voor optie (2)).

Voor de verkeersbordpalen wordt de volgende modellering voorgesteld: `Speeltoestel :: type :: Sociaal spel :: type gedetailleerd :: Verkeerspleinpaaltje`

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
