### ISSUE TITLE
Vraag gemeente Hoorn - Sport objecten in IMBOR 

### ISSUE THREAD

**Issue by EJvandekamp** [Stichting-CROW/imbor#1233]
Hoi Evert Jan,

Even een vraag.
We zijn nu met sport objecten bezig om die in te vullen volgens de ImBor standaard in ons beheersysteem.
De ondergronden van sport en speel objecten vallen nu onder wegen -> rubbertegels in elementverharding, kunstgras onder half verharding. En als een basketveld asfalt of beton is gaan die daar heen.
Wat je nu ziet is dat je onder wegen objecten alleen maar de attributen van wegen kwijt kan en niet de attributen die bij een sport ondergrond object horen. Kunstgras en rubbertegels hebben een valdemping of een sport-type of ….
Zie de vele sport-type die nu al in ImBor staan. Kan me zo voorstellen dat die andere aanvullende attribuut typen hebben dan gewoon klinkers.
Hoe kijken jullie daarna? Worden de attributen onder wegen nog uitgebreid naar andere vakdisciplines of kunnen we de attributen van de andere disciplines ook gewoon onder wegen gebruiken.

Tevens denk ik dat we zelf wel sport-type mogen toevoegen zoals Jeu de Boules baan.
Met vriendelijke groet,

Nico van Caspel

**Comment by JHLJoosten** [comment]
Heren,

Heb Nico van Caspel gebeld (is bekende van mij) en hem uitgelegd dat je bij verharde objecten en groene objecten de functies speel- en sportondergrond moet gebruiken in combinatie met het objecttype Sportveld.

Groet,

Jochem

**Comment by JHLJoosten** [comment]
Afsluiten na toelichting aan indiener.
