### ISSUE TITLE
Functie begraven Groenobject of andere oplossing

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1236]
Veel gemeenten hebben onderhoudsverplichting voor het groen op begraafplaatsen. De vakken waarin graven liggen worden daarom vaak in Plantsoenbeheer opgenomen als groenvlakken (meestal zonder de uitsparingen van de individuele graven). De vraag is daarom of er voor dit soort groenvakken (bijv. gras), waarin graven liggen een functie toegevoegd kan worden, zijnde 'Begraven'.
Of is er al een andere manier om dit soort groenvakken te onderscheiden van normale groenvakken?

**Comment by wjtmollema** [comment]
Op dit moment kan die relatie tussen een `Groenobject` en een begraafplaatsobject alleen gelegd worden met een semantische relatie, bijv. `Grafvak` :: `bevat` :: `Gras- en kruidachtigen`.

De suggestie van de melder wordt in overweging genomen. Hierbij zijn er twee typen mogelijkheden, ongeacht de uitwerking uiteindelijke toe te voegen term:
1. `Begraven` o.i.d. toevoegen aan `<<subklasseVanGroenobject>>Gebruiksfunctie`;
2. `Begraven`/ `Graven herbergen` o.i.d. toevoegen als `Functie` en relateren middels `voertUit` aan tenminste `Gras- en kruidachtigen`.

**Comment by GreenpointAdviesPN** [comment]
Grafvak :: bevat :: Gras- en kruidachtigen, dat is inderdaad een optie die we nu aan kunnen. Echter, dat valt of staat met het beheren van die Grafvak objecten. Dat zal in de praktijk nogal eens achterstallig zijn.

Als ik je goed begrijp zou:
1. dit betekenen dat er een attribuut bij zou komen die middels boolean aangeeft of dit een begraaffunctie heeft is of niet
2. dit een nieuw functie-object introduceren, nl. Begraven / Graven herbergen

Onze voorkeur zou dan uitgaan naar een attribuut. Dat is makkelijker te benaderen in zoekacties dan een relatie. Hoewel een relatie minder impact heeft op paspoorten. het attribuut zal bij de meeste Gras- en kruidachten niet gevuld zijn of op false staan.

**Comment by wjtmollema** [comment]
Bedankt voor je reactie. 

Nee, in het voorgaande bericht heb ik wat jij optie (1) noemt niet voorgesteld. De tegenwerpingen tegen een attribuutoplossing die jij benoemt, zijn de reden dat ik die oplossing niet heb voorgesteld: het neemt bij alle objecten ruimte in, terwijl het slechts voor marginale objecten van toepassing is. 

Maar ook deze optie zal het IMBOR-team in overweging nemen. Bedankt voor de inbreng!

**Comment by wjtmollema** [comment]
Er wordt voorgesteld om `Graven herbergen` als `Functie` toe te voegen. 

@RiX012 Dit is in lijn met de wens om functies conform nen2660:activity op te nemen en niet als attributen.
