### ISSUE TITLE
Inconsistente naamgeving nen2660 en nen3610

### ISSUE THREAD

**Issue by keesnieuwstad** [Stichting-CROW/imbor#1237]
**Beschrijf de bug**

De vraag is of onderstaande een IMBOR of een NEN-issue is, maar het heeft wel impact op hoe resulaten van IMBOR-queries eruitzien.

In de naamgeving via skos:prefLabel kent heeft twee varianten, zie onder.

nen2660:RealObject ---> skos:prefLabel   "ReëelObject"@nl
nen3610:ReëelObject ---> skos:prefLabel   "Reëel object"@nl

**Om te reproduceren**

Naast het feit dat dit in imbor-kern.ttl file te zien is, legde volgende SPARQL Query op imbor-kern.ttl legde dit issue bloot.

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?objectNaam ?parentNaam ?onderdeelNaam
    WHERE {
    VALUES ?objectNaam {
	      "Tunnel"@nl
	}
    ?s skos:prefLabel ?objectNaam .
    ?s rdfs:subClassOf*/skos:prefLabel ?parentNaam .
    ?t skos:prefLabel ?parentNaam .
    ?t sh:property/skos:prefLabel ?onderdeelNaam .
}

**Je verwachtte**
Dat de twee skos:pefLabels gelijke inhoud zouden hebben.

**Versie of uitgave van IMBOR**
Versie: 2022 (denk ik).

**Zie ook onderstaand screenshot**

![ReelObject-label-naam](https://github.com/Stichting-CROW/imbor/assets/122113304/16e7ac58-3361-4451-80f4-e9be36362a37)

**Comment by RiX012** [comment]
Bedankt voor het comment, het is inderdaad vreemd maar het klopt; de termen komen toevallig bijna overeen, maar betekenen iets anders in de verschillende normen (NEN2660-2 en NEN3610).
