### ISSUE TITLE
Link ik Technische documentatie werkt niet

### ISSUE THREAD

**Issue by keesnieuwstad** [Stichting-CROW/imbor#1238]
**Beschrijf de bug**
Op de webpagina: https://docs.crow.nl/imbor/techdoc/versies/Publicatie-IMBOR2022-20231017/

in de paragraaf: **3.1 Model van begrippen** staat: 

> De IMBOR Vocabulaire is te verkennen op:
> begrippen.crow.nl/IMBOR

Deze link werkt niet.

**Om te reproduceren**
Zie de beschrijving (spreekt voor zich).

**Je verwachtte**
Dat de pagina zou openen.

**Versie of uitgave van IMBOR**
- Versie: IMBOR Technische documentatie, CROW Informatiemodel Beheer Openbare Ruimte, TechDoc IMBOR2022 Publicatie 26 oktober 2023

**Comment by RiX012** [comment]
Merci, inderdaad broken link. Dit moet https://begrippen.crow.nl/imbor/nl/ zijn. Aangepast!
