### ISSUE TITLE
Gemeente Roosendaal - IMBOR vraag mbt selecteren overrijdbare berm

### ISSUE THREAD

**Issue by EJvandekamp** [Stichting-CROW/imbor#1239]
Hallo Evert Jan,

Ik ben de bermblokken aan het vullen in I-asset. Ik kan de Secubric en de taludblokken niet kwijt. Imbor laat de afmeting niet zien:

Secubric
[https://swaansinfra.nl/upload/02f038_ProducttekeningSecuBric6.pdf](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fswaansinfra.nl%2Fupload%2F02f038_ProducttekeningSecuBric6.pdf&data=05%7C02%7Cevertjan.vandekamp%40crow.nl%7Cf19417d6414f48a4613c08dc1c209c3e%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638416173876720271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rWgcFGU%2F3NsEtXqfODNma1ZP874hL5tHH7UpKHpnXDA%3D&reserved=0) 

(secubricblok, we passen de 60 en 80 toe)

 

Deze komt niet voor in het pull-down menu.

Ook zie ik geen goede omschrijving voor het formaat:
 

Wordt deze snel toegepast? Wij zijn namelijk niet de enige die deze blokken toepast.

Taludblok
27,2 x 25 x 20
 

Met vriendelijke groet,

Devid van Erve                                              
Sr Beheerder Verhardingen
Groep Beheer
Gemeente Roosendaal 
| Team Beheer 
| tel: 140165
| [d.van.erve@roosendaal.nl](mailto:d.van.erve@roosendaal.nl)

**Comment by gvoorhorst** [comment]
Als aanvulling: wellicht is het gezien de veelheid aan formaten van verharding beter om 3 velden te maken:
- Lengte verhardingselement
- Breedte verhardingselement
- Dikte verhardingselement

Gezien de veelheid aan formaten zal de lijst immers nooit volledig zijn.

**Comment by RiX012** [comment]
@JochemMollema graag deze meenemen in 2025 versie

**Comment by JochemMollema** [comment]
Attribuut afmeting, enumeratietype Elementenverharding en bijbehorende domeinwaarden verwijderd.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden
