### ISSUE TITLE
Gemeente Roosendaal - vraag m.b.t. overrijdbare berm

### ISSUE THREAD

**Issue by EJvandekamp** [Stichting-CROW/imbor#1244]
Hallo Evert Jan,

Ik ben de bermblokken aan het vullen in I-asset. Ik kan de Secubric en de taludblokken niet kwijt. Imbor laat de afmeting niet zien:

Secubric
![image](https://github.com/Stichting-CROW/imbor/assets/99896085/b7cbdce4-82e9-473f-9419-e336073299d8)

[https://swaansinfra.nl/upload/02f038_ProducttekeningSecuBric6.pdf](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fswaansinfra.nl%2Fupload%2F02f038_ProducttekeningSecuBric6.pdf&data=05%7C02%7Cevertjan.vandekamp%40crow.nl%7Cf19417d6414f48a4613c08dc1c209c3e%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638416173876720271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rWgcFGU%2F3NsEtXqfODNma1ZP874hL5tHH7UpKHpnXDA%3D&reserved=0) (secubricblok, we passen de 60 en 80 toe)

 

Deze komt niet voor in het pull-down menu.

Ook zie ik geen goede omschrijving voor het formaat:
 
![image](https://github.com/Stichting-CROW/imbor/assets/99896085/af81d83f-4e0d-48f0-8f80-67accc29fc64)

Wordt deze snel toegepast? Wij zijn namelijk niet de enige die deze blokken toepast.

Taludblok
27,2 x 25 x 20
 

Met vriendelijke groet,

Devid van Erve                                              
Sr Beheerder Verhardingen
Groep Beheer
Gemeente Roosendaal 
| Team Beheer 
| tel: 140165
| [d.van.erve@roosendaal.nl](mailto:d.van.erve@roosendaal.nl) 
| [www.roosendaal.nl](https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.roosendaal.nl%2F&data=05%7C02%7Cevertjan.vandekamp%40crow.nl%7Cf19417d6414f48a4613c08dc1c209c3e%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638416173876729309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BZrf47ByVw2MCubkPknhylPhwAfq8zm389RZeoKVACc%3D&reserved=0)

Afwezig op woensdag

**Comment by EJvandekamp** [comment]
Hoi Devid, 

Excuus voor de late reactie. 

De oplossing voor onderstaande probleem is als volgt: zowel het attribuut <<afmeting>> als het attribuut <<formaat>> zijn van het TypeAttribuut ‘Referentie’. Dat betekent dat de gebruiker de door IMBOR geserveerde domeinwaardenlijst zelf uit mag breiden. Mocht je dit niet zelf kunnen, dat is het een taak voor de functioneel beheerder of voor de leveranciers. 

Vragen zoals deze verzamelen we ook op GitHub. Een instructie voor het gebruik van GitHUB vind je hier: https://github.com/Stichting-CROW/imbor/issues/1172. De vraag die je stelt kun je hier volgen: https://github.com/Stichting-CROW/imbor/issues/1244 


Met vriendelijke groet, 

Evert Jan van de Kamp

**Comment by JochemMollema** [comment]
Aan de enumeratie ElementenverhardingAfmeting zijn de volgende afmetingen toegevoegd.
117,5 x 60 x 10
117,5 x 80 x 10
27,2 x 25 x 20

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
