### ISSUE TITLE
Gemeente Haarlem: aanpassen attribuut beheerafspraak van 0 op 1 relatie in 0 op N relatie

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1246]
Gemeente Haarlem: aanpassen attribuut beheerafspraak van 0 op 1 relatie in 0 op N relatie. Het kan voorkomen dat er  meerdere beheerafspraken bij een object van toepassing zijn.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Er wordt om toestemming verzocht deze issue te mogen sluiten.
