### ISSUE TITLE
Gemeente Venray: gebruiksfunctie Randvoorziening

### ISSUE THREAD

**Issue by gvoorhorst** [Stichting-CROW/imbor#1247]
![Gebruiksfunctie onbekend](https://github.com/Stichting-CROW/imbor/assets/140704871/9e25b4ee-cec8-4054-b61d-f62d5d750fca)
![image](https://github.com/Stichting-CROW/imbor/assets/140704871/0672e562-9d8c-4842-b5de-e6a2cfa803a9)

In het vorige beheersysteem hadden we de functie "Randvoorziening". Dit gebruikten we voor gevallen waar een rand klinkers rondom kolken of putdeksels was gelegd. Zie bijvoorbeeld bijgaande afbeeldingen. 

Bij mijn weten is daar in IMBOR geen gebruiksfunctie voor. Zie ik iets over het hoofd of kunnen jullie dit toevoegen voor de volgende versie?

**Comment by wjtmollema** [comment]
Bedankt voor het aandragen van dit voorbeeld. 

De term 'Randvoorziening' is binnen GWSW (https://data.gwsw.nl/1.6/Basis/index.html?menu_item=individuals&item=../../def/1.6/Basis/RandvoorzieningColl) in gebruik als verzamelterm voor "Vloeistofdichte voorziening[en] als onderdeel van het rioolstelsel, die als doel he[bben] de lozing van vuil uit het rioolstelsel op het oppervlaktewater te verminderen."

Het lijkt me daarom onwenselijk om de term 'Randvoorziening' op te nemen voor een nieuw gebruik als `VerhardingGebruiksfunctie`. Daarentegen kan er wel gepoogd worden om in de behoefte van de gemeente Venray te voorzien door een `Functie` `Omgeven van dekselrand` te introduceren.

Het IMBOR-team neemt dit voorstel in behandeling.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
