### ISSUE TITLE
Vraag gemeente Dordrecht - IMBOR spelen in Excel

### ISSUE THREAD

**Issue by EJvandekamp** [Stichting-CROW/imbor#1248]
Beste, 

Via jullie website kan ik het acces bestand van IMBOR spelen 2022 downloaden en openen. Ik bezit alleen geen Access, waardoor het bestand niet te openen is. Wat ik nodig heb is hoe de IMBOR voor spelen is opgebouwd. Welke objecttypen kent spelen, welke subtypen enz enz. Is het mogelijk dit in een Excel of word bestand aan te leveren? Ik wil mijn beheersysteem volgens het IMBOR model opbouwen. Voorbeeld van mijn vraag is dan: Hoe zet ik de veerelementen weg? Hoe de schommels en hoe de kunstgras ondergronden? Voorbeeld van het antwoord dat ik zoek is dan: Veerelement valt onder Objectgroep Type(Speeltoestellen)-subtype(Veerelementen)-Sub-subtype(Enkelvoudig veerelement)- Naam. Is het mogelijk om het uniforme bestand voor spelen op deze manier in te zien in word, excel, of op de website? 

Alvast dank. Met vriendelijke groet,

Bart Pennings
bjp.pennings@dordrecht.nl

**Comment by EJvandekamp** [comment]
Geachte heer Pennings, Beste Bart, 

Fijn dat je jouw beheersysteem volgens het IMBOR model wilt opbouwen!

Mijn advies zou zijn om Access te downloaden, zodat je de Access database kan gaan gebruiken. Dan heeft onze voorkeur. Ik zal bij mijn collega's navragen of het mogelijk is om een Excel-bestand te verstrekken. 

Vragen over IMBOR verzamelen we als CROW op GitHUB. Uw vraag wordt dan ook hier afgesloten. U kunt uw vraag blijven volgen via: https://github.com/Stichting-CROW/imbor/issues/1248.

Met vriendelijke groet, 

Evert Jan van de Kamp

**Comment by RiX012** [comment]
Ik zal een voorbeeld maken hoe met een (simpele) query deze kennis uit ons (gratis) SPARQL-Endpoint gehaald kan worden.

**Comment by RiX012** [comment]
Triply YasGUI is een gratis webapplicatie waarmee SPARQL queries uitgevoerd kunnen worden. Het enige wat gedaan hoeft te worden is het (open) IMBOR SPARQL-Endpoint invoeren en de juiste query schrijven. 

Ik heb dit gedaan op deze link: https://api.triplydb.com/s/dfcLjizXi

Als deze query gedraaid is kan rechts in beeld op de download knop gedrukt worden: 
![image](https://github.com/Stichting-CROW/imbor/assets/56293445/caeb5b8c-7e5c-4ec1-9ce2-add06c85567e)
Dan komt er een CSV bestand uit welke met bijvoorbeeld Excel geopend kan worden. 

De query kan uiteraard aangepast worden om het resultaat nog specifieker te maken of extra informatie beschikbaar te laten komen. Daar kan ik uiteraard mee helpen indien nodig.
