### ISSUE TITLE
imbor:Eenheid wellicht nu overbodig

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1249]
Vanuit GWSW is aangegeven dat het gebruik van QUDT voor eenheden gebruikelijk is. Mede daarom in `imbor:Eenheid`  nu overbodig. 
We moeten beoordelen of we de IMBOR Eenheden nu kunnen laten vervallen.

**Comment by RiX012** [comment]
> m/dag 	qudt:DerivedUnit 	unit:M-PER-HR 	http://qudt.org/vocab/unit/M-PER-HR 	Projectie niet kloppend; dit is de beste optie.

Eens, maar dan moet wellicht de eenheid in IMBOR ook aangepast worden.

**Comment by RiX012** [comment]
> m1/2/s 	qudt:DerivedUnit 	unit:M-PER-SEC 	http://qudt.org/vocab/unit/M-PER-SEC 	Foute eenheid in IMBOR: ofwel m1/s ofwel m2/s ofwel opties voor beiden maken.

Geen idee wat dit in IMBOR moet zijn. Maar zoals het er nu in zit is het in ieder geval niet goed. Twee opties maken lijkt me dan meest logisch

**Comment by RiX012** [comment]
> PN 	 [qudt:Unit 	 unit:BAR 	http://qudt.org/vocab/unit/BAR 	Geen QUDT-optie voor. Over deze 'nominale druk' kan ik het volgende vinden: "PN is an alphanumeric designation used for reference purposes, comprising the letters PN followed by a dimensionless number relating to component pressure/temperature capability, taking into account component material mechanical properties and component dimensional characteristics." (https://whatispiping.com/what-is-dn-and-pn/). Als dit als eenheid zou moeten fungeren, moet hier bar van worden gemaakt.

Inhoudelijk weet ik niet wat we hier moeten doen. Even met @Stichting-CROW/extern-marivon overleggen? Eventueel zouden we een specialisatie kunnen maken op QUDT, maar ik ontwijk dit liever.

**Comment by RiX012** [comment]
> µ 	  	  	  	Geen QUDT-optie voor. Dit is eigenlijk geen eenheid. Het wordt nu alleen gebruikt voor het attribuut contractiecoëfficiënt doorlaatprofiel dat afkomstig is uit GWSW, waar deze eigenschap een xsd:decimal is, en niks meer. Zie https://kennis.hunzeenaas.nl/index.php/Bestand:Hydraulische_weerstand_doorlaat.jpg voor een voorbeeld van de eenheidsloosheid van de contractiecoëfficiënt, dat ook gelijk duidelijk maakt waarom het in IMBOR terecht is gekomen: µ is de variabele die wordt gebruikt voor de contractiecoëfficiënt.

Moeten deze dan niet gewoon uit IMBOR halen. Of wellicht tussen haakjes of in de definitie vermelden van het attribuut?

**Comment by wjtmollema** [comment]
> > m/dag 	qudt:DerivedUnit 	unit:M-PER-HR 	http://qudt.org/vocab/unit/M-PER-HR 	Projectie niet kloppend; dit is de beste optie.
> 
> Eens, maar dan moet wellicht de eenheid in IMBOR ook aangepast worden.

OK, bij deze vraag ik toestemming dit te wijzigen.



> > m1/2/s 	qudt:DerivedUnit 	unit:M-PER-SEC 	http://qudt.org/vocab/unit/M-PER-SEC 	Foute eenheid in IMBOR: ofwel m1/s ofwel m2/s ofwel opties voor beiden maken.
> 
> Geen idee wat dit in IMBOR moet zijn. Maar zoals het er nu in zit is het in ieder geval niet goed. Twee opties maken lijkt me dan meest logisch

Kanttekening: willen we hier dan een nieuw attribuut voor introduceren of kan hetzelfde attribuut twee keer voorkomen bij een klasse maar met een andere eenheid? Dat laatste lijkt me zeer onwenselijk, maar er is geen modelleerregel die het uitsluit.

> > PN 	 [qudt:Unit 	 unit:BAR 	http://qudt.org/vocab/unit/BAR 	Geen QUDT-optie voor. Over deze 'nominale druk' kan ik het volgende vinden: "PN is an alphanumeric designation used for reference purposes, comprising the letters PN followed by a dimensionless number relating to component pressure/temperature capability, taking into account component material mechanical properties and component dimensional characteristics." (https://whatispiping.com/what-is-dn-and-pn/). Als dit als eenheid zou moeten fungeren, moet hier bar van worden gemaakt.
> 
> Inhoudelijk weet ik niet wat we hier moeten doen. Even met @Stichting-CROW/extern-marivon overleggen? Eventueel zouden we een specialisatie kunnen maken op QUDT, maar ik ontwijk dit liever.

Ik zal dit aan Marinus voorleggen per mail.



> > µ 	  	  	  	Geen QUDT-optie voor. Dit is eigenlijk geen eenheid. Het wordt nu alleen gebruikt voor het attribuut contractiecoëfficiënt doorlaatprofiel dat afkomstig is uit GWSW, waar deze eigenschap een xsd:decimal is, en niks meer. Zie https://kennis.hunzeenaas.nl/index.php/Bestand:Hydraulische_weerstand_doorlaat.jpg voor een voorbeeld van de eenheidsloosheid van de contractiecoëfficiënt, dat ook gelijk duidelijk maakt waarom het in IMBOR terecht is gekomen: µ is de variabele die wordt gebruikt voor de contractiecoëfficiënt.
> 
> Moeten deze dan niet gewoon uit IMBOR halen. Of wellicht tussen haakjes of in de definitie vermelden van het attribuut?

Vermelden in de definitie lijkt me veilig, waarbij het als eenheid verwijderd wordt. OK?

**Comment by wjtmollema** [comment]
Marinus heeft namens Stichting RIONED de vraag wat met PN te doen beantwoord. Hij pleit ervoor deze waarde te laten vervallen, omdat het dimensieloos is. De bovenstaande tabel is hierop aangepast.

**Comment by RiX012** [comment]
Wanneer dit is doorgevoerd in AccesDB, werkt @RiX012 de documentatie en de pipeline bij.

**Comment by wjtmollema** [comment]
Er bleek ook een eenheid in IMBOR 2022 te zitten die helemaal niet werd gebruikt in imborKern_K_KlassenAttributen: Ra, "De waarde voor de kleurweergave-index (van 1 tot 100)."

**Comment by wjtmollema** [comment]
@RiX012 Ik vraag hierbij nog om expliciete toestemming om de Collectie Eenheid uit imborVoc_Collecties te verwijderen

**Comment by RiX012** [comment]
Volgens mij was de oplossing:
- In `imborKern_K_KlassenAttributen` de kolom Eenheid niet laten putten uit `imborVoc_Termen`, maar uit `refModel_Mapping`
- De `MappingGUID` combineert dan de juiste zaken om de eenheid af te leiden. 
- Vanuit `refModel_Domeinwaarden kan dan de kolom 'Toelichting` gebruikt worden ter presentatie in `imborKern_K_KlassenAttributen` 
- Rr mag een kolom aan `refModel_Mapping` worden toegevoegd 'Collectie' waarin we de eenheden uit die tabel voorzien van de collectie 'Eenheid'. Als dat te ingewikkeld wordt mag hij verwijderd worden.

**Comment by RiX012** [comment]
> `m NAP`
> `pae`

Nagevraag gedaan hoe eigen units te definiëren als extensie van QUDT. Wacht nog op antwoord.

**Comment by wjtmollema** [comment]
**Update**

- imbor-URI's toegevoegd aan imborVoc_Termen
- URI's van NEN3610, NEN2660-2, INSPIRE toegevoegd aan imborVoc_Termen
- QUDT-eenheden toegevoegd aan imborVoc_Termen, incl. URI's
- Eenheden opzoekmechanisme in imborKern_K_KlassenAttributen bevraagt nu imborVoc_Termen op Collectie Eenheid
- refModel-tabellen zijn nog steeds onderdeel van de database. @RiX012 De eer is aan jou om deze tabellen eruit te halen zodra de oplossing voor IMGeo, IMKL, NEN2767, GWSW en SOR is vastgesteld.

**Comment by RiX012** [comment]
@JochemMollema 
Graag de volgende aanpassingen doorvoeren qua eenheden. Dan is deze compleet.
[Eenheden aanpasssingen.xlsx](https://github.com/user-attachments/files/17600327/Eenheden.aanpasssingen.xlsx)

**Comment by JochemMollema** [comment]
Laatste aanpassingen verwerkt. 

@RiX012 De melding kan gesloten worden.
