### ISSUE TITLE
Wegfunctie niet in Access database (formulier) en wel in LD versie

### ISSUE THREAD

**Issue by LuukWijnholts** [Stichting-CROW/imbor#125]
De eigenschap Wegfunctie is niet meer gekoppeld aan Verhardingsobject in de access database, maar nog wel in de LD variant. Deze eigenschap zou in de LD variant ook niet meer voor moeten komen.

Daarnaast zijn in de access bestand de domeinwaarden van Wegfunctie toegevoegd aan de domeinwaarden van Gebruiksfunctie (gekoppeld aan Beheerobject), maar dit is nog niet het geval in de LD variant. Deze dienen nog toegevoegd te worden.

**Comment by RiX012** [comment]
Nu duidelijk dat deze changes in Access zijn gemaakt vlak nadat de LD transformatie pijplijn is gedraaid. We onderzoeken de delta's en kijken of het nodig/handig is om nieuwe LD versie te publiceren.

**Comment by RiX012** [comment]
Niet meer van toepassing vanwege IMBOR2022 (was issue voor IMBOR-LD 2020-08
