### ISSUE TITLE
Tekstuele fout in term imborvoc_termen

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#1250]
e9fa737d-8b64-4119-b6e8-a98d37288192: term "Afvoeren hemelwater naar de ondergrond " eindigd op een spatie
5f4a60c9-e4fd-4c5f-8810-30be99d289fe: definitie is afgekapt; eindigd op " (Bron: definities.geostandaarden.n"

**Comment by RiX012** [comment]
Thanks, gaan we aanpassen
