### ISSUE TITLE
PNH: Deksloof

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1251]
De provincie gebruikt het object Deksloof. Hoe gaan we daarmee om als we volgens IMBOR willen modelleren?

**Comment by wjtmollema** [comment]
Hier is in IMBOR ook een objecttype voor: `Sloof`. In de definitie, die afkomstig is uit IMGeo, wordt de nadruk gelegd op de toepassing samen met een Pijler. Maar een `Sloof` kan ook toegepast worden bij een `Damwand`. 

Wellicht moet voor de gewenste toepassing van de Provincie Noord-Holland de definitie aangepast worden.

**Comment by wjtmollema** [comment]
@RiX012 Kan deze issue gesloten worden?

**Comment by RiX012** [comment]
Ja, als we de definitie breder hanteren.
