### ISSUE TITLE
PNH: Geluidscherm en Dijk

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1252]
Geluidsscherm valt bij ons onder Geluidswerende voorziening, zoals bij ons ook Dijk als een geluidswerende voorziening kan worden aangemerkt. Een geluidsscherm kan bovendien op een Dijk zijn geplaatst. Is het ook mogelijk om een dergelijke indeling met IMBOR te realiseren?

**Comment by RiX012** [comment]
Eerste reactie op het gebruik van semantische relaties is: IMBOR geeft een klein aantal verplichte relaties (kardinaliteit 1:n), maar vooral veel 'veel voorkomende' relaties. (zie ook hier: https://docs.crow.nl/imbor/techdoc/#semantische-relaties) Het staat dus de gebruiker ook vrij om bijvoorbeeld een Geluidsscherm op een Dijk te plaatsen ook al ligt die niet vast in IMBOR, mits er maar gebruik gemaakt wordt van de NEN2660-2 relaties.

**Comment by wjtmollema** [comment]
Aanvullend op het bovenstaande commentaar zou de volgende uitwerking mogelijk zijn:

`Dijklichaam :: voert uit :: Beperken van geluidshinder`

Als de Provincie Noord-Holland hiervan op de hoogte gesteld is en ze is daarmee geholpen, dan kan deze issue gesloten worden.

**Comment by wjtmollema** [comment]
Deze is volgens mij gereed om gesloten te worden.
