### ISSUE TITLE
PNH: FunderingsType bij Geluidscherm

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1253]
Een aanvullende vraag is het attribuut Funderingstype. Deze komt niet voor bij Geluidscherm, terwijl deze bij ons ook daar wordt gebruikt. Wij kennen (ik ken ze nog niet allemaal, ben ik aan het navragen) de volgende funderingstypes:

BEP = Betonpaal
Betonpaal = Betonpaal
BOP = Boorpaal (Dus geen Betonvloer op palen)
BUP = Buispaal
OS = Op   staal

**Comment by wjtmollema** [comment]
Sinds IMBOR 2022 is `Fundering` een objecttype; niet langer een attribuut. 

Zie hier de inhoud van het enumeratietype `FunderingType`:
Enumeratietype	Domeinwaarde
FunderingType	Betonvloer op palen
FunderingType	Fundatieplaat
FunderingType	Gebonden fundering
FunderingType	Gedeeltelijk onderheid
FunderingType	Geovlies
FunderingType	Grasfundatie
FunderingType	Grondverbetering
FunderingType	Houten roosterwerk
FunderingType	Kespen
FunderingType	Ketelzand
FunderingType	Ketelzand fundering
FunderingType	Kleef en onderheid
FunderingType	Kunststof stabiliteitsconstructie
FunderingType	Onderheid
FunderingType	Onderheid stuit
FunderingType	Ongebonden fundering
FunderingType	Op staal
FunderingType	Paalfundering
FunderingType	Paaljuk
FunderingType	Poerenfundering
FunderingType	Polystyreen fundering
FunderingType	Prefab fundering
FunderingType	Rietmatten
FunderingType	Sloofconstructie
FunderingType	Wapeningsnet
FunderingType	Zelfbindende fundering


Volgens mij is alleen de term 'Boorpaal' hier een aanvulling op. Deze kan worden toegevoegd. Wellicht kan de Provincie Noord-Holland hiervoor hun definitie aanleveren?

**Comment by wjtmollema** [comment]
@RiX012 Deze is volgens mij goed om door te voeren en kan direct daarna gesloten worden.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
