### ISSUE TITLE
Inversie van nen2660:hasPart toevoegen in IMBOR model

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1255]
Omdat in de meeste IMBOR (en GWSW) toepassingen geldt dat de inverse van `nen2660:hasPart` ook geldt, voegen we dit in het IMBOR model toe. Dit mag volgens de NEN2660-2.

```turtle
https://w3id.org/nen2660/def#isPartOf rdf:type rdf:Property ;
    rdfs:seeAlso nen2660-term:hasPart ;
    skos:definition "A decomposition (isPartOf) relation between concrete concepts"@en, 
                            "Een decompositie (isPartOf) relatie tussen concrete concepten"@nl ;
    skos:prefLabel "is part of"@en, 
                             "is deel van"@nl;
    rdf:type owl:ObjectProperty ;
    owl:inverseOf https://w3id.org/nen2660/def#hasPart .
```

Dit op basis van pagina 21 uit de NEN2660-2

**Comment by wjtmollema** [comment]
`heeft deel` is als term toegevoegd aan imborVoc_Termen.

**Comment by RiX012** [comment]
> `is onderdeel van` is als term toegevoegd aan imborVoc_Termen.

@wjtmollema Deze moet dan ook in de refModel tabellen worden opgenomen. Deze mapt gewoon precies hetzelfde als `hasPart`
