### ISSUE TITLE
Gemeente Venray: Afsluitpaal - nieuw type

### ISSUE THREAD

**Issue by gvoorhorst** [Stichting-CROW/imbor#1256]
Binnen de gemeente Venray willen we de afsluitpalen gaan inventariseren. 

In IMBOR zijn de volgende typen mogelijk binnen het objecttype Afsluitpaal:

![image](https://github.com/Stichting-CROW/imbor/assets/140704871/b63fa7af-87a1-45cb-a74e-c124c5ea96b4)

Volgens mij voorziet dit niet in alle mogelijkheden. Zie het voorbeeld hieronder. Deze is niet verwijderbaar.

Kunnen jullie er een type bij maken, bijvoorbeeld 'anti-inrijpaal' zodat we deze palen ook van een type kunnen voorzien. 

![image](https://github.com/Stichting-CROW/imbor/assets/140704871/c9b52448-be7b-47b6-a71e-1e8fd10e8854)

**Comment by wjtmollema** [comment]
Bedankt voor de melding.

**Voorgestelde verwerking**
Het toevoegen van een nieuwe domeinwaarde aan `AfsluitpaalType`: `Anti-inrijpaal` of `Vaste fietspadpaal`

**Comment by wjtmollema** [comment]
@RiX012 Akkoord?
