### ISSUE TITLE
Gemeente Roosendaal: halfverharding Type gedetailleerd verder aanvullen

### ISSUE THREAD

**Issue by DErveRSD** [Stichting-CROW/imbor#1257]
Type gedetailleerd bij samenhangend vind ik te summier. In de gemeente Roosendaal leggen we aan en onderhouden we verschillende soorten halfverharding. Niet alles heeft hetzelfde onderhoud, daarom wil ik de Type gedetailleerd_I lijst verder uitgebreid hebben.

Lijst aanvullen met:
Graustabiel, Graulivijn, Dolomiet, Gralux, Achterhoeks Padvast, BGS-pad

Als alternatief kan Gravel worden gekozen, maar ik wil in mijn beheersysteem precies weten wat ik heb. Dan kan ik daar mijn vervangingsplannen op schrijven.

**Comment by JHLJoosten** [comment]
Hoi David, Sorry dat hier nog niet op is gereageerd. Ik zet deze door om te beoordelen.
Met vriendelijke groet,
John

**Comment by DErveRSD** [comment]
Is deze al beoordeeld?

**Comment by RiX012** [comment]
@JochemMollema, wil je deze meenemen icm met #1273?

**Comment by JochemMollema** [comment]
Graustabiel, Graulivijn, Dolomiet, Gralux, Achterhoeks Padvast, BGS-pad als verschijningsvormen toegevoegd aan Halfverharding.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
