### ISSUE TITLE
Afstemming IMBOR 2024 en GWSW: voorbeelden van imbor:breedte vs. gwsw:breedteLeiding

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1264]
Bij de afstemming van IMBOR en GWSW is geconstateerd dat er voorbeelden zijn van algemene eigenschappen die IMBOR bij een klasse registreert die binnen GWSW nog nader worden gespecificeerd. Een voorbeeld is `imbor:breedte` vs. `gwsw:breedteLeiding`. In IMBOR wordt `breedte` bij de klasse `Leiding` geïntroduceerd. In GWSW wordt 'Breedte leiding' ook op het niveau van de Leiding toegekend. In dit geval kan `breedte` bij integratie vervangen worden door 'Breedte leiding'. 

De vraag is nu als volgt: zijn er gevallen waarin IMBOR breedte, lengte, hoogte, diameter, oppervlakte etc. op een _hoger_ niveau toekent dan GWSW een specifiekere variant van dezelfde eigenschap toekent? In al die gevallen ontstaat er namelijk een 'eigenschappenconflict': er kunnen dan, bijv., bij een object twee breedtes geregistreerd worden.

**Comment by wjtmollema** [comment]
@RiX012 Van het bovenstaande heb ik de volgende voorbeelden gevonden:
- breedte: De toekenning van breedte aan Constructieonderdeel in IMBOR conflicteert met Breedte klep en Breedte deksel in GWSW
- hoogte: De toekenning van hoogte aan Constructieonderdeel in IMBOR conflicteert met Hoogte klep in GWSW
- kleur: De toekenning van kleur aan Constructie in IMBOR conflicteert met Kleur in GWSW.
- lengte: De toekenning van lengte aan Constructieonderdeel in IMBOR conflicteert met Lengte deksel en Lengte buisdeel in GWSW
- SDR-waarde: Zit in IMBOR bij Holle Leiding, maar in GWSW bij Kunststof leiding.
- toegankelijk: Zit in IMBOR bij Holle leiding en Put, maar in GWSW _alleen_ bij Leiding.
- verbindingstype: Zit in IMBOR bij Holle leiding, maar in GWSW bij Leiding.
- verhoogd risico: De toekenning van verhoogd risico aan IMKL-object in IMBOR conflicteert met Verhoogd risico in GWSW (waar het alleen op Mechanische rioolleiding en Mechanische transportleiding van toepassing is).
- wandruwheid binnenonder/binnenboven: Zit in IMBOR bij Holle leiding, maar in GWSW bij Leiding.
- WIBON-thema: De toekenning van WIBON-thema aan IMKL-object in IMBOR conflicteert met WIBON-thema in GWSW (waar het direct op Put en Leiding van toepassing is

**Comment by wjtmollema** [comment]
@JochemMollema Zaken om mee te nemen in check op GWSW 1.6.1

**Comment by JochemMollema** [comment]
Breedte, hoogte en lengte zijn standaard attributen van de klasse Constructieonderdeel, hiervoor worden geen aanpassingen gedaan.

Kathodische bescherming is verkeerd gemodelleerd en hoort niet bij de klasse Holle leiding, maar bij de klasse Transportleiding.

Kleur is op een lager niveau gemodelleerd dan de klasse Constructie.

SDR-waarde is als attribuut verkeerd gemodelleerd, het moet niet bij de klasse Holle leiding gemodelleerd worden, maar bij de klassen Rioolleiding en Transportleiding.

**Comment by JochemMollema** [comment]
verhoogd risico en WIBON-thema zijn verhuisd naar het informatieobject IMKL-informatie.

**Comment by JochemMollema** [comment]
verbindingstype is binnen IMBOR op het juiste niveau gemodelleerd, IMBOR Holle leiding is gelijk aan GWSW Leiding. Dit is ook het geval voor de attributen wandruwheid binnenonder en wandruwheid  binnenboven.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden
