### ISSUE TITLE
Gemeente Utrecht: laatste baggerjaar toevoegen aan Watergang, Watervlakte

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1268]
De gemeente Utrecht dient een verzoek in om een attribuut `laatste baggerjaar` toe te voegen aan de klassen `Watergang` en `Watervlakte`.

Definitie: Jaar waarin de laatste baggerwerkzaamheden van het waterobject zijn uitgevoerd.

**Comment by JochemMollema** [comment]
Attribuut laatste baggerjaar toegevoegd aan de objecttypen Watergang en Watervlakte.

**Comment by JochemMollema** [comment]
@RiX012 : deze issue kan gesloten worden.
