### ISSUE TITLE
Groningen: oplossing voor waterbufferende fundering

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1269]
Oplossing voor waterbufferende fundering, deze mogelijkheid verwerken als attributen van het objecttype Constructielaag verhardingsobject.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**

1. Een mogelijkheid is om hier een attribuut voor toe te voegen: `waterbufferend` (boolean); maar wellicht moet...
2. een andere mogelijkheid is om dit als een `type` op te voeren binnen `FunderingType` als `Waterbufferende fundering`; echter lijkt dit een fout te begaan door functie en constructie te verwarren in de typering; dus...
3. een laatste mogelijkheid is om hier een`Functie` voor te introduceren: `Bufferen van water`; alleen is het zo dat...
4. hier al een functie voor is: `Tijdelijke berging van hemelwater`

De vraag is dus of dit niet al uitgedrukt kan worden m.b.v. de bestaande IMBOR-bouwstenen. Het IMBOR-team moet de 'waterbufferende werking' van een fundering nader onderzoeken.

**Comment by JochemMollema** [comment]
Attribuut waterbufferend toegevoegd aan objecttype Constructielaag.

**Comment by JochemMollema** [comment]
@RiX012: deze issue kan gesloten worden.
