### ISSUE TITLE
VRAAG: Put voor ondergrondse container.

### ISSUE THREAD

**Issue by JHLJoosten** [Stichting-CROW/imbor#1270]
Onderstaande komt via de helpdesk binnen. Hebben jullie ene oplossing hiervoor? of moet dit worden toegevoegd.

Goedemorgen,

Wij van gemeente Heemstede en Bloemendaal willen graag volledig volgens het IMBOR-model werken.
Echter lopen we soms vast op wat onderdelen.

Zo nu ben ik op zoek naar de behuizing “put” die om een ondergrondse afvalcontainer zit.
Hoe en waar zou ik dit kunnen vinden in het model?

Het is soms lastig zoeken naar de juiste benamingen.
Alvast bedankt voor jullie reactie.

Met vriendelijke groet,

Irma Drost
Geo-gegevensbeheer | afd. informatie voorzieningen
Afwezig op vrijdag
(023) 5485872 | bloemendaal.nl | heemstede.nl
Gemeenten Bloemendaal en Heemstede werken ambtelijk samen

**Comment by JochemMollema** [comment]
Beste Irma,

De put voor de container wordt in IMBOR 2024 toegevoegd als objecttype Containerput.

Je kunt de leverancier van de gemeente vragen om dit objecttype alvast toe te voegen aan het beheersysteem.

Groet,

Jochem Mollema
