### ISSUE TITLE
Gemeente Amsterdam: Aanvulling Sport

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1272]
In het verleden heb ik wel eens een  suggesties gedaan van uit Amsterdam Sport als aanvulling op de IMBOR.
Ik heb in deze Excel weer wat suggesties om te wijzigen/aan te vullen voor eventueel een nieuwe versie.
[Aanvullingen  IMBOR Sport.xlsx](https://github.com/Stichting-CROW/imbor/files/15095638/Aanvullingen.IMBOR.Sport.xlsx)

**Comment by wjtmollema** [comment]
@RiX012 Vind jij dit impact 1?

**Comment by RiX012** [comment]
> @RiX012 Vind jij dit impact 1?

Ja, de aanvulling zijn overzichtelijk toch?

**Comment by wjtmollema** [comment]
Het gaat hier om de volgende wijzigingen:

- `Cricketpitch` toevoegen aan `SportveldType`
- Kogelslingersector verplaatsen naar `SportveldTypeGedetailleerd` met als BovenliggendeWaarde `Atletiekbaanonderdeel`
- Kogelstootsector verplaatsen naar `SportveldTypeGedetailleerd` met als BovenliggendeWaarde `Atletiekbaanonderdeel`
- Verspringsector verplaatsen naar `SportveldTypeGedetailleerd` met als BovenliggendeWaarde `Atletiekbaanonderdeel`
- Hinkstapsector verplaatsen naar `SportveldTypeGedetailleerd` met als BovenliggendeWaarde `Atletiekbaanonderdeel`
- Binnenterrein atletiekbaan  verplaatsen naar  `SportveldTypeGedetailleerd` met als BovenliggendeWaarde `Atletiekbaanonderdeel`

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
