### ISSUE TITLE
Gemeente Roosendaal Elementenverharding Voegvulling

### ISSUE THREAD

**Issue by DErveRSD** [Stichting-CROW/imbor#1273]
De gemeente Roosendaal voegt haar natuursteen op een aantal plaatsen met een onkruidwerende voeg. Deze kunnen we niet aangeven in IMBOR. Kan deze worden toegevoegd. De voegvulling is er wel voor Asfalt en Beton namelijk.

Wat mij betreft wordt het een ja/nee vak onder elementenverharding.

In het verleden buiten IMBOR was dit een aanvinkvakje. Dat lijkt mij ook de oplossing. Merk hoeft niet perce te worden benoemd.

**Comment by wjtmollema** [comment]
Bedankt voor het doen van de melding. 

**Voorgestelde uitwerking**

- Het toevoegen van het attribuut `voegvulling` aan `Elementenverharding`;
- Het toevoegen van een enumeratietype `ElementenverhardingVoegvulling` (in lijn met de reeds bestaande `AsfaltverhardingVoegvulling` en `BetonverhardingVoegvulling`.
- Overwegen of het bovenstaande ook geldt voor de attributen `voeg` en `soort voeg`.

**Comment by wjtmollema** [comment]
Oplossing hiervoor in samenhang met de volgende (voormalige) typeringen ontwikkelen:
```
Grasbetonsteen met grond
Grasbetonsteen met split
```

**Comment by JochemMollema** [comment]
Attribuut voegvulling is toegevoegd aan objecttype Elementenverharding.
De enumeratie ElementenverhardingVoegvulling  is toegevoegd.
Domeinwaarden Grasbetonsteen met grond en Grasbetonsteen met split toegevoegd aan de enumeratie ElementenverhardingVoegvulling.

@RiX012 deze issue kan gesloten worden.
