### ISSUE TITLE
Registratie "Drempelbreedte en -hoogte" bij put-onderdeel 'Overstortdrempel' (IMBOR 2020)

### ISSUE THREAD

**Issue by EJHeringa** [Stichting-CROW/imbor#1275]
Beste IMBOR-gebruikers,

Even een vraag ten aanzien van de registratie van hoogte en breedte van overstortdrempels in IMBOR 2020. 

Ben er niet helemaal zeker van welke wijze van registratie wenselijk is binnen het IMBOR_2020.
Onze oplossing zou in eerste instantie zijn om bij de keuze van het onderdeel 'Overstortdrempel' i.c.m. Objecttype 'Rioolput' de velden breedte en de hoogte in te vullen.
Omdat er als type onderdeel 'Overstortdrempel' is gekozen zou het logisch zijn dat het niet om de breedte cq. hoogte van de put, maar om de overstortdrempel gaat. 
Is dit een terechte aanname? Zo niet; op welke wijze dient dan de breedte cq. hoogte van deze drempels geregistreerd te worden?

Graag reacties.
![Drempel_overstort](https://github.com/Stichting-CROW/imbor/assets/61451356/259b2982-3c8e-4e9b-a44a-caaffe8001cb)

Alvast bedankt!

**Comment by wjtmollema** [comment]
Beste E. J. Heringa.

Namens het IMBOR-team wil ik de volgende reactie op uw melding met u delen:

1. De registratie van de afmetingen van Overstortdrempels bij Rioolputten is niet mogelijk in IMBOR 2020; 
2. IMBOR 2020 wordt niet meer gewijzigd of ondersteund; en 
3. in IMBOR 2022 is de Overstortdrempel een zelfstandig objecttype met de attributen lengte, breedte, etc., en is gerelateerd aan een Rioolput met een 'heeft deel'-semantische relatie.

Mocht u hier nog verdere vragen over hebben, antwoord dan gerust op dit bericht.

**Comment by wjtmollema** [comment]
@RiX012 Dit is geen openstaande issue, maar een antwoord op een gebruikersvraag. Kan nu gesloten worden m.i.

**Comment by RiX012** [comment]
Door beantwoording van de vraag is deze issue afgerond.
