### ISSUE TITLE
TOOI gebruiken voor de lijsten gemeenten, provincies, etc.

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1276]
Gebruik maken van de TOOI registraties en id's ipv eigen lijsten hanteren:
https://standaarden.overheid.nl/tooi/waardelijsten/item?lijst_uri=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fset%2Frwc_provincies_compleet%2F1&id=https%3A%2F%2Fidentifier.overheid.nl%2Ftooi%2Fid%2Fprovincie%2Fpv22

**Comment by wjtmollema** [comment]
1. URI's kunnen overgenomen worden voor de IMBOR-objecttypes Gemeente, Provincie, etc.;
2. Specifieke provincies en gemeenten zijn nu niet opgenomen in IMBOR;
3. Er kan wel nagedacht worden over een verwijzingsconstructie i.r.t. https://github.com/Stichting-CROW/imbor/issues/1258

**Comment by wjtmollema** [comment]
IMBOR zal de TOOI gaan gebruiken voor het standaardiseren van de klassen `Ministerie, Gemeente, Waterschap, Samenwerkingsorganisatie, Provincie`. De URIs voor deze klassen worden overgenomen, maar niet de registers voor gemeenten, provincies, etc. IMBOR-gebruikers kunnen instanties van de voorgenoemde klassen instantiëren en hiervoor de registers aanspreken, bijv. https://identifier.overheid.nl/tooi/id/gemeente/gm0228 voor gemeente Ede of 
https://identifier.overheid.nl/tooi/id/oorg/oorg10004 voor Rijkswaterstaat. Deze bijbehorende URIs spelen dus een identificerende rol in de IMBOR-modellering, maar moet een IMBOR-toepassing zelf ophalen. Concreet leidt dit tot de volgende wijzigingen:

Finale wijzigingen:
a.	URIs worden overgenomen in imborVoc_Termen voor `Ministerie, Gemeente, Waterschap en Provincie.`
b.	De klasse `Samenwerkingsorganisatie` wordt toegevoegd aan imborVoc_Termen met inbegrip van de bijbehorende URI.
c.	De klasse `Overige overheidsorganisatie` wordt toegevoegd aan imborVoc_Termen met inbegrip van de bijbehorende URI.
d.	De klasse `Caribische openbare lichamen` wordt toegevoegd aan imborVoc_Termen met inbegrip van de bijbehorende URI.
e.	`Ministerie van Economische Zaken` vervalt als term in IMBOR; wordt vervangen door Register Ministeries.
f.	`Ministerie van Infrastructuur en Waterstaat` vervalt als term in IMBOR; wordt vervangen door Register Ministeries.
g.	`Ministerie van Defensie` vervalt als term in IMBOR; wordt vervangen door Register Ministeries.
h.	`Ministerie van Landbouw, Natuur en Voedselkwaliteit` vervalt als term in IMBOR; wordt vervangen door Register Ministeries.
i.	`ProRail` vervalt als term in IMBOR; TOOI biedt hier geen register voor, maar dit wordt getackeld in: https://github.com/Stichting-CROW/imbor/issues/1258
j.	`Havenschap` vervalt als term in IMBOR; wordt vervangen door Register Samenwerkingsorganisaties.
k.	`Veiligheidsregio` vervalt als term in IMBOR; wordt vervangen door Register Samenwerkingsorganisaties.
l.	`Rijkswaterstaat` vervalt als term in IMBOR; wordt vervangen door Register Overige overheidsorganisaties.
m.	`Rijksvastgoedbedrijf` vervalt als term in IMBOR; wordt vervangen door Register Overige overheidsorganisaties.
n.	`Recreatieschap` vervalt als term in IMBOR; wordt vervangen door Register Samenwerkingsorganisaties.
o.	Bijbehorende enumeratietypes (`BeheerdObjectEigenaar, BeheerdObjectEigenaarGedetailleerd, BeheerdObjectBeheerder, BeheerdObjectBeheerderGedetailleerd, ObjectTweedeEigenaar` en `ObjectTweedeBeheerder`)_ worden opgeschoond.

**Comment by RiX012** [comment]
Vraag is: _de URIs zijn voor nu opgenomen in de toelichting, maar is het niet beter om de URIs de plaats van de IMBORGUID over te laten nemen?_ 

- [ ] Voor nu is het de bedoeling dat in de mapping tabellen (ref*) moeten de URI's van TOOI toegevoegd worden (ala QUDT)

De klasse ZBO hoeft niet opgenomen te worden als het (voorlopig) nog geen nut heeft in IMBOR. Anders uiteraard wel.

**Comment by wjtmollema** [comment]
**Actiepunt**

Verwijderen URI's uit toelichting. Voorlopige verwerking URI's in lijn met QUDT in refModel_Mapping, etc.

**Comment by wjtmollema** [comment]
Verwerkt in nieuw gepushte versie.

**Comment by RiX012** [comment]
Opgenomen in documentatie (later beschikbaar op: https://docs.crow.nl/imbor/techdoc/#tooi)
