### ISSUE TITLE
Stamlot in IMBOR?

### ISSUE THREAD

**Issue by heemstede** [Stichting-CROW/imbor#1277]
Bij de gemeente Heemstede en Bloemendaal wordt gebruikgemaakt van "stamlot"
Is dit ook in het IMBOR beschikbaar, en zo ja, waar staat deze?

**Comment by JHLJoosten** [comment]
@JochemMollema Weet jij hier antwoord op?

**Comment by JHLJoosten** [comment]
We nemen deze vraag mee naar een gesprek met het Norminstituut over een aantal openstaande punten.

**Comment by wjtmollema** [comment]
@RiX012 Wat mij betreft kan deze gesloten worden

**Comment by RiX012** [comment]
> Bij de gemeente Heemstede en Bloemendaal wordt gebruikgemaakt van "stamlot" Is dit ook in het IMBOR beschikbaar, en zo ja, waar staat deze?

Stamlot valt inderdaad onder de dynamische gegevens en is daarmee niet in de IMBOR scope.
