### ISSUE TITLE
Materiaal voor bord en folie spiltsen

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1278]
**Issue toelichten**
Volgens het model kan er maximaal 1 waarde van het materiaal geregistreerd worden bij een bord-object. Nu staan de materialen van de borden en folies in 1 tabel.
Is het mogelijk voor zowel het bord als de folie een materiaal toe te kennen?

**Eventueel een verbetervoorstel of eigen inzicht**

**Comment by wjtmollema** [comment]
Hallo Stefan,

Bedankt voor je vraag. Op dit moment kan je meerdere materialen aan hetzelfde bord relateren m.b.v. de semantische relatie `bestaat uit`. De multipliciteit van een individuele relatie is 0-1, omdat, bijvoorbeeld, een `Verkeersbord` maar 1 keer uit `Aluminium` kan bestaan. Echter kan ditzelfde `Verkeersbord` ook een `bestaat uit`-relatie hebben met `Diamond grade retroreflecterende folie`.

Hopelijk beantwoordt dit je vraag; zo niet, laat dat dan gerust weten.
