### ISSUE TITLE
MBOR-attributen voor Stuw

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1279]
PNH: In ons huidig datamodel hebben wij een objecttype Stuw, waar wij twee attributen vastleggen die schijnbaar niet in IMBOR kunnen worden gemapt: ‘KERENDEHOOGTE’ en ‘VASTOFBEWEEGBAAR’. Zijn er alternatieve attributen die we kunnen gebruiken, of is er een speciale reden da deze attributen niet zijn opgenomen?

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**

- Toevoegen van een attribuut `kerende hoogte` aan `Stuw` omdat een alternatief ontbreekt.
- 'vast of beweegbaar' hoeft wellicht niet toegevoegd te worden. Hieronder staan de bestaande types van `Stuw`. De vraag aan Provincie Noord-Holland is of het type al vertelt of het een vaste of beweegbare stuw is of dat er binnen de types variatie voor kan komen wat betreft dit gegeven. Als het eerste het geval is, dan is een nieuw attribuut overbodig; als echter dat laatste het geval is, dan is het toevoegen van dit attribuut nuttig.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#467886" vlink="#96607D">


Term | Definitie
-- | --
Balgstuw | Een stuw waarbij een rubberen doek,   bevestigd aan de waterbodem en de constructies aan de oevers of in het water,   volgepompt kan worden met lucht om water tegen te houden.
Brievenbusstuw | Een stuw met kleine   doorstroomopening, vaak van circa 0,5 bij 2 meter.
Cascadestuw | Een stuw die bestaat   uit een getrapte constructie in de watergang, gelijk een vispassage, die vaak   bestaat uit diverse materialen.
Conserveringstuw | Een stuw die in een waterloop wordt geplaatst met als doel het besparen van water en het tegengaan van uitdroging. Een mogelijke bijwerking van het gebruik van dit type stuw is een hoger grondwaterpeil, doordat het water dat de stuw tegenhoudt door de omringende oevergrond wordt opgenomen.
Drijverstuw | Een onafhankelijk functionerende stuw waarbij verschillen evenredig over een gebied verdeeld worden, wanneer het boven- en onderpand een vast peilverschil ten opzichte van elkaar moeten behouden. De stuw drijft met zijn grote drijver op het lage pand en zorgt voor een opwaartse kracht, waardoor de stuwbak in staat is een bepaalde hoeveelheid water te dragen/keren. Het systeem is hierbij in evenwicht. (Bron: Gegevenswoordenboek Waterschap Hunze en Aa's)
Gronddamstuw | Een stuw in het   midden van een damwand die in de grond is bevestigd en regelbaar is in hoogte   zodat het waterpeil beheerst kan worden.
Hevelstuw | Een stuw die   gebruikmaakt van een buis om het water van de toestroom (gedeeltelijk) af te   vangen en te herleiden.
Inlaat- en/of   aflaatstuw | Inlaatstuw: een stuw   met als onderdeel een inlaat die overtollig water afvoert naar een   nabijgelegen waterberging. Aflaatstuw: een stuw met een voorziening die de   waterspiegel doet dalen.
Klepstuw | Een stuw met een   opening en een afsluitbare klep voor die opening ten behoeve van   waterbeheersing.
Knijpstuw | Een stuw met een   V-vormige overstort die het waterafvoerende vermogen van een sloot reguleert.
Meetstuw | Een stuw die bestaat   uit een kunstmatige verhoging van de bodem van een waterloop of een door   overstortschuiven voorziene rechte of V-vormige overlaat waardoor deze   instelbaar zijn, waarmee kritische stroming wordt gecreëerd om debieten te   meten.
Schotbalkstuw | Een stuw waarvan het   schut, een kunstwerkdeel dat het waterniveau aan een zijde van de stuw, wordt   bepaald door schotbalken.
Schuifstuw | Een stuw met een   beweegbare schuif, die dient om de waterstand boven- en benedenstrooms van de   constructie of een debiet te regelen. (Bron: Aquo)
Segmentstuw | Een stuw die twee of   meer kleppen of openingen heeft die afzonderlijk bediend of gesloten kunnen   worden.
Stuwbak | Een uitstroombak aan   de benedenstroomse zijde van een stuw.
Trommelstuw | Een stuw bestaande   uit een klep, een tegenklep en een nis, waarbij de klep het water tegenhoudt,   maar de nis vult en de tegenklep activeert.



</body>

</html>

**Comment by JochemMollema** [comment]
Attributen kerende hoogte boven waterlijn en beweegbaar ja/nee zijn toegevoegd aan het objecttype Stuw.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.

**Comment by JochemMollema** [comment]
Bij nader inzien is via de bestaande verschijningsvormen te achterhalen of een stuw beweegbaar is. Het attribuut beweegbaar is hiermee overbodig.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden, de aanpassing voor het attribuut beweegbaar is teruggedraaid,
