### ISSUE TITLE
verschil tussen bouwjaar en productiejaar in borden?

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1281]
Bij de dragers van borden ben ik opzoek naar het productiejaar. Voor paal, portaal en zweepmast vind ik onder klasse Paalconstructie het  attribuut 'productiejaar'. Voor de ophangconstructie en uithouder ben ik ook opzoek naar het productiejaar. Nu vind ik daar geen gelijk attribuut. Als alternatief dacht ik aan het attribuut 'bouwjaar' onder de klasse Constructie. Maar is dit juist? Wat is het verschil tussen deze 2 attributen?

**Eventueel een verbetervoorstel of eigen inzicht**
Indien niet toepasbaar ook een attribuut productiejaar toevoegen aan de ophangconstructie en de uithouder

**Comment by wjtmollema** [comment]
Bedankt voor de melding Stefan. Er is inderdaad een inhoudelijk verschil tussen de twee. Productiejaar gaat over het jaar van productie door de fabrikant. Dit kan een ander jaartal zijn dan het bouwjaar of jaar van aanleg.

**Voorgestelde verwerking**

1. `productiejaar` toevoegen bij `Ophangconstructie` of bovenliggende klasse;
2. `productiejaar` toevoegen bij `Uithouder` of bovenliggende klasse;

**Comment by wjtmollema** [comment]
@RiX012 Akkoord?

**Comment by RiX012** [comment]
> @RiX012 Akkoord?

Yes

**Comment by StefanvanGerwen** [comment]
Hartelijk dank

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
