### ISSUE TITLE
Materiaal borden

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1282]
Momenteel kunnen we niet alle materialen kwijt. In het tabblad relaties staan niet alle mogelijke waarden die toegewezen dienen te worden, onder de SemantischeRelatie 'bestaat uit'.

**Eventueel een verbetervoorstel of eigen inzicht**
Is onderstaande lijst op te nemen in de materialenlijst (bestaat uit)?
•	Coil coating Aluminium
•	Cradle tot cradle aluminium
•	Refurbished aluminium
•	Bamboe (Biobased)
•	Rijstvlies (Biobased)
•	Bermgras/hennep met Bio-composite (Biobased)
•	Sealwise PVC
•	Honingraat Bio Recycling

**Comment by wjtmollema** [comment]
Bedankt voor je bericht Stefan. IMBOR wil open omgaan met materialen, omdat de standaard tot nu toe niet in staat is gebleken alles te standaardiseren. In de toekomst zal IMBOR dan ook gebruikmaken van externe materialenlijsten.

Over deze specifieke materialen materialen moet de IMBOR Expertgroep Verkeer eerst een uitspraak doen.

**Comment by JochemMollema** [comment]
In afwachting van een Nederlandse standaarden voor materialen, de materialen toegevoegd die de provinicie nodig heeft.
• Coil coating Aluminium
• Cradle tot cradle aluminium
• Refurbished aluminium
• Bamboe (Biobased)
• Rijstvlies (Biobased)
• Bermgras/hennep met Bio-composite (Biobased)
• Sealwise PVC
• Honingraat Bio Recycling

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.

**Comment by RiX012** [comment]
@JochemMollema deze materialen ontbreken in de hierarchie. Ze moeten subklasse zijn van `Materie` of van iets wat al een subklasse is van `Materie`. Voor 'Sealwise PVC' kan dat bijvoorbeeld de klasse `PVC` zijn. 

Misschien een goede check query of alles wel in de hierarchie tabel voorkomt wat daar moet staan?

**Comment by JochemMollema** [comment]
@RiX012  Alle tabellen zijn weer op elkaar afgestemd.
