### ISSUE TITLE
Uitspraken over 'instantiatie' van het model

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#129]
Momenteel doet IMBOR alleen maar impliciet uitspraken over hoe men mag instantieren. Voorbeeld: een objecttype wordt ingedeeld in meerdere vakdisciplines. Hoort dan de instantie van dat object ook in meerdere vakdisciplines? Momenteel is daar alleen een 'mondelinge praktijkrichtlijn voor'. Die luidt nu: ja, het object is uniek en de vakdiscipline is alleen maar een zoekmechanisme. Uitspraken over instantiatie moeten geformaliseerd worden.

We moeten eenduidig iets zeggen over instanties. We gaan hier _wel_ wat over zeggen, of we zeggen dat we er _niks_ over zeggen.

**Comment by redmer** [comment]
Wat betreft je voorbeeld: met de scheiding vocabulaire en klassen, zie ik het zo:

1. Een vocabulaire-item (`skos:Concept`) behoort tot een vakdiscipline (`skos:Collection`).
2. De instantieerbare klasse (`owl:Class`) heeft een eigenschap `dct:subject`, met als waarde het bijbehorende `skos:Concept`.
3. De instantie verwijst alleen naar de klasse (`rdf:type`). 

---

1. Of kwalificaties van de klasse weerslag hebben op de instantie, hangt af van de semantiek van die kwalificaties. Bij `rdfs:subClassOf` wel (een instantie is ook een instantie van de superklasses), `rdfs:label` niet. 
2. Of instanties in een UI gevonden moeten kunnen worden aan de hand van een vakdiscipline (of een om het even welke andere kwalificatie van de klasse), is een implementatiekeuze.

**Comment by RiX012** [comment]
Het is een 'documentatie' issue, maar wel een elementaire. Hierover moet meer informatie worden ingewonnen hoe 'men' dit doet

**Comment by JochemMollema** [comment]
Uitgewerkt   in de tabel imborKern_K_VakdisciplineObjecttypes
--
