### ISSUE TITLE
wijziging/verzoek vaste keuzelijst "constructielaagsoort" 

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/imbor#1291]
Ik kreeg dit verzoek per mail, via de klantenservice, van een gemeente

**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Volgens onze wegbeheerder mist hij bij de vaste picklijst  “constructielaagsoort” de domeinwaarde “samilaag”
Momenteel is het een vaste lijst waar we als gebruiker geen domeinwaarden aan toe kunnen/mogen voegen.

**Beschrijf de oplossing die je voor je ziet**

**Wat voor alternatieven heb je overwogen?*
Een beknopte en heldere beschrijving van alternatieve oplossingen die je hebt overwegen.

**Meer context**
Voeg andere context of bijvoorbeeld schermfoto's toe. Denk eraan, deze melding is openbaar.

**Comment by wjtmollema** [comment]
Er zijn twee opties voor de verwerking van deze issue:

1. Datatype van `constructielaagsoort` wijzigen in `Referentie`;
2. Toevoegen van `Samilaag` aan `ConstructielaagVerhardingsobjectConstructielaagsoort`.

**Comment by JochemMollema** [comment]
Gekozen voor optie 2: domeinwaarde Samilaag toegevoegd aan enumeratie ConstructielaagConstructielaagsoort.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden
