### ISSUE TITLE
Algemeen functionele gebieden

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#1292]
Graag bij module algemeen twee functionele | registratieve gebieden opnemen
vraag verzoek namen provincie Noord-Brabant

- Sportterrein
- Natuurgebied
 (incl. definitie)
Gr. Ernst

**Comment by wjtmollema** [comment]
Beste ernst63,

Bedankt voor het doorgeven van de melding. Deze wijziging kan worden verzorgd. 

**Voorgestelde verwerking**

1. Natuurgebied toevoegen aan Algemeen in imborKern__K_VakdisciplinesObjecttypen
2. Sportterrein toevoegen aan Algemeen in imborKern__K_VakdisciplinesObjecttypen

@RiX012 is verwerking akkoord?

**Comment by RiX012** [comment]
Ok
