### ISSUE TITLE
EindeGarantieperiode

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#1293]
Verzoek namens Provincie Noord-Brabant:

Het is van belang voor het beheer en onderhoud van de assets dat er tijdig een laatste inspectie wordt gedaan om te kijken of er nog aanspraak kan worden gemaakt op garantie. Derhalve is het van belang dat de garantiedatum van het object is geregistreerd.

Graag heroverwegen om "EindeGarantieperiode" weer op te nemen als attribuutveld

**Comment by wjtmollema** [comment]
Beste ernst63, 

Bedankt voor het delen van het verzoek namens de Provincie Noord-Brabant. Gelukkig kan ik melden dat het attribuut `einde garantieperiode` nog steeds onderdeel is van IMBOR 2022, maar is verplaatst naar het `Informatieobject` `Oplever-informatie`. Zie onderstaande afbeelding.  Een `Informatieobject` is een bundel eigenschappen die een IMBOR-objecttype nader beschrijven.

![image](https://github.com/user-attachments/assets/d89f7cd6-9b61-4d87-a03a-e7aa2645e187)
