### ISSUE TITLE
"Goot" objecten missen kenmerken en relaties

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#1294]
'Goot objecten' zoals Lijngoot en Molgoot missen kenmerken die in GWSW gedefinieerd zijn voor deze objecttypen
Voorbeelden zijn: vorm,verbindingstype en wanddikte

Ook mist de relatie met Materie voor deze objecttypen

Graag de goot objecttypen aanvullen met de kenmerken  en relaties die in GWSW gedefinieerd zijn

**Comment by wjtmollema** [comment]
Bedankt voor de melding. 

Dit probleem wordt opgelost door de directe aanlevering van IMBOR Stedelijk Water door de ontologie van het GWSW in IMBOR 2025.

**Comment by RiX012** [comment]
Verwerkt in #1356
