### ISSUE TITLE
breedte en hoogte attribuut van (Riool)putten hebben verkeerde eenheid

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#1295]
Breedte en hoogte attribuut van (Riool)putten hebben verkeerde eenheid

eenheid van breedte en hoogte attribuut van (Riool)putten moeten conform GWSW de eenheid mm hebben

**Comment by wjtmollema** [comment]
Bedankt voor de opmerkzaamheid. Gelukkig mag ik je erop wijzen dat in de reeds gesloten issue 1096 (https://github.com/Stichting-CROW/imbor/issues/1096) dit probleem al is geïdentificeerd en opgelost.
