### ISSUE TITLE
Gemeente Utrecht: Toevoegen van objecttype Hellingbaan

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1297]
De gemeente Utrecht heeft een gebruikssituatie en wil daar IMBOR bij toepassen. Een hellend parkeerdek moet onderscheiden worden van een vlak parkeerdek. Echter loopt de gemeente tegen het ontbreken van een specifiek objecttype aan voor het hellende parkeerdek: `Hellingbaan`. Dit is op dit moment een term binnen IMBOR, maar de betekenis van die term slaat op een onderdeel van een `Speeltoestel`.

Zie hieronder het voorbeeld van de gemeente:
![image](https://github.com/user-attachments/assets/06bf75d8-ed40-49f3-a79c-55216f4d722c)

**Voorgestelde verwerking**

- Toevoegen van objecttype `Hellingbaan` als subklasse van `Gebouwcomponent`, net als `Parkeerdek`.

**Comment by JochemMollema** [comment]
Hellingbaan is als zelfstandig objecttype verwerkt en gepostioneerd onder de klasse Gebouwcomponent.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
