### ISSUE TITLE
domeinwaarden toevoegen aan VlakmarkeringMarkeringToepassing t.b.v. type Drempelmarkering

### ISSUE THREAD

**Issue by StefanvanGerwen** [Stichting-CROW/imbor#1298]
Drempel markering kan worden toegepast op een verkeersdrempel en op een verkeersplateau. Bij deze toepassingen zijn verschillende afmetingen aan de orde. Momenteel kunnen de waarden verkeersdrempel en verkeersplateau toegekend worden.

Toevoegen van de domeinwaarden van 'verkeersdrempel' en 'verkeersplateau' als VlakmarkeringMarkeringToepassing voor het vlakmarkeringsType Drempelmarkering.

**Comment by JochemMollema** [comment]
Domeinwaarden Verkeersdrempelmarkering en Verkeersplateaumarkering zijn aan de enumeratie VlakmarkeringMarkeringToepassing toegevoegd.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden
