### ISSUE TITLE
Zou de mogelijkheid er kunnen komen om naast de 'latest' versie van IMBOR ook de oudere versie refereerbaar te houden

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#130]
Verzoek van Amsterdam

Kunnen we de versie in de URI opnemen voor oudere versies. Met dan wel ongeversioneerd altijd de latest.

**Comment by RiX012** [comment]
Dit kan inmiddels. De oplossing is gevonden/uitgewerkt door Miltos van Amsterdam. Het huidige LDP van CROW voorziet hier nog niet in, maar onze nieuwe oplossingen moeten dat wel gaan doen.

**Comment by JochemMollema** [comment]
IMBOR-team: niet in deze versie.
