### ISSUE TITLE
Orientatierichting verkeersborden richting aanvullen

### ISSUE THREAD

**Issue by ErikAkkerman** [Stichting-CROW/imbor#1300]
Bij het attribuut Oriëntatierichting staat de volgende omschrijving:
Oriëntatierichting van het bord ten opzichte van het noorden in graden met een afwijking van maximaal +/- 5 graden.

Hierbij is niet de draairichting aangegeven zodat er tussen applicaties verschillen ontstaan in de richting waarin gerekend wordt. 
We zouden graag zien dat aangevuld wordt dat de orientatierichting met de klok mee of tegen de klok in van 0 tot 360 gaat of van 360 tot 0.

**Comment by RiX012** [comment]
In IMBOR is daar inderdaad niets over vastgelegd. Ik ben nog even in BGT/IMGeo gedoken, maar daar zit het ook niet in. Het is dus een toevoeging vanuit IMBOR ooit geweest. Uiteindelijk baseren we ons allemaal via via op de ISO19107 en daar staat de volgende passage:

> 
> The datatype Bearing denotes a direction. The bearing can take either one of two forms:
> •	A set of angles, one a planar bearing, and the second a measure of altitude (positive above the horizontal, negative below the horizon), essentially creating a local spherical coordinate system.
> •	A derived directional vector from the coordinate system at the initial point, a unit vector with the direction associated to the set of angles.
> Since the two types of measures are identical, the values of bearing are the same, but the interpretations will depend on the usage (usually a reference direction, the "0" offset and a direction of rotation, clockwise or counter clockwise).

Hier kunnen we in IMBOR dus een keuze over maken.

**Comment by JochemMollema** [comment]
Definitie oriëntatierichting uitgebreid dat het hier om een richting gaat met de klok mee.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
