### ISSUE TITLE
Relatie SOR en IMBOR moet herzien worden

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1301]
De status van SOR is onduidelijk. Vandaar dat we in de nieuwe versie de relatie naar de SOR moeten herzien:
- In Acces menu eruit
- Documentatie aanpassen
- Inhoudelijk nader bekijken

**Comment by JHLJoosten** [comment]
@JHLJoosten , Kun je dit meenemen in de communicatie naad de beheercommissie.

**Comment by RiX012** [comment]
Wordt verder verwerkt in. #1362
