### ISSUE TITLE
Registreren Container opstelplaatsen (gemeente Ede)

### ISSUE THREAD

**Issue by JHLJoosten** [Stichting-CROW/imbor#1302]
Wij vragen ons namelijk op dit moment af, hoe we containeropstelplaatsen kunnen registreren binnen het IMBOR. Deze worden op verschillende manieren aangelegd. situatie 1 is een containeropstelplaats waarbij de ondergrond bestaat uit FlowBlocks. Er is niet iets als een Gebruiksfunctie bij de verhardingsobjecten voor containeropstelplaats. En we vragen ons ook af of zo’n vlak hoort bij de verhardingsobjecten, of valt het misschien onder een ander objecttype? (We weten eigenlijk ook niet precies bij welke type en type detail Flowblocks onder vallen?)
situatie 2 is een een containeropstelplaats onder de type Halfverharding, maar ook hier kunnen we niet iets toevoegen als Gebruiksfunctie = Containeropstelplaats, volgens mij.

Hoe kunnen we dit registreren? We gebruiken nog IMBOR 2020.

stefan.van.dam@ede.nl
![foto1](https://github.com/user-attachments/assets/50cb26b0-dff7-4c85-a69a-464bf13550b6)
![foto2](https://github.com/user-attachments/assets/ae379cd6-540d-4765-850e-a59d263984f0)

**Comment by wjtmollema** [comment]
IMBOR 2020:
- Objecttype Verzamelplaats : type : Vuilcontainerplaats

IMBOR 2022:

- Objecttype Vuilcontainerplaats
- Objecttype Opstelplaats : type : Containerplaats

IMBOR 2025:
- Objecttype Opstelplaats : type : Containerplaats / Vuilcontainerplaats

Het gaat hierbij om 'Ruimtelijke gebieden' die corresponderen in geometrie met de Verharding. Dit gegeven wordt dus niet als gebruiksfunctie geregistreerd bij het object dat de Verharding representeert.

**Comment by JHLJoosten** [comment]
Thanks Thonas,
Ik zal dit ook met Ede communiceren zo.
John

**Comment by JHLJoosten** [comment]
gecommuniceerd.

**Comment by JHLJoosten** [comment]
@JochemMollema Kunnen we hier antwoord op geven?

Hoi John,

Dank voor je antwoord. Maar waar vind ik die Ruimtelijke gebieden dan? Of wordt dat ingeregeld door de software leverancier van je BOR-pakket?
En begrijp ik het dan goed dat je een vlak hebt in de verhardingslaag, daar geef je alles aan wat de verharding betreft, en daarboven (of eronder) heb je nog een laag met dezelfde vlak, maar dan wat de ruimtelijk gebied is? En zo ja, wat is dan het verschil tussen een containeropstelplaats (wat in mijn ogen een gebruiksfunctie is van een verhardingsvlak) en een hondenlosloopgebied (wat de gebruiksfunctie kan zijn van bijv. een groenvlak)?

Daarnaast ben ik nog benieuwd naar de reactie op mijn andere vraag die ik toendertijd heb gesteld via de mail (helemaal onderaan deze mail). Dat was deze: 
Daarnaast vroegen we ons ook het volgende af. Wij zitten nu op IMBOR 2020. In de toekomst gaan we vast nog een keer over op IMBOR 2022. Maar nu kregen we een keer te horen tijdens een IMBOR cursus die door jullie werd gegeven, dat in IMBOR 2022 alles een niveau hoger komt te liggen. Dus waar je nu 1 tabel hebt met alle verhardingsobjecten erin, komt er dan straks 6 tabellen met per tabel de type verharding erin. Dit is voor onze wegbeheerders vrijwel niet werkbaar, en dat lijkt voor mij als data specialist ook erg onwaarschijnlijk. Qua inregelen en functioneel beheer kost het allemaal veel meer tijd. Dus we vroegen ons af of we dat toen niet misschien verkeerd hadden begrepen, en hoe het dan wel zit.

Alvast dank weer voor de reactie!
