### ISSUE TITLE
Redundatie: Certificering-informatie kan via Document

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1303]
De gegevens van Certificering-informatie kunnen uitgedrukt worden m.b.v. Document als in DocumentType 'Certificaat' beschikbaar is.

Er wordt voorgesteld om Certificering-informatie te verwijderen.

**Comment by RiX012** [comment]
Er zitten toch ook een aantal attributen op dit InformatieObject?

**Comment by wjtmollema** [comment]
Die zijn redundant. 

Als TypeDocument = Certificaat, dan geldt de volgende projectie:
certificaatdatum --> documentdatum
certificeringsinstantie --> subklasse van Rol
certificaatnummer --> documentnummer
aanwezigheid certificaat --> Waar = er is een Document zodanig dat geldt Object :: is beschreven door :: Document; Onwaar = er is geen Document zodanig dat geldt dat idem.

**Comment by RiX012** [comment]
Ok, met deze onderbouwing wat mij betreft prima

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
