### ISSUE TITLE
Redundantie: Groenobject :: invasieve soort is overbodig in het licht van Soortnaam groenobject :: invasieve soort.

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1304]
Er worden nu twee manieren van modelleren gefaciliteerd: invasieve soort bij Groenobject en bij Soortnaam groenobject. Het is de laatste die behouden moet worden. Daarmee is de eerste rudimentair.

De voorgestelde verwerking is om 'invasieve soort' te laten vervallen bij Groenobject.

**Comment by RiX012** [comment]
Inderdaad doorvoeren

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
