### ISSUE TITLE
Informatieobject Verkeerstelling: waar komt deze modellering vandaan en waar moet het heen?

### ISSUE THREAD

**Issue by wjtmollema** [Stichting-CROW/imbor#1307]
Het informatieobject `Verkeerstelling` heeft betrekking op dynamische gegevens en hoort dus niet thuis in IMBOR. Maar, wanneer dit verwijderd wordt, worden er dan bestaande processen die hier gebruik van maken bemoeilijkt? Zo ja, bij welke standaard voor dynamische gegevens hoort dit thuis of van welke standaard is dit al een onderdeel? Of wordt dit onderdeel van IMBOR niet gebruikt en kan het komen te vervallen?

Oorsprong: #971

**Comment by RiX012** [comment]
Wordt opgelost in #1325
