### ISSUE TITLE
De breedte van lengtemarkeringen

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#132]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
In het IMBOR zitten vier variabelen voor ‘midden kant- en deelstrepen’, zowel doorgetrokken als onderbroken (zie bijgevoegde tabel). Volgens het CROW zijn dit lengtemarkeringen. Wanneer gaat het om een ‘brede’ of ‘smalle’ kant/deelstreep

**Beschrijf de oplossing die je voor je ziet**
Er zijn 4 breedtes mogelijk (5,10,15,20cm). Deze gebruiken als type gedetailleerd i.p.v. smalle en brede strepen.

**Wat voor alternatieven heb je overwogen?**
Smal breed kan zo worden gelaten mits er definities van smal en breed worden gegeven. Dan zou breedte (in cm) als type extra gedetailleerd kunnen worden toegevoegd.

**Meer context**
![2-breedtelengtemarkeringen](https://user-images.githubusercontent.com/79521492/108851186-758b7880-75e4-11eb-9492-94dbc2623fac.jpg)

**Comment by wjtmollema** [comment]
Zie #1195 voor de verwerking van deze issue.
