### ISSUE TITLE
Norminstituut: aanpassing van de attributen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1321]
Na overleg met het Norminstituut
Groeiplaats als objecttype direct onder de klasse ReëelObject hangen.
De hierachische relatie met de klassen Constructie en Bouwwerk komen hiermee te vervallen.
Bij de klasse Groeiplaats de volgende attributen toevoegen:
-	Beheerafspraak
-	Aanleghoogte
-	Bouwjaar
-	Breedte
-	Lengte
-	Inhoud
-	Maaiveldhoogte
-	Oppervlakte
Verder vervalt bij Groeiplaats het attribuut verdichting.
Toevoegen bij Groeiplaats het attribuut belasting met enumeratie FysiekObjectBelasting.
Enumeraties ScheidingBelasting en VerhardingBelasting laten vervallen voor 1 generieke enumeratie FysiekObjectBelasting.

**Comment by JochemMollema** [comment]
Objecttype Groeiplaats in de Hiërarchie direct onder Reëel object geplaatst. Dit vanwege het bijzondere karakter van het objecttype Groeiplaats.

Aan Klasse Groeiplaats zijn de volgende attributen toegevoegd.

Aanleghoogte
Bouwjaar
Breedte
Lengte
Inhoud
Maaiveldhoogte
Oppervlakte

**Comment by JochemMollema** [comment]
Attribuut verdichting verwijderd bij Klasse Groeiplaats

**Comment by JochemMollema** [comment]
Toevoegen bij Groeiplaats het attribuut belasting met enumeratie FysiekObjectBelasting.
Enumeraties ScheidingBelasting en VerhardingBelasting laten vervallen voor 1 generieke enumeratie FysiekObjectBelasting. opgelost en beschreven in issue 1324

**Comment by RiX012** [comment]
> Klassen Constructie en Bouwwerk komen hiermee te vervallen.

Deze komen niet te
