### ISSUE TITLE
Norminstituut: attribuut Stedelijkheid (buurt) wel in IMBOR

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1322]
Attribuut stedelijkheid (buurt) toch binnen de vaste gegevens van IMBOR opnemen en niet bij de variabele gegevens van het Handboek Bomen.

**Comment by RiX012** [comment]
Ik denk `Geo-object`, omdat ruimten ook beheerafspraken moeten kennen

**Comment by JochemMollema** [comment]
Attribuut stedelijkheid buurt toegevoegd.

Definitie: Stedelijkheid (van een gebied). Een maatstaf voor de concentratie van menselijke activiteiten gebaseerd op de gemiddelde omgevingsadressendichtheid (oad).

Enumeratietype BoomStedelijkheidBuurt toegevoegd met waardenlijst.

Niet bepaald 
Niet (volledig) te beoordelen
Niet stedelijk (1,0)
Weinig stedelijk (1,1)
Matig stedelijk (1,2)
Sterk stedelijk (1,3)
Zeer sterk stedelijk (1,4)
