### ISSUE TITLE
Attribuut beheerafspraak verhuizen naar klasse ReëelObject

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1323]
Attribuut beheerafspraak verhuizen naar ReëelObject en klasse BeheerdObject laten vervallen.

**Comment by RiX012** [comment]
Ik denk `FunctioneleRuimte`, omdat ruimten ook beheerafspraken moeten kennen

**Comment by JochemMollema** [comment]
Voorstel om voor nu het attribuut beheerafspraak alleen toe te kennen aan de Klasse ReëelObject. 

Aanpassing attribuut beheerafspraak verhuist naar klasse ReëelObject. 

Klasse BeheerdObject verwijderd.

**Comment by RiX012** [comment]
Ik zou willen voorstellen om hem op Geo-object te hangen. Dan kunnen ook de ruimten beheerafspraken kunnen. Dit zie ik bij een aantal wel nodig zijn.
