### ISSUE TITLE
Verkeerskundige informatie krijgt eigen informatiemodellen, niet in IMBOR opnemen maar wel afstemmen waar nodig

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#1325]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
In IMBOR zit ook IMWV, wat wegen beschrijft vanuit een verkeerskundig perspectief. Het ministerie van IenW heeft CROW gevraagd om te werken aan een informatiemodel Verkeerstekens, dat ook de verkeerskundige maatregelen meeneemt; bij het NWB wordt het wegennetwerk gepubliceerd, het (niet-semantische) informatiemodel daarvan beschrijft ook de wegen vanuit verkeerskundig perspectief. Verkeerskunde is een ander vakgebied dan beheer en zou daarom eigen modellen moeten hebben.

**Beschrijf de oplossing die je voor je ziet**
1. Het IMWV model zou uit IMBOR gehaald moeten worden
2. Bij de verkeersborden (let op, in IMBOR zitten veel meer borden) geldt dat in IMBOR zou moeten staan dát er een verkeerskundig bord is, als beheerobject, maar niet welke verkeerskundige inhoud op het bord staat, dat regelt het informatiemodel verkeerstekens. Nu worden nog allerlei bordcodes en dergelijke in IMBOR opgenomen, dit is onderzocht in [deze issues](https://github.com/Stichting-CROW/verkeersborden/issues?q=is%3Aopen+is%3Aissue+label%3A%22relatie+imbor%22) bij het informatiemodel
NB wel opletten, er komen alleen nog maar verkeersborden in het model, niet bewegwijzering en straatnaamborden. Die zitten nu soms gemengd in IMBOR.
NB George, het dataportaal voor landelijke verkeersbordeninformatie, is nu nog niet ingericht naar het informatiemodel, daar zijn soms twee beheerobjecten (een bord en onderbord) als één bord in het model opgenomen; het informatiemodel verkeerstekens wil juist erg goed op de areaalgegevens conform IMBOR aansluiten en werkt met fysieke borden. Dus dat zou goed moeten kunnen aansluiten op IMBOR

**Wat voor alternatieven heb je overwogen?*
Een beknopte en heldere beschrijving van alternatieve oplossingen die je hebt overwegen.

**Meer context**
Voeg andere context of bijvoorbeeld schermfoto's toe. Denk eraan, deze melding is openbaar.

**Comment by RiX012** [comment]
Relatie met #1089 #1107 #1210

**Comment by RiX012** [comment]
IMWV is een op zichzelf staande ontwikkeling. Deze wordt in de markt echter nauwelijks tot niet gebruikt. Vanwege praktisch (beheer) oogpunt is deze toentertijd samengevoegd in de 'Productcatalogus Openbare Ruimte'. Alle informatiebehoeften (zowel m.b.t. vaste gegevens en dynamische gegevens) is uiteindelijk in IMBOR versies terecht gekomen. 

Het lijkt inderdaad wijs om:
1. Te identificeren wat er nu in IMBOR zit m.b.t. IMWV
2. Dit als apart model te 'bewaren' buiten IMBOR
3. IMWV dynamische gegevens te laten vervallen in IMBOR
4. Relatie tussen Informatiemodel Verkeerstekens en IMBOR vast te stellen.

_Instructie IMWV uit 2018:_
[IMWV-catalogus - Gebruiksinstructie v.2018 - Toelichting status-Instructie.pdf](https://github.com/user-attachments/files/17292850/IMWV-catalogus.-.Gebruiksinstructie.v.2018.-.Toelichting.status-Instructie.pdf)

**Comment by JochemMollema** [comment]
De informatieobjecten Resultaat verkeerstelling, Verkeersintensiteit-informatie en Verkeerstelling zijn verwijderd. Het betreft hier dynamische gegevens.

**Comment by JochemMollema** [comment]
Thx,

Groet,

Jochem

Van: Rik ***@***.***>
Verzonden: donderdag 31 oktober 2024 17:03
Aan: Stichting-CROW/imbor ***@***.***>
CC: Jochem Mollema ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Stichting-CROW/imbor] Verkeerskundige informatie krijgt eigen informatiemodellen, niet in IMBOR opnemen maar wel afstemmen waar nodig (Issue #1325)


@JochemMollema<https://github.com/JochemMollema> het attribuut verkeersintensiteit en de daarbij behorende eenheid Personenauto-equivalenten vallen ook onder dynamische gegevens uit IMWV.

Dus ook uit IMBOR en in het IMWV handvat

**Comment by RiX012** [comment]
#1357 documenteerd deze
