### ISSUE TITLE
Rol lozingsvergunninghouder is nog als attribuut aanwezig en moet rol worden.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1328]
Rol lozingsvergunninghouder is nog als attribuut aanwezig bij objecttype RioleringNode en moet rol worden.

**Comment by JochemMollema** [comment]
Attribuut lozingsvergunningshouder verwijderd en lozingsvergunningshouder als subklasse van Rol toegevoegd.

**Comment by RiX012** [comment]
Relatie met #1192 #1258
