### ISSUE TITLE
Taludmarkeringen (plateau- en drempelmarkering)

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#133]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
In het IMBOR kunnen taludmarkeringen momenteel alleen op ‘Type’ niveau worden ingedeeld onder Symbool-, tekst- en vlakmarkering

**Beschrijf de oplossing die je voor je ziet**
Het toevoegen van ‘Taludmarkering’ onder type gedetailleerd. 

**Wat voor alternatieven heb je overwogen?**
nvt

**Meer context**
![3-taludmarkering](https://user-images.githubusercontent.com/79521492/108851665-fa769200-75e4-11eb-986e-92b8b68a0b22.jpg)
Voorbeeld van taludmarkering

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gealloceerd naar https://github.com/Stichting-CROW/imbor/issues/1095. Derhalve wordt deze issue gesloten.
