### ISSUE TITLE
1 enumeratie voor type bevestiging FysiekObjectTypeBevestiging. 

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1333]
1 enumeratie voor type bevestiging FysiekObjectTypeBevestiging.

SensorTypeBevestiging, ApparaatTypeBevestiging, InstallatieTypeBevestiging en BordTypeBevestiging kunnen vervallen.

**Comment by JochemMollema** [comment]
Enumeratietype  SensorTypeBevestiging is vervallen
Enumeratietype  ApparaatTypeBevestiging is vervallen
Enumeratietype  InstallatieTypeBevestiging is vervallen
Enumeratietype  BordTypeBevestiging is vervallen

Enumeratietype FysiekObjectTypeBevestiging is toegevoegd.

**Comment by RiX012** [comment]
Relatie met #1093
