### ISSUE TITLE
Samenvoegen van de enumeratietypes WegasRijrichting en FietspadRijrichting

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1334]
Samenvoegen van de enumeratietypes WegasRijrichting en FietspadRijrichting en nieuw enumeratietype FysiekObjectRijrichting en idem voor de enumeraties voor de verkeersrichting.

**Comment by JochemMollema** [comment]
Enumeratietypes WegasRijrichting en FietspadRijrichting laten vervallen.
Enumeratietype FysiekObjectRijrichting toegevoegd.

Enumeratietypes WegasVerkeersrichting en FietspadVerkeersrichting laten vervallen.
Enumeratietype FysiekObjectVerkeersrichting toegevoegd.

**Comment by RiX012** [comment]
Relatie met #1093
