### ISSUE TITLE
Aquaduct

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#1336]
Bij het objecttype Aquaduct is slechts de doorvaartbreedte opgenomen, maar niet de doorvaartdiepte. Dit lijkt me een gewenste aanvulling

gr. Ernst

**Comment by JochemMollema** [comment]
Attribuut doorvaartdiepte toegevoegd aan de klasse Aquaduct in de tabel imborKern_K_KlassenAttributen.

@RiX012 deze issue kan gesloten worden.
