### ISSUE TITLE
Verkeerde definitie Voorwaarschuwingsdriehoek

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#134]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Volgens de CROW beschrijving van voorwaarschuwingsdriehoeken   zijn er drie varianten: klein, middel en groot. Waarbij de midden variant   zowel bibeko als bubeko kan liggen. Deze beschrijving sluit daarom niet   duidelijk aan bij de typering in het IMBOR, waar onderscheid wordt gemaakt   tussen fietspad, bibeko en bubeko op het niveau ‘Type extra gedetailleerd’   (zie onderstaande tabel).

**Beschrijf de oplossing die je voor je ziet**
Wijzig de naamgeving op het niveau ‘Type   extra gedetailleerd’ naar klein, middel en groot

**Wat voor alternatieven heb je overwogen?**
Aanvulling met exacte maatvoering

**Meer context**
![1-voorwaarschuwingsdriehoek](https://user-images.githubusercontent.com/79521492/108852054-6c4edb80-75e5-11eb-8ff2-aa05bc4d7a18.jpg)
![4-voorwaarschuwingsdriehoek](https://user-images.githubusercontent.com/79521492/108852069-6eb13580-75e5-11eb-8e54-a472e67bea0c.jpg)

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gealloceerd naar #1095. Derhalve wordt deze issue gesloten.
