### ISSUE TITLE
Mapping-tabellen uit IMBOR worden als handvatten naast de Access-database aangeboden.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1350]
Mapping-tabellen uit IMBOR worden als handvatten naast de Access-database aangeboden. ref-tabellen worden verwijderd.

**Comment by JochemMollema** [comment]
ref-tabellen met bijbehorende formulieren en queries verwijderd.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden, per handvat van IMBOR is een aparte issue aangemaakt.

**Comment by RiX012** [comment]
Wordt opgelost in aparte issues: #1357 #1358 #1359 #1360 #1361 #1362 ##1363
