### ISSUE TITLE
Knopen en assen verhuizen naar topologische elementen

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1352]
De huidige knopen en assen moeten, nu de topologische elementen goed gemodelleerd zijn volgens de NEN43610 (#997), verhuizen van ruimten naar topologische elementen. Dit is in lijn met `Hulplijn`. 

Verandering: 

`Spoorknoop` en `Wegknoop` subklasse van `Vertex`
`Spooras`, `Wegas` en `Waterloopas` subklasse van `Edge`

**Comment by JochemMollema** [comment]
Hulplijn als klasse verhuist van bovenliggende klasse Functionele zonering naar bovenliggende klasse Edge.

**Comment by JochemMollema** [comment]
Spoorknoop en Wegknoop verhuist naar bovenliggende klasse Vertex.

Spooras en Wegas verhuist naar bovenliggende klasse Edge.

**Comment by JochemMollema** [comment]
Meetpunt verhuist naar verschijningsvorm van RioleringNode.

Representatie fysiek object van klasse naar objecttype (Topologisch element).
Gebiedsoriëntatie verhuist naar verschijningsvorm van Representatie fysiek object
Hydraulisch rioleringsmodel verhuist naar verschijningsvorm van Representatie fysiek object
Rioolstreng verhuist naar verschijningsvorm van Representatie fysiek object
Uitlaat verhuist naar verschijningsvorm van Representatie fysiek object

**Comment by RiX012** [comment]
> Representatie fysiek object van klasse naar objecttype (Topologisch element).

@JochemMollema als je dit doet betekent het dat `Representatie fysiek object` niet meer abstract kan zijn. In de Voc_termen tabel moet dan `Representatie fysiek object` dus `concreet` worden. 

Misschien sowieso goed om hiervoor een check query in te bouwen. Deze query zou moeten kijken naar klassen die geen childs meer hebben. Deze zouden eigenlijk allemaal `concreet` moeten zijn en sommige gevallen dus ook van de collectie `Objecttype`

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
