### ISSUE TITLE
Geen definities voor wegmarkeringen in het IMBOR

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#136]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Met uitzondering van enkele pijlen   ontbreekt voor elke wegmarkering in het IMBOR een duidelijke definitie. Het   IMBOR is echter een uiterst geschikte plek om de definities van de diverse   wegmarkeringen vast te leggen

**Beschrijf de oplossing die je voor je ziet**
Toevoegen van de definities van de diverse   wegmarkeringen

**Wat voor alternatieven heb je overwogen?**
Eventueel een verwijzing/link naar de bijbehorende en verklarende CROW documentatie

**Meer context**
Suggestie voor definities van wegmarkeringen
[Markeringen_Definities_Sweco.xlsx](https://github.com/Stichting-CROW/imbor/files/6029510/Markeringen_Definities_Sweco.xlsx)

**Comment by JochemMollema** [comment]
In de huidige versie zijn de definities beschikbaar.
