### ISSUE TITLE
Toevoegen van functiebeschrijving/toepassing

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#138]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Via het CROW is het bijgevoegde overzicht te vinden met een beschrijving van de toepassing van enkele wegmarkeringen. Deze toepassingen komen overeen met de functie beschrijving van enkele IMBOR objecten. Wellicht kan bijgevoegde tabel worden gekoppeld aan de toepassingen in IMBOR.

**Beschrijf de oplossing die je voor je ziet**
Toevoegen van de variabele ‘Toepassing’   of ‘Functie’ om het gebruik van de wegmarkeringen extra te kunnen duiden.

**Wat voor alternatieven heb je overwogen?**
Op een andere manier de koppeling verbeteren tussen wegmarkering en functie in het IMBOR

**Meer context**
![8-overzicht_markeringen](https://user-images.githubusercontent.com/79521492/108859134-344b9680-75ed-11eb-9958-2f0648013b2e.jpg)

**Comment by wjtmollema** [comment]
Melding wordt gesloten omdat het project voor de hermodellering van `imbor:Wegmarkering` is afgerond.
