### ISSUE TITLE
Bij IMBOR Project meer verschijningsvormen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1386]
Bij IMBOR Project meer verschijningsvormen dan de bestaande 5 types.

Meer types zoeken en toevoegen zoals:
- Boomveiligheidscontrole
-

**Comment by RiX012** [comment]
Referentielijst van maken, inclusief een aantal voorbeelden

**Comment by JochemMollema** [comment]
Enumeratietype ProjectVerschijningsvorm kan niet gewijzigd worden in een referentie. Dit attribuut is een standaard attruibuut voor veel objecttypes.

Nieuwe domeinwaarden toegevoegd aan ProjectVerschijningsvorm:
- Boomtaxatie
- Boomveiligheidscontrole
- Groeiplaatsinspectie
- Inspectie boombeleid
- Inspectie boomonderhoud
- Inventarisatie boomgegevens

@RiX012 deze melding kan gesloten worden
