### ISSUE TITLE
Verkeersbord: C20-100 verwijderen uit markeringen

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#139]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
We vinden het vreemd dat een dergelijk verkeersbord bij markering is opgenomen. Alsmede uit de omschrijving kunnen we niet afleiden wat C20-100 betekent. (definitie zou mooi zijn!).

**Beschrijf de oplossing die je voor je ziet**
Verwijderen.

**Wat voor alternatieven heb je overwogen?**
nvt

**Meer context**
nvt

**Comment by wjtmollema** [comment]
`Verkeersbord: C20-100` heeft sinds de release van IMBOR 2022 de volgende definitie: "Wegmarkering die aangeeft dat de weg gesloten is voor voertuigen waarvan de aslast hoger is dan tien ton."
