### ISSUE TITLE
Kolom `BovenliggendAttribuut` kan komen te vervallen

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1390]
Doordat in `imborKern_Hierarchie` nu alle hierarchie bepaald (zie #1266) wordt kan deze kolom in Access komen te vervallen.

**Comment by JochemMollema** [comment]
Kolom BovenliggendAttribuut verwijderd uit tabel imborKern_Attributen 

@RiX012 deze melding kan gesloten worden.
