### ISSUE TITLE
Definities van Actor, Rol, speelt, heeftBetrekkingOp 

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#1391]
Voortvloeiend uit #1258 moeten nog deze definities worden toegevoegd:

- `Actor`: Een entiteit die in staat is om handelingen uit te voeren en een specifieke functie of positie te vervullen in een bepaalde context.
- `Rol`: Een samenhangende verzameling van verwachtingen, verantwoordelijkheden, bevoegdheden en gedragingen die een Actor kan aannemen in relatie tot iets.
- `speelt`: Een relatie die aangeeft dat een Actor een bepaalde Rol op zich neemt of uitvoert.
- `heeftBetrekkingOp`: Een relatie die aangeeft dat een Rol alleen geldt in de context van een iets specifieks.

**Comment by JochemMollema** [comment]
Definities Actor, Rol, speelt en heeft betrekking op toegevoegd.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
