### ISSUE TITLE
Jaar constitutie terug veranderen in jaar van aanleg of aanlegjaar

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#1397]
Jaar constitutie terug veranderen in jaar van aanleg of aanlegjaar

Bij het matchen van IMBOR en Handboek bomen, tussen IMBOR en GWSW en bij het bepalen van de minimale dataset wordt het attribuut jaar constitutie niet gezien als synoniem voor jaar van aanleg of aanlegjaar. Omdat jaar van aanleg een belangrijk attribuut is voor objecttypen wordt voorgesteld om de naamsverandering ongedaan te maken.

**Comment by JochemMollema** [comment]
Jaar van constitutie gewijzigd in aanlegjaar.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.

**Comment by RiX012** [comment]
Dit draait de beslissing uit #1106 deels terug.
