### ISSUE TITLE
Vraag: Wat is het verschil in het attribuut functie tussen de waarden ‘deelstreep/kantstreep’, ‘kantstreep’ en ‘deelstreep’?

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#140]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
We zijn erg benieuwd naar juiste registratie voor functie ‘definities’ betreffende de genoemde waarden.

**Beschrijf de oplossing die je voor je ziet**
Lijkt dat deelstreep/kantstreep dubbelop is t.o.v. kantstreep en deelstreep.

**Wat voor alternatieven heb je overwogen?**
nvt

**Meer context**
nvt

**Comment by wjtmollema** [comment]
Zie voor verwerking van deze issue #1197.
