### ISSUE TITLE
Hoe om te gaan met dubbel doorgetrokken (deel)strepen bij kruispunten als er meerdere stroken gescheiden worden?

### ISSUE THREAD

**Issue by SwecoWessel** [Stichting-CROW/imbor#141]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Ons voorstel zou zijn om dergelijke dubbele strepen, als éen element te zien en derhalve als één lijn te registeren met type gedetailleerd bijvoorbeeld 10-10-10 (lijndikte, leegruimte, lijndikte)

**Beschrijf de oplossing die je voor je ziet**
Andere alternatieven is om deze als twee strepen te registeren. Maar waar leg je dan de grens (want een verdrijvingsvlak is weer één polygoon).

**Wat voor alternatieven heb je overwogen?**
nvt

**Meer context**
![11-dubbelestreep](https://user-images.githubusercontent.com/79521492/108859819-e5523100-75ed-11eb-8cfb-7384c7f49e78.jpg)

**Comment by wjtmollema** [comment]
Melding wordt gesloten omdat het project voor de hermodellering van `imbor:Wegmarkering` is afgerond.
