### ISSUE TITLE
Registratie van een tweede beheerder en een tweede eigenaar

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#151]
Logboek-id | 2521 (in Datacatalogus)
--- | ---
Logboeknummer | 4 (v2021)
Ingediend | 19-Nov-2020

**Comment by JochemMollema** [comment]
Tweede   eigenaar en tweede beheerder geregistreerd bij Groenobject, Terreindeel,   Verhardingsobject en Waterobject.
--
