### ISSUE TITLE
Gebruiksfunctie Rietkraag (bij Beschoeiing) opnemen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#152]
Logboek-id | 2522 (in Datacatalogus)
--- | ---
Logboeknummer | 5 (v2021)
Ingediend | 19-Nov-2020

**Comment by RiX012** [comment]
Vanwege de consistentie zou ik persoonlijk voor optie 3 kiezen. Maar dat is vanuit een modeloogpunt

**Comment by wjtmollema** [comment]
Tot de presentatie van een nader tegenargument is Optie 3 verwerkt en wordt `Rietkraag` wordt toegevoegd aan `RietlandType`.
