### ISSUE TITLE
Bij Scheidingen ook Bereikbaarheid en Bereikbaarheid gedetailleerd opnemen (ook bij kunstwerken van toepassing)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#154]
Logboek-id | 2524 (in Datacatalogus)
--- | ---
Logboeknummer | 7 (v2021)
Ingediend | 19-Nov-2020

**Comment by JochemMollema** [comment]
Klasse   Bereikbaarheid toegevoegd aan: Beschoeiing, Damwand, Geluidsscherm, Hek,   Kademuur, Kwelscherm, Luchtscherm en Muur
--
