### ISSUE TITLE
Voor materialen mogelijk dat er ook meerdere materialen mogelijk zijn per object.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#155]
Logboek-id | 2525 (in Datacatalogus)
--- | ---
Logboeknummer | 8 (v2021)
Ingediend | 19-Nov-2020

**Comment by JochemMollema** [comment]
Waar van   toepassing kan bij de klassen van de voormalige objecttypegroepen meerdere   materialen geregistreerd worden.
--
