### ISSUE TITLE
Filters toevoegen van materialen per objecttype.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#156]
Materialenlijst mogelijk uit meerdere niveaus.

	Hoe actueel houden met de vele samenstellingen. Met name voor het gebruik van materiaal bij de funderingslagen. Ook de vele veranderingen die nu plaats vinden in het kader van duurzaamheid.

Logboek-id | 2526 (in Datacatalogus)
--- | ---
Logboeknummer | 9 (v2021)
Ingediend | 19-Nov-2020

**Comment by JochemMollema** [comment]
Per objecttype is aangegeven welke materialen van toepassing zijn.
