### ISSUE TITLE
De naam van het attribuut LengteVoegen is verwarrend.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#157]
Bedoeld wordt “de lengte van de voegen”. Je kan het ook lezen als “langsvoeg”

Ik stel voor het woordje “van” er tussen te zetten of als anders de woorden om te draaien zodat je krijgt : “voeglengte”

Anders ga ik opzoek naar de andere voegen zoals: dwars

Logboek-id | 2527 (in Datacatalogus)
--- | ---
Logboeknummer | 10 (v2021)
Ingediend | 19-Nov-2020

**Comment by JochemMollema** [comment]
Attribuutnaam aangepast   in Lengte van voegen
--
