### ISSUE TITLE
In de layout in het tabblad beheerobject is een ‘schuifje’ nodig om TypeEigenaarPlus te zien.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#161]
Logboek-id | 2531 (in Datacatalogus)
--- | ---
Logboeknummer | 14 (v2021)
Ingediend | 22-Oct-2020

**Comment by JochemMollema** [comment]
In IMBOR2021 is gekozen voor een andere weergave van de attributen. Dit attribuut is hiermee weer zichtbaar.
