### ISSUE TITLE
Uitstroomband als objecttype opnemen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#162]
De uitstroomband
Een alternatief voor een kolk in een bandenrij waarachter plek is om water te bergen: de uitstroomband: robuust, aan te brengen in nieuw- en bestaand gebied. Onderhoudsvriendelijk, begrijpbaar, zichtbaar waterbeheer.

Logboek-id | 2532 (in Datacatalogus)
--- | ---
Logboeknummer | 15 (v2021)
Ingediend | 15-Oct-2020

**Comment by JochemMollema** [comment]
Uitstroomband is als objecttype toegevoegd.
