### ISSUE TITLE
Bomen in IMBOR t.b.v. DSO

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#164]
Een gemeente kan nu een lijst laten vaststellen met monumentale bomen. In IMBOR kan nu een beleidstatus vastgelegd worden bij een boom (er wordt verwezen naar richtlijnen van NVTB). Voor het aanvragen van een kapvergunning is het belangrijk een link te ku

Logboek-id | 2534 (in Datacatalogus)
--- | ---
Logboeknummer | 17 (v2021)
Ingediend | 14-Aug-2020

***

**Antwoord:** er behoefte is/komt om bij monumentale bomen te kunnen verwijzen naar bijbehorende documenten (status, besluit, werkingsgebied).

**Comment by JochemMollema** [comment]
Kan via het informatieobject document opgelost worden.
