### ISSUE TITLE
Wat betreft het attribuut Type Extra Gedetailleerd zouden wij vanuit verhardingen graag de domeinwaarde Steenmastiekasfalt 8G+ toegevoegd zien.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#170]
Dit is een verhardingssoort die toegepast wordt als een vorm van een geluidsreducerende deklaag, maar het valt niet onder de term Dunne geluidsreducerende deklaag.
De specificatie 8G+ geeft aan dat het wel geluidsreducerende eigenschappen heeft (het is du

Logboek-id | 2540 (in Datacatalogus)
--- | ---
Logboeknummer | 23 (v2021)
Ingediend | 24-Nov-2020

***

**Antwoord:** Steenmastiekasfalt NL 8G+ wordt als type extra gedetailleerd van Dichte deklagen toegevoegd.

**Comment by wjtmollema** [comment]
Het is mogelijk niet nodig dit door te voeren. Het objecttype `Asfaltverharding` bevat namelijk al een attribuut `geluidsreducerend` (boolean) en kan in de semantische relatie `bestaatUit` komen te staan t.o.v. een nieuw materiaal `SMA 8G+` (gelijk het reeds bestaande `SMA 8A`).

De voorgestelde verwerking is dan ook om niets te wijzigen aan `AsfaltverhardingTypeExtraGedetailleerd` maar om een nieuw materiaal `SMA 8G+` toe te voegen aan de klasse `Materie`.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
