### ISSUE TITLE
Github #117 - In de markeringen IMBOR wordt de bajonetpijl 2 maal genoemd. #117

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#171]
Logboek-id | 2541 (in Datacatalogus)
--- | ---
Logboeknummer | 24 (v2021)
Ingediend | 25-Nov-2020

**Comment by redmer** [comment]
Duplicaat van #117

**Comment by wjtmollema** [comment]
#117 is gesloten, want de melding is per IMBOR 2022 achterhaald. Derhalve wordt deze issue ook gesloten.
