### ISSUE TITLE
Bij beheerobject is het attribuut relatievehoogteligging niet zichtbaar in het formulier

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#173]
Logboek-id | 2543 (in Datacatalogus)
--- | ---
Logboeknummer | 26 (v2021)
Ingediend | 25-Nov-2020

**Comment by JochemMollema** [comment]
In IMBOR2021 is gekozen voor een andere weergave van de attributen. Dit attribuut is hiermee weer zichtbaar.
