### ISSUE TITLE
Welke gebruiksfunctie krijgt een verhardingsobject welke als parkeerplaats gebruikt wordt bij het onderhoud van hoogspanningsmasten of windmolens maar die niet als algemene parkeerplaats gebruikt mag worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#177]
Logboek-id | 2547 (in Datacatalogus)
--- | ---
Logboeknummer | 30 (v2021)
Ingediend | 03-Dec-2020

**Comment by JochemMollema** [comment]
Dit kan ook via eigenaar, hekken en borden geregeld worden. Geen aparte gebruiksfunctie nodig.
