### ISSUE TITLE
De markering P voor Parkeervak ontbreekt

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#181]
Logboek-id | 2551 (in Datacatalogus)
--- | ---
Logboeknummer | 34 (v2021)
Ingediend | 30-Nov-2020

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gealloceerd naar https://github.com/Stichting-CROW/imbor/issues/1095. Derhalve wordt deze issue gesloten.
