### ISSUE TITLE
Wat is het verschil in het attribuut functie tussen de waarden ‘deelstreep/kantstreep’, ‘kantstreep’ en ‘deelstreep’?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#182]
Logboek-id | 2552 (in Datacatalogus)
--- | ---
Logboeknummer | 35 (v2021)
Ingediend | 30-Nov-2020

**Comment by wjtmollema** [comment]
Zie voor verwerking van deze issue #1197.
