### ISSUE TITLE
Hoe om te gaan met taludsymbool op verkeersdrempels?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#184]
Logboek-id | 2554 (in Datacatalogus)
--- | ---
Logboeknummer | 37 (v2021)
Ingediend | 30-Nov-2020

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gealloceerd naar https://github.com/Stichting-CROW/imbor/issues/1095. Derhalve wordt deze issue gesloten.
