### ISSUE TITLE
Toevoegen tekst 70 (N617, Schijndel voor rotonde)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#187]
Logboek-id | 2557 (in Datacatalogus)
--- | ---
Logboeknummer | 40 (v2021)
Ingediend | 30-Nov-2020

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gealloceerd naar https://github.com/Stichting-CROW/imbor/issues/1095. Derhalve wordt deze issue gesloten.
