### ISSUE TITLE
Voor pijlen en symbolen, wat is dan de functie? (Woord-, getal- en zonemarkering?)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#189]
Logboek-id | 2559 (in Datacatalogus)
--- | ---
Logboeknummer | 42 (v2021)
Ingediend | 30-Nov-2020

**Comment by wjtmollema** [comment]
Melding wordt gesloten omdat het project voor de hermodellering van `imbor:Wegmarkering` is afgerond.
