### ISSUE TITLE
Fietsstraat kan niet geregistreerd worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#191]
Omdat wij geen gebruik willen maken van de methode om een fietsstraat via de IMWV-attributen, hebben wij ervoor gekozen deze waarde toe te voegen aan het attribuut Type Rijstrook. Mocht je daar ook nog iets mee willen, dan zou dat fijn zijn.
Theoretisch m

Logboek-id | 2561 (in Datacatalogus)
--- | ---
Logboeknummer | 44 (v2021)
Ingediend | 26-Nov-2020

***

**Antwoord:** Fietsstraat wordt als gebruiksfunctie toegevoegd.

**Comment by JochemMollema** [comment]
Fietststraat als gebruiksfunctie van Verharding vastgelegd.
