### ISSUE TITLE
Bij Attribuutsoort staat nog  ‘Vrij invoerveld’ terwijl dit een vaste lijst moet zijn.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#192]
Logboek-id | 2562 (in Datacatalogus)
--- | ---
Logboeknummer | 45 (v2021)
Ingediend | 23-Nov-2020

**Comment by JochemMollema** [comment]
Gaat   over veegfrequentie bij verhardingsobject. Van vrij invoerveld veranderd in   een suggestielijst, net als alle andere frequentielijsten.
--
