### ISSUE TITLE
Bij Berm type wegberm en type spoorber, wegberm hernoemen in berm. Ook definitie aanpassen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#194]
Logboek-id | 2564 (in Datacatalogus)
--- | ---
Logboeknummer | 47 (v2021)
Ingediend | 22-Sep-2020

**Comment by JochemMollema** [comment]
Objecttype Wegberm omgezet naar Berm met types Wegberm en Spoorberm, definities aangepast.
