### ISSUE TITLE
Oplossing voor verschillende waarden in de klasses voor stamdiameter, hoogteklasse van CROW en Norminstituut

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#197]
Oplossen via specifieke attributen voor CROW en Norminstituut i.p.v.  Overlappen of tegenstrijdige domeinwaarden binnen 1 vaste lijst.

Logboek-id | 2567 (in Datacatalogus)
--- | ---
Logboeknummer | 50 (v2021)
Ingediend | 01-Dec-2020

**Comment by wjtmollema** [comment]
Deze issue is geabsolveerd door #1125 en #1135
