### ISSUE TITLE
Attributen voor het registreren van gemeentelijk vastgoed van Peel en Maas.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#198]
o	Id
o	Naam
o	Straat huisnr
o	Postcode
o	Woonplaats
o	BAG-pandid
o	categorie
o	functie
o	m2 bruto vloeropp
o	renovatiejaar
o	status gebruik
o	extra info gebruik
o	soort contract
o	docnr contract
o	MOP j/n
o	datum actualisatie MOP
o	docnr MOP
o	grootboeknr

Logboek-id | 2568 (in Datacatalogus)
--- | ---
Logboeknummer | 51 (v2021)
Ingediend | 01-Dec-2020

**Comment by JochemMollema** [comment]
Voor de registratie van een (gemeentelijk) gebouw is de consultatieversie van de samenhangende objectenregistratie als vertrekpunt genomen.

Reeds aanwezig in IMBOR 2022:

- Id
- Naam
- Straat
- huisnr
- Postcode
- Woonplaats
- BAG-pandid
- categorie --> type
- extra info gebruik --> via infomatieobject memo
- docnr contract --> via informatieobject document
- soort contract --> via informatieobject document
- 
Toegevoegd aan het objecttype Gebouw:
- jaar renovatie
- grootboeknummer
- bruto vloeroppervlak
- gebruikstatus met enumeratie

Aan de lijst met activiteiten zijn de volgende 'functies' toegevoegd>:
- Faciliteren van culturele activiteiten
- Faciliteren van onderwijs
- Faciliteren van religieuze activiteiten

Niet toegevoegd, dynamsche gegevens:
- MOP j/n
- datum actualisatie MOP
- docnr MOP
