### ISSUE TITLE
Een rotatiepaneel heeft 3 standen, elke afbeelding vast kunnen leggen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#199]
Logboek-id | 2569 (in Datacatalogus)
--- | ---
Logboeknummer | 52 (v2021)
Ingediend | 01-Sep-2020

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Complexere rotatiepanelen kunnen trouwens meer dan drie afbeeldingen bevatten. 
- Optie 1 **geen impact**: De huidige attributen en informatieobjecten uit IMBOR 2022 kunnen gebruikt worden voor het registreren van meerdere verkeersbordsymbolen bij een `Rotatiepaneel`. Namelijk: `symbool` (0-N-relatie waarmee drie verschillende symbolen aan het `Rotatiepaneel` gekoppeld kunnen worden; en `Informatieobject: Document` waarmee een of meerdere documenten van `type document :: Afbeelding` of `type document :: Foto` de verschillende afbeeldingen op het `Rotatiepaneel` kunnen vastleggen. 
- Optie 2 **lage impact**: Toevoegen van attribuut `modelnaam` aan `Verkeersbord` voor de registratie van een string met alle bordcodes voor de symbolen die het `Rotatiepaneel` bevat.
- Optie 3 **middelhoge impact**: Toevoegen van attribuut `bordcodes rotatiepaneel` met een 0-N-relatie aan `Verkeersbord` voor de registratie van alle bordcodes voor de symbolen die het `Rotatiepaneel` bevat, met als enumeratielijst `VerkeersbordTypeGedetailleerd` omdat op websites van fabrikanten de mogelijke combinaties van borden (gelijk mogelijke verkeerssituaties) niet gelimiteerd zijn.

**Comment by RiX012** [comment]
Ik weet niet aan wie we dit voor moeten leggen, maar mijn voorkeur heeft optie 1

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
