### ISSUE TITLE
Generieke oplossing voor braakliggend, nu bij Verhardingsobject en Groenobject wellicht beter als gebruiksfunctie.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#201]
Logboek-id | 2571 (in Datacatalogus)
--- | ---
Logboeknummer | 54 (v2021)
Ingediend | 01-Feb-2020

**Comment by WizzyTheDataWizard** [comment]
Graag meenemen in de wijzigingen na de consulatieronde van IMBOR 2022. Dit is vaak een probleem bij dataconversies naar IMBOR.

**Comment by RiX012** [comment]
Eens.
