### ISSUE TITLE
Molgoot als gebruiksfunctie en als bor-functie toevoegen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#202]
Logboek-id | 2572 (in Datacatalogus)
--- | ---
Logboeknummer | 55 (v2021)
Ingediend | 01-Dec-2020

**Comment by JochemMollema** [comment]
Domeinwaarde   molgoot toegevoegd aan de tabel met Termen, de waarde molgoot toegevoegd aan   de tabel met domeinwaarden bij het attribuut gebruiksfunctie, de waarde   molgoot toegevoegd aan de tabel met domeinwaarden per objecttype. Alleen   relevant voor het objecttype Verhardingsobject. bor-functie molgoot   toegevoegd voor uitwisseling met geovoorziening. Extra uitwisselregel voor   molgoot aangemaakt in de tabel RefMODEL_Mapping om een molgoot als functie   van Elementenverharding te kunnen registreren.
--
