### ISSUE TITLE
Instroomvoorzieining en uitstroomvoorziening als gebruiksfunctie en als bor-functie

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#203]
Logboek-id | 2573 (in Datacatalogus)
--- | ---
Logboeknummer | 56 (v2021)
Ingediend | 01-Dec-2020

**Comment by JochemMollema** [comment]
Instroomvoorziening   en uitstroomvoorziening als domeinwaarden toegevoegd aan de tabel met termen.   Instroomvoorziening en uitstroomvoorziening toegevoegd als domeinwaarden van   gebruiksfunctie en als waarden gekoppeld aan groenobject, terreindeel en   verhardingsobject. Voor de mapping naar de geovoorziening zijn de waarden   Instroomvoorziening en uitstroomvoorziening toegevoegd als bor-functie.   Uitwisselregels toegevoegd aan de tabel RefMODEL_Mapping.
--
