### ISSUE TITLE
Hoe om te gaan met een uitneembare wegdrempel? Graag hiervoor een attribuut toevoegen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#204]
Logboek-id | 2574 (in Datacatalogus)
--- | ---
Logboeknummer | 57 (v2021)
Ingediend | 01-Dec-2020

**Comment by JochemMollema** [comment]
Het attribuut verplaatsbaar is toegevoegd aan Verkeersdrempel
