### ISSUE TITLE
Toevoegen van de functies Speelondergrond en Sportondergrond om deze waarden uit te kunnen wisselen met de geovoorziening.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#205]
Logboek-id | 2575 (in Datacatalogus)
--- | ---
Logboeknummer | 58 (v2021)
Ingediend | 01-Dec-2020

**Comment by JochemMollema** [comment]
Speelondergrond   en sportondergrond toegevoegd als bor-functies en mapping gemaakt tussen   Verhardingsobject en OnbegroeidTerreindeel.
--
