### ISSUE TITLE
Fout in de mapping grasklinkers (1x naar open verharding en 1x naar half verhard)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#206]
Logboek-id | 2576 (in Datacatalogus)
--- | ---
Logboeknummer | 59 (v2021)
Ingediend | 10-Dec-2020

**Comment by JochemMollema** [comment]
Grasklinkers   is in IMGeo 2.2 gekoppeld aan half verhard en niet aan open verharding.   Aangepast in de tabel RefMODEL_Mapping.
--
