### ISSUE TITLE
Bij Verhardingsobjecten is de uitwisseling van betonverharding niet zichtbaar in het formulier van de mapping

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#207]
Logboek-id | 2577 (in Datacatalogus)
--- | ---
Logboeknummer | 60 (v2021)
Ingediend | 10-Dec-2020

**Comment by JochemMollema** [comment]
Grasklinkers   is in IMGeo 2.2 gekoppeld aan half verhard en niet aan open verharding.   Aangepast in de tabel RefMODEL_Mapping.
--
