### ISSUE TITLE
Toevoegen van vochtmeters die o.a. gebruikt worden om tijdig signalen te krijgen aangaande watergeven

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#210]
Logboek-id | 2580 (in Datacatalogus)
--- | ---
Logboeknummer | 63 (v2021)
Ingediend | 17-Dec-2020

**Comment by JochemMollema** [comment]
Sensor

**Comment by JochemMollema** [comment]
Vochtmeter is toegevoegd als nieuw objecttype binnen de Klasse Sensor.
