### ISSUE TITLE
Broekbos komt niet voor in de mapping IMBOR-IMGeo

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#211]
Logboek-id | 2581 (in Datacatalogus)
--- | ---
Logboeknummer | 64 (v2021)
Ingediend | 15-Dec-2020

**Comment by JochemMollema** [comment]
Broekbos   toegevoegd aan de mapping. In de mapping naar IMGeo de voorvoegsels Loofbos:   Groenvoorziening: etc verwijderd.
--
