### ISSUE TITLE
Nieuwe verschijningsvormen van verkeersborden. Zie lijst.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#215]
Logboek-id | 2585 (in Datacatalogus)
--- | ---
Logboeknummer | 68 (v2021)
Ingediend | 12-Jan-2021

**Comment by wjtmollema** [comment]
@RiX012 Deze issue heeft geen inhoud omdat de import geen lijst van voorgestelde verkeersborden heeft meegenomen in de tekst van de melding.
