### ISSUE TITLE
Wegdekreflector ontbreekt nog

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#217]
Kan op 2 manieren: als 'toevoeging' aan een punt, lijn en vlakmarkering. En/of als apart 'Type markering', dat als lijn of punt kan worden ingetekend. Even overleggen?
Onderverdeling: kunststof, glasbol, solar.  Kunststof kent ook weer verschillende typen

Logboek-id | 169 (in Datacatalogus)
--- | ---
Logboeknummer | 70 (v2021)
Ingediend | 25-May-2016
Afgehandeld | 25-Jun-2018

***

**Antwoord:** Uitgewerkt als actieve wegmarkering

**Comment by JochemMollema** [comment]
Wegdekreflector als objecttype binnen de klasse Weginrichtingsobjecten opgenomen.
