### ISSUE TITLE
Hoe om te gaan met archiefgegevens

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#219]
Deze gebruiken wij als Gelderland om zaken als oorspronkelijke wapening, staalkwaliteit, betonkwaliteit, etc… te kunnen benaderen. Weten we niet altijd.
Zou je eigenlijk als attributen willen opnemen. Wij linken zelf naar achterliggende bestanden, indien 

Logboek-id | 557 (in Datacatalogus)
--- | ---
Logboeknummer | 72 (v2021)
Ingediend | 16-May-2017

**Comment by JochemMollema** [comment]
IMBOR-team: niet in IMBOR. opbouw historie is onderdeel van het beheersysteem.
