### ISSUE TITLE
Groenstructuur: voorstel opname als gebruiksfunctie (nog geen IMBOR 1.2),  nu bij memoveld invullen en bij CROW melden. Dit om ruimte voor beleidsvertaling te creëren binnen IMBOR. Dit als verlengde van de groenbeheersystematiek.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#221]
Logboek-id | 1101 (in Datacatalogus)
--- | ---
Logboeknummer | 75 (v2021)
Ingediend | 15-Jan-2018

***

**Antwoord:** Nu generieke gebruiksfunctie: Onderdeel van groenstructuur. Verdere indeling wordt opgepakt in volgende versie

**Comment by wjtmollema** [comment]
Gesloten vanwege de toevoeging van `groenstructuur` aan IMBOR, zie issue #583 . Voor de ontwikkeling van de uitwerking van `groenstructuur`, zie #979 .
