### ISSUE TITLE
Controle verschijningsvormen markeringen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#222]
Logboek-id | 1130 (in Datacatalogus)
--- | ---
Logboeknummer | 76 (v2021)
Ingediend | 02-Feb-2018

**Comment by wjtmollema** [comment]
@RiX012 Ik vermoed dat deze melding slaat op het tweemaal voorkomen van `Bajonetpijl` in IMBOR 2020. Dat maakt de melding redundant. Zie #117 en #171. Deze melding is namelijk twee jaar eerder ingediend dan #117 en #171.
