### ISSUE TITLE
Hoogte komt bij alle objecttypes binnen de groep voor. Attribuut kan een niveau hoger.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#223]
Logboek-id | 1132 (in Datacatalogus)
--- | ---
Logboeknummer | 77 (v2021)
Ingediend | 13-Feb-2018

***

**Antwoord:** Kan in versie 2018 niet aangepast worden, i.v.m. bevriezen van de attributen. Modelmatig is het wel correct om de hoogte te verplaatsen naar de objecttypegroep.

**Comment by JochemMollema** [comment]
Is meegenomen in de herstructurering.
