### ISSUE TITLE
Hoe om te gaan met andere werkzaamheden als maaien, zoals hooien en klepelen?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#224]
Logboek-id | 1138 (in Datacatalogus)
--- | ---
Logboeknummer | 78 (v2021)
Ingediend | 14-Mar-2018

**Comment by JochemMollema** [comment]
Het gaat hier om maatregelen. Deze behoren niet tot de scope van IMBOR en moeten conform een methodiek binnen het beheersysteem geregistreerd worden.
