### ISSUE TITLE
Hoe om te gaan met groene of blauwe daken?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#227]
Logboek-id | 1155 (in Datacatalogus)
--- | ---
Logboeknummer | 81 (v2021)
Ingediend | 24-Apr-2018

***

**Antwoord:** Wordt opgepakt in volgende versie via een aparte werkgroep.

**Comment by JochemMollema** [comment]
vegetatiedaken kunnen als objecttype geregistreerd worden.
