### ISSUE TITLE
Voor vormbomen, leibomen en gekandelaberde bomen is een knipfrequentie wenselijk

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#228]
Logboek-id | 1158 (in Datacatalogus)
--- | ---
Logboeknummer | 82 (v2021)
Ingediend | 01-May-2018

**Comment by JochemMollema** [comment]
Is   aangepast en kan vastgelegd worden via het attribuut Onderhoudsfrequentie
--
