### ISSUE TITLE
Wegvak: is dit eigenlijk ook niet een beheervak?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#229]
Logboek-id | 1168 (in Datacatalogus)
--- | ---
Logboeknummer | 83 (v2021)
Ingediend | 03-May-2018

**Comment by JochemMollema** [comment]
Wordt voorgelegd aan de werkgroep

**Comment by JochemMollema** [comment]
In IMBOR 2022 als zelfstandig objecttype. Geen reacties uit de consultatie.
