### ISSUE TITLE
Nieuw objecttype meetpunt? Met types bouten in de weg, zwart/wit stippen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#230]
Logboek-id | 1169 (in Datacatalogus)
--- | ---
Logboeknummer | 84 (v2021)
Ingediend | 03-May-2018
Afgehandeld | 25-Jun-2018

***

**Antwoord:** Objecttype buiten de scope van IMBOR.

**Comment by JochemMollema** [comment]
Meetpunt als objecttype binnen de klasse Weginrichtingsobjecten toegevoegd.
