### ISSUE TITLE
Krijgt historie (en toekomst) nu ook een plek, oftewel hebben alle datavelden een datum tag van ingang, zodat je informatie over een willekeurig datum kunt opvragen (historisch)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#232]
Logboek-id | 1174 (in Datacatalogus)
--- | ---
Logboeknummer | 86 (v2021)
Ingediend | 08-May-2018

***

**Antwoord:** Dit is vooral een aangelegenheid van het beheersysteem. Historie bijhouden op attribuutniveau is zeker wenselijk. IMBOR en IMWV kunnen hiervoor een voorstel doen.

**Comment by JochemMollema** [comment]
IMBOR-team: het vastleggen van de historie van objecten en onderdelen is functionaliteit van het beheersysteem.
