### ISSUE TITLE
Afstromend vermogen of vergelijkbaar toevoegen aan objecten of gebieden

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#235]
Logboek-id | 1230 (in Datacatalogus)
--- | ---
Logboeknummer | 89 (v2021)
Ingediend | 25-May-2018
Afgehandeld | 03-Dec-2018

***

**Antwoord:** Is onderdeel van het hydraulisch model van GWSW -->  geen onderdeel van IMBOR.

**Comment by JochemMollema** [comment]
Alle attributen van GWSW-basis worden binnen IMBOR geregistreerd, ook de attributen die met afstroming en berging te maken hebben.
