### ISSUE TITLE
Bij imbor zou het fijn zijn als we maaien en klepelen kunnen gebruiken en het afvoeren dan wel afzuigen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#243]
Logboek-id | 1335 (in Datacatalogus)
--- | ---
Logboeknummer | 97 (v2021)
Ingediend | 26-Jun-2018

**Comment by JochemMollema** [comment]
Binnen IMBOR 2022 zijn maatregelen niet meer als attribuut beschikbaar. Dit moet buiten het IMBOR-model geregistreerd worden.
