### ISSUE TITLE
Bij een rooster de relatie leggen met het onderliggende object, bijvoorbeeld een opvangput.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#244]
Logboek-id | 1337 (in Datacatalogus)
--- | ---
Logboeknummer | 98 (v2021)
Ingediend | 27-Jun-2018

***

**Antwoord:** Rioned: akkoord, is conform CROW.

**Comment by JochemMollema** [comment]
Binnen IMBOR 2021 kunnen semantische relaties tussen objecten vastgelegd worden.
