### ISSUE TITLE
Graag beheervak hernoemen in beheergebied, dit dekt beter de lading.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#245]
Logboek-id | 1340 (in Datacatalogus)
--- | ---
Logboeknummer | 99 (v2021)
Ingediend | 15-Jun-2018

**Comment by JochemMollema** [comment]
Wordt besproken binnen de werkgroepen.

**Comment by JochemMollema** [comment]
Aangepast

**Comment by JochemMollema** [comment]
Na overleg blijft het beheervak.
