### ISSUE TITLE
Koppeling bomen en wegtype

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#246]
Bij de koppeling van bomen aan wegtype zou het mooi zijn als er een handreiking gedaan wordt op welke wijze deze wegtype indeling vastgelegd kan worden bij het objecttype. Dit zou bijvoorbeeld vastgelegd kunnen worden in het beheergebied attribuut van de

Logboek-id | 1341 (in Datacatalogus)
--- | ---
Logboeknummer | 100 (v2021)
Ingediend | 25-Jun-2018

**Comment by JochemMollema** [comment]
Binnen IMBOR 2021 kunnen semantische relaties tussen objecten vastgelegd worden.
