### ISSUE TITLE
Biodiversiteit als waarde aan de referentietabel met boomsoorten toevoegen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#247]
Logboek-id | 1342 (in Datacatalogus)
--- | ---
Logboeknummer | 101 (v2021)
Ingediend | 28-Jun-2018

**Comment by wjtmollema** [comment]
**Constatering**
Het toevoegen van `Biodiversiteit` aan `VegetatieobjectSoortnaam` conflicteert met de huidige werkwijze, namelijk het verwijzen naar `Organisatiespecifieke domeinwaarden` (voor een overweging van de validiteit van die oplossing, zie https://github.com/Stichting-CROW/imbor/issues/1056#issuecomment-1348729319). In de toelichting bij de definitie van `soortnaam` wordt verwezen naar http://www.internationalplantnames.com. 

**Voorgestelde verwerking**
Niet verwerken zoals aangedragen, omdat `Biodiversiteit` geen internationale plantensoortnaam is.
