### ISSUE TITLE
Graag gehele sportvloerenlijst (incl. padel) verwerken binnen IMBOR.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#251]
Voorstel: toevoegen

Logboek-id | 1381 (in Datacatalogus)
--- | ---
Logboeknummer | 105 (v2021)
Ingediend | 01-Sep-2018

**Comment by JochemMollema** [comment]
Sporten en materialen sportvloeren verwerkt in IMBOR 2022.
