### ISSUE TITLE
Bij goten aan kunnen geven welke afdekking er bij hoort

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#252]
Rioned: dit is conform GWSW, kan verwerkt worden.

Logboek-id | 1403 (in Datacatalogus)
--- | ---
Logboeknummer | 106 (v2021)
Ingediend | 24-Sep-2018

**Comment by JochemMollema** [comment]
Via semantische relaties kan bij goten de afdekking (lees afzonderlijke objecttypen) geregistreerd worden.
