### ISSUE TITLE
Bij putdeksel niet alle GWSW-attributen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#253]
Logboek-id | 1404 (in Datacatalogus)
--- | ---
Logboeknummer | 107 (v2021)
Ingediend | 24-Sep-2018

***

**Antwoord:** Rioned: kunnen conform GWSW toegevoegd worden.

**Comment by JochemMollema** [comment]
In IMBOR 2021 zijn alle GWSW-attibuten van het objecttype Deksel opgenomen.
