### ISSUE TITLE
Graag aandacht voor naamgeving attributen en het door elkaar gebruiken van Attribuut Beheerder en Attribuut Publicatie

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#254]
Richting de toekomst zou het een hele fijne verbetering zijn als er één schrijfwijze komt per attribuut...

Logboek-id | 1416 (in Datacatalogus)
--- | ---
Logboeknummer | 108 (v2021)
Ingediend | 12-Oct-2018

**Comment by JochemMollema** [comment]
Voor objecttypes, attributen en domeinwaarden is 1 schrijfwijze nog beschikbaar. Het gaat hier om de schrijfwijzen die het best leesbaar zijn. Het gaat hier om de waarden die de gebruiker leest, ziet of uitwisselt.
