### ISSUE TITLE
Afbeelding wel/niet een attribuut van een beheerobject, wordt wel getoond in de kennismodule, niet in IMBOR.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#255]
Logboek-id | 1435 (in Datacatalogus)
--- | ---
Logboeknummer | 109 (v2021)
Ingediend | 23-Oct-2018

**Comment by JochemMollema** [comment]
Afbeelding en andere attributen voor het vastleggen van documenten/bestanden in het model worden in IMBOR 2021 met het informatieobject Document vastgelegd. Attributen Afbeelding, Foto en QR code vervallen hiermee.
