### ISSUE TITLE
Hoe om te gaan met inritbanden. Nu als vlak vanuit BGT aangeleverd.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#256]
Wordt nu als volgt verwerkt:
•	type: ‘elementverharding’
•	type gedetailleerd: ‘betonelement’
•	type extra gedetailleerd ‘<<geen waarde>>
•	Wegfunctie: ‘verkeersdrempel’
•	BGT fysiek voorkomen: ‘Open verharding’(komt vanuit BGT)
•	BGT fysiek voorkomen plu

Logboek-id | 1440 (in Datacatalogus)
--- | ---
Logboeknummer | 110 (v2021)
Ingediend | 01-Nov-2018

**Comment by wjtmollema** [comment]
**Constatering**
Sinds IMBOR 2022 is met de introductie van `Elementenverharding :: type gedetailleerd :: Inritblok` deze issue achterhaald.
