### ISSUE TITLE
Bij Materiaal filter uitwerken voor materialen die alleen bij een verhardingsobject voor kunnen komen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#258]
CROW

Logboek-id | 1503 (in Datacatalogus)
--- | ---
Logboeknummer | 112 (v2021)
Ingediend | 16-Nov-2018

**Comment by JochemMollema** [comment]
In IMBOR 2021 is voor elk objecttype uitgewerkt welke materialen er van toepassing zijn. Dit is een aparte tabel vastgelegd en in de database in het formulier van het objecttype raadpleegbaar.
