### ISSUE TITLE
In de suggestielijst met soortnamen ook standaard de waarde onbekend opnemen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#259]
Logboek-id | 1505 (in Datacatalogus)
--- | ---
Logboeknummer | 113 (v2021)
Ingediend | 21-Nov-2018

**Comment by JochemMollema** [comment]
Kan binnen het beheersysteem gedaan worden. Binnen IMBOR is er geen  lijst met soortnamen.
