### ISSUE TITLE
De onderverdeling voor Bos laten beginnen met Type Bos en daarna te kiezen voor Loofbos, Naaldbos en Gemengd bos

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#260]
Logboek-id | 1506 (in Datacatalogus)
--- | ---
Logboeknummer | 114 (v2021)
Ingediend | 21-Nov-2018

**Comment by JochemMollema** [comment]
Nieuwe indeling Bos in versie 2022 (conform SOR)
