### ISSUE TITLE
Filter voor materiaal toepassen bij meubilair, niet alle materialen zijn relevant

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#261]
CROW

Logboek-id | 1525 (in Datacatalogus)
--- | ---
Logboeknummer | 115 (v2021)
Ingediend | 23-Nov-2018

**Comment by JochemMollema** [comment]
Domeinwaarden van materiaal zijn gefilterd aanwezig bij elk objecttype met het attribuut materiaal.
