### ISSUE TITLE
Hoogte als generiek attribuut van alle vegetatieobjecten modelleren.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#262]
Logboek-id | 1532 (in Datacatalogus)
--- | ---
Logboeknummer | 116 (v2021)
Ingediend | 28-Nov-2018

**Comment by JochemMollema** [comment]
Hoogte is als attribuut toegevoegd aan klimplant, gevelgroen, vegetatiedak en solitaire plant.
