### ISSUE TITLE
Uitzoeken opname Warmte en koude opslag binnen IMBOR

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#263]
CROW

Logboek-id | 1572 (in Datacatalogus)
--- | ---
Logboeknummer | 117 (v2021)
Ingediend | 07-Dec-2018

**Comment by wjtmollema** [comment]
De opname van Warmte- en koudeopslag in IMBOR is onderzocht in het kader van het onderzoeken van  de intersectie tussen IMBOR en de energietransitie. Het uitbreidingsvoorstel voor het energiethema 'bodemwarmte' is bijgevoegd aan deze opmerking. 

Aansluitend moet gekeken worden naar hoe Warmte- en koudeopslag is ondergebracht in de symbologie van de Nederlandse CAD Standaard (NLCS).  De benamingen van relevante NLCS-omschrijvingen zijn: 

- `WTB_WARMTENET_BRONPUT`
- `WTB_WARMTENET_PUT`
- `WARMTEOPSLAG`

In de terminologie van de bodemwarmtesector wordt de bovenstaande 'bronput' ook wel een 'productieput' genoemd.

**Voorstel opname objecttypen, attributen en domeinwaarden voor energiethema 'bodemwarmte'**
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Packages/oice_16_974fa576_32c1d314_127/AC/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/Thomas/AppData/Local/Packages/oice_16_974fa576_32c1d314_127/AC/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/Thomas/AppData/Local/Packages/oice_16_974fa576_32c1d314_127/AC/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NL style='tab-interval:35.4pt;word-wrap:break-word'>




Objecttype | Attribuut/domeinwaarde | Toelichting
-- | -- | --
Injectieput | N.v.t. | In de grond geboorde put die onderdeel uitmaakt van de   installatie die grondwarmte opneemt. Het afgekoelde water gaat via de   injectieput weer terug in de grond, in dezelfde diepe aardlaag.
Productieput | N.v.t. | In de grond geboorde put die onderdeel uitmaakt van de   installatie die grondwarmte opneemt. Vanuit de productieput wordt het warme   water omhoog gepompt. Een warmtewisselaar haalt de warmte er daar uit zodat   die kan worden gebruikt.
Utiliteitsnet | type: Warmtenet | Het bestaande IMBOR-objecttype Utiliteitsnet kan uitgebreid   worden om ook te voorzien in de registratie van netwerken ten behoeve van   warmtetransport.
Warmte- en koudeopslag | N.v.t. | Slaat energie uit het gebouw en/of de omgeving op in de bodem - een aquifer (een waterhoudende zand- en/of kiezellaag). Een aquifer is van nature aanwezig in de bodem. (Een blinde vlek van IMBOR, zoals geconstateerd bij de gemeente  Utrecht, is het vermogen om Warmte- en koudeopslag als assets te kunnen   registreren. De Thermische pijpleiding zit in IMBOR, maar niet de installatie   zelf).
Warmtebron | N.v.t. | Om in de modellering van warmtenetten te voorzien is naast de al   in IMBOR aanwezige Warmtepomp ook de Warmtebron zelf benodigd. De locatie van   de warmtebron is een belangrijk aspect, evenals de diepte en aan welke   Warmtepomp, Injectieput of Productieput hij verbonden is.
Warmtebron | type geothermie: Dieptegeothermie | Er is sprake van ‘diepte geothermie’ wanneer er tot 2500 meter   diep geboord wordt. Als binnen dezelfde installatie zowel bodemwarmte als   grondwaterwarmte worden gebruikt, zouden meerdere waarden van toepassing   kunnen zijn (ondiepe geothermie + hydrothermie; diepte geothermie +   hydrothermie). Het voorstel is dus om hier een 1-N-attribuut van te maken, of   om de bovenstaande twee combinaties als optionele domeinwaarden te hanteren.
Warmtebron | type geothermie: Hydrothermie | Hydrothermie is het geval wanneer grond- of oppervlaktewater   wordt gebruikt als warmtebron. Als binnen dezelfde installatie zowel   bodemwarmte als grondwaterwarmte worden gebruikt, zouden meerdere waarden van   toepassing kunnen zijn (ondiepe geothermie + hydrothermie; diepte geothermie   + hydrothermie). Het voorstel is dus om hier een 1-N-attribuut van te maken,   of om de bovenstaande twee combinaties als optionele domeinwaarden te   hanteren.
Warmtebron | type geothermie: Ondiepe geothermie | Men spreekt van ‘ondiepe geothermie’ wanneer er tot 300 meter   diep geboord wordt. Als binnen dezelfde installatie zowel bodemwarmte als   grondwaterwarmte worden gebruikt, zouden meerdere waarden van toepassing   kunnen zijn (ondiepe geothermie + hydrothermie; diepte geothermie +   hydrothermie). Het voorstel is dus om hier een 1-N-attribuut van te maken, of   om de bovenstaande twee combinaties als optionele domeinwaarden te hanteren.
Warmtebron | type: Bodemcollector: type gedetailleerd: Verticale bodemcollector | Bij een gesloten verticale bodemcollector wordt er een put   geboord van gemiddeld 40-160 meter diep. De buizeninstallatie die warmte   extraheert uit de ondergrond is verticaal in de ondergrond aangebracht. Het   aantal putten dat geboord moet worden is afhankelijk van het vermogen van de   warmtepomp en de bodemsamenstelling.    De reden tot opname van deze typering is het kunnen registreren   van verschillende soorten Warmtebronnen, aangezien de installaties   verschillen en derhalve ander beheer nodig hebben.
Warmtebron | type: Bodemcollector | Een bodemcollector is een buizeninstallatie die warmte uit de   ondergrond op kan nemen uit de ondergrond.   De reden tot opname van deze typering is het kunnen registreren   van verschillende soorten Warmtebronnen, aangezien de installaties   verschillen en derhalve ander beheer nodig hebben.
Warmtebron | type: Bodemcollector: type gedetailleerd: Horizontale   bodemcollector | Bij een gesloten bodemcollector wordt een systeem van buizen   aangelegd onder de tuin op circa 80-100cm onder de plaatselijke vorstlijn. De   buizeninstallatie die warmte extraheert uit de ondergrond is horizontaal in   de ondergrond aangebracht en beslaat daarmee een grotere oppervlakte dan de   verticale variant en ligt tevens substantieel ondieper.    De reden tot opname van deze typering is het kunnen registreren   van verschillende soorten Warmtebronnen, aangezien de installaties   verschillen en derhalve ander beheer nodig hebben.
Warmtebron | Type: Open bron | Bij een open bron worden er twee bronnen geboord die in dezelfde   grondlagen uitkomen.    De reden tot opname van deze typering is het kunnen registreren   van verschillende soorten Warmtepompen, aangezien de installaties verschillen   en derhalve ander beheer nodig hebben.
Warmtepomp | type geothermie: Dieptegeothermie | Er is sprake van ‘diepte geothermie’ wanneer er tot 2500 meter   diep geboord wordt. Als binnen dezelfde installatie zowel bodemwarmte als   grondwaterwarmte worden gebruikt, zouden meerdere waarden van toepassing   kunnen zijn (ondiepe geothermie + hydrothermie; diepte geothermie +   hydrothermie). Het voorstel is dus om hier een 1-N-attribuut van te maken, of   om de bovenstaande twee combinaties als optionele domeinwaarden te hanteren.
Warmtepomp | type geothermie: Hydrothermie | Hydrothermie is het geval wanneer grond- of oppervlaktewater   wordt gebruikt als warmtebron. Als binnen dezelfde installatie zowel   bodemwarmte als grondwaterwarmte worden gebruikt, zouden meerdere waarden van   toepassing kunnen zijn (ondiepe geothermie + hydrothermie; diepte geothermie   + hydrothermie). Het voorstel is dus om hier een 1-N-attribuut van te maken,   of om de bovenstaande twee combinaties als optionele domeinwaarden te hanteren.
Warmtepomp | type geothermie: Ondiepe geothermie | Men spreekt van ‘ondiepe geothermie’ wanneer er tot 300 meter   diep geboord wordt. Als binnen dezelfde installatie zowel bodemwarmte als   grondwaterwarmte worden gebruikt, zouden meerdere waarden van toepassing   kunnen zijn (ondiepe geothermie + hydrothermie; diepte geothermie +   hydrothermie). Het voorstel is dus om hier een 1-N-attribuut van te maken, of   om de bovenstaande twee combinaties als optionele domeinwaarden te hanteren.
Warmtepomp: | type: Lucht/lucht warmtepomp | De lucht-lucht warmtepomp gebruikt de buitenlucht als bron, de   warmte wordt uit de lucht gehaald en in de woning afgegeven.    De reden tot opname van deze typering is het kunnen registreren   van verschillende soorten Warmtepompen, aangezien de installaties verschillen   en derhalve ander beheer nodig hebben.
Warmtepomp: | type: Lucht/water warmtepomp | De lucht-water warmtepomp gebruikt de   buitenlucht of ventilatielucht als bron. Er wordt energie uit de lucht   gehaald en omgezet naar warmte. Deze warmte wordt overgedragen aan het   verwarmingssysteem en het tapwater in de woning. De reden tot opname van deze   typering is het kunnen registreren van verschillende soorten Warmtepompen,   aangezien de installaties verschillen en derhalve ander beheer nodig hebben.
Warmtewisselaar | N.v.t. | Een warmtewisselaar is een apparaat dat warmte van een vloeistof   of gas gescheiden overbrengt naar een ander medium. Dit is daarmee een   belangrijk onderdeel van installaties die warmte opnemen uit Warmtebronnen.   De Warmtewisselaar is verbonden met de Warmtepomp.
Warmtewisselaar | type: Buizenwarmtewisselaar | Er zijn verschillende soorten Warmtewisselaars. In zijn meest   eenvoudige vorm is het een buis in een andere buis, ofwel een buis met   daaromheen een mantel. Het ene medium stroomt door de ene buis en het andere   medium door de mantel. Als er een temperatuurverschil bestaat tussen de twee   vloeistoffen, zal warmte van de warme vloeistof naar de koudere vloeistof   worden overgedragen.
Warmtewisselaar | type: Platenwarmtewisselaar | Er zijn verschillende soorten Warmtewisselaars. Een   platenwarmtewisselaar is een specifiek type warmtewisselaar. Een   platenwarmtewisselaar bestaat uit een aantal dunne, geribbelde platen. Deze   platen worden tegen elkaar aangedrukt in een frame, waarbij de randen van de   platen zijn voorzien van een pakking of waarbij de platen aan de randen aan   elkaar worden gelast. Op deze manier ontstaan parallelle kanalen tussen de   platen. De ene vloeistof wordt door de even kanalen geleid, terwijl de andere   vloeistof door de oneven kanalen wordt geleid. Als er een temperatuurverschil   bestaat tussen de twee vloeistoffen, zal warmte door de platen heen van de   warme vloeistof naar de koudere vloeistof worden overgedragen.




</body>

</html>

**Comment by wjtmollema** [comment]
#978

**Comment by wjtmollema** [comment]
**Bespreekpunt**
Kan dit toegevoegd worden of moet dit nog wachten op een werkgroepoordeel?

**Comment by RiX012** [comment]
> **Bespreekpunt** Kan dit toegevoegd worden of moet dit nog wachten op een werkgroepoordeel?

Toevoegen voor 2024 release en daarna eventueel checken met expert
