### ISSUE TITLE
Uitzoeken opname Beregeningsbron binnen IMBOR

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#264]
CROW

Logboek-id | 1573 (in Datacatalogus)
--- | ---
Logboeknummer | 118 (v2021)
Ingediend | 07-Dec-2018

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Een beregeningsbron is een door middel van een boring aangelegde toegang tot een grondwaterbron om grondwater af te tappen voor beregeningsdoeleinden. Een beregeningsbron is aangesloten op een `Beregeningsput`, een `Pomp`, een giertank of direct op de `Beregeningsinstallatie` zelf.

Als zodanig is er binnen IMBOR 2022 een overeenkomst met `Brandput`, omdat deze volgens diens definitie ("Put, in de grond geslagen tot aan een watervoerende laag.") ook toegang geeft tot grondwater. Het voorstel is daarmee om `Beregeningsbron` gelijksoortig te modelleren, namelijk als `subKlasseVan` `Put` en `IMKLBasis object`.
