### ISSUE TITLE
Bij Geleideconstructie type Geleidebarrier zijn de waarden voor type gedetailleerd (vast en verplaatsbaar) niet logisch. --> attribuut Verplaatsbaar toevoegen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#265]
Logboek-id | 1590 (in Datacatalogus)
--- | ---
Logboeknummer | 119 (v2021)
Ingediend | 20-Dec-2018

**Comment by JochemMollema** [comment]
Bij geleideconstructie is het attribuut Verplaatsbaar toegevoegd en zijn  bij type Geleidebarrier de types gedetailleerd vast en verplaatsbaar verwijderd.
