### ISSUE TITLE
Hoe om te gaan met reclameborden met een dubbele functie?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#268]
Ruimte is een schaars goed. Steden zijn meer en meer genoodzaakt efficiënter om te gaan met de beschikbare openbare ruimte. Om die reden heeft JCDecaux Mupi’s ontwikkeld met een dubbele functie, waardoor andere objecten van straat kunnen worden genomen. D

Logboek-id | 1599 (in Datacatalogus)
--- | ---
Logboeknummer | 122 (v2021)
Ingediend | 21-Dec-2018

**Comment by wjtmollema** [comment]
**Constatering**
Deze issue is achterhaald omdat de 'dubbele functies' inmiddels met behulp van semantische relaties gelegd kunnen worden (zij ze `voertUit` of `isVerbondenMet`).
