### ISSUE TITLE
Hoe om te gaan met struinpaden?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#270]
Uitzoeken: welk beheer wordt hier uitgevoerd? Alleen bewegwijzering checken of ook periodiek maaien?

Logboek-id | 1657 (in Datacatalogus)
--- | ---
Logboeknummer | 125 (v2021)
Ingediend | 02-Apr-2019

**Comment by JochemMollema** [comment]
Struinpad is als synoniem van de gebruiksfunctie Pad door gras geregistreerd.
