### ISSUE TITLE
Hoe om te gaan met Grindgazon?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#273]
Logboek-id | 1661 (in Datacatalogus)
--- | ---
Logboeknummer | 128 (v2021)
Ingediend | 02-Apr-2019

**Comment by wjtmollema** [comment]
**Constatering**
In IMBOR 2022 is `Grindgazon` opgenomen als `type gedetailleerd` van `Halfverharding` met als bovenliggende domeinwaarde `Los`.

Deze issue kan als achterhaald beschouwd worden.
