### ISSUE TITLE
Hoe om te gaan met de functies van daken?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#274]
Functies van daken: Op de lijst voor de volgende versie. Dan uitwerken hoe om te gaan met groen op daken van gebouwen, i.v.m.  particulier-openbaar; wijze waarop dit in de BGT of BAG wordt verwerkt, e.v.
Voorstel voor volgende versie (of nu overleggen met

Logboek-id | 1662 (in Datacatalogus)
--- | ---
Logboeknummer | 129 (v2021)
Ingediend | 02-Apr-2019

**Comment by wjtmollema** [comment]
Overweging voor de werkgroep Groen: Welke attributen en objecttypen ontbreken er in IMBOR 2024 als de volgende objecttypes zijn opgenomen:

- `Vegetatiedak`
- `Gevelgroen`

**Comment by JochemMollema** [comment]
Attributen oppervlakte, bergend oppervlak en bergend vermogen zijn aan het objecttype Vegetatiedak toegevoegd.

**Comment by JochemMollema** [comment]
@RiX012: deze issue kan gesloten worden.
