### ISSUE TITLE
Toevoegen informatiebord van een pomp

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#277]
Checken met specialist

Logboek-id | 1665 (in Datacatalogus)
--- | ---
Logboeknummer | 132 (v2021)
Ingediend | 02-Apr-2019

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking** (kan dienen als voorzet voor het in de beschrijving van de issue beschreven 'checken met specialist')
Het toevoegen van een domeinwaarde `Pompinformatiebord` als `type` van `Informatiebord` (enumeratietype: `InformatiebordType`).
