### ISSUE TITLE
CROW: LigtIn, Ondergrond en OnderdeelVan lijken als attributen erg op elkaar. Voorstel om hier met IMBOR 2020 1 attribuut te maken.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#278]
Logboek-id | 1673 (in Datacatalogus)
--- | ---
Logboeknummer | 133 (v2021)
Ingediend | 12-Apr-2019

**Comment by JochemMollema** [comment]
Verwerkt via Semantische relatie is verbonden  met.
