### ISSUE TITLE
Met de introductie van IMGeo 2.2 worden Woonerf en Voetgangersgebied als nieuwe objecttypes toegevoegd.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#279]
Logboek-id | 1689 (in Datacatalogus)
--- | ---
Logboeknummer | 134 (v2021)
Ingediend | 14-May-2019

**Comment by JochemMollema** [comment]
Woonerf en Voetgangersgebied verwerkt in de mapping tussen IMBOR 2021 en IMGeo 2.2
