### ISSUE TITLE
Definities en indeling bij bomen wijzigen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#280]
Boom niet vrij uitgroeiend  --> Boom waarbij de omgeving voorwaarden stelt aan het eindbeeld en waarbij een takvrije zone of een takvrije stam wordt voorgeschreven (bron: RAW)

Gekandelaberde boom -->  nieuwe CROW-indeling waarbij lei- knot- en gekandelab

Logboek-id | 1720 (in Datacatalogus)
--- | ---
Logboeknummer | 136 (v2021)
Ingediend | 07-Jun-2019

**Comment by wjtmollema** [comment]
Deze issue is overbodig geworden door het ontstaan van een gedetailleerdere issue omtrent de afstemming van de `type`-indeling van `Boom` met het Handboek Bomen 2022, zie #1067.
