### ISSUE TITLE
Hoe om te gaan met ondoordringbaar worteldoek t.b.v. bestrijding Japanse duizendknoop

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#283]
In vakliteratuur is steeds meer te vinden over de bestrijding van Japanse duizendknoop (Fallopia japonica). Eén van de methoden is: De groeiplaats wordt ingekleed met ondoordringbaar worteldoek en daarna afgedekt met circa 20 centimeter grond. Aan de rand

Logboek-id | 1734 (in Datacatalogus)
--- | ---
Logboeknummer | 139 (v2021)
Ingediend | 13-Jun-2019

**Comment by JochemMollema** [comment]
Aan het objecttype Groeiplaats is het attribuut worteldoek toegevoegd.
