### ISSUE TITLE
De mogelijkheid om de verandering van de maaiveldhoogte in de tijd vast te leggen ontbreekt in IMBOR.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#284]
-	MVH is de (oorspronkelijke) aanleg–maaiveldhoogte putten
-	MVHACT (actueel) ca. 1 x per 5 jaar worden alle putten in hoogte gemeten (inclusief datum van de meting)
Hiermee wordt o.a. het verloop van de putten in kaart gebracht, dus waar er hoeveel zakki

Logboek-id | 1759 (in Datacatalogus)
--- | ---
Logboeknummer | 140 (v2021)
Ingediend | 21-Jun-2019

**Comment by JochemMollema** [comment]
Dit kan via het informatieobject inwinning geregistreerd worden. Hierbij geldt een 0 op n relatie, waardoor de verandering in de tijd ook vastgelegd kan worden voor elk attribuut, dus ook voor de maaiveldhoogte.

Aan het informatieobject inwinning-informatie is het attribuut domeinwaarde toegevoegd.
