### ISSUE TITLE
Boomveiligheidsklasse ook bij terreindeel opnemen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#285]
Logboek-id | 1775 (in Datacatalogus)
--- | ---
Logboeknummer | 141 (v2021)
Ingediend | 08-Jul-2019

**Comment by JochemMollema** [comment]
Terreindeel is als objecttype komen te vervallen. Boomveiligheidscontrole wel als attribuut bij Bos en Houtwal.
