### ISSUE TITLE
Kleur bij bijzondere tegel ken ik geen voorbeelden verder, maar is destijds door de beheerders aangegeven als gewenst

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#288]
Logboek-id | 1778 (in Datacatalogus)
--- | ---
Logboeknummer | 144 (v2021)
Ingediend | 08-Jul-2019

**Comment by JochemMollema** [comment]
Kleur is in IMBOR 2022 een attribuut van Bijzondere tegel
