### ISSUE TITLE
Bij glijbanen attribuut voor de vorm (talud, spiraal, etc.)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#290]
Bij verschijningsvormen de types gedetailleerd en extra gedetailleerd met een vorm in de naamgeving verwijderen.

Logboek-id | 1780 (in Datacatalogus)
--- | ---
Logboeknummer | 146 (v2021)
Ingediend | 08-Jul-2019
Afgehandeld | 12-Sep-2019

***

**Antwoord:** Aan tabel REF_Vorm Bocht, Gebogen, Gemengde tunnel, Spiraal, Tunnel, Talud en Vrijstaand toegevoegd In tabel X_AttributenDomeinwaarden voor attribuut Vorm de domeinwaarden Bocht, Gebogen, Gemengde tunnel, Spiraal, Tunnel, Talud en Vrijstaand toegevoegd.
I

**Comment by JochemMollema** [comment]
Controle bij type onderdeel of deze tunnels en glijbanen nog in de lijst met type onderdelen staan.
