### ISSUE TITLE
Algemene oplossing in IMBOR voor onderdelen (samenvoegen van de bestaande oplossingen, o.a. kunstwerkonderdeel, constructionderdeel, toestelonderdeel, etc.)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#293]
Logboek-id | 1783 (in Datacatalogus)
--- | ---
Logboeknummer | 149 (v2021)
Ingediend | 06-Aug-2019

**Comment by JochemMollema** [comment]
1.	Het objecttype Onderdeel heet nu Constructieonderdeel
2.	Constructieonderdeel wordt gebruikt voor het vastleggen van:
a.	De constructieonderdelen uit GWSW
b.	De overbruggingsdelen uit IMGeo, type Overbruggingsdeel toegevoegd voor de indeling binnen Constructieonderdeel
c.	Alle grote onderdelen van de Tunnel, type Tunneldeel toegevoegd voor de indeling binnen Constructieonderdeel
d.	De sluisdeur met verschijningsvormen
e.	Overige verschijningsvormen verwijderd.
3.	Type onderdeel van vaste lijst naar suggestielijst. Waardenlijst kan door de organisatie/leverancier gemakkelijk uitgebreid worden.
4.	Constructieonderdeel is geen beheerobject, maar een onderdeel en erft gegevens van het bovenliggende objecttype over. Hiervoor is de klasse Identificatie toegevoegd.
