### ISSUE TITLE
Gebruiksfunctie en wegfunctie samenvoegen: 1 oplossing voor functies binnen IMBOR

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#294]
Logboek-id | 1784 (in Datacatalogus)
--- | ---
Logboeknummer | 150 (v2021)
Ingediend | 06-Aug-2019

**Comment by JochemMollema** [comment]
Wegfunctie en gebruiksfunctie zijn in versie 2020-08 samengevoegd.
