### ISSUE TITLE
Aan de tabel met onderdelen bepalen op welke manier de NEN-bouwdelen en NEN elmenten toegevoegd kunnen worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#295]
Logboek-id | 1814 (in Datacatalogus)
--- | ---
Logboeknummer | 151 (v2021)
Ingediend | 21-Aug-2019

**Comment by JochemMollema** [comment]
Binnen IMBOR (2022) wordt de relatie met NEN2767 op het nievau van NEN Beheerobject gelegd. Bouwdelen en elementen worden niet als onderdeel vastgelegd.
