### ISSUE TITLE
Bij de boom de scheefstand registreren met een waardenlijst: 0- 15 graden, 16 - 60 graden, 61 - 100 graden

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#300]
Logboek-id | 1885 (in Datacatalogus)
--- | ---
Logboeknummer | 157 (v2021)
Ingediend | 13-Sep-2019

**Comment by wjtmollema** [comment]
**Overweging** (kan als input fungeren voor de werkgroep)
Scheefstand kan beschouwd worden als inspectiegegeven en dus als kwaliteitsgegeven. Die beschouwing zou leiden tot de redenering dat omdat het een kwaliteitsgegeven is, het gegeven niet binnen de scope van IMBOR valt. Daarentegen zou beweerd kunnen worden dat, aangezien scheefstand met de groei van een `Boom` samenhangt (net als `stamdiameterklasse actueel`, `kroondiameterklasse actueel` `opkroonhoogteklasse actueel`), een proces dat zich over een lange tijdsperiode uitstrekt, het _wel_ binnen de IMBOR-scope zou vallen. Deze overweging leidt tot twee opties voor verwerking.

**Voorgestelde verwerking**
1. [Optie]: Het afwijzen van het voorstel op basis van de **Overweging** dat het een _inspectiegegeven_ betreft.
2. [Optie]: Het honoreren van het voorstel op basis van de **Overweging** dat het een gegeven is dat in lijn met overige over een lange termijn 'dynamische' boomgegevens gemodelleerd kan worden.

Het kiezen van optie (2) leidt tot het volgende:
- Het toevoegen van `scheefstandklasse` aan de klasse `Boom`, van het datatype `Enumeratie`: N.v.t.` waarden in lijst;`
- Het toevoegen van de domeinwaarden `0 tot 15 graden`, `15 tot 60 graden`; `60 tot 90 graden` (meer dan 90 graden lijkt de deur te openen voor het registreren van onzinnige waarden). Andere opdelingen kunnen overwogen worden (zoals lineaire stappen van 15 graden of van 30 graden).

**Comment by wjtmollema** [comment]
Het Handboek Bomen beschouwt scheefstand als een afwijking/gebrek dat naar voren komt tijdens een boomveiligheidscontrole. Dit moet dus conform optie (1) gezien worden als een _inspectiegegeven_. De op dit moment prevalente manier van denken over inspectiegegevens binnen de ontwikkeling van IMBOR is om deze niet op te nemen.

Het voorstel wordt daardoor aangepast naar het tot nader order sluiten van deze issue.

**Comment by wjtmollema** [comment]
Op dit moment geen onderdeel van IMBOR-modellering van Handboek Bomen. Daarom kan dit van de milestone af. Het kan blijven staan als issue voor de Expertgroep.

**Comment by JochemMollema** [comment]
Item kan voor IMBOR gesloten worden. Scheefstand is conform het Handboek bomen een inspectiegegeven.
