### ISSUE TITLE
Review publicatie Halteplaatsen (Haltedatabase) informatie gelijktrekken met IMBOR

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#301]
Logboek-id | 1888 (in Datacatalogus)
--- | ---
Logboeknummer | 158 (v2021)
Ingediend | 01-Sep-2019

**Comment by wjtmollema** [comment]
**Constatering**
Tot de betreffende publicatie is geïdentificeerd, wordt deze issue gesloten en als achterhaald beschouwd. Zie voor een recente uitbreiding van het `ObjectType` `Halteplaats` de volgende issue: #975
