### ISSUE TITLE
Mogelijkheid om aantal stammen aan te geven bij meerstammig = ja

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#302]
Het aantal stammen nu als memo. Is het mogelijk nadat het wijzigen weer mogelijk is om meerstammig te wijzigen/aan te vullen met standaard waarden zoals: éénstammig, tweestammig, driestammig, vierstammig, etc. Bij memo is daar lastig op te filteren door d

Logboek-id | 1919 (in Datacatalogus)
--- | ---
Logboeknummer | 159 (v2021)
Ingediend | 23-Sep-2019

**Comment by wjtmollema** [comment]
Volgens #1116 en het Handboek Bomen is meerstammigheid een `specifiek boomkenmerk`. Op dit moment is ook binnen het Handboek Bomen ook geen gealloceerde plek voor het `aantal stammen`. Voorgesteld wordt om dit door de specialisten van het Norminstituut te laten oplossen.

**Comment by wjtmollema** [comment]
Op dit moment geen onderdeel van IMBOR-modellering van Handboek Bomen. Daarom kan dit van de milestone af. Het kan blijven staan als issue voor de Expertgroep.

**Comment by JochemMollema** [comment]
Meerstammigheid is een gegeven wat als specifiek boomkenmerk vastgelegd kan worden. Het aantal stammen doet er niet toe.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
