### ISSUE TITLE
Boomgroep is geen goede benaming voor de waarden in de lijst, Boomstructuur is beter.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#303]
Logboek-id | 1920 (in Datacatalogus)
--- | ---
Logboeknummer | 160 (v2021)
Ingediend | 23-Sep-2019

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking** (kan als input fungeren voor de werkgroep)
Het aanpassen van de term `Boomgroep` naar `Boomstructuur` of `Plantverband`. De motivatie hiervoor is het argument dat de naam van het attribuut een te grote terminologische overeenkomst heeft met de domeinwaarde `Bomengroep`. Een verandering van de term in `Boomstructuur` of `Plantverband` zou dit op kunnen lossen.

Een kanttekening hierbij is dat het Handboek Bomen 2022 wel consistent spreekt over een 'boomgroep' in de door het attribuut aangewezen betekenis. Het gebruiken van een andere benaming voor hetzelfde vermindert de kwaliteit van de mate van afstemming tussen beide standaarden.

**Comment by wjtmollema** [comment]
Afgehandeld in #1119
