### ISSUE TITLE
Afstemming IMBOR met de Index Natuur en Landschap, van de provincies.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#306]
https://www.bij12.nl/onderwerpen/natuur-en-landschap/index-natuur-en-landschap/

Logboek-id | 1949 (in Datacatalogus)
--- | ---
Logboeknummer | 163 (v2021)
Ingediend | 31-Oct-2019

**Comment by wjtmollema** [comment]
**Constatering**
Deze issue is hetzelfde als #310. In die issue is een opdrachtomschrijving geplaatst voor de werkgroep. Derhalve kan de huidige issue gesloten worden.
