### ISSUE TITLE
Lijnafwatering en molgoot samenvoegen conform GWSW

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#307]
Logboek-id | 1954 (in Datacatalogus)
--- | ---
Logboeknummer | 164 (v2021)
Ingediend | 01-Nov-2019

**Comment by JochemMollema** [comment]
- Lijngoot toegevoegd aan IMBOR, GWSW maakt duidelijk onderscheid tussen molgoot en lijngoot.
- Objecttype Lijnafwatering laten vervallen. 4 objecttypes op het zelfde niveau
++ Lijngoot
++ Molgoot
++ Taludgoot
++ Verholen goot
De open leidingen zijn op basis van een groter belang voor Riolering verhuist van Weginrichtingsobjecten naar Holle leidingen.
