### ISSUE TITLE
Hoe om te gaan met gecombineerde verharding? Bijvoorbeeld sierbestrating welke in cement gelegd is?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#308]
Logboek-id | 1971 (in Datacatalogus)
--- | ---
Logboeknummer | 165 (v2021)
Ingediend | 06-Nov-2019

**Comment by JochemMollema** [comment]
Dit kan nu via een toelichting bij gemengde bestrating geregistreerd worden. Meenemen naar werkgroep Wegen.

**Comment by wjtmollema** [comment]
**Constatering**
De huidige oplossing is afdoende omdat het een detailniveau betreft waar men in de praktijk niet aan toe komt. Het gebruik van `toelichting gemengde bestrating` dekt dit voldoende af.
