### ISSUE TITLE
Definities niet compleet of zonder inhoud. Het veel gebruikte “Type extra gedetailleerd van…” heeft geen aanvullende betekenis t.o.v. taxonomie.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#312]
Logboek-id | 2113 (in Datacatalogus)
--- | ---
Logboeknummer | 170 (v2021)
Ingediend | 06-Jan-2020

***

**Antwoord:** Reactie Rik Opgenoort (CROW): 
Correcte observatie, 
Zou inderdaad handig zijn als die in IMBOR Access aangepast zou worden.

**Comment by JochemMollema** [comment]
In IMBOR 2021 hebben alle objecttypes, attributen en domeinwaarden een definitie welke door betrokken werkgroepen gecontroleerd kunnen worden.
