### ISSUE TITLE
Functieruimte is een mooiere benaming dan functioneel gebied, want daar vallen zowel lijnvormige als vlakvormige objecten onder.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#313]
Logboek-id | 2124 (in Datacatalogus)
--- | ---
Logboeknummer | 172 (v2021)
Ingediend | 06-Jan-2020

***

**Antwoord:** Pakken we op in versie 2021. Nu is de aansluiting bij IMGeo belangrijker.

**Comment by JochemMollema** [comment]
IMBOR team: dit wordt voorgelegd aan de werkgroep(en)
