### ISSUE TITLE
De komst van sensoren en aanverwante zaken worden niet meegenomen in IMBOR. Bijvoorbeeld wordt er bij verlichting geen rekening gehouden met datakabels en sensoren.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#314]
Logboek-id | 2126 (in Datacatalogus)
--- | ---
Logboeknummer | 173 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
Sensoren is in IMBOR 2022 een aparte zoekingang geworden, ook wordt aansluiting gezocht bij het sensorregister.
