### ISSUE TITLE
Recyclebaar: Wellicht koppeling maken met materialenpaspoort?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#315]
En dan breder trekken dan enkel voor faunavoorziening, dus ook voor andere types?) Of koppeling maken met 10R model van Stiho?

Logboek-id | 2131 (in Datacatalogus)
--- | ---
Logboeknummer | 174 (v2021)
Ingediend | 06-Jan-2020

***

**Antwoord:** Dit onderwerp wordt meegenomen in de doorontwikkeling van IMBOR.

**Comment by JochemMollema** [comment]
Binnen IMBOR 2022 kan materie apart geregistreerd worden en betekent dit dat de gebruikers in een beheersysteem een materialenpaspoor op kunnen bouwen.
