### ISSUE TITLE
Als van alle objecten de functie wordt benoemd, zie je omgekeerd mooi uit welke objecten kan worden gekozen om een in de Openbare ruimte gestelde functionele eis optimaal te kunnen vervullen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#316]
Logboek-id | 2136 (in Datacatalogus)
--- | ---
Logboeknummer | 175 (v2021)
Ingediend | 06-Jan-2020

***

**Antwoord:** Wordt via filters opgelost ijn versie IMBOR 2021

**Comment by JochemMollema** [comment]
Domeinwaarden specifiek voor objecttypes zijn toegevoegd aan IMBOR 2021.
