### ISSUE TITLE
Kabels en leidingen zou moeten matchen met het IMKL 2015

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#317]
Detail niveau van leidingen is zeer beperkt en komt bijvoorbeeld Objecttype niet voor.
Ik kom gedetailleerde info tegen van type leidingen maar niet de domeinwaarde m.b.t. objecttype.

Logboek-id | 2138 (in Datacatalogus)
--- | ---
Logboeknummer | 176 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
IMBOR 2022 is vergeleken met versie 2.0 van IMKL. De relevante gegevens van IMKL 2.0 zijn binnen IMBOR verwerkt. Beide modellen sluiten niet naadloos op elkaar aan.
