### ISSUE TITLE
Bereikbaarheidplus 	bevat domeinwaarden dit niet bij put horen (hoogwerken, maaikorven etc

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#319]
filters op atrribuut aanbrengen

Logboek-id | 2172 (in Datacatalogus)
--- | ---
Logboeknummer | 178 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
Domeinwaarden specifiek voor objecttypes zijn toegevoegd aan IMBOR 2021.
