### ISSUE TITLE
Rioolput materiaal bevat domeinwaarden die niet bij put horen filters op atrribuut aanbrengen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#320]
Logboek-id | 2180 (in Datacatalogus)
--- | ---
Logboeknummer | 179 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
Domeinwaarden specifiek voor objecttypes zijn toegevoegd aan IMBOR 2021.
