### ISSUE TITLE
Het zou enorm handig zijn als er bordpictogrammen toegevoegd zouden worden acces database.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#323]
Logboek-id | 2237 (in Datacatalogus)
--- | ---
Logboeknummer | 182 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
De pictogrammen van de borden worden niet in de Access-database opgeslagen. IMBOR 2022 is de laatste versie die via Access gsdistribueerd wordt. Linken met een website is een betere optie.
