### ISSUE TITLE
Hetgeen wij als gegevensentiteit missen is het ‘object’ sensor.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#324]
Onze suggestie zou zijn om het type sensor beschikbaar te maken bij elk ruimtelijk object.
Maar ook dat het te positioneren is op zogenaamde ‘groene’ daken, waarbij een sensor wordt ingezet om te toetsen op het Sedum op een duurzaam groen dak wel voldoend

Logboek-id | 2252 (in Datacatalogus)
--- | ---
Logboeknummer | 183 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
Via semantische relaties kunnen de verschillende soorten sensoren gekoppeld worden aan relevante objecten.
