### ISSUE TITLE
Attribuut BeschermdeFloraEnFauna kent alleen Ja/Nee terwijl Attribuut TypeBeschermingsstatusPlus ook verschillende domeinnamen kent in relatie tot flora en fauna.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#325]
Graag die uit Attribuut TypeBeschermingsstatusPlus ook beschikbaar maken voor BeschermdeFloraEnFauna

Logboek-id | 2267 (in Datacatalogus)
--- | ---
Logboeknummer | 184 (v2021)
Ingediend | 06-Jan-2020

**Comment by JochemMollema** [comment]
Uitgewerkt via Klasse Flora en Fauna
