### ISSUE TITLE
Bij combinatieborden ook de hoogte van symbolen op het bord aangeven en of er sprake is van digitale informatie in/op het bord.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#327]
De volgorde op het bord is ook belangrijk. Bovenelkaar of naastelkaar.

Logboek-id | 2317 (in Datacatalogus)
--- | ---
Logboeknummer | 187 (v2021)
Ingediend | 21-Feb-2020

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
1. _Hoogte van symbolen op het bord_: In lijn met de bestaande attributen `letterhoogteklasse opschrift` e.d. kan een attribuut genaamd `hoogteklasse symbool` worden voorgesteld, met klassen in `mm` als domeinwaarden. Hier is de onderstaande **Overweging** op van toepassing.
2. _Lokalisatie van symbolen op het bord_: Er kan gekozen worden voor het toevoegen van een attribuut genaamd `symboollokalisatie` met als domeinwaarden `Verticaal geplaatst` (alt.: `Boven elkaar`) en `Horizontaal geplaatst` (alt.: `Naast elkaar`). Ook hier is de onderstaande **Overweging** op van toepassing).
3. _Digitale informatie op het bord_: Digitale informatie op een `Bord` wijst erop dat dit betrekking heeft op het `ObjectType` `Informatiepaneel`. Het relateren van het `InformatieObject` `Bordopschrift` aan `Informatiepaneel` stelt de IMBOR-gebruiker in staat om 0 op N opschriften te registreren. Dit is afdoende voor het registreren van digitale informatie.

**Overweging**
Deze melding leidt tot de constatering van de (mogelijke) redundantie van attributen zoals `symbool`, `waarde`, `opschrift`, `letterhoogteklasse opschrift` bij de klassen `Bord` en `Verkeersbord` vanwege het bestaan van het `InformatieObject` `Bordopschrift`. Op dit moment worden er twee modelleringen voor hetzelfde gegeven gefaciliteerd, beschouw bijvoorbeeld: 
1. `Verkeersbord :: opschrift :: [waarde] :: letterhoogteklasse opschrift :: 20 mm`
2. `Bordopschrift :: opschrift :: [waarde] :: hoogte :: 20`
Ook voor `ondertekst`, `letterhoogteklasse ondertekst`, `stijl opschrift` en `symbool` zijn twee verschillende registraties mogelijk. Voor beide mogelijkheden (`ObjectType`-gerelateerd en `InformatieObject`-gerelateerd) zij er ook verschillen.

_Exclusief mogelijk binnen `Verkeersbord`_
- `letterhoogteklasse huisnummers` (zou m.b.v. `hoogte` ook 'verborgen' met `Bordopschrift` gemodelleerd kunnen worden, maar dat is niet expliciet)
- `huisnummerverwijzing` (zou m.b.v. `opschrift` ook 'verborgen' met `Bordopschrift` gemodelleerd kunnen worden, maar dat is niet expliciet)

**Comment by wjtmollema** [comment]
**Herziening overweging**
NEN 3381 geeft regelgeving voor de plaatsing van symbolen op borden en hun hoogte, wat de opname van attributen voor het registreren van variaties in de beheerfase overbodig maakt.
