### ISSUE TITLE
Verbeteren van het vastleggen van de onderdelen van het opschrift van het verkeersbord.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#331]
De tabel IMBORK_BordOpschrift bevat in de gewenste situatie de volgende velden:
- OpschriftID ) --> bestaand veld in IMBOR
- BordID ) --> bestaand veld in IMBOR
- TypeOpschrift: --> Tekst, Symbool, Display, …
- LinksonderBreedte (positie aangrijpingspunt

Logboek-id | 2357 (in Datacatalogus)
--- | ---
Logboeknummer | 192 (v2021)
Ingediend | 20-Mar-2020

**Comment by JochemMollema** [comment]
Is verwerkt in het informatieobject Bordopschrift
