### ISSUE TITLE
Boomveer een plek geven binnen het model.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#335]
Wat is een boomveer precies? 'Een boomveer is een innovatief, klimaatadaptief boomsysteem', zegt boominnovator Stef Janssen. 'Hiermee is het mogelijk om de boom niet klemvast, zoals in een boombak, en niet grondgebonden te laten groeien. De boom wordt sub

Logboek-id | 2367 (in Datacatalogus)
--- | ---
Logboeknummer | 196 (v2021)
Ingediend | 07-Apr-2020

**Comment by JochemMollema** [comment]
Opnemen in de lijst met boomvoorzieningen

**Comment by JochemMollema** [comment]
Boomveer is toegevoegd als boomvoorziening.
