### ISSUE TITLE
Toevoegen extra domeinwaarden bij Wegmarkering

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#338]
Toevoegen van extra waarden:

Bij symbool: Zigzagstreep, Gehandicaptenparkeerplaats

Bij Letters, cijfers en zones: lettermarkering: P

Bij Dwarsmarkering, Doorgetrokken brede stre(e)p(en):
Stopstreep dubbel
Stopstreep enkel
Voetgangersoversteekplaats

Bi

Logboek-id | 2372 (in Datacatalogus)
--- | ---
Logboeknummer | 199 (v2021)
Ingediend | 14-Apr-2020

**Comment by wjtmollema** [comment]
De behandeling van deze issue wordt gedeeltelijk gealloceerd naar https://github.com/Stichting-CROW/imbor/issues/1095.

**Comment by wjtmollema** [comment]
De overblijvende voorstellen uit deze issue zijn:

- Zigzagstreep
- Gehandicaptenparkeerplaats
- Stopstreep dubbel
- Stopstreep enkel

**Comment by wjtmollema** [comment]
Voor de verwerking van de bovenstaande gevallen, zie #1196.
