### ISSUE TITLE
Controle bij verschijningsvormen op definities die zomaar afgebroken worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#339]
Logboek-id | 2390 (in Datacatalogus)
--- | ---
Logboeknummer | 200 (v2021)

**Comment by JochemMollema** [comment]
Alle definities zijn gecontroleerd.

**Comment by JochemMollema** [comment]
Afgebroken definities zijn hersteld en waar nodig aangevuld.
