### ISSUE TITLE
In de tabel X_O_Attributen nog een keer controleren welke combinaties van objecttypes en attributen uit GWSW afkomstig zijn.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#340]
Logboek-id | 2391 (in Datacatalogus)
--- | ---
Logboeknummer | 201 (v2021)
Ingediend | 18-May-2020

**Comment by JochemMollema** [comment]
Gecontroleerd, wordt ook meegenomen met de match tussen GWSW 1.6 en IMBOR 2021
