### ISSUE TITLE
Aansluiting GWSW - IMBOR, vraag over "kast"

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#343]
In het overleg met de softwareleveranciers werd het volgende voorbeeld genoemd over aansluiting GWSW - IMBOR:
in GWSW zit een kast, met een beperkt aantal attributen.
in IMBOR, voor verlichting, zitten in een kast véél meer soorten attributen

Checkvraag

Logboek-id | 2396 (in Datacatalogus)
--- | ---
Logboeknummer | 204 (v2021)
Ingediend | 19-May-2020

**Comment by JochemMollema** [comment]
Kasten zijn in IMBOR opgedeeld in aparte objecttypen, sluit beter aan bij GWSW.
