### ISSUE TITLE
Verwerken onderzoek naar verschijningsvormen verkeersregelinstallaties.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#349]
Logboek-id | 2431 (in Datacatalogus)
--- | ---
Logboeknummer | 216 (v2021)
Ingediend | 01-May-2020

**Comment by wjtmollema** [comment]
**Constatering**
Uit het onderzoek naar de verschijningsvormen van `Verkeerslantaarn` die (als uitzondering) voorkomen in Nederland zijn de volgende verschijningsvormen in IMBOR 2022 nog onverwerkt gebleven. Voor ieder van deze typeringen zijn foto's gevonden van bestaande instanties die als rechtvaardiging van de opname van de verschijningsvorm kunnen dienen.
- `Verkeerslantaarn :: type :: Onderlicht :: type gedetailleerd :: Rechtsaf voor fietsers op eigen risico`
- `Verkeerslantaarn :: type :: Fietslicht :: type gedetailleerd :: Driekleurig fietslicht met fietserherkenningarmatuur`
- `Verkeerslantaarn :: type :: Fietslicht :: type gedetailleerd :: Driekleurig fietslicht met AFTG-armatuur (Alle Fietsers Tegelijk Groen)`
- `Verkeerslantaarn :: type :: Onderlicht :: type gedetailleerd :: Rechtsaf voor fietsers vrij`
- `Verkeerslantaarn :: type :: Onderlicht :: type gedetailleerd :: Verkeerssituatie met fietsers in de voorrang`
- `Verkeerslantaarn :: type :: Fietslicht :: type gedetailleerd :: Snelste fietsroutearmatuur`
- `Verkeerslantaarn :: type :: Fietslicht :: type gedetailleerd :: Driekleurig fietslicht met Regensensorarmatuur`
- `Verkeerslantaarn :: type :: Rijstrooklicht :: Enkel rechtsafarmatuur`
