### ISSUE TITLE
Verwerken onderzoek naar APV-borden en Sport- en spelborden

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#350]
Logboek-id | 2432 (in Datacatalogus)
--- | ---
Logboeknummer | 217 (v2021)
Ingediend | 01-May-2020

**Comment by wjtmollema** [comment]
**Constatering**
De resultaten van het in 2020 uitgevoerde onderzoek naar de verschijningsvormen van **APV-bord** en **Informatiebord** zijn verwerkt in IMBOR 2022, op de volgende verschijningsvormen na, die op een accordering wachten:
-  `Informatiebord :: type :: Buurtbord :: type gedetailleerd :: Buurtregelbord`;
- `Informatiebord :: type :: Buurtbord :: type gedetailleerd :: Speelplaatsregelbord`;
-  `Informatiebord :: type :: Veiligheidsinstructiebord`;
- `APV-bord :: type :: Scheepvaartverbod`;

In het onderzoek zijn de bovenstaande verschijningsvormen onderbouwd met foto's van bestaande borden.
