### ISSUE TITLE
Verwerken vergelijking IMBOR 2020-01 en de Bordenwijzer 2017

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#351]
Logboek-id | 2433 (in Datacatalogus)
--- | ---
Logboeknummer | 218 (v2021)
Ingediend | 01-May-2020

**Comment by wjtmollema** [comment]
**Constatering**
Uit het onderzoek naar de samenhang tussen IMBOR 2022 en Bordenwijzer 2017 zijn de volgende verschijningsvormen onverwerkt gebleven:

- `Verkeersbord :: type :: Snelheidsbord :: type gedetailleerd :: A0130fs`
- `Verkeersbord :: type :: Combinatiebord :: type gedetailleerd :: D01_BB18-1r`
- `Verkeersbord :: type :: Parkeerbord :: type gedetailleerd :: E08r`
- `Verkeersbord :: type :: Combinatiebord :: type gedetailleerd :: F03_OB206ps`
- `Verkeersbord :: type :: Combinatiebord :: type gedetailleerd :: J21_OB320f`
- `Verkeersbord :: type :: Onderbord :: type gedetailleerd :: OB312`
- `Verkeersbord :: type :: Onderbord :: type gedetailleerd :: OB603t`
- `Verkeersbord :: type :: Onderbord :: type gedetailleerd :: OB604t`
- `Verkeersbord :: type :: Onderbord :: type gedetailleerd :: OB605t`
- `Verkeersbord :: type :: Onderbord :: type gedetailleerd :: OB615t`
- `Verkeersbord :: type :: Bewegwijzeringsbord :: type gedetailleerd :: BW101Sv14b`
- `Verkeersbord :: type :: Bewegwijzeringsbord :: type gedetailleerd :: BW101Sv14l`
- `Verkeersbord :: type :: Bewegwijzeringsbord :: type gedetailleerd :: BW101Sv14r`
- `Verkeersbord :: type :: Bewegwijzeringsbord voor (brom)fietsers :: type gedetailleerd :: BW210lb, BW210rb, BW210h, BW210rh, BW210l, BW210r, BW210b`
- `Verkeersbord :: type :: Bewegwijzeringsbord voor (brom)fietsers :: type gedetailleerd :: BW211lb, BW211rb, BW211lh, BW211l, BW211r, BW211b`
- `Verkeersbord :: type :: Bebakening :: type gedetailleerd :: BB01rtb`

Al deze instanties moeten professioneel beoordeeld worden bijvoorbeeld op het nut van het opnemen van bepaalde tijdelijke informatieborden, vanwege het bestaan van het attribuut `tijdelijk` om dit te ondervangen.

**Comment by JochemMollema** [comment]
De volgende bordcodes zijn toegevoegd aan IMBOR 2025 (met het verzoek aan de nog op te starten expertcommissie om de totale lijst van bordcodes nog een keer te beoordelen.
D01_BB18-1r
E08r
F03_OB206ps
J21_OB320f
OB312
OB603t
OB604t
OB605t
OB615t
BW101Sv14b
BW101Sv14l
BW101Sv14r
BW210lb
BW210rb
BW210h
BW210rh
BW210l
BW210r
BW210b
BW211lb
BW211rb
BW211lh
BW211l
BW211r
BW211b
BB01rtb

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
