### ISSUE TITLE
Algemene oplossing voort LigtIn, HoortBij en OnderdeelVan

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#353]
Logboek-id | 2450 (in Datacatalogus)
--- | ---
Logboeknummer | 220 (v2021)
Ingediend | 03-Jul-2020

**Comment by JochemMollema** [comment]
1.	Semantische relaties toegevoegd aan de tabel imborVoc_Termen.
a.	bevat
b.	heeft deel
c.	Is verbonden met
d.	heeft informatieobject
2.	In de tabel imborVoc_Collecties is de collectie Semantische relatie toegevoegd.
3.	De tabel voor het vastleggen van Semantische relaties is aangemaakt: imborKern_ObjecttypesSemantischeRelaties.
4.	Aan het hoofdmenu van IMBOR is een knop toegevoegd voor alle Semantische relaties tussen objecttypes.
5.	Aan het formulier van het objecttype is een subformulier toegevoegd voor het weergeven van de semantische relaties.
