### ISSUE TITLE
Vergelijk GWSW 1.5.1 met IMBOR 2020-02, verwerken van nieuwe, gewijzigde en vervallen vaste gegevens

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#355]
Logboek-id | 2493 (in Datacatalogus)
--- | ---
Logboeknummer | 222 (v2021)
Ingediend | 01-Jul-2020

**Comment by JochemMollema** [comment]
Vergelijking is uitgevoerd, verschillen en aanpassingen worden verwerkt als aparte meldingen.
