### ISSUE TITLE
Uitzoeken onderborden met tekst lijnbussen op vluchtstrook en einde lijnbussen op vluchtstrook.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#356]
Logboek-id | 2508 (in Datacatalogus)
--- | ---
Logboeknummer | 223 (v2021)
Ingediend | 01-Jul-2020

**Comment by wjtmollema** [comment]
**Constatering**
Het bijgevoegde document beschrijft het gebruik van deze borden door Rijkswaterstaat. Hierin is opgenomen dat de borden (foto's bijgevoegd) variaties op `J37` zijn. Echter is voor de teksten `bij file bus op vluchtstrook` en `einde bus op vluchtstrook` geen onderbordcode (`OBxx`) gespecificeerd. Echter is er geen sprake van een gescheiden Onderbord/Verkeersbordconstructie, maar van een `Combinatiebord`.

**Voorgestelde verwerking**
Vanwege het ontbreken van een onderbordcode kan het volgende voorstel worden ingediend, zodat IMBOR over het expressievermogen beschikt om het verkeersbord te modelleren:
- Optie 1: `J37_OB-Waarde` (met als bovenliggende domeinwaarde `Combinatiebord`), waarbij het attribuut `waarde` wordt aangesproken om `bij file bus op vluchtstrook` en `einde bus op vluchtstrook` op te nemen;
- Optie 2: `J37_OB`, waarbij het attribuut `opschrift` wordt aangesproken om `bij file bus op vluchtstrook` en `einde bus op vluchtstrook` op te nemen;

![image](https://user-images.githubusercontent.com/90725038/212267481-d5f78c3d-875d-4b7c-b51a-8e2267cab606.png)

https://www.opovzeeland.nl/storage/finder/files/1-Richtlijn-Bus-op-vluchtstrook.pdf

**Comment by RiX012** [comment]
Voorwerken zoals voorgesteld.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
