### ISSUE TITLE
Bij Wegmarkering het attribuut richting toevoegen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#357]
Logboek-id | 2510 (in Datacatalogus)
--- | ---
Logboeknummer | 224 (v2021)
Ingediend | 08-Sep-2020

**Comment by wjtmollema** [comment]
**Verwerking**
In imborKern_KlassenAttributen is het attribuut 'richting' toegevoegd bij de klasse 'Wegmarkering.'

**Motivatie**
Het attribuut 'richting' is een zinnige toevoeging aan de klasse 'Wegmarkering' omdat dit attribuut de ligging van de Wegmarkering op het wegdek helpt detailleren.
