### ISSUE TITLE
BeschermdeFloraEnFaunaPlus ook als attribuut toevoegen aan Waterobject, Boom en SolitairePlant

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#359]
Logboek-id | 2512 (in Datacatalogus)
--- | ---
Logboeknummer | 226 (v2021)
Ingediend | 10-Sep-2020

**Comment by JochemMollema** [comment]
Bij Boom, Solitaire plant en Waterobject is de klasse Flora en Fauna toegevoegd
