### ISSUE TITLE
spaties achter labels

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#36]
Omdat je veel queries wil doen via binding met de labels is het extra irritant als er spaties in staan

otl:TypePlus2_2053
  rdf:type rdfs:Class ;
  p:guid <urn:uuid:34C101EE-B6C9-46D9-A0FE-9519EE0F0968> ;
  rdfs:label "BW201-RB "@nl-NL ;
  rdfs:subClassOf otl:TypePlus_2543 ;
  skos:definition "Fietsers rechts oversteken"@nl-NL ;
  skos:prefLabel "BW201-RB "@nl-NL ;
.

**Comment by RiX012** [comment]
In de 2020-08 Access is dit verholpen. De LD versie is nu ook daarop gebaseerd.
