### ISSUE TITLE
Aan de tabel X_ObjecttypeAttributen kun je naast de eenheid ook het gewenstye aantal decimalen registreren.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#361]
Logboek-id | 2514 (in Datacatalogus)
--- | ---
Logboeknummer | 228 (v2021)
Ingediend | 29-Sep-2020

**Comment by JochemMollema** [comment]
IMBOR-team: het vastleggen van decimalen wordt niet doorgevoerd.
