### ISSUE TITLE
Nieuw type bord: Havennummerbord

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#362]
Logboek-id | 2515 (in Datacatalogus)
--- | ---
Logboeknummer | 229 (v2021)
Ingediend | 29-Sep-2020

**Comment by wjtmollema** [comment]
**Constatering**
Uit de melding blijkt niet wat de exacte gebruikstoepassing is van de term `Havennummerbord`. Als er echter op een gebruikstoepassing gewezen wordt zoals in de onderstaande afbeelding is afgebeeld, dan kan de volgende voorgestelde verwerking worden benoemd. (In deze verwerking wordt ook een ander ontbrekend informatiebord meegenomen, dat dezelfde functie heeft als een `Havennummerbord`, namelijk een `Bedrijfsnaambord`.)

`Voorgestelde verwerking`
De borden die ter beschouwing liggen kunnen niet aangeduid worden met een RVV- of niet-RVV-code. Daarom is het niet verstandig om de te modelleren binnen `Verkeersbord`. Het voorstel is om ze te modelleren als detailleringen van `Informatiebord`, ook al hebben ze de functie bewegwijzering. Een alternatief voorstel is om wel een modellering binnen `Verkeersbord`, waarbij de voorstellen als bovenliggende waarde het `type` `Bewegwijzeringsbord` krijgen.
- Het toevoegen van `Havennummerbord` aan `InformatiebordType` als bovenliggende waarde `Informatiebord`.
- Het toevoegen van `Bedrijfsnaambord` aan `InformatiebordType` als bovenliggende waarde `Informatiebord`.

**Alternatief voorstel** (gedeelde bovenliggende waarde): Beide afbeeldingen kunnen ook begripsmatig ondergebracht worden als `Bedrijfsnaambord` waarbij Afbeelding 2 wordt aangeduid als `Industriebewegwijzeringsbord`. Dit leidt tot de volgende voorstellen:
- Het toevoegen van `Bedrijfsnaambord` aan `InformatiebordType` als bovenliggende waarde `Informatiebord`.
- Het toevoegen van `Havennummerbord` aan `InformatiebordTypeGedetailleerd` als bovenliggende waarde `Bedrijfsnaambord`.
- Het toevoegen van `Industriebewegwijzeringsbord` aan `InformatiebordTypeGedetailleerd` als bovenliggende waarde `Bedrijfsnaambord`.

**Afbeelding 1: Havennummerbord**
![image](https://user-images.githubusercontent.com/90725038/212269006-3a9eb713-b6da-42cd-b814-27c79e97a6d2.png)
**Afbeelding 2: Bedrijfsnaambord**
![image](https://user-images.githubusercontent.com/90725038/212269845-9281b5ba-66dc-4ba0-88f7-4b75a918f5c4.png)
