### ISSUE TITLE
IMBOR Vastgoed - registratie van vastgoedobjecten waar de organisatie eigenaar en/of beheerder van is. Opnemen van Types van een pand.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#365]
Logboek-id | 2518 (in Datacatalogus)
--- | ---
Logboeknummer | 232 (v2021)
Ingediend | 25-Jan-2021

**Comment by JochemMollema** [comment]
Types conform SOR opgenomen in versie 2022
