### ISSUE TITLE
Uitbreiding attributen Gebouw op basis van bestaande registratie in het beheersysteem.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#366]
Logboek-id | 2519 (in Datacatalogus)
--- | ---
Logboeknummer | 233 (v2021)
Ingediend | 25-Jan-2021

**Comment by JochemMollema** [comment]
Van verschillende gemeenten is er attribuutinformatie beschikbaar om bij een gebouw te registreren.

**Comment by JochemMollema** [comment]
Alle door de gemeente Moerdijk geleverde gegevens (op het ambitieniveau na, is dynamisch gegeven) kunnen binnen IMBOR 2022 verwerkt worden. Voor de indeling van de gebouwen wordt de consultatieversie van de SOR als basis genomen die in volgende versies van IMBOR verder uitgewerkt kan worden.
