### ISSUE TITLE
Fouten in publicatieversie 2020-08. 2x domeinwaarde Windmolens bij NEN-object, D105 2x

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#367]
Logboek-id | 2586 (in Datacatalogus)
--- | ---
Logboeknummer | 234 (v2021)
Ingediend | 02-Feb-2021

***

**Antwoord:** D105 als typeplus bij Rijrichtingbord verwijderd
Windmolens bij NEN-object: 1 record verwijderd

**Comment by JochemMollema** [comment]
Afgehandeld
