### ISSUE TITLE
Attribuut Zichtbaar ja/nee toevoegen bij Beschoeiing, Damwand en Muur

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#368]
Logboek-id | 2587 (in Datacatalogus)
--- | ---
Logboeknummer | 235 (v2021)
Ingediend | 05-Feb-2021

**Comment by JochemMollema** [comment]
Attribuut zichtbaar toegevoegd bij Beschoeiing, Damwand en Muur.
