### ISSUE TITLE
Gemaal en Vuilvang toevpegen aan Vakdiscipline civiele constructies

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#369]
Logboek-id | 2588 (in Datacatalogus)
--- | ---
Logboeknummer | 236 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Toegevoegd,

**Comment by JochemMollema** [comment]
Afgehandeld
