### ISSUE TITLE
Bij Meubilair twee keer kleur als attribuut 1x met 1 -1 en 1x met 1-N.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#370]
Logboek-id | 2589 (in Datacatalogus)
--- | ---
Logboeknummer | 237 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Keuze voor 1-N om meerdere kleuren te kunnen registreren.

**Comment by JochemMollema** [comment]
Afgehandeld
