### ISSUE TITLE
Bij 5 objecten komen dubbele waarden voor HerbeoordeeldeKlasse voor:  Duiker,  Flyover, Kademuur, Muur en Viaduct.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#371]
Logboek-id | 2590 (in Datacatalogus)
--- | ---
Logboeknummer | 238 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** 1 waarde bij elk objecttype verwijderd.

**Comment by JochemMollema** [comment]
Afgehandeld
