### ISSUE TITLE
Attribuut StadsdeelOfKern via overerving van beheerobject en specifiek bij Wijk.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#372]
Logboek-id | 2591 (in Datacatalogus)
--- | ---
Logboeknummer | 239 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Attribuut StadsdeelOfKern verwijderd bij Wijk.

**Comment by JochemMollema** [comment]
Afgehandeld
