### ISSUE TITLE
Attribuut Gemeente, registratie bij klasse Beheerobject en niet bij OpenbareRuimte, Woonplaats en StadsdeelOfKern.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#373]
Logboek-id | 2592 (in Datacatalogus)
--- | ---
Logboeknummer | 240 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Attribuut Gemeente verwijderd bij OpenbareRuimte, Woonplaats en StadsdeelOfKern.

**Comment by JochemMollema** [comment]
Afgehandeld
