### ISSUE TITLE
Attribuut Wijk, registratie bij klasse Beheerobject en niet bij Buurt.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#374]
Logboek-id | 2593 (in Datacatalogus)
--- | ---
Logboeknummer | 241 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Attribuut Wijk verwijderd bij Buurt

**Comment by JochemMollema** [comment]
Afgehandeld
