### ISSUE TITLE
Bij Domeinwaarden LengteDroogTalud de voorvoegsels Lengte droog talud weggehaald.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#375]
Logboek-id | 2594 (in Datacatalogus)
--- | ---
Logboeknummer | 242 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Lengte droog talud groter dan 2 m. gewijzigd in 2m. en groter, Lengte droog talud tot 2 m. gewijzigd in tot 2m.

**Comment by JochemMollema** [comment]
Afgehandeld
