### ISSUE TITLE
Fout bij Type van Rioolput Reinigende put ook als typeplus van Inspectieput.  Conform GWSW moet het een typeplus van inspectieput zijn

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#376]
Logboek-id | 2595 (in Datacatalogus)
--- | ---
Logboeknummer | 243 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Type Reinigende put verwijderd als type van Rioolput (conform GWSW Basis 1.5.1)

**Comment by JochemMollema** [comment]
Afgehandeld
