### ISSUE TITLE
Moet er bij Gemaal nog een onderverdeling komen tussen Rioolgemalen en andere gemalen?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#377]
Logboek-id | 2596 (in Datacatalogus)
--- | ---
Logboeknummer | 244 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

**Comment by JochemMollema** [comment]
Onderscheid gemaakt tussen rioolgemalen en andere gemalen. Bij Rioolgemaal types gedetailleerd conform GWSW.
