### ISSUE TITLE
Zowel in de SOR als in GWSW wordt Dijk als fysiek object opgevoerd. IMBOR gaat uit groen of grijs met een gebruiksfunctie Dijklichaam.  Moet Dijk als objecttype toegevoegd worden?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#378]
Logboek-id | 2597 (in Datacatalogus)
--- | ---
Logboeknummer | 245 (v2021)
Ingediend | 06-Feb-2021

**Comment by JochemMollema** [comment]
Dijk wordt als Dijklichaam toegevoegd, aansluiting op SOR. Dit wordt een civiele constructie.
