### ISSUE TITLE
Nieuwe waarde bij reservoir, type Steenwolkoffer en Zandkoffer. Samenvoegen met Grindkoffer?

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#379]
Logboek-id | 2598 (in Datacatalogus)
--- | ---
Logboeknummer | 246 (v2021)
Ingediend | 06-Feb-2021

**Comment by JochemMollema** [comment]
Steenwolkoffer en Zandkoffer als objecttypen toegevoegd.
