### ISSUE TITLE
GWSW 1.5.1 - Onderdeel type Doorlaat, typeplus Mechanische afsluiter typeplus2 Stuwklep toevoegen

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#383]
Logboek-id | 2602 (in Datacatalogus)
--- | ---
Logboeknummer | 250 (v2021)
Ingediend | 06-Feb-2021

**Comment by JochemMollema** [comment]
Mechanische afsluiter, Opening in wand en Wervelventiel als objecttypen toegevoegd.
