### ISSUE TITLE
GWSW 1.5.1 - Bij Rioolput type Pompput, typeplus 	Luchtinjectie-unit toevoegen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#389]
Logboek-id | 2608 (in Datacatalogus)
--- | ---
Logboeknummer | 256 (v2021)
Ingediend | 06-Feb-2021

**Comment by JochemMollema** [comment]
Type gedetailleerd van Pompput: Luchtinjectie-unit toegevoegd.
