### ISSUE TITLE
GWSW 1.5.1 - Vacuümpompstation  twee keer opgenomen als type (1x bij Gemaal en 1 x typeplus bij Rioolput) Moet conform GWSW bij Gemaal opgenomen worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#390]
Logboek-id | 2609 (in Datacatalogus)
--- | ---
Logboeknummer | 257 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Bij Rioolput verwijderd.

**Comment by JochemMollema** [comment]
Afgehandeld
