### ISSUE TITLE
GWSW 1.5.1 - In GWSW is zuiveringsgebied hernoemt in Zuiveringseenheid.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#391]
Logboek-id | 2610 (in Datacatalogus)
--- | ---
Logboeknummer | 258 (v2021)
Ingediend | 06-Feb-2021

**Comment by JochemMollema** [comment]
Zuiveringsgebied gewijzigd in Zuiveringseenheid. Definitie ook gewijzigd.

Een afbakening van de zone, waarbinnen al het afvalwater naar eenzelfde rioolwaterzuivering wordt afgevoerd om daar gezuiverd te worden. De grenzen van het gebied hoeven zich niet te beperken tot de gemeentegrenzen.
