### ISSUE TITLE
GWSW 1.5.1 - Schrijfwijzen van gemalen is gewijzigd.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#393]
Logboek-id | 2611 (in Datacatalogus)
--- | ---
Logboeknummer | 260 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Waarde Gemaal in droge opstelling gewijzigd in Gemaal droge opstelling en Gemaal in natte opstelling gewijzigd in Gemaal natte opstelling. (

**Comment by JochemMollema** [comment]
Afgehandeld
