### ISSUE TITLE
IMBOR-NEN2767 -  Opname Verkeerscentrale als nieuw objecttype (ook in NEN)

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#394]
Logboek-id | 2613 (in Datacatalogus)
--- | ---
Logboeknummer | 261 (v2021)
Ingediend | 06-Feb-2021

**Comment by wjtmollema** [comment]
**Constatering**
Rijkswaterstaat schrijft over de sinds 1996 actieve `Verkeerscentrale` 'De Wijde Blik' "In deze verkeerscentrale komt de informatie van de verkeerssignalering, dynamische route-informatiepanelen, toerittdoseringen, wisselbewegwijzering en incidentmanagementcamera’s samen." Deze informatie kan gebruikt worden voor een definitie van de term.

**Voorgestelde verwerking**
- Opname van de term `Verkeerscentrale` bij `GebouwTypeGedetailleerd` met als bovenliggende domeinwaarde `Bedrijfsgebouw`.
