### ISSUE TITLE
Lengte en breedte toevoegen als attributen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#395]
Logboek-id | 2614 (in Datacatalogus)
--- | ---
Logboeknummer | 262 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Lengte en breedte toegevoegd aan Klasse Vegetatiedak.

**Comment by JochemMollema** [comment]
Afgehandeld
