### ISSUE TITLE
Lengte toevoegen als attribuut aan Gevelgroen en Klimplant

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#396]
Logboek-id | 2615 (in Datacatalogus)
--- | ---
Logboeknummer | 263 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Lengte toegevoegd als attribuut aan Gevelgroen en Klimplant

**Comment by JochemMollema** [comment]
Afgehandeld
