### ISSUE TITLE
Lengte en leverancier toevoegen aan Terreindeel, gegevens gelijktrekken aan Groenobject.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#397]
Logboek-id | 2616 (in Datacatalogus)
--- | ---
Logboeknummer | 264 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Lengte en leverancier toegevoegd als attributen aan Terreindeel.

**Comment by JochemMollema** [comment]
Afgehandeld
