### ISSUE TITLE
Opname van Attribuut Hoogte bij Waterinrichtingsobject.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#398]
Logboek-id | 2617 (in Datacatalogus)
--- | ---
Logboeknummer | 265 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Hoogte toegevoegd als attribuut aan Waterinrichingsobject,

**Comment by JochemMollema** [comment]
Afgehandeld
