### ISSUE TITLE
Algemeen: revisietekeningnummer laten vervallen en registreren via Object-documentkoppeling.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#399]
Logboek-id | 2618 (in Datacatalogus)
--- | ---
Logboeknummer | 266 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

**Comment by JochemMollema** [comment]
Meenemen in de herstructurering

**Comment by JochemMollema** [comment]
Verwerkt in via informatieobject Document
