### ISSUE TITLE
URI Strategie en Waardelijsten

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#4]
In de wiki staat een duidelijke uri-strategie beschreven met /def/objecttype en def/prop voor objecttypes en attributen. Ik zou een /def/waardelijst (of cv voor ControlledVocabulary) willen voorstellen voor waardelijsten/domeinen.

**Comment by RiX012** [comment]
@redmer  volgens mij heb je in de laatste versie juist alles onder /id/ gezet?

**Comment by redmer** [comment]
Dit had ik niet correct gelezen dan. Als we kijken naar https://github.com/Stichting-CROW/imbor/blob/master/data/transformaties/000%20Namespaces.ttl#L7-L12 dan zie ik daar (deze definities komen ook in de RML voor):

```
PREFIX graph: <http://linkeddata.crow.nl/imbor/id/graph/>
PREFIX imbor: <http://linkeddata.crow.nl/imbor/id/objecttype/>
PREFIX imborp: <http://linkeddata.crow.nl/imbor/id/eigenschap/>
PREFIX imborvwl: <http://linkeddata.crow.nl/imbor/id/domeinwaarde/>
PREFIX shape: <http://linkeddata.crow.nl/imbor/id/shape/>
PREFIX groep: <http://linkeddata.crow.nl/imbor/id/groepering/>
```

Ik denk dat alles wel `/def/` kan, ja.

**Comment by RiX012** [comment]
> Ik denk dat alles wel /def/ kan, ja.>

Prima! Easy fix
