### ISSUE TITLE
Bij Apparaat wel gegevens van de drager, maar niet van de TypeOndersteuningsconstructie.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#400]
Logboek-id | 2619 (in Datacatalogus)
--- | ---
Logboeknummer | 267 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

**Comment by JochemMollema** [comment]
Meenemen in de herstructurering

**Comment by JochemMollema** [comment]
Alle "apparaten" behoren tot de klasse Ondersteuningsconstructie waarin Type ondersteuningsconstructie in uitgewerkt is.
