### ISSUE TITLE
Bij Groenobject komt nog het attribuut IMGeoFysiekVoorkomen voor. Deze hoort bij Geo-object.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#401]
Logboek-id | 2620 (in Datacatalogus)
--- | ---
Logboeknummer | 268 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Bij Groenobject, Terreindeel, Verhardingsobject en Waterobject IMGeoFysiekVoorkomen als attribuut verwijderd.

**Comment by JochemMollema** [comment]
Afgehandeld
