### ISSUE TITLE
Voor onderhoud en beheer groenobjecten 1 term voor frequenties, nu snoeifrequentie, knipfrequentie en maaifrequentie. Voorstel Onderhoudsfrequentie

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#402]
Logboek-id | 2621 (in Datacatalogus)
--- | ---
Logboeknummer | 269 (v2021)
Ingediend | 06-Feb-2021

**Comment by JochemMollema** [comment]
snoeifrequentie, knipfrequentie en maaifrequentie  samengevoegd tot Onderhoudsfrequentie
