### ISSUE TITLE
Bij Groenobject, Terreindeel en Verhardingsobject wel GedeeldBeheer maar de tweede Beheerder kan niet geregistreerd worden. Dit kan bij Waterobject wel.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#404]
Logboek-id | 2623 (in Datacatalogus)
--- | ---
Logboeknummer | 271 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Beheerder2 als attribuut toegevoegd aan Groenobject, Terreindeel en Verhardingsobject.

**Comment by JochemMollema** [comment]
Afgehandeld
