### ISSUE TITLE
Drijfvuilnet en Bilgepompinstallatie verwijderen als bor-type.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#405]
Logboek-id | 2624 (in Datacatalogus)
--- | ---
Logboeknummer | 272 (v2021)
Ingediend | 06-Feb-2021
Afgehandeld | 06-Feb-2021

***

**Antwoord:** Drijfvuilnet en Bilgepompinstallatie verwijderd als bor-type.

**Comment by JochemMollema** [comment]
Afgehandeld
