### ISSUE TITLE
Attributen met een directe of indirecte documentrelatie komen te vervallen.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#406]
De attributen: Besteknummer, Revisietekeningnummer, Verkeersbesluit, Verkeersbesluitdatum en Verkeersbesluitnummer  komen te vervallen en worden vervangen door een gestandaardiseerde oplossing voor de registratie van documenten.

Logboek-id | 2625 (in Datacatalogus)
--- | ---
Logboeknummer | 273 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Besteknummer, Revisietekeningnummer, Verkeersbesluit, Verkeersbesluitdatum en Verkeersbesluitnummer als attributen laten vervallen.

**Comment by JochemMollema** [comment]
Nog open laten staan, verwerking nog niet afgerond. Het Informatieobject Document moet nog gemaakt worden.

**Comment by JochemMollema** [comment]
Verwerkt via het gebruik en het toevoegen van het informatieobject Document.
