### ISSUE TITLE
Verwijderen van Certificaat bij Groeiplaatsinrichting.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#407]
Het betreft een overbodig gegeven.

Logboek-id | 2626 (in Datacatalogus)
--- | ---
Logboeknummer | 274 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Attribuut verwijderd bij Groeiplaatsinrichting.

**Comment by JochemMollema** [comment]
Afgehandeld
