### ISSUE TITLE
Certificaat en certificaatnummer niet van toepassing op alle objecttypes binnen de groep/klasse Meubilair.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#408]
Logboek-id | 2627 (in Datacatalogus)
--- | ---
Logboeknummer | 275 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Certificering toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
