### ISSUE TITLE
EAN-code niet van toepassing op alle objecttypes binnen de groep/klasse Meubilair.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#409]
Logboek-id | 2628 (in Datacatalogus)
--- | ---
Logboeknummer | 276 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** EAN-code als onderdeel van de klasse Communicatie wordt alleen geregistreerd bij objecttypes waar dit relevant is.

**Comment by JochemMollema** [comment]
Afgehandeld
