### ISSUE TITLE
Klasse Monument toevoegen aan objecttype Herdenkingsmonument.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#410]
Logboek-id | 2629 (in Datacatalogus)
--- | ---
Logboeknummer | 277 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Klasse Monument toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
