### ISSUE TITLE
Klasse Monument toevoegen aan objecttype Graf.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#411]
Logboek-id | 2630 (in Datacatalogus)
--- | ---
Logboeknummer | 278 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Klasse Monument toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
