### ISSUE TITLE
Niet alle kunstwerken zijn monumenten.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#412]
Logboek-id | 2631 (in Datacatalogus)
--- | ---
Logboeknummer | 279 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Monument toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
