### ISSUE TITLE
Niet alle bouwwerken zijn monumenten.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#413]
Logboek-id | 2632 (in Datacatalogus)
--- | ---
Logboeknummer | 280 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Monument toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
