### ISSUE TITLE
Niet alle objecttypes binnen de groep Meubilair kunnen gedragen of ondersteund worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#414]
Logboek-id | 2633 (in Datacatalogus)
--- | ---
Logboeknummer | 281 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** De klasse Ondersteuningsconstructie is niet aan alle objecttypes binnen de groep meubilair toegekend.

**Comment by JochemMollema** [comment]
Afgehandeld
