### ISSUE TITLE
Niet alle objecttypes binnen de groep Bakken kunnen gedragen of ondersteund worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#415]
Logboek-id | 2634 (in Datacatalogus)
--- | ---
Logboeknummer | 282 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** De klasse Ondersteuningsconstructie is niet aan alle objecttypes binnen de groep Bakken toegekend.

**Comment by JochemMollema** [comment]
Afgehandeld
