### ISSUE TITLE
Niet alle objecttypes binnen de groep Apparaten kunnen gedragen of ondersteund worden.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#416]
Logboek-id | 2635 (in Datacatalogus)
--- | ---
Logboeknummer | 283 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** De klasse Ondersteuningsconstructie is niet aan alle objecttypes binnen de groep Apparaten toegekend.

**Comment by JochemMollema** [comment]
Afgehandeld
