### ISSUE TITLE
Niet bij alle fysieke objecten is er een relatie met de ondergrond.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#417]
Logboek-id | 2636 (in Datacatalogus)
--- | ---
Logboeknummer | 284 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Ondergrond toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
