### ISSUE TITLE
Niet alle fysieke objecten hebben of kunnen te maken hebben met zetting.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#418]
Logboek-id | 2637 (in Datacatalogus)
--- | ---
Logboeknummer | 285 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Zetting toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
