### ISSUE TITLE
Niet alle fysieke objecten hebben een constructie.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#420]
Logboek-id | 2639 (in Datacatalogus)
--- | ---
Logboeknummer | 287 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Constructie toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
