### ISSUE TITLE
Niet alle punt- en lijnobjecten hebben de klasse Standplaats

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#421]
Logboek-id | 2640 (in Datacatalogus)
--- | ---
Logboeknummer | 288 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Standplaats toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
