### ISSUE TITLE
Niet alle bouwwerken, bakken, kunstwerken, scheidingen en meubilair krijgen de klasse FloraEnFauna.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#422]
Logboek-id | 2641 (in Datacatalogus)
--- | ---
Logboeknummer | 289 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse FloraEnFauna toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
