### ISSUE TITLE
Attribuut TypeBewerking bij Put heroverwegen, hernoemen of alleen bij Kolk.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#423]
Logboek-id | 2642 (in Datacatalogus)
--- | ---
Logboeknummer | 290 (v2021)
Ingediend | 08-Feb-2021

**Comment by JochemMollema** [comment]
Type bewerking als attribuut bij klasse Put verwijderd, komt ook niet in GWSW voor. Bij Kolk gaat het om type reiniging.
