### ISSUE TITLE
Samenvoegen van de attributen Knipfrequentie, Snoeifrequentie en Maaifrequentie tot Onderhoudsfrequentie.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#424]
Logboek-id | 2643 (in Datacatalogus)
--- | ---
Logboeknummer | 291 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

***

**Antwoord:** Knipfrequentie, Snoeifrequentie en Maaifrequentie zijn vervallen als attribuut en  Onderhoudsfrequentie.is toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
