### ISSUE TITLE
Niet alle IMBOR-objecttypes behoren tot de klasse Onderhoud

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#425]
Logboek-id | 2644 (in Datacatalogus)
--- | ---
Logboeknummer | 292 (v2021)
Ingediend | 08-Feb-2021
Afgehandeld | 08-Feb-2021

**Comment by JochemMollema** [comment]
Afgehandeld, alleen relevante objecttypes behoren tot de klasse Onderhoud.
