### ISSUE TITLE
Niet alle objecten uit de groepen Apparaten, Borden, Bouwwerken, Kunstwerken en Meubilair zijn verlichtingsobjecten.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#426]
Logboek-id | 2645 (in Datacatalogus)
--- | ---
Logboeknummer | 293 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Alleen bij relevante objecttypes is de klasse Verlichtingsobject toegevoegd.

**Comment by JochemMollema** [comment]
Afgehandeld
