### ISSUE TITLE
Attribuut Diameter verhuist van groep Apparaten naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#427]
Logboek-id | 2646 (in Datacatalogus)
--- | ---
Logboeknummer | 294 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Diameter alleen bij de objecttypes Meetbuis en Telpaal.

**Comment by JochemMollema** [comment]
Afgehandeld
