### ISSUE TITLE
Attribuut Meetpunt verhuist van groep Apparaten naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#428]
Logboek-id | 2647 (in Datacatalogus)
--- | ---
Logboeknummer | 295 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Meetpunt alleen bij de objecttypes: Camera, Debietmeter, Detector, Drukmeter, GMS-sensor, Kwaliteitssensor, Lichtsensor, Luchtkwaliteitssensor, Meetbuis, Overstortmeter, Peilbuis, Referentiemicrofoon, Regenmeter, Telpaal, Waterniveaumeter, Weegpunt, Weerstation, Wifi-antenne, Windmeter, Zichtmeter

**Comment by JochemMollema** [comment]
Afgehandeld
