### ISSUE TITLE
Attribuut OnderdeelVan verhuist van groep Apparaten naar objecttypes,

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#429]
Logboek-id | 2648 (in Datacatalogus)
--- | ---
Logboeknummer | 296 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** OnderdeelVan geregistreerd bij de objecttypes: Aansluitvoorziening, Armatuur, Brandblusinstallatie, Camera, Debietmeter, Detector, Drukknop, Drukmeter, GMS-sensor, Groep, Handhavingssysteem, Hoofdpost, Hydrant, Kwaliteitssensor, Lamp, Lichtsensor, Luchtkwaliteitssensor, Luidspreker, Meetbuis, Nutsaansluiting, Overstortmeter, Pigging-installatie, Referentiemicrofoon, Regenmeter, Sirene, Sproeikop, Telpaal, Tunnelventilatie, Verkeerslantaarn, Vuilwaterinnamestation, Vulpunt, Wachttijdvoorspeller, Waterniveaumeter, Weegpunt, Weerstation, Wifi-antenne, Wildsignalering, Windmeter, Zichtmeter, Zonnepaneel

**Comment by JochemMollema** [comment]
Deze melding nog niet sluiten, gaat ook verwerkt worden bij het vastleggen van de semantische relaties.

**Comment by JochemMollema** [comment]
Het attribuut OnderdeelVan is vervallen, relaties tussen objecten worden via semantische relaties beschreven.
