### ISSUE TITLE
Attribuut Richtingnummer verhuist van groep Apparaten naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#430]
Logboek-id | 2649 (in Datacatalogus)
--- | ---
Logboeknummer | 297 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Richtingnummer geregistreerd bij de objecttypes: Camera, Wachttijdvoorspeller, Zichtmeter

**Comment by JochemMollema** [comment]
Afgehandeld
