### ISSUE TITLE
Attribuut VerbondenMetHoofdpost verhuist van groep Apparaten naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#431]
Logboek-id | 2650 (in Datacatalogus)
--- | ---
Logboeknummer | 298 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** VerbondenMetHoofdpost geregistreerd bij de objecttypes: Armatuur, Beregeningsinstallatie,Camera, Debietmeter, Detector, Drukknop, Drukmeter, GMS-sensor, Handhavingssysteem, Kwaliteitssensor, Lichtsensor, Luchtkwaliteitssensor, Luidspreker, Meetbuis, Overstortmeter, Peilbuis, Pomp, Referentiemicrofoon, Regenmeter, Sirene, Telpaal, Toegangshekinstallatie, ToeritDoseerInstallatie, Wachttijdvoorspeller, Waterniveaumeter, Weegpunt, Weerstation, Wifi-antenne, Windmeter, Zichtmeter

**Comment by JochemMollema** [comment]
Deze melding nog niet sluiten, gaat mee met het beschrijven van de semantische relaties.

**Comment by JochemMollema** [comment]
Attribuut verbonden met hoofdpost blijft, het betreft hier een ja/nee attribuut en geen semantische relatie.
