### ISSUE TITLE
Attribuut Verplaatsbaar verhuist van groep Apparaten naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#432]
Logboek-id | 2651 (in Datacatalogus)
--- | ---
Logboeknummer | 299 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Verplaatsbaar geregistreerd bij de objecttypes: Armatuur, Brandblusinstallatie, Camera, Luidspreker, Pigging-installatie, Pomp, Weerstation

**Comment by JochemMollema** [comment]
Afgehandeld
