### ISSUE TITLE
Attribuut Diameter verhuist van groep Bakken naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#433]
Logboek-id | 2652 (in Datacatalogus)
--- | ---
Logboeknummer | 300 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Diameter geregistreerd bij Plantenbak.

**Comment by JochemMollema** [comment]
Afgehandeld
