### ISSUE TITLE
Attribuut Ondergronds verhuist van groep Bakken naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#434]
Logboek-id | 2653 (in Datacatalogus)
--- | ---
Logboeknummer | 301 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Ondergronds geregistreerd bij Container en Opslagtank.

**Comment by JochemMollema** [comment]
Afgehandeld
