### ISSUE TITLE
Attribuut Netbeheerder verhuist van groep Draagsystemen naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#436]
Logboek-id | 2655 (in Datacatalogus)
--- | ---
Logboeknummer | 303 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Netbeheerder geregistreerd bij Ophangconstructie, Paal, Portaal, Spandraad, Wandarm, Zweepmast

**Comment by JochemMollema** [comment]
Afgehandeld
