### ISSUE TITLE
Attribuut Verplaatsbaar verhuist van groep Draagsystemen naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#437]
Logboek-id | 2656 (in Datacatalogus)
--- | ---
Logboeknummer | 304 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Verplaatsbaar geregistreerd bij Paal, Portaal en Zweepmast

**Comment by JochemMollema** [comment]
Afgehandeld
