### ISSUE TITLE
Attribuut Diameter verhuist van groep Meubilair naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#438]
Logboek-id | 2657 (in Datacatalogus)
--- | ---
Logboeknummer | 305 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Diameter geregistreerd bij Afsluitpaal, Bolder, Boomrooster, Dispenser, Hoogtebegrenzer, Markeringspaal, Meldpaal, Oplaadpaal, Paddenstoel, Poller, Raaipaal, Rookpaal, Routepaal, Schoolzonepaal, Speeltoestel, Sportmeubilair, Sporttoestel, Strandoriëntatiepaal, Strandpaal, Tafel, VerzinkbarePiramide, Vlaggenmast, Voorzieningenpaal en Zitelement

**Comment by JochemMollema** [comment]
Afgehandeld
