### ISSUE TITLE
Attribuut Reclame verhuist van groep Meubilair naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#439]
Logboek-id | 2658 (in Datacatalogus)
--- | ---
Logboeknummer | 306 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Reclame geregistreerd bij Abri, Betaalautomaat, Brievenbus, Fietsparkeervoorziening, Informatiezuil, Parkeerautomaat, Vitrinekast en Vlaggenmast

**Comment by JochemMollema** [comment]
Afgehandeld
