### ISSUE TITLE
Shacl Shapes in het metamodel beschrijven instanties, niet de IMBOR klasses

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#44]
Dit vormt een probleem als we de OTL zelf willen controleren. 

Of een OTL die voortbouwt op IMBOR willen controleren.

**Comment by redmer** [comment]
Het lukt me niet om consistent goede validatierapportages te krijgen over de klasses en eigenschappen in IMBOR. Het draait wel goed op instantiedata (Carnvalskombord). 

Iets voor een volgende versie, @RiX012 ?

**Comment by RiX012** [comment]
Heb even contact gehad met onze productowner @ElisabethKloren. Als dit issue nu ingewikkelder is dan vooraf voorzien zullen we het inderdaad nu moeten laten.

**Comment by redmer** [comment]
Het is me toch gelukt! 🚂 komt zo online

**Comment by redmer** [comment]
Ik heb dit getest met de Gemeente-voorbeelddata en met de ontologie zelf met shaclvalidate van TQ.
