### ISSUE TITLE
Attribuut TypeOnderdeel verhuist van groep Meubilair naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#440]
Logboek-id | 2659 (in Datacatalogus)
--- | ---
Logboeknummer | 307 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** TypeOnderdeel geregistreerd bij Abri, Faunameubilair, Faunaverblijfplaats, Fietsparkeervoorziening, Kunstobject, Slagboominstallatie, Speeltoestel, Sportmeubilair, Sporttoestel, Toiletvoorziening

**Comment by JochemMollema** [comment]
Deze melding moet nog open blijven staan en meegenomen worden in de herziening van de onderdelen binnen IMBOR.
