### ISSUE TITLE
Attribuut Verplaatsbaar verhuist van groep Meubilair naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#441]
Logboek-id | 2660 (in Datacatalogus)
--- | ---
Logboeknummer | 308 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Verplaatsbaar geregistreerd bij Afsluitpaal, Asbak, Boomstam, Faunameubilair, Faunaverblijfplaats, Fietsparkeervoorziening, Fietspomp, Kunstobject, Leuning, Opslagcontainer, Speeltoestel, Sportmeubilair, Sporttoestel, Tafel, Toiletvoorziening, Veiligheidsvoorziening en Zitelement

**Comment by JochemMollema** [comment]
Afgehandeld
