### ISSUE TITLE
Attribuut Verplaatsbaar verhuist van groep Scheidingen naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#442]
Logboek-id | 2661 (in Datacatalogus)
--- | ---
Logboeknummer | 309 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Verplaatsbaaer geregistreerd bij Hek.

**Comment by JochemMollema** [comment]
Afgehandeld
