### ISSUE TITLE
Attribuut Wegnummer verhuist van groep Scheidingen naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#443]
Logboek-id | 2662 (in Datacatalogus)
--- | ---
Logboeknummer | 310 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Wegnummer geregistreerd bij Geluidsscherm, Kademuur en Luchtscherm

**Comment by JochemMollema** [comment]
Afgehandeld
