### ISSUE TITLE
Attribuut Reclame verhuist van groep Borden naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#444]
Logboek-id | 2663 (in Datacatalogus)
--- | ---
Logboeknummer | 311 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Attribuut Reclame geregistreerd bij Informatiebord, Informatiepaneel, Klok en Reclamebord

**Comment by JochemMollema** [comment]
Afgehandeld
