### ISSUE TITLE
Attribuut Huisnummer verhuist van groep Bouwwerken naar objecttypes.

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#445]
Logboek-id | 2664 (in Datacatalogus)
--- | ---
Logboeknummer | 312 (v2021)
Ingediend | 09-Feb-2021
Afgehandeld | 09-Feb-2021

***

**Antwoord:** Attribuut Huisnummer geregistreerd bij Gemaal en Pand.

**Comment by JochemMollema** [comment]
Afgehandeld
