### ISSUE TITLE
Toevoeg van een combinatiebord als type van een scheepvaartbord

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#451]
Logboek-id | 2670 (in Datacatalogus)
--- | ---
Logboeknummer | 318 (v2021)
Ingediend | 15-Feb-2021

**Comment by wjtmollema** [comment]
`Voorgestelde verwerking`
- Toevoegen van `Scheepvaartcombinatiebord` aan `ScheepvaartbordType` met als bovenliggende waarde `Scheepvaartbord`.
- Toevoegen van n.t.b. bordcodes van `Scheepvaartcombinatiebord`en.
