### ISSUE TITLE
Haagas voorzien van attributen voor het bepalen van de knipoppervlakte van een haag.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#459]
Haagas voorzien van attributen voor het bepalen van de knipoppervlakte van een haag.

**Comment by GreenpointAdviesPN** [comment]
Ik zou deze attributen liever zien op het Haag-object. Haagas is een hulpobject (volgens definitie).

**Comment by JochemMollema** [comment]
Het objecttype Haagas wordt alleen gebruikt voor het bepalen van de lengte van de haag. Het gaat hierbij om een hulpobject wat niet verplicht gebruikt hoeft te worden. De knipoppervlakte hoort bij het hoofdobject Haag en niet bij het hulpobject Haagas.

@RiX012 deze issue kan gesloten worden.
