### ISSUE TITLE
Toevoegen 3 typen sport

### ISSUE THREAD

**Issue by HarroVerhoeven** [Stichting-CROW/imbor#463]
Van: Diederik, Enrico 
Verzonden: donderdag 25 maart 2021 08:31
Aan: 'Verhoeven, Harro' <Harro.Verhoeven@crow.nl>
CC: Marcel Zijlstra (MZijlstra@amsterdam.nl) <MZijlstra@amsterdam.nl>
Onderwerp: Imbor aanvulling

Beste Harro,

We hebben in het verleden met elkaar gemaild over IMBOR
2020  en het sport gedeelte.

Nu zie ik dat in de vaste lijst van attribuut “Type Sport” dat Hockey, Handbal en Golf als sport ontbreken,
dit zo wel een zeer wenselijke aanvulling zijn in de nieuwe versie van IMBOR.

Met vriendelijke groet,
Enrico Diederik
Databeheer 
Team Ondersteuning 
Sporthallen en -parken 

X Gemeente Amsterdam
X Sport en Bos
X 

e.diederik@amsterdam.nl

**Comment by JochemMollema** [comment]
Hockey, Handbal en Golf toegevoegd als waarden biuj type sport.
