### ISSUE TITLE
Duidelijk maken dat SPARQL-voorbeelden.ipynb gebruik maakt van inferencing

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#47]
De queries in het SPARQL-voorbeelden.ipynb notebook gaan goed omdat er bovenin voor de sparql interpreter geconfigureerd is dat inferencing gebruikt moet worden.

Als je de queries uit het notebook copy-paste naar een andere omgeving gaat dat niet automatisch goed... de rdfs:subClassOf queries doen dan standaard alleen de directe subclasses. Als je de query aanpast naar rdfs:subClassOf* gaat het wel goed.

misschien goed om dat duidelijk te maken in het notebook. ik las er ook even overheen en moest even goed nadenken wat er aan de hand was...

**Comment by redmer** [comment]
Correct. Ik denk dat het handiger is om al deze queries te herschrijven naar `rdfs:subClassOf+`, dan nog weer het inferentie-concept te gaan beschrijven in onze documentatie.

**Comment by RiX012** [comment]
Aangepast in Jupyter voorbeeld.
