### ISSUE TITLE
Nieuwe indeling voor bevaarbaarheidsklasse 

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#479]
Nieuwe indeling voor bevaarbaarheidsklasse (2011 ipv 1992)

**Comment by JochemMollema** [comment]
Nieuwe indeling verwerkt. Zie bijlage.
[GithubIMBOR479.xlsx](https://github.com/Stichting-CROW/imbor/files/6425624/GithubIMBOR479.xlsx)

**Comment by wjtmollema** [comment]
Deze indeling is verwerkt sinds IMBOR 2022.
