### ISSUE TITLE
Aanpassen copyright en andere verwijzingen naar W3C in ReSpec

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#48]

**Comment by redmer** [comment]
Ik heb dit op de backlog gezet (https://crow-serviceportaal.atlassian.net/browse/DLD-110?atlOrigin=eyJpIjoiNDEwMDZkZDJkODc3NGM1ODhhNmU2Y2ZkMDJiN2I3MTQiLCJwIjoiaiJ9) voor het vervolg. 

Als je hier meer prioriteit in ziet, dan ga ik er meteen mee bezig.

**Comment by ElisabethKloren** [comment]
Akkoord, is niet voor deze release

**Comment by RiX012** [comment]
Licentie aanpassen nu IMBOR open is

**Comment by RiX012** [comment]
Overlap #944

**Comment by RiX012** [comment]
Informatie geplaatst op: https://docs.crow.nl/imbor/techdoc/#licenties
LICENSE file weggehaald.
