### ISSUE TITLE
Versie namen releases

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#49]
Wat hier op Github 0.6 versie heet, hebben we in de communicatie met de Provincies steeds 1.0 genoemd 😉

Dit jaar gaan de 2.0 en 3.0 opleveren, beide gefinancierd vanuit de Provincies.

**Comment by redmer** [comment]
Ik heb hierom het versienummer in de distributie gewijzigd naar `1.0.0`. Updates aan de code kunnen het kleineversienummer nog wel wijzigen, maar het blijft voorlopig bij `1.x.x`.
