### ISSUE TITLE
Types van Objecttype Reservoir verhuizen naar Objecttype

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#502]
Types van Objecttype Reservoir verhuizen naar Objecttype

Voor een betere aansluiting op GWSW.

Bassin
Bergbezinkbassin
Bergingsbassin
Bezinkbassin
Infiltratiebassin
Zuiveringsreservoir
-  Biofilter
- IBA

**Comment by JochemMollema** [comment]
Bassin wordt uitgewerkt in zwembad en dok.

**Comment by JochemMollema** [comment]
Dok en Zwembad als objecttype toegevoegd.

**Comment by JochemMollema** [comment]
Bergbezinkbassin
Bergingsbassin
Bezinkbassin
Infiltratiebassin
Zuiveringsreservoir

Toegevoegd als objecttypen.

**Comment by RiX012** [comment]
type gedetailleerd
