### ISSUE TITLE
BOR Meld en Beeldkwaliteit (KOR) als informatieobject verwerken.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#505]
BOR Meld en Beeldkwaliteit (KOR) als informatieobject verwerken. Meldingen en beeldkwaliteit kunnen  als infomatieobjecten aan objecttypen toegevoegd worden. Dit zijn gerelateerde gegevens en worden los van IMBOR uitgewerkt.

**Comment by JochemMollema** [comment]
In de werkversie van IMBOR worden de gegevens van MELD en KOR verwijderd.

**Comment by RiX012** [comment]
Ik denk dat dit niet als InformatieObject persé gemodelleerd hoeft te worden. Dit zou een tussenoplossing zijn totdat BOR Meld en KOR op een juiste manier gemodelleerd en gerelateerd aan IMBOR zijn.
