### ISSUE TITLE
Attributen die de relatie tussen NEN en IMBOR beschrijven, horen niet in het informatiemodel thuis.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#507]
Attributen die de relatie tussen NEN en IMBOR beschrijven, horen niet in het informatiemodel thuis. Dit moet buiten het informatiemodel opgelost worden.

**Comment by RiX012** [comment]
type gedetailleerd

**Comment by JochemMollema** [comment]
De attributen NEN-element, NEN-object en NEN-versie worden verwijderd. De aansluiting tussen IMBOR en NEN moet op een andere manier geregeld worden.
