### ISSUE TITLE
Shapes voor objecten en eigenschappen die niet in IMBOR zitten

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#51]
Bijvoorbeeld `shape:OBB788Shape`.

via Luuk Wijnholts

**Comment by RiX012** [comment]
@redmer Deze is gefixt toch? Zoja graag Close

**Comment by redmer** [comment]
Deze filtering is niet opgelost, omdat de koppeling tussen objecten en eigenschappen in IMBOR (in Access) de concrete tabel-basis is voor de `sh:Shape`s. Die koppeling bevat geen verwijzing naar een informatiemodel en dus wordt er ook niet op gefilterd.
