### ISSUE TITLE
Amsterdam - Ecologie - biotooptype en biotoopsubtype toevoegen aan voormalige types van Terreindeel

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#510]
Amsterdam - Ecologie - biotooptype en biotoopsubtype toevoegen aan voormalige types van Terreindeel.

**Comment by JochemMollema** [comment]
Biotooptype en biotoopsubtype als attributen toegevoegd aan klasse Groenobject.

**Comment by JochemMollema** [comment]
type gedetailleerd

**Comment by RiX012** [comment]
type gedetailleerd

**Comment by RiX012** [comment]
type gedetailleerd

**Comment by JochemMollema** [comment]
type gedetailleerd
