### ISSUE TITLE
Bij Brug bespreken: attributen Hoofdroute en Hoofdvaarroute , zijn routes informatieobjecten?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#526]
Bij Brug bespreken: attributen Hoofdroute en Hoofdvaarroute , zijn routes informatieobjecten?

**Comment by JochemMollema** [comment]
Routes als informatieobject verwerken

**Comment by wjtmollema** [comment]
**Constatering**
Routes zijn op dit moment voor verschillende doeleinden binnen verschillende klassen opgenomen. Hieronder een overzicht:
- `hoofdroute`: `Vaste brug`, `Beweegbare brug`;
- `hoofdvaarroute`: `Vaste brug`, `Beweegbare brug`, `Sluis`;
- `looproutenummer`: `Speelterrein`;
- `routenummer`: `Wegas`.
- `routenummer inzameling`: `Container`, `Afvalbak`
- `type route`: `Wegas`.

Het komt in gemeentelijke datasets vaak voor dat men `type route` wil kunnen registreren op het niveau van `Kunstwerk`, maar niet op het niveau van abstractie van `Wegas` ofwel omdat de gemeentelijke afdeling zelf geen routekaart beheert (dit doet bijv. een andere organisatie, maar niet de afdeling zelf o.b.v. `Wegas`). Dit is een reden die als bestaansrecht voor een `InformatieObject` '`Route-informatie`' (of `Routeinformatie`) kan fungeren.

Daarnaast ziet men bij `Container`, `Afvalbak` en `Speelterrein` het gebruik van routes voor gemeentelijke activiteiten, namelijk inspectie en inzameling. Aangezien een gemeentelijke activiteit zoals strooien al binnen `type route` uitgebreid is uitgewerkt, zou het niet misplaatst zijn dit voor de inspectie van `Speelterrein`en en de inzameling van afval ook te doen.

**Voorgestelde verwerking**
- Het toevoegen van een `InformatieObject` '`Route-informatie`' met als multipliciteit `0 op N relatie`;
- Het plaatsen van `Route-informatie` in de relatie `isBeschrevenDoor` aan tenminste `Vaste brug`, `Beweegbare brug`, `Sluis`, `Speelterrein`, `Container`, `Afvalbak` en `Wegas`. Overige `Klassen` waarbij `Route-informatie` zinnig zou zijn, zijn: `Kunstwerk`, `Wegknoop`, `Weg`; `ReëelObject` is misschien een te breed domein;
- Het toevoegen van de attributen `routenummer` en `type route` aan `Route-informatie`;
- Het toevoegen van de domeinwaarden uit `WegasTypeRoute` aan `Route-informatieTypeRoute` met als aanvullingen: `Inspectielooproute` en `Afvalinzamelroute`;
- Het laten vervallen van de attributen `hoofdroute`, `hoofdvaarroute`, `looproutenummer`, `routenummer inzameling`, `routenummer` en `type route` bij hun bijbehorende klassen;
- Het aanpassen van `routenummer` van `Enumeratie` naar `Referentie` om organisatiespecifieke routenummers m.b.t. afvalinzameling, inspectie etc. te accommoderen.

**Comment by RiX012** [comment]
Ik vind het wel een charmant voorstel en denk dat we het moeten verwerken.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld.
