### ISSUE TITLE
Gebruikerswens decompositie kunstwerken in IMBOR of NEN 2767

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#53]
In IMBOR staan de vaste gegevens die een asset manager nodig heeft voor het tactisch beheer van een kunstwerk, in aanvulling op de gegevens die in IMGeo gevraagd worden.
Bij NEN 2767 (Conditiemeting gebouwen en kunstwerken) wordt een lijst van kunstwerk- en gebouwonderdelen verstrekt, met enkele gegevens die uit een inspectie of conditiemeting kunnen komen. Deze lijst bevat een soort decompositie, en wordt in de bouwwereld vaak als zodanig gebruikt.

Als IMBOR gebruikt wordt om een objecttypebibliotheek op te stellen en areaalgegevens te kunnen modelleren, willen de opstellers daarbij graag een decompositie hebben op basis van NEN 2767 om:

1. De onderdelen van kunstwerken en hun eigenschappen te kunnen opnemen in hun objecttypebibliotheek. Dit vraagt om publicatie van de bekende onderdelen uit NEN 2767 in linked data formaat.
2. Automatisch te kunnen controleren of bij een dataset over een kunstwerk alle onderdelen geleverd zijn met bijbehorende informatie; met de vraag: zijn alle / is het juiste aantal van alle kunstwerkonderdelen meegeleverd bij de data over dit kunstwerk? Dit vraagt om publicatie van een decompositie met cardinaliteiten van de onderdelen in linked data formaat (hoeveel minimaal en maximaal van elk onderdeel aanwezig moet zijn in de data). De gegevens uit de NEN 2767 tabellen moeten daarbij wel opnieuw worden beoordeeld op volledigheid en betrouwbaarheid, omdat er nu soms foutjes en circelredeneringen in zitten, en niet per se de regels voor decomponeren zijn gevolgd die voor redeneringen voor computers nodig zijn, zoals de geheel-deel relatie.  (checken of dit klopt: soms zijn alleen de onderdelen benoemd waar een inspectie op nodig is, logisch maar leidt niet tot volledigheid.

Hoe gebeurt dat nu?
Gebruikers "vertalen" elk op eigen manier de gegevens uit NEN 2767 naar een decompositie, met die onderdelen / het detailniveau die zij zelf nodig hebben. Dit zorgt voor werk bij elke asset manager, in plaats van een keer een collectieve inspanning.

**Comment by ElisabethKloren** [comment]
CROW wil geen eigen interpretatie van de NEN 2767 maken. Dan ontstaat dubbele administratie, dat leidt alleen tot verwarring. We willen een optimale aansluiting op de NEN 2767. Daarom zijn we in gesprek over een gezamenlijk plan. Deze issue is bedoeld om de behoefte vanuit de IMBOR gebruiker scherp te krijgen.

**Comment by nreyngou** [comment]
CROW wil vanzelfsprekend geen eigen NEN2767-4 decompositie gaan bouwen. In goede afspraken met de NEN normcommissie kan een gezamenlijke groep van IMBOR kunstwerk experts en NEN 2767  normcommissieleden echter wel degelijk aan de slag om voor bepaalde beheerobjecten (bijvoorbeeld brug, viaduct, tunnel) concept nieuwe decomposities te gaan bouwen. Dit volgens de regels van de NTA 8035. Deze concept decomposities kunnen dan getoetst worden door de NEN normcommissie en voorlopig op het linked data portaal van CROW worden gezet.  Als de decompositie ooit door NEN zelf als linked data beschikbaar wordt gesteld (of overgedragen wordt aan BIM Loket, zoals ooit geopperd door de normcommissie) kan deze weer worden weggehaald. 

Dit is niet de mooiste oplossing. Maar wel de meest pragmatische en degene waarmee provincies snel geholpen zijn. We doen dan ook niks dubbel omdat we aansluiting met de NEN normcommissie zoeken.

**Comment by RiX012** [comment]
Er wordt nu een traject gestart samen met de NEN. Om te verkennen wat de verhouding tussen de twee is en hoe deze wellicht beter samen kunnen werken. @HarroVerhoeven is hier o.a. mee bezig.

**Comment by RiX012** [comment]
> Er wordt nu een traject gestart samen met de NEN. Om te verkennen wat de verhouding tussen de twee is en hoe deze wellicht beter samen kunnen werken. @HarroVerhoeven is hier o.a. mee bezig.

Loopt in apart traject, wordt buiten deze Repo gehaald
