### ISSUE TITLE
Nieuw objecttype: Lichtkrant?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#534]
Nieuw objecttype: Lichtkrant?

**Comment by wjtmollema** [comment]
`Voorgestelde verwerking`
Een `Lichtkrant` kan beschouwd worden als een `Informatiepaneel`. Daarom kan beargumenteerd worden dat een zelfstandig objecttype niet nodig is.
- Toevoegen van `Lichtkrant` aan `InformatiepaneelType` met als bovenliggende domeinwaarde `Informatiepaneel`.
