### ISSUE TITLE
Beheerobject – beheergebied | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#535]
Een stuk verharding kan een rol als beheerobject hebben daarmee lijkt die relatie 1 – 1. Echter een stuk verharding kan door meerdere beheergebieden lopen waardoor er ergens een 1 – N relatie met beheergebied moet zijn.

**Comment by JochemMollema** [comment]
Relatie tussen object en beheergebied verandert in 0 - N.
