### ISSUE TITLE
Gebiedsindeling | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#536]
Gebiedsindelingen zijn virtuele objecten (NEN 3610) en staan los van fysieke verhardingen. Het zijn zelfstandige objecttypen met eigen eigenschappen. Gebiedsindelingen kunnen wel relaties hebben met verhardingen maar zijn er geen eigenschappen van. Ze horen al helemaal niet verhardingsobjecten te begrenzen.

**Comment by JochemMollema** [comment]
Gebiedsindelingen zijn binnen IMBOR als zelfstandige objecttypes beschikbaar. Voor administratieve doeleinden wordt wel de waarden van de gebiedsindeingen bij objecten vastgelegd.
