### ISSUE TITLE
Geo-object – BGT functie en BGT fysiek voorkomen | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#537]
Geo-object is een rol die een verharding kan hebben in een geo-registratie. BGT wegdeel is niet conform de nieuwe NEN 2660 en NEN 3610 omdat het een (uit functie en verharding) samengesteld objecttype is. Dit geeft mapping problemen met BGT want functie hoort geen eigenschap te zijn bij een fysiek verhardingsobject.

**Comment by JochemMollema** [comment]
Voor de mapping naar IMGeo/BGT zijn extra attributen opgenomen. Deze worden automatisch toegekend en zijn voor het beheer niet relevant.
