### ISSUE TITLE
Decompositie | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#538]
Ik zie bij de attributen diverse zaken staan die onderdelen van verharding betreffen zoals:
Fundering onder- tussen en deklagen.
Het doet mij afvragen of al die verschillende onderdelen altijd dezelfde begrenzing hebben. Bijv.: Is de plek waar het materiaal verandert ook de plek waar de fundering verandert? Ik ben geen echte expert maar dit lijkt me iets om te verifiëren (PIM?). Een verhardingsobject heeft diverse onderdelen in ieder geval een fundering en meerdere lagen. Als één van die verandert ontstaat er dan een nieuwe verhardingsobject

**Comment by JochemMollema** [comment]
In IMBOR 2022 is de fundering als apart objecttype uitgewerkt.
