### ISSUE TITLE
Gebruikerswens samenhang IMBOR en IMGeo

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#54]
Partijen willen een combinatie van IMGeo en IMBOR gebruiken in hun OTL, en ook om uit te vragen aan de markt. De bestaande mapping in Access is daar gelaten, deze is geschikt voor het berichtenverkeer van de BGT, maar niet voor een zuivere vertaling in linked data waarmee automatisering kan plaatsvinden. De wens is een mapping te hebben in IMBOR-linked data

**Comment by ElisabethKloren** [comment]
Rik heeft bij het opstellen van IMBOR 1.0 geadviseerd, om de mapping op IMGeo nog niet in linked data te maken, omdat daar interpretatie bij komt kijken van IMGeo; IMGeo is nog niet beschikbaar in linked data.
 Wetende dat in het kader van SOR (samenhangende objectenregistratie) IMGeo ook aangepast gaat worden, is het misschien wel zonde om die mapping te proberen te maken.

**Comment by ElisabethKloren** [comment]
(mail) Hoi Elisabeth, 

Met zo'n sterk advies lijkt de keus me duidelijk. Voor nu geen uren van CROW aan besteden.

Met vriendelijke groet,
Niels Reyngoud

**Comment by ElisabethKloren** [comment]
Elisabeth,

Ik ben me bewust van Rik’s mening hierin, en hij heeft ook wel een punt. Maar Amsterdam heeft nu behoefte aan die mapping en richtlijnen hoe die mapping het beste gedaan kan worden.

1)	Het gaat nog wel even duren voordat imgeo op de schop gaat, zo snel loopt het DIS Geo/SOR traject niet.
2)	Het gaat in eerste instantie over de mapping constructies (dus owl:EquivalentClass in combinatie met restricties, of iets met shacl…) en niet over de inhoudelijke mapping.
3)	De inhoudelijke mapping is naar beste eer en geweten gedaan door het imbor team. Ik ben het eens met Rik dat de documentatie en uitgangspunten van die mapping niet zo goed gedocumenteerd zijn als de linked data transformatie. Maar Rik mag ook wel vertrouwen hebben in de kennis van Jochem en anderen die er aan gewerkt hebben.

Samenvattend, de mapping is er gewoon in de access database. Het gaat om de beste semantische constructie om die mapping in uit te drukken.

Dus wat we vragen van de semantische experts om een gezamenlijke mening te vormen over wat in het licht van de NTA de beste constructies zijn voor een mapping en om daar ook nog bij op te schrijven dat een mapping altijd vanuit een van beide modellen/invalshoeken is en hoe je daar mee om gaat.
En Amsterdam heeft die adviezen dus in de komende weken nodig. Als we dat niet voor elkaar kunnen krijgen moeten we dat terugkoppelen aan Amsterdam zodat ze niet nodeloos zitten te wachten daarop.

Mvg, Niels

**Comment by RiX012** [comment]
@NielsHoffmann @ElisabethKloren @nreyngou 
Laat ik allereerst mijn punt nogmaals herhalen over de mapping IMGEO en IMBOR in de Access database. Ik heb er best vertrouwen in dat dit naar eer en geweten is gedaan, maar als ik niet de modelleerregels hiervoor heb heeft het echt geen waarde voor mij. Dit is tweeledig: 1) de semantiek eruit halen is niet mogelijk of is een interpretatie. Dus we zullen nooit kunnen achterhalen wat er precies bedoelt is voor mapping (welke usecase afhankelijk is imo) en 2) we kunnen geen aanpassingen of uitbreidingen doen zonder dat we weten hoe de mapping gedaan is. Hiermee is het totaal niet duurzaam.

Maar... zoals @NielsHoffmann terecht aangeeft zouden we de mapping content As Is kunnen nemen en gewoon als goed beschouwen. Deze design decision kunnen we implementeren en de gevolgen accepteren. 
Wanneer we dat doen kunnen we wel aan de slag met een aantal 'best practices' over wat mogelijke oplossingen voor ontologie mappingen kunnen zijn. Ik zou dan echter niet alleen het technische gedeelte willen uitzoeken, maar vooral starten vanuit de use case (met name het proces) en vanuit daar oplossingen aandragen. Omdat (net zoals bij OTL's) er verschillende mate van 'ingewikkeldheid' zijn voor mapping-use case combinatie. Het uitschrijven van mogelijke use cases, met bijbehorende 'governance' constructies EN bijbehorende technische implementaties kan zeker waarde hebben. Met name om dezelfde reden dat ik het versiemanagement stuk geschreven hebt: iedereen zegt maar wat en niemand lijkt elkaar goed te begrijpen, laat staan elkaars oplossingen in waarde schatten. Kortom, het speelveld in kaart brengen.

**Comment by NielsHoffmann** [comment]
Volgens mij maken we het allemaal veel te ingewikkeld. In de imbor database staat een mapping naar imgeo. in die mapping staat dat 'dit ding in imbor' (met eventueel deze eigenschap) hetzelfde is als 'dit ding in imgeo' (met eventueel een eigenschap).  Dat is niet use case afhankelijk of ingewikkelder dan dat. Die mapping is niet tot stand gekomen op basis van semantische regels oid. Maar puur op de definitie van de objecttypen: een Geleideconstructie in imbor is hetzelfde als een Geleideconstructie in imgeo, en die vind je in imgeo in Weginrichtingselement met plus-type geleideconstructie. die kennis uit de imbor access database moeten we toch kunnen 'vertalen' naar een linked data constructie?

De use case is wat mij betreft ook duidelijk. In het beheer/bor-systeem (gisib, iAsset, Obsurv) zitten objecten met een imbor typering en die wil je kunnen relateren aan je bgt/imgeo systeem waar diezelfde objecten in zitten met een imgeo typering. De geometrische afbakening van die objecten wordt bepaald in je bgt systeem en de aanvullende eigenschappen bevinden zich in het bor-systeem. afhankelijk van je inrichting of workflow is de primaire richting van 'synchronisatie' tussen die systemen van bor->bgt of van bgt->bor. Maar in beide gevallen wil je die communicatie eenduidig vormgeven op basis van boven beschreven mapping.

**Comment by RiX012** [comment]
Agree to disagree Niels. :) Ik denk dat je het simplificeert. De mapping die in de IMBOR database staat is te gebruiken met de eerder beschreven opmerkingen. De use case maakt vervolgens uit hoe je deze interpreteert en welke oplossing je gebruikt. Zeggen dat iets hetzelfde is als iets anders is nagenoeg altijd context afhankelijk en zal voor de ene organisatie niet gelden en voor een ander wel.
Er zit bijvoorbeeld een belangrijk verschil tussen het relateren (zwakke semantische relatie) en het subtyperen (sterke semantische relatie). Als je de gevolgtrekking zelf gaat doen of de regels hiervoor in je eigen software gaat implementeren kun je met zwakke relaties uit de voeten. Wil je de gevolgtrekkingen al meenemen in je data zul je met sterke relaties aan de slag moeten. Dit is wat mij betreft één soort van use case afhankelijkheid.

Kortom wat jij beschrijft is imo één use case. Deze is op zich uit te werken uiteraard, maar mijn voorstel was om het wat breder te beschouwen. Juist omdat het speelveld en de mogelijkheden imo eindeloos zijn en er geen one-size-fits-all oplossing is en zou moeten zijn.

**Comment by NielsHoffmann** [comment]
Ik ben nog steeds van mening dat de mapping die in de access database staat redelijk helder is... Je zou deze bijna als een axioma kunnen beschouwen, de experts stellen dat deze objecten (in de context van beheer openbare ruimte) hetzelfde zijn. Hoe je dat vervolgens in een linked data constructie wil modelleren is wel use-case afhankelijk denk ik. En daar ben ik ook nog niet helemaal uit... De eerste use case is het kunnen afleiden van een imgeo object van een imbor object, maar dan moet het imbor object wel alle eigenschappen hebben (inclusief geometrie) om een imgeo object te 'genereren'. Een andere use case is het kunnen relateren van een imbor object aan een imgeo object via bv nta8035:heeftBegrenzing (maar dan moeten de imgeo objecten ruimtelijke gebieden zijn...) en dan de relatie specialiseren of beperken op welke imbor objecten aan welke imgeo objecten gerelateerd kunnen zijn.... dus dat vereist nog wel meer discussie om de use-cases helder te krijgen inderdaad...

**Comment by RiX012** [comment]
De beslissing om deze als axioma te beschouwen is wat mij betreft een design decision. If so, dan ben ik het verder helemaal met je eens.

**Comment by nreyngou** [comment]
Vanuit een gebruikersperspectief is het wel van belang dat we dit jaar 'iets' met IMGeo doen. Momenteel zijn de IMGeo attributen uit de transformatie gelaten en deze zijn dus niet beschikbaar in OTL-IMBOR. DIt betekent dat als je als provincie of gemeente OTL-IMBOR wil gebruiken om data uit te vragen aan een aannemer (user story) je momenteel onvolledig bent. Het liefst wil je zowel IMGeo als IMBOR attributen uitvragen.

Volgens mij is daarvoor nodig:
1) Linked data versie van IMGeo (waarin de IMGeo attributen staan) EN
2) Mapping tussen IMGeo en IMBOR; welk object met welke attributen in IMBOR wordt gerepresenteerd door welk object met welke attributen in IMGeo

OF 

3) Toch IMGeo attributen via IMBOR beschikbaar gaan stellen

Het laatste is onwenselijk, omdat dit niet de verantwoordelijkheid is van CROW, maar van Geonovum. Maar hoe snel kan het eerste worden gerealiseerd? Moeten we voorlopig niet toch voor een minder mooie of minder perfecte oplossing kiezen waarmee we in ieder geval wel die attributen beschikbaar kunnen stellen?

**Comment by ElisabethKloren** [comment]
@NielsHoffmann heeft hierover contact met Geonovum; die zijn in elk geval bereid om hun linked data variant van de actuele IMGeo versie te publiceren op Github, heb ik dat goed begrepen? Wij (CROW) kunnen vervolgens doen wat we moeten doen (gebruiksdoel vaststellen, NTA 8035-proof oplossing bedenken) om een mapping te maken > voor we die mapping publiceren stemmen we die af met Geonovum zodat beide partijen erachter staan.

**Comment by RiX012** [comment]
@JochemMollema en Arnoud de Boer hebben afspraken gemaakt over de mapping tussen IMBOR en IMGeo in de Access versie. 
Geonovum heeft in november de LD versie van IMGeo (BGT) gepubliceerd.
IMBOR is ook beschikbaar als LD.
Michel Bohms heeft een voorstel uitgewerkt om in LD (technisch) te mappen.
Nu wordt de actie ondernomen om de tabel uit Access te vertalen naar een LD mapping tussen IMBOR en IMGeo.

**Comment by RiX012** [comment]
Zie verder issue #12
