### ISSUE TITLE
FloraEnFauna Installatie Ondergrond | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#541]
Het is een klasse dus ik neem aan dat het een zelfstandig objecttype is en geen eigenschap van verhardingsobject. De attributen die erbij genoemd worden kunnen geen eigenschappen zijn van het verhardingsobject.

**Comment by JochemMollema** [comment]
Flora en Fauna informatie kan in versie 2022 via een informatieobject aan relevante objecten gekoppeld worden. In theorie en praktijk ook aan een verhardingsobject.
