### ISSUE TITLE
Groenbeheer | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#542]
Dit hoort niet thuis bij een verhardingsobject. Dit heeft met vegetatie te maken niet met verharding.

**Comment by JochemMollema** [comment]
Dit heeft hier te maken met een maatregel die bijvoorbeeld bij grasbetonstenen van toepassing is. Beheergegevens zijn uit IMBOR verwijderd.
