### ISSUE TITLE
Inspectie Kwaliteit Onderhoud | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#543]
Heeft (conform definitie) betrekking op de rol beheerobject niet direct op verhardingsobject. Ik weet niet precies of dit voor de praktijk een groot probleem is maar een rollenmodel kan hier misschien nuttig zijn.

**Comment by JochemMollema** [comment]
In versie 2022 zijn alle inspectiegegevens en onderhoudsgegevens verwijderd. IMBOR richt zich op de vaste gegevens.
