### ISSUE TITLE
Verhardingsobject | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#545]
In deze klasse staan veel eigenschappen. Zijn die allemaal verplicht? Zo ja dan krijg je bij elke wijziging in één attribuutwaarde een nieuw te registreren verhardingsobject. Dat zou niet werkbaar zijn.

**Comment by JochemMollema** [comment]
Nee, deze zijn niet verplicht.  Werkgroep Wegen kan voor versie 2023 een minimale dataset definiëren.
