### ISSUE TITLE
Aan- of vrijliggend | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#546]
Dat gaat over wat er naast het verhardingsobject ligt en niet over het verhardingsobject zelf. De ligging van het fietspad is geen eigenschap het verhardingsobject. Het zegt alleen iets over objecten in de buurt van het verhardingsobject maar daar moet een verhardingsobject niet op worden begrensd.

**Comment by JochemMollema** [comment]
Dit gaat wel over het verhardingsobject zelf en geeft aan de ligging t.o.v. de hoofdrijbaan.
