### ISSUE TITLE
Breedte lengte | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#547]
Waarom zaken als breedte en lengte opnemen als je al geometrie hebt? Dit zijn afgeleide gegevens van de geometrie. Dat moet je aan applicatie functionaliteit en informatieproducten overlaten en niet in een basismodel stoppen. Daarbij komt ook nog dat verharding in breedte kan variëren.

**Comment by JochemMollema** [comment]
Deze waarden zijn belang om te kunnen rekenen.
