### ISSUE TITLE
Modaliteit wegnummer wegvaknummer wegcategorie etc. | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#548]
Dit gaat allemaal over het gebruik/de indeling en het netwerk van de verhardingen maar dit zegt niks over de fysieke verharding zelf. Dit zijn aparte virtuele (functionele en registratieve) objecttypen. Zie NEN 3610 en ook de SOR.

**Comment by JochemMollema** [comment]
Het zijn gegevens die wel relevant zijn voor de wegbeheerder en de verkeerskundige.
