### ISSUE TITLE
Algemeen | RWS (Remco in 't Hout) Analyse: Verhardingsobject

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#549]
Het model bevat een schat aan waardevolle concepten waar ik veel potentie in zie. De structuur / onderlinge samenhang van die concepten lijkt echter te gericht op één of enkele technische implementatie(-s) of doelgroep(-en) waardoor IMBOR niet alle potentiele doelgroepen kan bedienen.
Het model oogt als een implementatiemodel en niet als een informatiemodel. Verbanden tussen concepten zijn niet meer zo zuiver als ze kunnen zijn (conform NEN 3610 NEN 2660).
De klassen die in de attribuuttabel staan zijn veelal aparte objecttypen of vormen een groep attributen die bij andere objecttypen horen en niet bij Verhardingsobject. Deze Klasse kolom helpt IMBOR meer richting NENE 2660 NEN 3610 / informatiemodel te bewegen.

**Comment by JochemMollema** [comment]
RWS heeft toelichting van CROW gekregen.
