### ISSUE TITLE
IMKL themaklasse

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#550]
Via deze weg en eerdere mailings heb ik al vaker aangegeven dat als we de domeinwaarden van het IMKL willen gebruiken deze dan ook juist qua benaming moeten overnemen. Dit voorkomt extra mappings of onduidelijkheden.
![IMKL themaklasse](https://user-images.githubusercontent.com/40396592/126984201-8b220f50-81db-4f49-9bc3-f6e67b7d11f3.jpg)
![IMKL themaklasse in IMBOR](https://user-images.githubusercontent.com/40396592/126984371-715f16dd-3bc5-4c6c-947a-c7b59c3b2eff.jpg)

Riool onderdruk en weesleiding in IMBOR komen niet overeen met het IMKL model

**Comment by JochemMollema** [comment]
Aangepast
