### ISSUE TITLE
Vaste lijst: Botsklasse aanpassen aan herziene norm EN 12767:2019

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#552]
De norm voorschriften is in 2019 herzien dit heeft impact voor de domeinwaarden onder het attribuut **botsklasse**.

Twee voorbeelden:
Oude botsklasse 100HE3 = herziene botsklasse 100-HE-C-NR ( NR betekent in dit geval dat alle volgende eigenschappen door de aanvrager niet gespecificeerd zijn)
Oude botsklasse 100NE3 = herziene botsklasse 100-NE-B-S-NR-MD-0 (NR betekent in dit geval dat de collapse modus SE of NS mag zijn)

**Comment by wjtmollema** [comment]
Dit is sinds IMBOR 2022 onderdeel van het model.
