### ISSUE TITLE
Toevoegen objecttype Zero-emissiezone als functioneel gebied.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#556]
Toevoegen objecttype Zero-emissiezone als functioneel gebied.

Zones waarbinnen geen logistieke voertuigen mogen komen die emissies uitstoten

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
De `Zero-emissiezone` mag door gemeenten vanaf 2025 aangewezen worden. Het verschil met een `Milieuzone` (nu een `type` van `Verkeerszone`) is dat:

> "In tegenstelling tot bij een milieuzone geldt een zero-emissiezone alleen voor zakelijke logistiek. Dit houdt in dat vrachtwagens, bestelbussen en bedrijfswagens emissievrij moeten rijden binnen deze zones." ([Bron](https://www.amegafleet.nl/duurzaamheid/zero-emissiezones/#:~:text=Zero%2Demissiezone%3A,moeten%20rijden%20binnen%20deze%20zones.))

Anders omschreven:

> "Bij een milieuzone mogen oude diesel personenauto’s,
bestelwagens, vrachtwagens en bussen de milieuzone niet inrijden.
Veel steden in Nederland hebben al een milieuzone ingevoerd,
zoals Amsterdam, Rotterdam, Den Haag, Utrecht, Haarlem,
Eindhoven en Breda.
Zero-emissiezones gelden alleen voor vrachtverkeer en
bedrijfswagens die zakelijk worden gebruikt. Vanaf 2025 kunnen
gemeenten deze emissievrije zones invoeren. Vanaf 2030 moeten
alle vrachtwagens, bestelbussen en bedrijfswagens in deze zones
volledig emissievrij rijden. Zo worden stadscentra duurzamer,
leefbaarder en aantrekkelijker." ([Bron](https://www.ames.nl/media/27077/whitepaper_emissiezone_vw.pdf))

Maar in de praktijk namen TNO en Topsector Logistiek in 2020 aan dat de grenzen van `Zero-emissiezone`s tenminste die van reeds bestaande `Milieuzone`s worden en in steden zonder `Milieuzone` worden opgesteld op basis van vergelijkbare criteria ([Bron](https://topsectorlogistiek.nl/wp-content/uploads/2021/03/20210223-Zero-emissiezones-in-de-praktijk-TNO-Decamod-Effectrapportage.pdf)). Echter is dat de _minimale_ begrenzing voor de `Zero-emissiezone`. De _maximale_ begrenzing beslaat een groter gebied.

Derhalve is het logisch als de termen `Zero-emissiezone` en `Milieuzone` in IMBOR sterk gerelateerd zijn. "Toevoegen objecttype Zero-emissiezone als functioneel gebied." is daarom niet de juiste suggestie. Eerder: 
- `Verkeerszone :: type :: Zero-emissiezone`; of 
- `Verkeerszone :: type :: Milieuzone :: type gedetailleerd :: Zero-emissiezone`.

Een voordeel van de tweede optie is dat door de subsumptie van `Zero-emissiezone` onder `Milieuzone` erkend wordt dat de `Zero-emissiezone` ook een soort `Milieuzone`. In de praktijk kunnen de begrenzingen van de `Zero-emissiezone` echter die van de `Milieuzone` omvatten, wat de tweede optie minder aantrekkelijk maakt. Daarnaast zijn de doelstellingen niet exact hetzelfde, wat de subsumptie ook onlogisch maakt. Dit wijst op het voordeel van de eerste optie: de doelstellingen van `Zero-emissiezone` en `Milieuzone` worden onderscheiden. Naar deze optie gaat daardoor de onpartijdige voorkeur uit.
