### ISSUE TITLE
Relatie geografische objecten met beheerobjecten (fysieke objectypes)  (Sweco 17-02-2020)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#559]
1. Sportterrein is geografisch object en onderdeel van sport maar heeft geen relatie naar bijbehorende fysieke objecten. Begraafplaatsen is vergelijkbaar maar onder algemeen en ook zonder relatie naar bijbehorende fysieke objecten. 
•	Moeten hier geen relaties tussen kunnen worden gelegd? Alle andere relaties zijn wel definieert, wijk, grondsoort etc.. 

2. Lichtpunt en verkeersregelinstallatie/verkeersystemen worden ook vaak als een geografische groepering van beheerobjecten/onderdelen beheert en / of getekend. Vaak wordt het merendeel van de beheer processen aan de groepering gekoppeld. Mist nu in IMBOR. 
•	Waarom zijn deze niet opgenomen? Speelterrein is er bijvoorbeeld weer wel, is ook een samenvoeging van ondergronden/groen/verharding/hekwerk etc.. 

3. Geografische objecten zoals de registratieve en functionele gebieden zijn nu hetzelfde gemodelleerd als beheerobjecten.
•	Waarom hebben geografische objecten zoals de registratieve en functionele gebieden dezelfde beheerobject kenmerken als de fysieke beheerobjecten? Moeten die geregistreerd kunnen worden? Lijkt een hoop overbodige informatie en verwarring. Bij woonplaats moet nu ook een buurt, waterschap, gebruiksfunctie, jaarvanaanleg, etc. kunnen worden geregistreerd. Is niet gewenst.

**Comment by JochemMollema** [comment]
1. Relaties kunnen gelegd worden, ook wanneer deze nog niet in het model beschreven zijn. Uitwerking via werkgroepen in versie 2023.
2. VRI opgenomen
3.  Via klassenindeling andere attributen
