### ISSUE TITLE
IMBOR eigenschappen gelinkt aan extern gegevensmodel 

### ISSUE THREAD

**Issue by LuukWijnholts** [Stichting-CROW/imbor#56]
Voorbeeld: Attribuut 297 Aangemaakt door behoort tot het objecttype 400 Beheerobject wat beide onderdeel is van IMBOR maar er wordt gerefereerd naar het Informatiemodel d.m.v. InformatiemodelID naar de NEN. 

Hierdoor gaat deze niet mee in de transformatie naar de LD versie, terwijl dit wel een IMBOR eigenschap is.

**Comment by redmer** [comment]
Ik heb dit uitgezocht middels een SPARQL query. Er zijn (in IMBOR 2020-07) 347 objecttype-attribuutkoppelingen waarbij het informatiemodel van de koppeling niet gelijk is aan het attribuut of het objecttype. 

```sparql
PREFIX graph: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/graph/>
PREFIX imborp: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/eigenschap/>
PREFIX groep: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/groepering/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX imbor: <http://linkeddata.crow.nl/publication-v2/ns/crow/imbor/def/objecttype/>
select
    (replace(str(?oa), str(groep:OA), "") as ?ObjecttypeAttribuutLink) 
    (?im as ?InformatiemodelLink)
    (replace(str(?attr), str(imborp:P), "") as ?AttribuutID)
    (?AttribuutL as ?Attribuut)
    (?imA as ?InformatiemodelAttribuut)
    (replace(str(?obj), str(imbor:OBB), "") as ?ObjectID)
    (?ObjectTypeL as ?Objecttype)
    (?imA as ?InformatiemodelObject)
where { 
    ?oa imborp:attribuut ?attr ;
        imborp:object ?obj ;
        imborp:informatiemodel/rdfs:label ?im ;
        .
    
    ?attr rdfs:label ?AttribuutL ; imborp:informatiemodel/rdfs:label ?imA .
    ?obj rdfs:label ?ObjectTypeL ; imborp:informatiemodel/rdfs:label ?imO .
    
    filter ((?im != ?imO) || (?im != ?imA))
} limit 10000
```

**Comment by RiX012** [comment]
@JochemMollema @HarroVerhoeven 
Ik heb de query van Redmer even uitgewerkt op de IMBOR Access versie die we op dit moment hebben. Onderstaande Excel is de uitwerking hiervan. 
[ObjectAttribuut Link eigenaardigheden.xlsx](https://github.com/Stichting-CROW/imbor/files/4931250/ObjectAttribuut.Link.eigenaardigheden.xlsx)
Wat te zien is, is dat er dus 347 regels in de tabel X_ObjecttypesAttributen zijn, waarvan het informatiemodel van de koppeling niet gelijk is aan het informatiemodel van het attribuut of het objecttype.

Omdat wij de bij de transformatie alleen regels meenemen (vooralsnog) die van het informatiemodel 'IMBOR' zijn ontstaan er vreemde zaken zoals Luuk hierboven schetst.

Hoe moeten wij dit interpreteren. Waarom is bijvoorbeeld de link tussen het IMBOR object 'Beheerobject' en het IMBOR attribuut 'Aangemaakt door' van de NEN3610?

**Comment by RiX012** [comment]
Niet meer van toepassing vanwege IMBOR2022 (was issue voor IMBOR-LD 2020-08
