### ISSUE TITLE
Wat wordt eigenlijk met hulpobjecten bedoeld  (Sweco 17-02-2020)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#560]
•	Het zijn nu voornamelijk onderdelen, hulpobjecten lijkt geen goede benaming voor onderdelen. Veel onderdelen worden vaak ook specifiek beheert. 
•	Waarom zijn veldbelijningen hulpobjecten en bv. wegmarkeringen beheerobjecten in weginrichtingsobjecten?
•	Wat is het nut van profiellijnen als hulpobject in IMBOR? Is toch geen beheerobject? Is dat niet meer iets voor de BGT?
•	Onderdelen en compartiment zijn OnderdelenVan maar hebben wel hun eigen beheerobject kenmerken terwijl velen hiervan niet kunnen afwijken van het bovenliggende beheerobject en zouden moeten worden overerft. 
•	Is er geen mooiere en betere decompositie oplossing te bedenken voor de onderdelen in plaats van een beheerobject met de naam ‘Onderdelen’? 
•	Kenmerken aan onderdelen zijn zeer breed opgezet doordat alle onderdelen vanuit verschillende vakdisciplines erin moeten passen. Dit creëert veel overtollige kenmerken bij veel onderdelen.
•	Compartimenten horen vanuit de definitie bij Overstortput, bijzondere constructie, stuwput, sceptic tank en bergingsvijver, allen beheerobjecten die niet (of misschien anders) aanwezig zijn in IMBOR

**Comment by JochemMollema** [comment]
In IMBOR 2022 komen de hulpobjecten als klasse niet meer voor.
