### ISSUE TITLE
Objecttypes zelf voorzien vaak aan een te brede informatiebehoefte  (Sweco 17-02-2020)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#561]
1. Zo heeft een beweegbare brug een andere informatiebehoefte dan een vaste brug. Hier worden nu kenmerken gecombineerd. Dus bijvoorbeeld de bediening kenmerken bij een vaste brug. Dit creëert veel ballast in het model.
•	Kan dit specifieker worden uitgesplitst per type bv.? Of het groenobject toch verder opsplitsen in meerdere objecttypes

2. Bij groenobjecten hebben hagen, beplantingen en grassen hele specifieke en andere informatiebehoefte die nu allemaal aan een groenobject komen maar helemaal niet voor alle groenobjecten relevant zijn. Bv. Haagvoetoppervlakte bij grassen. Dit creëert veel ballast in het model.
•	Kan dit specifieker worden uitgesplitst per type bv.? Of het groenobject toch verder opsplitsen in meerdere objecttypes?

**Comment by JochemMollema** [comment]
Is doorgevoerd
