### ISSUE TITLE
Belangrijke kenmerken van het type 1:n worden nutteloos voor rapportages, aantallenanalyses en benchmarks.   (Sweco 17-02-2020)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#563]
Bijvoorbeeld gebruiksfunctie was een belangrijk kenmerk om wegbegrotingen op te groeperen of filteren of een aantallenanalyse per (hoofd)gebruiksfunctie op te maken of een risicoanalyse op te maken. Bijvoorbeeld alles van het type parkeren is van minder risico dan rijbaan in de berekeningen of prioriteitstellingen. Al deze acties worden nagenoeg onmogelijk of heel erg foutgevoelig met een 1:n benadering. 
•	Wees daarvan bewust. Voor belangrijke 1:n kenmerken is het misschien beter om twee keer het kenmerk te registreren waarvan er één het hoofdkenmerk is met 1:1 relatie t.b.v. bovenstaande rapportages / acties.

**Comment by JochemMollema** [comment]
registratie van de hoofdfunctie

**Comment by RiX012** [comment]
We hebben dit voor Functies nu in ieder geval doorgevoerd. Voor kenmerken konden we hier geen generieke oplossing voor herkennen
