### ISSUE TITLE
Ontbrekend kenmerk voor IMKL van groot belang  (Sweco 17-02-2020)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#565]
Bij alle leidingelementen mist het veld IMKL thema. Zonder kan er niet worden uitgewisseld via WIBON. Bv. Meubilair – Drinkwaterpunt / Kast. Wij zijn genoodzaakt om dit kenmerk toe te voegen maar de klant ziet dit als niet IMBOR conform. Dit wordt vanuit de aanbesteding (/ hun IMBOR advies vanuit InArea) ook eigenlijk zo door hen gezien. In ons optiek absurd. Door de noodzaak en wettelijke eis mogen we het toch toevoegen om de WIBON te laten functioneren. Moerdijk zal hier waarschijnlijk ook melding van maken.

**Comment by JochemMollema** [comment]
CROW en Geonovum hebben de match tussen IMKL en IMBOR besproken en binnen IMBOR een mapping toegevoegd hoe IMKL verwerkt is binnen IMBOR. Het attribuut WIBON-thema speelt hierbij een belangrijke rol. Het aansluiten van de beide modellen lukt nog niet volledig en is ook een aandachtspunt voor de volgende versie van IMBOR.
