### ISSUE TITLE
Objectnaam en objectnummer op Beheerobject niveau

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#57]
Objectnummer is aanwezig bij (bijna) alle objecttypegroepen, maar objectnaam maar op een aantal.
WISH: Objectnaam en objectnummer op Beheerobject niveau. zodat ze eenduidig beschikbaar zijn voor alle objecten.

**Comment by RiX012** [comment]
Toegevoegd in 2020-08
