### ISSUE TITLE
Mening over het overnemen van XSD standaard voor gegevenstypen. (Sweco 02-06-2021)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#570]
Ja dat is logisch om te doen, alleen is deze niet specifiek genoeg of /en wordt er teveel gebruik gemaakt van zelfde kenmerken bij verschillende beheerobjecten met verschillende eenheden. Bij hoeveelheden zoals breedte zal, per verschillend in gebruik zijnde breedte, moeten worden aangegeven welke eenheid erbij hoort. Een breedte van een weg gaat bijvoorbeeld in m terwijl de breedte van een leiding in mm wordt bijgehouden in de markt (ook in het GWSW). IMBOR hanteert één attribuut breedte zonder eenheid. Dit gaat problemen opleveren bij het uitwisselen, als eenheden niet zijn gespecificeerd. Een ander voorbeeld, om een datum succesvol te kunnen uitwisselen moet exact worden aangegeven hoe die moet worden opgemaakt om fouten te voorkomen. Dit zijn voorbeelden die niet verschillend te interpreteren moeten zijn waardoor er maatwerk of fouten ontstaan, het moet zodanig zijn beschreven dat ontwikkelaars / software het automatisch moeten kunnen interpreteren waar geen verschil in mogelijk is. Zie onderstaande voorbeelden uit het GWSW hoe wij het graag zouden zien:
![afbeelding](https://user-images.githubusercontent.com/56293445/131104037-0a839c05-0aef-45f2-b71f-628833cd0daa.png)
![afbeelding](https://user-images.githubusercontent.com/56293445/131104062-0e0f29fc-fce6-4fc2-acd5-19f1d7c37e37.png)
![afbeelding](https://user-images.githubusercontent.com/56293445/131104072-16921f77-4d1f-4b4d-a79c-29a45c96b8c2.png)

**Comment by JochemMollema** [comment]
Opgelost door het vastleggen van de dimensies via een lagere klasse dan constructie.
