### ISSUE TITLE
Sportveld: Handbalveld toevoegen

### ISSUE THREAD

**Issue by arjangijlstra** [Stichting-CROW/imbor#574]
Handbal zou toegevoegd zijn, las ik in een eerdere issue. In IMBOR 2021.04.04 ontbreekt handbal in de Access database.
Graag type Handbalveld en typesport Handbal toevoegen

**Comment by JochemMollema** [comment]
Bij type sport is handbal toegevoegd en bij type sportveld handbalveld.
