### ISSUE TITLE
Groen: Braakliggend op niveau van TYPE

### ISSUE THREAD

**Issue by arjangijlstra** [Stichting-CROW/imbor#578]
Braakliggend zit nu als TYPE_DETAIL onder de TYPE Bouwland, terwijl dit niet altijd bouwland is. Perken of boomspiegels kunnen ook braakliggend/onbegroeid zijn. Dit kunnen we nu enkel kwijt onder TYPE Bouwland.

**Comment by JochemMollema** [comment]
Braakliggend als attribuut toevoegen
