### ISSUE TITLE
Bespreken of alle boomvoorzieningen als afzonderlijke objecttypes opgenomen moeten worden

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#579]
Bespreken of alle boomvoorzieningen als afzonderlijke objecttypes opgenomen moeten worden. Nu overlap met objecttypen.

**Comment by wjtmollema** [comment]
Een argument voor de opname van de ondergrondse voorzieningen die als domeinwaarden van `boomvoorziening` figureren (te weten:
- `Beluchtingsdrain` (een `Drain` is een zelfstandig `ObjectType`)
- `Beluchtingssysteem aanlegfase` 
- `Beluchtingssysteem permanent` 
- `Bomengranulaat` (dit is een `type` van `Groeiplaatsinrichting` en als zodanig al zelfstandig)
- `Bomengrond` (dit is een `type` van `Groeiplaatsinrichting` en als zodanig al zelfstandig)
- `Bomenzand` (dit is een `type` van `Groeiplaatsinrichting` en als zodanig al zelfstandig)
- `Boombank` (dit is een `type` van `Zitelement` en als zodanig al zelfstandig)
- `Boombunker` (dit is een `type` van `Groeiplaatsinrichting` en als zodanig al zelfstandig)
- `Boomkratten` (dit is een `type` van `Groeiplaatsinrichting` en als zodanig al zelfstandig)
- `Drainage` (een `Drain` is een zelfstandig `ObjectType`)
- `Gietrand` (gedeeltelijk ondergronds)
- `Infiltratiesysteem`
- `Lavasubstraat`
- `Ondergrondse boomverankering`
- `Sandwichconstructie` (dit is een `type` van `Groeiplaatsinrichting` en als zodanig al zelfstandig)
- `Watergeefdrain` (een `Drain` is een zelfstandig `ObjectType`; `Watergeefdrain` zou een `type` kunnen worden)
- `Watergeefsysteem` (`Beregeningsinstallatie` of `Sproeikop` zijn zelfstandige `ObjectType`n; mogelijk gedeeltelijk ondergronds, net als `Beregeningsleiding` en `Beregeningsput`)
- `Wortelgeleiding`
- `Wortelwering`)

...dat afkomstig is vanuit de gemeente Deventer is dat de ondergrondse boomvoorzieningen belangrijk zijn om mee te kunnen leveren als onderdeel van een IMKL-levering aan het KLIC om de aan het oog onttrokken assets te beschermen tegen graafschade.

Voor de volgende domeinwaarden geldt dit argument niet, omdat ze niet ondergronds zijn:
- `Boomhut`
- `Boomkorf` (dit is een `type` van `Boombeschermer` en als zodanig al zelfstandig)
- `Boompaal`
- `Boomspiegel` (nu al een `gebruiksfunctie` van `Groenobject` of `Verharding`)
- `Boomspiegel - beplant` (nu al een `gebruiksfunctie` van `Groenobject`)
- `Boomspiegel - gebonden steenslag` (nu al een `gebruiksfunctie` van `Halfverharding`)
- `Boomspiegel - halfverhard` (nu al een `gebruiksfunctie` van `Halfverharding`)
- `Boomspiegel - onverhard`  (nu al een `gebruiksfunctie` van `Onverhard`)
- `Boomveer`
- `Bovengrondse boomverankering`
- `Feestverlichting`
- `Kroonverankering`
- `Maaipaaltjes`
- `Nestkast` (dit is een `type` van `Faunaverblijfplaats` en als zodanig al zelfstandig)
- `Ondersteunen zware tak`
- `Parkeerbescherming` (dit is een `functie` van `Boombeschermer` (`type` `Boombumper`) en als zodanig al zelfstandig)
- `Sierhek` (dit is een `functie` van `Hek` en als zodanig al zelfstandig)
- `Standplaatsinrichting-algemeen`
- `Verplaatsbare boombak` (dit is een `type` en een attribuut van `Plantenbak` en als zodanig al zelfstandig)
- `Vleermuiskast` (dit is een `type` van `Faunaverblijfplaats` en als zodanig al zelfstandig)
- `Vlonder` (`Vlonder` is een zelfstandig `ObjectType`)

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Voor alle ondergrondse en bovengrondse domeinwaarden van `boomvoorziening` die nog niet als verschijningsvorm van een `ObjectType` in IMBOR zijn opgenomen, wordt in wat volgt een voorstel gedaan voor een uitwerking als zelfstandig `ObjectType`. Dit voorstel kan door de werkgroep beoordeeld worden.


- `ObjectType` `Beluchtingssysteem` als `subKlasseVan` `Constructieonderdeel`; met als invulling van `type` `Beluchtingssysteem aanlegfase` en `Beluchtingsysteem permanent`.
- `ObjectType` `Boomverankering` als `subKlasseVan` `Constructieonderdeel`; met als invulling van `type` `Ondergrondse boomverankering` en `Bovengrondse boomverankering` (of het gebruik van het attribuut `boven- of ondergronds` i.p.v. `type`).
- `ObjectType` `Drain` met als nieuwe `type`n `Beluchtingsdrain` en `Watergeefdrain`; '`Drainage`' gaat verwijzen naar `Drain`.
-  `ObjectType` `Gietrand` als `subKlasseVan` `Constructieonderdeel`; 
- `ObjectType` `Groeiplaatsinrichting` met als nieuw `type` `Lavasubstraat`; 
-  `ObjectType` `Infiltratiesysteem` als `subKlasseVan` `Installatie`; 
- `ObjectType` `Wortelscherm` als `subKlasseVan` `Scheiding` of `Constructieonderdeel`; met als invulling van `type` `Wortelgeleiding` en `Wortelwering`.

**Comment by wjtmollema** [comment]
Deze issue wordt afgehandeld in #1127 en wordt om die reden gesloten. De bevindingen hierboven worden daar geciteerd om meegenomen te worden in de afweging die ten grondslag ligt aan de definitieve verwerking.
