### ISSUE TITLE
Vegetatieobject-boom: Boom hoogte klasse actueel overlap

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#58]
Boom hoogte klasse actueel is een vaste lijst, en bevat de waarde 12-15 15-18 maar ook 12-18. Deze overlap in waarden lijkt niet wenselijk.

**Comment by RiX012** [comment]
De oorzaak hiervoor is dat er een dubbele beheersystematiek gefaciliteerd wordt. De ene is van het Norminstituut en de ander van CROW.
Een oplossingsrichting zou kunnen zijn om per systematiek een apart attribuut te introduceren met elk hun eigen waardelijst.
We gaan dit voorleggen aan de community.
