### ISSUE TITLE
vakdiscipline ecologie overbodig...

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#591]
Kijkend naar de objecten die onder de 'vakdiscipline' ecologie vallen verbaast het me dat hiervoor is gekozen. Dit kan prima onder de vakdiscipline groen. Daarnaast zijn er ook objecten die vallen onder faunavoorziening. De scheiding tussen de ecologie en faunavoorzieningen is ook dun, dus waarom dan niet deze objecten niet onder één vakdiscipline opnemen. Bijvoorbeeld onder de naam Fauna.

Daarwaar het ecologie betreft kan er mogelijk ook een activiteit ecologie aangekoppeld worden

**Comment by JochemMollema** [comment]
Ecologie is toegevoegd op verzoek van een gemeente als extra zoekingang/discipline.
