### ISSUE TITLE
registratiegebieden op verschillende plaatsen.

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#592]
Daar waar eerst de registratieve en functionele gebieden eerst onder de 'vakdiscipline' Algemeen waren ondergebracht, kom ik deze nu op andere plaatsen tegen:

kerngebied - ecologie
natuurgebied - ecologie
tracé - ecologie
verbindingszone - ecologie
ecologischperceel - faunavoorziening
beheervak - groen/riolering/ wegen / ...

Nederlandse aansluitende zone - water
Nedelandse continentaal plat - water
Nederlandse ...   - water
Visserijzone - water
...

Voorkeur om alle registratieve- en functionele gebieden op één plek (vakdiscipline)

**Comment by RiX012** [comment]
@JochemMollema Kan handig zijn om alle gebieden OOK in een eigen vakdiscipline te hebben, bijvoorbeeld 'Ruimten' of 'Gebieden' (naast de vakinhoudelijk indeling).

**Comment by JochemMollema** [comment]
Er is in de huidige opzet voor gekozen om de gebieden te gebruiken in combinatie met vakgebieden, dit om het zoeken en clusteren van objecttypen binnen het model te vergemakkelijken. Binnen een beheersysteem kan er naar eigen inzicht van de leverancier en de gebruikers een extra overzicht gemaakt worden waarbinnen alle gebieden beheerd kunnen worden.
