### ISSUE TITLE
kabels en leiding objecttypes

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#594]
Uitgaande van het integraal objectenbeheer en wat daarvoor conform IMKL kan worden uitgewisseld, zijn er objecttypes die ontbreken in de vakdiscipline 'kabels en leidingen'

Aan de vakdiscipline zou minimaal de volgende objecttypes moeten worden toegevoegd ( hierbij is aangehouden welke objecten er bij verschillende 'WIBON thema's'kunnen voorkomen:

- aansluitleiding en -put
- benzine- of olieput
- beregeningsleiding en -put
- drain en drainage put
- fauna-inspectieput
- Infiltratie bassin, - krat, - put
- loze leidingen en  -put
- mechanische transportleiding

kasten die eveneens bij andere thema's kunnen wvoorkomen zouden ook aan het rijtje kunnen worden toegevoegd...

**Comment by JochemMollema** [comment]
Bovenstaande objecttypen zijn allemaal toegevoegd.
