### ISSUE TITLE
TYPE 'Ongewapend nietverdeuveld beton' en 'Ongewapend nietverdeuveld beton' veranderen

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#595]
**Issue toelichten**
Voor OBJECTTYPE betonverharding
Wordt er onder TYPE onderscheid gemaakt tussen 'Ongewapend nietverdeuveld beton' en 'Ongewapend nietverdeuveld beton'.
Dit lijkt me overbodig aangezien onder TYPE GEDETAILLEED ook al onderscheid wordt gemaakt tussen 'Onverdeuveld' en 'Verdeuveld'.

**Eventueel een verbetervoorstel of eigen inzicht**
Voorstel is om TYPE 'Ongewapend nietverdeuveld beton' en 'Ongewapend nietverdeuveld beton' te veranderen in 'Ogewapend beton'. 
Via een niveau lager TYPE GEDETAILLEERD kan onderscheid gemaakt worden tussen 'Onverdeuveld' en 'Verdeuveld'.

**Comment by JochemMollema** [comment]
Type ongewapend beton toegevoegd met de types gedetailleerd onverdeuveld en verdeuveld.
