### ISSUE TITLE
Niet duidelijk waarom bepaalde objecttype onder Algemeen zijn geplaatst

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#596]
**Issue toelichten**
Het is me niet helemaal duidelijk waarom sommige objecten onder Algemeen zijn geplaatst.
Het lijkt zo te zijn dat als er geen plek voor was deze maar naar Algemeen zijn geplaatst. 
Misschien beter om dan algemeen Overig te noemen dat dekt meer de lading.
Sommige daarvan kunnen naar mijn beter naar Groen of Ecologie (wat volgens mij ook samen mag).

**Eventueel een verbetervoorstel of eigen inzicht**
Naar Groen of Ecologie:
- Heide
- Natuurgebied
- Bos
- Bouwland
- Duin
- Zandvlakte

**Comment by JochemMollema** [comment]
Heide --> groen
Natuurgebied --> ecologie
Bos --> groen en ecologie
Bouwland --> groen
Duin --> groen
Zandvlakte --> groen
