### ISSUE TITLE
Attribuut bor-FysiekVoorkomen heeft Enumeratie terwijl waarde automatisch bepaalt wordt

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#601]
Het attribuut bor-FysiekVoorkomen heeft als TypeAttribuut "Waarde wordt automatisch bepaald", maar heeft ook een EnumeratieType.
Dit lijkt een fout.

**Comment by JochemMollema** [comment]
Enumeratietypes:
GroenobjectBor-Fysiekvoorkomen
VerhardingsobjectBor-Fysiekvoorkomen vervallen
