### ISSUE TITLE
Toelichting geven op cryptische definitie InformatieObject (van GreenpointAdviesPN)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#602]
De uitleg van InformatieObject is te cryptisch. Wellicht letterlijke vertaling over nemen uit de NEN2660-2.

Sowieso op de Toelichting toevoegen:
>De interpretatie die IMBOR doet op het NEN2660-2 InformatieObject is dat het en ‘object’ op zichzelf is. Welke informatie bevat over een fysiek object (vandaar de isBeschrevenDoor relatie.) Hiermee scheiden van de informatie VAN het (fysieke) object met de informatie OVER het (fysieke) object.

**Comment by JochemMollema** [comment]
Definitie wordt uitgebreid.

**Comment by JochemMollema** [comment]
Een toelichting op het gebruik van de informatieobjecten wordt gegeven in de ReSpec-omgeving.
