### ISSUE TITLE
Aantal taal verbeteringen in IMBOR Vocabulair (van GreenpointAdviesPN)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#604]
Hierbij nog een paar taaldingen die opvielen in imborVoc_Collecties (is soms wellicht beetje muggenziften, maar goed als IMBOR een taal moet worden zijn toelichtingen heel belangrijk mijns inziens):
-	Toelichting van Datatype bevat een tikfout: “…gegevsntype…”
-	Toelichting van Domeinwaarde bevat een dubbel stuk tekst: “…die per organisatie verschillend kunnen zijn per organisatie”. Hier staat 2x “per organisatie”
-	Toelichting van Semantische relatie bevat een dubbele spatie: “…tussen  onderdelen…”
-	Toelichting van Semantische relatie bevat een beetje een kromme zin, m.n. door twee keer “…onderdelen…” te gebruiken. Kun je hier niet zeggen: “Registratie van de relaties die tussen onderdelen (objecttypen en informatieobjecten) onderling gelegd kan worden op basis van betekenis.”?
-	De term “onderdelen” wordt vaker gebruikt, maar niet gedefinieerd, behalve in de toelichting van Semantische relatie, waar het de groepering van Objecttype en InformatieObject blijkt te zijn
-	Zijn de toelichtingen in de tabel imborVoc_Collecties echt toelichtingen of definities? Het lijkt op, en ik zou pleiten voor, definities.

**Comment by JochemMollema** [comment]
Definities/toelichtingen aangepast, zie ook de ReSpec-omgeving voor de toelichting en definities.
