### ISSUE TITLE
Verwarring tussen termen Reëel object en ReëelObject

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#605]
Volgens imborKern_Klassenindeling is ReëelObject de parent van Reëel object en DiscreetObject. Maar de defininitie van DiscreetObject stelt dat dit is:
_"Reëel object dat bestaat uit een aaneengesloten hoeveelheid vormvaste materie, primair bijeengehouden door interne krachten (zwaartekracht of elektromagnetische kracht)."_

Moet dat niet zijn: "ReëelObject dat bestaat uit ..."?
Sowieso zijn de termen ReëelObject en Reëel object gemaakt om door de war gehaald te worden. Wellicht dat één van beide hernoemd kan worden?

**Comment by RiX012** [comment]
Dit is vreemd. Maar is een directe resultante van de NEN2660-2 en de NEN3610. Als we deze allebei willen blijven volgen moeten we het zo houden. 
Er zijn wel gesprekken gaande tussen beide partijen om dit beter af te stemmen.
