### ISSUE TITLE
Consultatie IMBOR 2021 of 2022 (aandachtspunt)

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#609]
Kijkend naar de uitnodiging valt me op dat deze niet strookt met de documenten en bijgevoegde documentatie. Zo wordt er over IMBOR 2021 gesproken en verwezen naar IMBOR 2021-10 terwijl we de IMBOR 2022 hebben ontvangen.
Dit betreft vooral ook de "ReSpec met de beschrijving van het model" ( wat een draft is

Als IMBOR in beheer gaat moet dit wel éénduidig zijn.

**Comment by RiX012** [comment]
Scherp, dankjewel. De URL zal 2021 blijven maar voor de rest is het aangepast. De URL zal namelijk gaan verhuizen naar een datumloze URL als de ReSpec uit de DRAFT status komt.
