### ISSUE TITLE
vakdiscipline Laadinfrastructuur !!

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#611]
In de acces data base is er een vakdiscipline  'laadinfrastructuur ' waaronder 7 objecttypes zijn opgenomen.

De vakdiscipline  'laadinfrastructuur' komt niet voor op de 'hoofdpagina ' waar ook de vakdisciplines zijn benoemd.

![IMBOR laadinfrastuctuur](https://user-images.githubusercontent.com/40396592/141780966-ed753ec0-78ea-499c-9d34-fc0890aef670.jpg)

**Comment by JochemMollema** [comment]
Vakdiscipline Laadinfrastructuur is tijdelijk aan IMBOR toegevoegd voor een project bij een gemeente, maar is niet meer als zoekingang aanwezig binnen de database.
