### ISSUE TITLE
Gebruik van enkelvoud of meervoud in benamingen verschijningsvormen

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#612]
**Issue toelichten**
Door heel IMBOR heen valt me op dat bij de verschijningsvormen: Type, type gedetailleerd etc.  vaak niet consequent gebruik wordt gemaakt van enkelvoudige of meervoudige benamingen. 
Voorstel is om dit aan te passen of alles meervoud of alles enkelvoud dan is de het model eenduidiger. 
Zie ook voorbeeld afbeelding over elementenverharding:
Type gedetailleerd: Betonplaten - Inritblok
Type: Straatbaksteen - Betonstraatstenen

**Eventueel een verbetervoorstel of eigen inzicht**
Voorstel is om dit aan te passen of alles meervoud of alles enkelvoud dan is de het model veel consistenter. 

![image](https://user-images.githubusercontent.com/80532038/142224982-9f2758bc-99af-4ed3-aa03-84180fd1b602.png)

**Comment by RiX012** [comment]
Overal enkelvoud (behalve bij groepen: zoals Vakdisciplines)
