### ISSUE TITLE
Objecttype: Onverhard Acces bevat 2x 'Open grond'

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#613]
**Issue toelichten**
Onder Onverhard komt in de Acces twee keer het Type 'Open grond' voor.

**Eventueel een verbetervoorstel of eigen inzicht**

![image](https://user-images.githubusercontent.com/80532038/142226118-b7c91301-c320-4b8d-91c8-80ad07fed4c3.png)

**Comment by JochemMollema** [comment]
1x mulchlaag verwijderd
