### ISSUE TITLE
Type: 'Bladmand' onder objecttype 'Afvalbak'

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#614]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Bladmanden kunnen nu niet geregistreerd worden in het IMBOR. 
Graag opnemen onder afvalbakken

**Beschrijf de oplossing die je voor je ziet**
Bladmanden kunnen een type zijn onder Objecttype Afvalbak.

**Wat voor alternatieven heb je overwogen?*
Onder hekwerk maar dat lijkt me niet logisch. Je wil het als punt object in de kaart zien.

**Meer context**
Definitie bladmand: Een mand of hekconstructie voor het inzamelen van uitsluitend bladafval in de herfst periode.
Ook wel 'bladkorf' genoemd.

*Issue ontdekt bij conversie van St. Anthonis

**Comment by JochemMollema** [comment]
Bladkorf is een type van een opslagbak.
