### ISSUE TITLE
Het zou helpen als dit issue/label hetzelfde heet als de consulatieversie... 2022...

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#615]
Ik moest 3x kijken of dit de juiste plek is om input te leveren voor de imbor2022 ontologie...

Verbetervoorstel template en label gelijk trekken met respec en rest vd communicatie

**Comment by RiX012** [comment]
Thanks inderdaad onhandig

**Comment by NielsHoffmann** [comment]
@RiX012 de link in de respec wijst ook niet naar de issues (https://github.com/Stichting-CROW/imbor/issues) maar naar de private repo waar imbor2022 in staat en de respec is slecht vindbaar...
