### ISSUE TITLE
rdfs:label (of skos:prefLabel) toevoegen bij de propertyshapes

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#616]
**Issue toelichten**
Als je de ontologie nu bekijkt via een editor of een 'visual viewer' (bv graph-explorer) dan krijg je voor de classes/nodeshapes keurig de preflabels te zien (als je dat instelt) maar voor de propertyshapes krijg je de guid... 

**Eventueel een verbetervoorstel of eigen inzicht**
sh:title ook opnemen in een label property zodat exploratief browsen een stuk gebruiksvriendelijker wordt.

**Comment by RiX012** [comment]
Is goed. `sh:title` vervangen door `skos:prefLabel`
