### ISSUE TITLE
documentatie/implementatie van 'referentiemodellen in LinkedData' (6.3) is mij onduidelijk

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#617]
**Issue toelichten**
Ik kan de rest van het model behoorlijk snel doorgronden, maar de gedachtegang en logica achter paragraaf 6.3 in de respec ontgaat me volledig.

**Eventueel een verbetervoorstel of eigen inzicht**

**Comment by RiX012** [comment]
Dit betreft inderdaad een wat ingewikkeld stuk. Hier wordt de relatie vastgelegd van IMBOR naar andere standaarden. Om dit generiek te houden hebben we alle standaarden waar we relaties naar leggen vooralsnog 'platgeslagen' naar `Objecttypen`, `Attribuut` en `Domeinwaarden`. Deze hebben we opgenomen in de graaf. Daarnaast hebben we een 'mapping element' aangemaakt waar alles tezamen komt (dus de 3 elementen uit het externe model en alle corresponderende IMBOR onderdelen).  Tezamen geeft het een relatief impliciet inzicht in de mapping. Later moet dit geupgrade worden naar een expliciete sterke semantische mapping. 

Wat betreft jou specifieke voorbeeld. We hebben gesteld dat het IMBOR Objecttype ‘Tunnelsegment’ een relatie heeft met het IMGEO ‘FunctioneelGebied’ + Attribuut bor-functie + Waarde ‘tunnelsegment’. Dit wordt vastgelegd op onderstaande “Mapping” element. (plus de rest van snippet)
![afbeelding](https://user-images.githubusercontent.com/56293445/153216378-9ae74da1-af16-44b2-95bf-9bc23014ae60.png)
