### ISSUE TITLE
Gebiedsindeling als eigenschap vormt een risico voor uitwisselbaarheid van gegevens

### ISSUE THREAD

**Issue by rhout-rws** [Stichting-CROW/imbor#618]
Bij reële objecten die worden geregistreerd met gebiedsindeling attributen is niet meer duidelijk of de begrenzing van het reëel object is beïnvloed door een virtuele ruimte. Is dat wel het geval dan wordt er afgeweken van NEN 2660 en NEN 3610 en is er geen sprake meer van een reëel object. Stel dat een stuk verharding wordt begrensd op een gemeentegrens, dan betreft het geen registratie meer van een reëel object. Het is immers niet meer alleen begrensd op basis van z'n fysieke begrenzing. Dit gaat direct ten koste van de uitwisselbaarheid van gegevens. Helemaal als verschillende partijen hier verschillend mee omgaan (de één begrenst op gemeentegrens, de ander op waterschap of gebiedstype en weer een ander begrenst niet op gebiedsindelingen)
Gebiedsindeling kunnen beter als zelfstandige objecttypen worden geregistreerd. Een gemeente is immers een ander objecttype dan een verharding en kent z'n eigen kenmerken,

**Comment by RiX012** [comment]
Correcte observatie. Gebieden ruimten worden nu ook volledig ondersteund in IMBOR. Modelmatig is dit dus op te lossen. 
Nadere toelichting opgenomen in ReSpec:
https://docs.crow.nl/imbor-2021/imbor-2021/#gebiedsindeling
