### ISSUE TITLE
Implementeer rollen voor enkele objecttypen

### ISSUE THREAD

**Issue by rhout-rws** [Stichting-CROW/imbor#619]
De top hiërarchie laat een aantal objecttypen zien als supertype van andere objecttypen, terwijl het eigenlijk rollen zijn. Bijv. "Beheerd object" en "Geo-object".
Zeker nu de top hiërarchie een poly hiërarchie is, zou het goed zijn deze concepten als rollen te implementeren. Een reëel object is geen type geo object, maar heeft slechts die rol wanneer er registratie van geo gegevens plaatsvindt.
Zo is ook een reëel object een type beheerd object, maar heeft het die rol wanneer een organisatie er beheer op uitvoert.
Niet beheerde reële objecten zijn nog steeds reële objecten. Dat komt nu niet in de hiërarchie tot uitdrukking.

**Comment by RiX012** [comment]
Rollen worden in de NEN2660-2 juist er uit geschrapt. Dat willen we hier dan ook volgen.
