### ISSUE TITLE
Besteknummer bij beheerobject

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#62]
Besteknummer is bij elk objecttype te verwachten en niet alleen bij het specifieke aantal objecten waar dit nu voorkomt. WISH: opnemen bij beheerobject
Omdat een object in meerdere bestekken opgenomen kan zijn moet dit wellicht als in dezelfde constructie als het memo veld hierbij zijn ook meerdere memo's mogelijk.

**Comment by RiX012** [comment]
Omdat momenteel de object - documentkoppeling nog onder de loep wordt genomen is dit nog niet gedaan. Deze wordt voorgelegd aan de community.

**Comment by RiX012** [comment]
Wordt opgelost via de nieuwe semantische relaties. In dit geval tussen Objecttype en Document (Bestek)
