### ISSUE TITLE
Definities top hiërarchie onevenwichtig en niet altijd heel sterk. 

### ISSUE THREAD

**Issue by rhout-rws** [Stichting-CROW/imbor#620]
In de top hiërarchie is duidelijk te zien dat definities verschillende herkomst hebben.  Er bij een aantal objecttypen gebreken voor:
-de definitie voegt niks toe aan de objecttypenaam, omdat de objecttypenaam weer terugkomt in de definitie en niet wordt toegelicht
-de definities bevatten overbodige (en geregeld verwarrende) zinsdelen. Dit is veel (maar niet uitsluitend) bij informatieobjecten het geval.
-de definitie omschrijft een activiteit in plaats van een objecttype
Een voorbeeld waar dit allemaal in samenkomt:
Bijv: Verkeersintensiteit:	 Het vastleggen (is activiteit en is overbodig) van de verkeersintensiteit (is objecttypenaam en legt dus niet uit wat verkeersintensiteit is) per prognosejaar bij een wegas.
Niet de gehele top hiërarchie is IMBOR, maar het zou mooi zijn als definities over de verschillende modellen consistenter en beter worden. Voor nu kunnen in ieder geval de suggestie om de IMBOR concepten na te lopen.
Onduidelijke definities leiden tot onduidelijke en vaak inconsistente data.

**Comment by RiX012** [comment]
Eens. Dit staat op de roadmap 2023 voor de inhoudelijke werkgroepen.

**Comment by RiX012** [comment]
#884 Zou dit grotendeels moeten behandelen

**Comment by RiX012** [comment]
Valt binnen de scope van #884
