### ISSUE TITLE
Teveel attributen bij verharding die de vastlegging van de begrenzing beïnvloeden

### ISSUE THREAD

**Issue by rhout-rws** [Stichting-CROW/imbor#621]
Het volgende speelt wellicht ook bij andere objecttypen:
Asfaltverharding kent behalve gebiedsindeling veel attributen die de te registreren begrenzing van het object beïnvloeden. Denk aan:
breedte, gebruiksfunctie, beheerder, belasting, op talud, type rijstrook, BGT functie, talud steilte, modaliteit, wegvaknummer, grondsoortnaam etc..
Als één van die eigenschappen wijzigt, dan zou er een nieuw object moeten worden geregistreerd. Dat kan tot een flinke versnippering van geregistreerde verhardingsvlakken leiden. Een versnippering die bij diverse eigenschappen niet eens te maken heeft met de fysieke kenmerken van de asfaltverharding zelf (denk bijv. aan wegvaknummer, grondsoortnaam, op talud, talud steilte).
Als organisatie ieder hun eigen keuze maken op basis van welke kenmerken ze asfaltverharding opknippen, dan leidt dat landelijk tot een onsamenhangende verhardingen registratie (idem bij gebiedsindeling).
Er moet duidelijk worden hoe dat voorkomen gaat worden.

**Comment by JochemMollema** [comment]
Toelichting gegeven, het belang van minimale datasets is hierbij onderstreept.
