### ISSUE TITLE
IMBOR lijkt een verzameling van standaarden

### ISSUE THREAD

**Issue by rhout-rws** [Stichting-CROW/imbor#622]
Voorbeeld: Bij asfaltverharding staan diverse attributen die allemaal met de functie te maken hebben:
gebruiksfunctie, BGT functie, BOR functie, modaliteit, type rijstrook, wegcategorie etc.

Hebben die attributen echt allemaal een eigen betekenis? Ik vermoed dat er inhoudelijke overlap in zit en dat hier ontdubbeling en betere onderlinge structurering van eigenschappen mogelijk is.
Door dit soort voorbeelden lijkt IMBOR vooral een verzameling van alle gehanteerde eigenschappen in IMBOR en andere standaarden weer te geven. IMBOR lijkt daarin niet te structuren of te kiezen en zichzelf tot een hanteerbare standaard vormen.
Wellicht ben ik niet voldoende bekend met de doelen van IMBOR en de implementaties tot nu toe. Zie ik iets over het hoofd? Dan hoor ik het graag.

**Comment by RiX012** [comment]
Voor een deel klopt dit ook. IMBOR is gebaseerd op een aantal standaarden en op de inhoud van de meeste beheerpakketten in gemeente en provincieland. Daarmee is het voor een deel een samen geraapte verzameling. Daar is een ook nog nieuwe kennis aan toegevoegd vanuit werkgroepen en heel veel ontdubbeld. Overlap zal er zeker zijn. Intentie was vooral om compleet te zijn, vanaf 2022 worden werkgroepen opgericht om per discipline kritischer en eenduidiger te zijn.
