### ISSUE TITLE
relaties IMBOR en KOR2018

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#625]
Voor de consultatie van IMBOR2022 heb ik **goed** nieuws te melden voor het onderdeel schouwen volgens Beeldkwaliteit CROW volgens de KOR2018.

Ook deze nieuwe versie 2022 van IMBOR heeft een sterke relatie met KOR2018. En dat is goed nieuws!
Want er is namelijk een eenduidige en uniforme mapping beschikbaar gesteld door het CROW tussen de IMBOR-objecten en de KOR2018-beeldmeetlatten. Die relatie is goed uitgewerkt.

Hierdoor kan software (dus ook Obsurv) veel automatische ondersteuning bieden, onder andere in de analyse of er binnen een te inspecteren meetlocatie wel of geen relevante objecten zijn voor de beeldmeetlatten van die schouwronde.
Dit heeft daardoor als voordeel dat de inspecteur direct veel inzicht krijgt o.a. in zijn werkvoorraad en het inspectieproces veel efficiënter kan doorlopen.

Ik zou graag zien dat alle IMBOR-relaties net zo sterk worden als deze!

Sweco

**Comment by HarroVerhoeven** [comment]
Bedankt voor dit compliment, Ernst! Fijn om ook zulke feedback te ontvangen. Maar ook alle kritische feedback wordt zeer gewaardeerd hoor!

**Comment by RiX012** [comment]
Noot is dat de KOR wel herzien en opnieuw gemodelleerd word komende ja(a)r(en). Dan moet dit ook strak gehouden worden.
