### ISSUE TITLE
Gebruik van sh:class voor relaties

### ISSUE THREAD

**Issue by WouterLubbers** [Stichting-CROW/imbor#626]
Het vastleggen van relaties op een klasse (hasPart, performs, isDescribedBy) door middel van sh:class levert problemen op in de praktijk. Een sh:class legt namelijk het type van alle waarden vast die deze relatie gebruiken. Het is natuurlijk mogelijk dat een object meerdere onderdelen heeft, meerdere functies vervult of door meerdere documenten beschreven wordt. In dat geval krijg je met sh:class altijd validatie-problemen: je stelt namelijk twee incoherente eisen aan instanties van een klasse, waardoor je altijd één van de twee eisen overtreedt.
Neem als voorbeeld 'geluidsscherm', dat twee performs relaties kent (afschermen en beperken van geluidshinder). De triple 'ex:Geluidsscherm_1 nen2660:performs ex:BeperkenVanGeluidshinder_1' zou een validatiefout geven, omdat 'ex:BeperkenVanGeluidshinder_1' geen instantie is van 'Afschermen'.

In plaats van het directe sh:class kun je sh:qualifiedValueShape [ sh:class imbor:Afschermen ] gebruiken.

**Comment by RiX012** [comment]
@MichelBohms Hebben jullie deze kwestie in de NEN2660-2 groep besproken. Wij hebben namelijk het idee dat we hier de NEN2660-2 helemaal volgen, maar @WouterLubbers heeft inderdaad een punt dat de validatie hier op mis zou gaan.

**Comment by MichelBohms** [comment]
sh:class doet hetzelfde als rdfs:range.
als je ongewenste inconsistentie krijgt dan heb je de range/class niet goed gekozen (te beperkt)
je moet de range dan op een generiekere klasse leggen

de oplossing qualifiedvalue kan ook want dan zeg je "kan" in die range zitten , niet perse....vgl met schema.orgs varianten van domain en range....

maar mn voorkeur blijft standaard class gebruiken op meer generieke klasse (eventueel via unions/sh:or)

**Comment by WouterLubbers** [comment]
Zeker voor decomposities is het niet mogelijk om de class anders/specifieker te definiëren. Een ding bestaat nu eenmaal uit meerdere onderdelen. Het gebruik van sh:or is helaas ook niet mogelijk. Stel, je hebt een klasse auto waarvoor je vast legt dat deze minimaal 1 motor en 3 wielen moet hebben:
```
ex:Car
	a owl:Class , sh:NodeShape ;
	sh:or (
        [
          sh:property [
            sh:path bs:hasPart ;
	    sh:class ex:Engine ;
            sh:minCount 1 ;
          ] ;
	]
	[
          sh:property [
            sh:path bs:hasPart ;
	    sh:class ex:Wheel ;
            sh:minCount 3 ;
          ] ;
        ]
    ) ;
.
```
Als je nu een instantie van Auto vastlegt met 4 wielen en een motor, voldoe je nog steeds aan geen van beide delen van de sh:or (het engine-deel niet omdat er ook wielen zijn vastgelegd en vice versa). Enige optie is dus een sh:qualifiedValueShape met qualified min/max count:
```
ex:Car
	a owl:Class , sh:NodeShape ;
	sh:property [
		sh:path bs:hasPart ;
		sh:qualifiedValueShape [ sh:class ex:Engine ] ;
		sh:qualifiedMinCount 1 ;
	] ;
	sh:property [
		sh:path bs:hasPart ;
		sh:qualifiedValueShape [ sh:class ex:Wheel ] ;
		sh:qualifiedMinCount 3 ;
	] ;
```

**Comment by MichelBohms** [comment]
Als je hier klein vb en/of uitleg over hebt, heel graag….




Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RiX012** [comment]
Geeft dit genoeg toelichting?
https://docs.crow.nl/imbor-2021/imbor-2021/#gekwalificeerde-waardeshapes
