### ISSUE TITLE
Kernmodel definities

### ISSUE THREAD

**Issue by WouterLubbers** [Stichting-CROW/imbor#627]
Ik zie in de 4 bestanden geen formele definitie van de verschillende imborKern attributen/klassen. Ik zou bijvoorbeeld verwachten dat imborKern:typeLijst geclassificeerd is als een owl:DatatypeProperty (of rdf:Property), inclusief een label, definitie en/of scopeNote.

Het zou mooi zijn om het kernmodel als een los klein bestand te publiceren.

**Comment by RiX012** [comment]
Goed punt @WouterLubbers  voor een aantal doen we dit wel. Deze zitten 'verwerkt' in de verschillende files. Namelijk `imborDef:bovenliggendeWaarde`, ' imborDef:imborEenheid' en 'imborDef:klasseType'. Maar we hebben dit niet voor alles gedaan. Vandaar dat we dit nog zullen doen voor:

- imbor:typeLijst
- ref:levensfaseTypering
- ref:imborAttribuutDomeinwaarde
- ref:imborObjecttype
- ref:Informatiemodel
- ref:RefAttribuut
- ref:refAttribuutDomeinwaarde
- ref:RefDomeinwaarde
- ref:RefMapping
- ref:refObjecttype
- ref:RefObjecttype

En daarnaast zullen we deze apart publiceren als 'IMBOR aanvullend metamodel'

**Comment by redmer** [comment]
Verwerkt met https://github.com/Stichting-CROW/imbor-2021/commit/5373ea4d5d66e45e8705eff20433553b319fb79b (nog niet zichtbaar).
