### ISSUE TITLE
Splitsing vocabulaire - ontologie

### ISSUE THREAD

**Issue by WouterLubbers** [Stichting-CROW/imbor#628]
De splitsing tussen vocabulaire en ontologie voelt wat overbodig. Er zit veel overlap in de twee (beiden bevatten dezelfde namen bijv.), waardoor het vocabulaire vooral een afgeslankte versie van de ontologie lijkt. Op zich hoeft dit natuurlijk geen probleem te zijn, maar voorwaarde is dan wel dat de twee 'views' op basis van dezelfde brondata opgebouwd worden. Anders is er een risico dat er tegenstrijdige definities of namen ontstaan.

**Comment by RiX012** [comment]
Dit is inderdaad overbodig, maar wel op dezelfde bron opgebouwd. In eerste instantie hadden we dit niet. Maar in de laatste versie van de NEN2660-2 is dit (volgens mij op aanraden van Sander :) ) er in geplaatst. Hier volgen we dus wederom alleen maar de NEN2660-2
