### ISSUE TITLE
Aspecten modelleren via InformationObjects

### ISSUE THREAD

**Issue by WouterLubbers** [Stichting-CROW/imbor#629]
Het deels modelleren van kenmerken via een InformationObject kan wat lastiger zijn om te bevragen met een query (aangezien je met meerdere patronen rekening moet houden). Sommige kenmerken zitten direct vast aan het object, terwijl anderen in een soort 'groep van kenmerken' zijn vastgelegd.

Uiteindelijk is het een modelleerkeuze en kan de huidige aanpak juist handig zijn als je de informationobjects wilt gebruiken als losse invulformulieren. Zolang het aansluit op het gewenste gebruik kan dit issue genegeerd worden 🙂

**Comment by RiX012** [comment]
Jep, zijn we met je eens. We hebben specifiek hiervoor gekozen omdat we verwachten dat deze zaken op termijn 'strakker' gemodelleerd gaan worden wanneer we beter met andere standaarden kunnen samenwerken. Het is wellicht zelfs een beetje oneigenlijk gebruik van het `InformationObject`, maar we gaan bij de implementatie waarschijnlijk merken of 'men' het snapt.
