### ISSUE TITLE
Afbeelding op beheerobject niveau

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#63]
Afbeelding/foto is bij elk objecttype te verwachten en niet alleen bij het specifieke aantal objecten waar dit nu voorkomt. WISH: opnemen bij beheerobject
Omdat een object in meerdere afbeeldingen kan hebben moet dit wellicht als in dezelfde constructie als het memo veld hierbij zijn ook meerdere memo's mogelijk.
Daarnaast wordt ook de term Foto gebruikt in IMBOR. kunnen we de eenduidige term afbeelding hiervoor gebruiken?

**Comment by RiX012** [comment]
In het beheersysteem kan dit opgelost worden via een object-documentkoppeling. Object-documentkoppeling uniformeren in de volgende versie van IMBOR.
De koppeling tussen object en document wordt momenteel onder de loep genomen.

**Comment by RiX012** [comment]
Wordt opgelost via de nieuwe semantische relaties. In dit geval tussen Objecttype en Document (afbeelding)
