### ISSUE TITLE
imborattribuutid 15006 onbekend in tabel refmodel_minimaledatasets

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#630]
In de tabel [refmodel_minimaledatasets] staan een aantal records met daarin waarde [15006] in kolom [imborattribuutid]. Deze waarde is nergens terug te vinden. Bijvoorbeeld in imborvoc_termen. Lijkt een foutieve of oude waarde te zijn. Alle andere records hebben een waarde die wel terug te vinden in [imborvoc_termen].

Verise IMBOR:
consultatieverise IMBOR 2022 Access.

**Comment by JochemMollema** [comment]
Het is niet duidelijk welk attribuut ontbreekt. Ook uit de vorige (tussen)versies blijkt dit niet.
