### ISSUE TITLE
Type detail 'Steenslagasfaltbeton' toevoegen onder 'Dichte deklagen'

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#631]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Het type gedetailleerd 'Steenslagasfaltbeton' mist onder objecttype 'Asfaltverharding' en type 'Dichte deklagen'

**Beschrijf de oplossing die je voor je ziet**
Toevoegen van type gedetailleerdbonder objecttype 'Asfaltverharding' en type 'Dichte deklagen'

**Wat voor alternatieven heb je overwogen?*

**Meer context**
 'Steenslagasfaltbeton'  wordt ook wel STAB genoemd

https://auto-en-vervoer.infonu.nl/verkeer/62861-asfaltopbouw-en-de-meestgebruikte-soorten.html

**Comment by JochemMollema** [comment]
Steenslagasfaltbeton als type gedetailleerd van dichte deklagen toegevoegd.
