### ISSUE TITLE
Attribuut 'domein' moet worden toegevoegd op 'GeoObject'

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#633]
Dit is een verplicht item uit de NEN3610 (net zoals identificatie) 
![afbeelding](https://user-images.githubusercontent.com/56293445/145411277-ad3377c6-2352-4928-ad9c-f0344657293b.png)
![afbeelding](https://user-images.githubusercontent.com/56293445/145411305-4aba59e9-8e42-441a-8f21-eda367ad4fa3.png)

**Comment by JochemMollema** [comment]
Het attribuut domein is aa de klasse Geo-object toegevoegd.
