### ISSUE TITLE
Tijdlijn geldigheid en Tijdlijn registratie in lijn brengen met de NEN3610

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#634]
![afbeelding](https://user-images.githubusercontent.com/56293445/145412382-c35b1c12-f4d7-4f48-a158-edd29062bf1f.png)
![afbeelding](https://user-images.githubusercontent.com/56293445/145412441-a863bbf1-6edc-45ba-aa3d-bb8aac9706e4.png)
![afbeelding](https://user-images.githubusercontent.com/56293445/145412551-3f444da9-a0d7-4d4f-8032-04680eb931aa.png)

**Comment by RiX012** [comment]
Voorstel @JochemMollema : 

- `beginGeldigheid` ter vervanging van `ingebruik tot` (inclusief term, definitie en multipliciteit)  
- `eindGeldigheid` ter vervanging van `ingebruik van` (inclusief term, definitie en multipliciteit)
- `tijdstipRegistratie` ter vervanging van `objectbegintijd` (inclusief term, definitie en multipliciteit)
- `eindRegistratie` ter vervanging van `objecteindtijd` en `eindregistratie` (inclusief term, definitie en multipliciteit)

**Comment by JochemMollema** [comment]
Het attribuut ingebruik van is gewijzigd in beginGeldigheid. 
Het attribuut ingebruik tot is gewijzigd in eindGeldigheid.
Het attribuut objectbegintijd wordt vervangen door tijdstipRegistratie.
Het attribuut objecteindtijd wordt vervangen door eindRegistratie.
