### ISSUE TITLE
Kleine wijziging in semantisch model NEN3610 doorvoeren

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#635]
![afbeelding](https://user-images.githubusercontent.com/56293445/145427632-2575e098-7200-4940-aee6-bdb392643beb.png)

**Comment by RiX012** [comment]
@JochemMollema 

Ik heb het reeds verwerkt in de documentatie dus je kunt het opzoeken in https://docs.crow.nl/imbor-2021/imbor-2021/#imbor-top-hierarchie
Komt er op neer dat er een extra hierarchie is toegevoegd (Verkeerruimte), een extra element (Luchtvaartruimte) en dat Waterruimte hernoemt is naar Waterverplaatsingsruimte

**Comment by JochemMollema** [comment]
Aanpassingen in de klassenindeling van de ruimte zijn doorgevoerd.
