### ISSUE TITLE
BeheerWijzer: opmerking over soortnamen solitairen en heesters

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#638]
De soortnaam wordt nu als informatie-object geregistreerd. Waarbij de datum nu automatisch wordt gevuld met datum invoer. Deze datum wordt op dit moment ook nog verwerkt vanuit bijvoorbeeld excellijsten. Is het dan toegestaan om deze datum handmatig te overschrijven?

Het is het nu mogelijk om solitairen als zelfstandig grafisch object te verwerken. In organisaties waar dit niet als grafisch wordt verwerkt komen een paar opties naar voren om het alleen administratief te verwerken. Momenteel is dit bij een klant verwerkt per soort en zou het wenselijk zijn per soort in de soortnamenlijst ook aan te geven dat het om een solitair gaat bij een nieuw attribuut met attribuutsoort Ja/nee toe te voegen. Het aantal kan dan bij hoeveelheid worden verwerkt. Het is niet de insteek om alle solitairen grafisch te gaan verwerken. Het kan ook door een ja/nee veld toe te voegen bij struiken, maar dan is niet bekend welke soort de solitair betreft.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Ten behoeve van het `ObjectType` `Solitaire plant` wordt voorgesteld aan het `InformatieObject` `Soortnaam groenobject` een booleaans attribuut toe te voegen t.b.v. filtermogelijkheden.

Gezien het datatype moet het mogelijk zijn in het veld `registratiedatum` gegevens uit de huidige, non-IMBOR-modellering op te nemen. Dit is een implementatiekwestie voor een softwarepakket.

Het voorstel is om de tweede suggestie af te wijzen, omdat het in principe een redundant gegeven is. Dit blijkt uit een beschouwing van de modellering: `Solitaire plant :: isBeschrevenDoor :: Soortnaam groenobject` met `Soortnaam groenobject :: soortnaam`. Het is een keuze van de IMBOR-gebruiker om de werkelijk bestaande `Solitaire plant`en niet allemaal geometrisch op te nemen. Het faciliteren van een achterdeur in `Soortnaam groenobject` is ongewenst omdat het binnen hetzelfde model meerdere registratievormen oplevert, wat modelmatig bezien een onzuiverheid is.
