### ISSUE TITLE
BeheerWijzer: vragen en opmerkingen over het registreren van type afval binnen IMBOR

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#639]
Ik mis nog een aantal onderdelen, maar mogelijk kijk ik op de verkeerde plek.
•	Type afval
o	Domeinwaarden
o	1:n
•	Kleur glas
o	Als attribuut
o	1:n

1:n als er geen onderscheid wordt gemaakt in compartimenten.

Vragen:
Waar kunnen de volgende waarden bij type afval opgenomen worden? Volgens mij komen deze nu niet voor in IMBOR. Daarnaast nu ook als 1:1, maar volgens mij is 1:n wenselijk.
•	KEA (kleine elektrische apparaten)
•	PMD (plastic, metaal en drinkkarton)
•	Batterijen

Daarnaast wordt er onderscheid gemaakt bij glas in kleur glas. Waar staat deze als attribuut in IMBOR? Ook graag als 1:n beschikbaar. 
•	Bont
•	Bruin
•	Groen
•	Wit (zuiver wit; doorschijnend)

Als bovenstaande niet aanwezig is graag als voorstel indienen? Bovenstaande is nog niet in detail met de klant besproken, maar mogelijk kan dit nog mee in de consultatie.

**Comment by GreenpointAdviesPN** [comment]
Is PMD ook al toegevoegd? Die was wel gevraagd, maar nog niet door Jochem genoemd.

**Comment by wjtmollema** [comment]
**Actie**
`PMD` toevoegen aan `AfvalbakTypeAfval` en `ContainerTypeAfval`.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Er wordt om toestemming verzocht deze issue te mogen sluiten.
