### ISSUE TITLE
Eenduidig gebruik jaaronderhoud, reparatie, conserveren

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#64]
Bij diverse objecten (bijv Leiding) worden verschillende 'Jaar' kenmerken onderscheiden zoals 
Jaar onderhoud,  jaar reparatie, jaar conserveren
Omdat repareren en conserveren ook een vorm van onderhoud is kan dit tot onduidelijkheid leiden. 
Eenduidig gebruik van deze termen is gewenst.

**Comment by RiX012** [comment]
Dit is een bekend issue. We werken een oplossingsrichting uit en leggen dit voor aan de community.

**Comment by JochemMollema** [comment]
Verwerkt binnen de klasse Onderhoud.
