### ISSUE TITLE
Hengelo: basisgegevens voor het registreren van projecten in IMBOR

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#641]
Objectnummer	Tekst	Vrij invoerveld
Objectnaam	Tekst	Vrij invoerveld
Projectstatus	Tekst	Suggestielijst
Jaar van uitvoering	Numeriek	Vrij invoerveld
Jaar start voorbereiding	Numeriek	Vrij invoerveld
Memo	Memo	Vrij invoerveld
Mutatiedatum	Datum	Waarde wordt automatisch bepaald
Wijk	Tekst	Waarde wordt automatisch bepaald
Buurt	Tekst	Waarde wordt automatisch bepaald
OpenbareRuimte	Tekst	Waarde wordt automatisch bepaald
Projectleider	Tekst	Vrij invoerveld
Projecttype 	Tekst	Suggestielijst
		
		
Suggestielijst projectstatus		
Initiatief		
Concept		
Definitief		
In uitvoering		
Uitgevoerd		

**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**

**Beschrijf de oplossing die je voor je ziet**
Een beknopte en heldere beschrijving van je wilt zien gebeuren.

**Wat voor alternatieven heb je overwogen?*
Een beknopte en heldere beschrijving van alternatieve oplossingen die je hebt overwegen.

**Meer context**
Voeg andere context of bijvoorbeeld schermfoto's toe. Denk eraan, deze melding is openbaar.

**Comment by RiX012** [comment]
Lijkt mij iets voor een inhoudelijke groep

**Comment by JochemMollema** [comment]
Bij project zijn de volgende (basis)gegevens toegevoegd:
- Projectstatus met enumeratie
- Projecttype --> type wordt als attribuut toegevoegd in de volgende versie wanneer ook een typelijst  voor de projecten beschikbaar is.
- Uitvoeringsjaar
- Startjaar

De naam van de projectleider is vooralsnog niet toegevoegd, dit i.v.m. AVG richtlijnen.
Alle andere voorgestelde gegevens zijn al beschikbaar rechtsstreeks bij het object of via een gekoppeld informatieobject.

Verdere uitwerkeing van het objecttype Project in een volgende versie.
