### ISSUE TITLE
Definitie 'heeft deel' rijmt niet met semantischerelaties tabel

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#649]
De definitie van semantische relatie 'heeft deel' is: "Het object aan de linkerkant van de relatie maakt deel uit van het object aan de rechterkant van de relatie." Dit ruimt niet met de Access tabel imborkern_k_objecttypensemantischerelaties, waarin je op basis van deze definitie bijv. zou lezen: "Viaduct maakt deel uit van Dek".
"Viaduct heeft deel Dek", zou kloppen als de definitie zou zijn in de trant van "Het object aan de linkerkant van de relatie bestaat (o.a.) uit het object aan de rechterkant van de relatie."

**Comment by RiX012** [comment]
Goed punt.

@JochemMollema de relaties nemen we direct over uit de NEN2660-2. Daarmee moeten ook de definities gelijk blijven. Graag de definities overnemen uit de volgende links. Wat mij betreft niet vertaald, indien toch nodig dan letterlijk vertaald.

`heeftDeel` https://w3id.org/nen2660/def#hasPart
`isVerbondenMet` https://w3id.org/nen2660/def#isConnectedTo
`isBeschrevenDoor` https://w3id.org/nen2660/def#isDescribedBy
`bevat`https://w3id.org/nen2660/def#contains
`heeftBegrenzing` https://w3id.org/nen2660/def#hasBoundary
 `voertUit` https://w3id.org/nen2660/def#executes

**Comment by JochemMollema** [comment]
Definities aangepast.
