### ISSUE TITLE
EindeGarantiePeriode voor meer objecttypes

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#65]
EindeGarantiePeriode is er ook voor bomen. Ik verwacht ook voor beplanting/planten mogelijk zelfs voor andere groenobjecten

**Comment by RiX012** [comment]
Leggen we voor aan community.

**Comment by JochemMollema** [comment]
Verwerkt via klasse Waarde. Veel objecttypes hebben de klasse Waarde gekregen.
