### ISSUE TITLE
Commentaar IMBOR-LD (MichelBohms)

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#651]
3.1 Niet volgens 2660, wel volgens MIM
 
3.2 Ok, ik begrijp nu 2660-2 link alleen op top level niveau, niet op meta/taal/binding-niveau.
(ben wel benieuwd naar code-implicaties dan…later)
 
3.2 Misschien betere uitleg van een logisch IM? Is het een raamwerk?
 
3.2 multiplicity: kun je ook gewoon cardinality noemen en dan specifiek min en max cardinality
 
4.1.1 ter info: er vind nog afstemming plaatse van de 2660-1 defs (zoals hier) en de 2660-2 defs.
 
4.1.2 no3: niet het MM/taal lijkt het, tot nu toe alleen top level model?
 
4.1.3 ‘performs’ is in de afstemming met deel 1 recent gewijzigd in ‘executes’ (afgestemd met mick baggen)
 
(Denk niet relevant maar ook: ChemicalBonding > ChemicalCompound)
 
Algemeen: door de links/refs (op zich mooi) worden alle meervouden enkelvoud. Soms wat verwarrend.
 
5.1.2.1 mbt:
“Speciaal geval is ook de kolom KlasseType. Deze is gekoppeld aan de IMBORGUID zoals hiervoor vermeld. KlasseType geeft aan of een IMBOR concept geïnstanteerd kan worden (Concreet) of niet (Abstract).”
 
Kan dit niet op standaard wijze via shacl?
Zag nog: https://www.w3.org/2014/data-shapes/track/issues/78
Zal holger eens vragen.
 
5.2 linked data (cq 2660 meta/taal) nu gepositioneerd als fysiek datamodel. Dat doet denk ik LD tekort. Het is wel degelijk in eerst instantie conceptueel/logisch (en ja ook fysiek bij keuze format/serialisatie).
 
Fig7: niet echt taalbinding. Vakdiscipline rdf:type rdfs:Container is bv ok maar Attribuut rdf:type rdf:Property is erg indirect. Eigenlijk zou je eigen MM moete mappen op 2660 MM denk ik.
 
Bv imborKern:Klass….is dit nu een metaconcept of een generiek concept (de meest generieke ibor klasse)?
 
5.2.3 “Ook wel…..” discreet object is maar beperkte subset van fysiek object….
 
5.2.4 Waar hangt Vakdiscipline in het toplevel? Of MM-iets? Valt het niet onder MM Object?
 
5.2.4.1 Met het ….zin loopt niet.
 
5.2.4.3 die 2 eigen metazaken (Attribuut en KlassAttribuut) zijn niet helder. Wijkt af van 2660?
 
6.1.1 Noot: maak dat begin 2022
 
6.1.3 punt 1: versimpelen naar “ …tussen het Begrippenkader en het Kernmodel”
 
6.1.6 zeg ook iets over BGT (instantie IMgeo)
 
6.1.12 eenheden en waarden? Niet eenheden en grootheden?
 
Noem hier nog misschien de licensievorm (CC BY).
 
9 geen specificatie/planning/programmeringfase? Waar worden requirements gespecificeerd?
 
9 D lijkt vreemde eend in OAGB bijt?
 
Referenties waar zijn de normatieve referenties?
 
CODE (turtle)
 
1-vocabulair
 
•	Ik mis skos import (daarna past te browsen in TBC)
•	Ik mis iets als:
https://.../skos/term
  a skos:ConceptScheme ;
en daarmee ook graph-uri
 
•	Prefix imborVoc noemen we in nen2660 nen2660-term
 
2-ontology
•	Ik mis iets als:
https://.../skos/term
  a owl:Ontology ;
en daarmee ook graph-uri
 
•	Check
 
Ik zie bij bv:
https://data.crow.nl/imbor/def/3a04ed3f-1a4a-462c-a979-0c9a92cc1e42
 
m3
maar er werd toch van QUDT gebruik gemaakt?
 
Ik mis imports
 
3-Domeinwaarden
 
•	Ik mis ontology / imports
 
 
4-addenda
 
•	Waarom trig? Kan niet in 1 .ttl?
•	Opent niet goed in TBC, waarschijnlijk door missende owl:Ontology (opent in tekst editor)
 
Bij onduidelijkheden kan ik nader toelichten,

**Comment by RiX012** [comment]
> 3.1 Niet volgens 2660, wel volgens MIM

@MichelBohms kun je deze nader toelichten. Doen we hier iets conflicterend aan de NEN2660-2? In principe gaat het er ons om dat we het Begrippenkader scheiden van de rest en als SKOS Vocabulaire kunnen distribueren.

**Comment by RiX012** [comment]
> 3.2 Ok, ik begrijp nu 2660-2 link alleen op top level niveau, niet op meta/taal/binding-niveau. (ben wel benieuwd naar code-implicaties dan…later)
> 
> 3.2 Misschien betere uitleg van een logisch IM? Is het een raamwerk?

Ja dit is niet handig. HIer zijn ook uitgebreide discussies met MIM-ers over geweest. Bottom line is dat het niet correct is om dit IMBOR-metamodel in MIM uit te drukken. Maar dat de ontologie zelf een logisch informatiemodel is. We gaan dit aanpassen. Er is hier echter nog wel onduidelijkheid/een mismatch hoe de NEN2660-2 (taalbinding) en het MIM zich verhouden. Dit gaan we apart bespreken.

**Comment by MichelBohms** [comment]
Ik bedoelde
3.1. is helemaal en alleen MIM
(of pakt dit in de skos binding hiervan exact hetzelfde uit als nen2660-2?)



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by MichelBohms** [comment]
Ok, helder
Belangrijk punt

The proof is in the binding…

Misschien komen mim en 2660 op zelfde uit na binding….



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RiX012** [comment]
> Ik bedoelde 3.1. is helemaal en alleen MIM (of pakt dit in de skos binding hiervan exact hetzelfde uit als nen2660-2?)

Dit hebben we op de nieuwe ReSpec inderdaad aangepast. Meer in lijn met SKOS

**Comment by RiX012** [comment]
> 3.2 multiplicity: kun je ook gewoon cardinality noemen en dan specifiek min en max cardinality

We hebben hier Joeri van Es (Geonovum / MIM) gevolgd die beschrijft dat de Multipliciteit een set van Kardinaliteiten is. De discussie hierover wordt inderdaad op alle niveaus gevoerd.

**Comment by RiX012** [comment]
> 4.1.1 ter info: er vind nog afstemming plaatse van de 2660-1 defs (zoals hier) en de 2660-2 defs.

Gaan we herzien zodra NEN2660 definitief beschikbaar komt.

**Comment by RiX012** [comment]
> 4.1.2 no3: niet het MM/taal lijkt het, tot nu toe alleen top level model?

We gebruiken de NEN2660-2 Praktisch toplevelmodel EN de NEN2660-2 taalbinding. Daarnaast wordt in de NEN2660-2 ook de relatie naar de NEN3610 gelegd op begrippenniveau (semantiek van relaties wordt niet beschreven). Wij hebben dat hier geïnterpreteerd/geïmplementeerd als `rdfs:subClassOf` relaties.

**Comment by RiX012** [comment]
> 4.1.3 ‘performs’ is in de afstemming met deel 1 recent gewijzigd in ‘executes’ (afgestemd met mick baggen)

Passen we aan

**Comment by MichelBohms** [comment]
Ok, ter info, ligt nu bij nen voor editorial afronding. Publicatie begin “22.



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by MichelBohms** [comment]
Ok, maar op taallevel vooral mim zichtbaar. Dus hoe is dan de link mim versus 2660-2-taal



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RiX012** [comment]
> 5.1.2.1 mbt: “Speciaal geval is ook de kolom KlasseType. Deze is gekoppeld aan de IMBORGUID zoals hiervoor vermeld. KlasseType geeft aan of een IMBOR concept geïnstanteerd kan worden (Concreet) of niet (Abstract).”
> 
> Kan dit niet op standaard wijze via shacl? Zag nog: https://www.w3.org/2014/data-shapes/track/issues/78 Zal holger eens vragen.

Bedankt voor het antwoord van Holger. We gaan met de Productowner van IMBOR overleggen of we het ook zo willen afdwingen. Indien ja, gaan we DASH volgen.

**Comment by RiX012** [comment]
> Ok, maar op taallevel vooral mim zichtbaar. Dus hoe is dan de link mim versus 2660-2-taal

Dit hebben we inderdaad aangepast. Binnenkort zichtbaar in de ReSpec. We drukken alles uit in NEN2660-2 en voegen de MIM metaconcepten als 'extra' ontologie toe.

**Comment by MichelBohms** [comment]
Mooi!



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RiX012** [comment]
> 5.2 linked data (cq 2660 meta/taal) nu gepositioneerd als fysiek datamodel. Dat doet denk ik LD tekort. Het is wel degelijk in eerst instantie conceptueel/logisch (en ja ook fysiek bij keuze format/serialisatie).

Mee eens. Dit gaan we anders uitleggen. IMBOR is eigenlijk alleen een begrippenmodel + logisch informatiemodel. Het fysieke datamodel gebruiken we alleen om uit te leggen hoe we de ontologie distribueren.

**Comment by RiX012** [comment]
> Fig7: niet echt taalbinding. Vakdiscipline rdf:type rdfs:Container is bv ok maar Attribuut rdf:type rdf:Property is erg indirect. Eigenlijk zou je eigen MM moete mappen op 2660 MM denk ik.

Uitleg passen we aan door introductie van ons eigen metamodel (komt in 3.2)

**Comment by RiX012** [comment]
> 5.2.4 Waar hangt Vakdiscipline in het toplevel? Of MM-iets? Valt het niet onder MM Object?

Het is inderdaad een groepering. Dit staat naast Object.

**Comment by RiX012** [comment]
> 5.2.4.3 die 2 eigen metazaken (Attribuut en KlassAttribuut) zijn niet helder. Wijkt af van 2660?

We hebben inmiddels het IMBOR 'Metamodel' expliciet gemaakt in de ReSpec. De opzet daarvan wijkt inderdaad af van de NEN2660-2 (en ook van MIM), maar in de LinkedData versie zorgen we middels een ETL-pipeline dat het er correct volgens de NEN2660-2 taalbinding uit komt. 
We hebben een IMBOR 'Metamodel' nodig om dat vanuit "legacy dingen" (zoals het onderscheidt tussen `Klasse` en `Objecttype` en het feit dat bijvoorbeeld een `Eenheid` aan een combinatie van Attribuut en Klasse hangen) nu eenmaal zo IMBOR zaten/zitten. 
Kortom, de (LinkedData) eindgebruiker zal niks te maken hebben met dat metamodel, maar volgt volledig de NEN2660-2.

**Comment by MichelBohms** [comment]
Ok!



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by MichelBohms** [comment]
Klinkt helemaal goed!



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RiX012** [comment]
> • Prefix imborVoc noemen we in nen2660 nen2660-term

@MichelBohms Bedoel je dat we `imborVoc` zouden moeten vervangen door `imbor-term`?

**Comment by RiX012** [comment]
> Ik zie bij bv: https://data.crow.nl/imbor/def/3a04ed3f-1a4a-462c-a979-0c9a92cc1e42
> 
> m3 maar er werd toch van QUDT gebruik gemaakt?

Klopt. Dit is ook legacy. De IMBOR Eenheden worden netjes vertaald naar QUDT en deze 'IMBOR eenheden' zitten er als legacy literals bij.

**Comment by MichelBohms** [comment]
Idd
Klein dingetje maar misschien goed om standaard te houden…



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by MichelBohms** [comment]
Ok!



Dr. ir. H.M. (Michel) Bohms
Scientist Specialist
Structural Reliability

T +31 (0)88 866 31 07
M +31 (0)63 038 12 20
E ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RiX012** [comment]
> 6.1.12 eenheden en waarden? Niet eenheden en grootheden?

Klopt. Dankje

**Comment by RiX012** [comment]
> 9 D lijkt vreemde eend in OAGB bijt?

Dat is het ook zeker, maar zo is nu eenmaal dat onderzoek ingestoken. We hebben het daarom ook maar als 'informatief' addendum er in gestopt.

**Comment by RiX012** [comment]
> 9 geen specificatie/planning/programmeringfase? Waar worden requirements gespecificeerd?

Die is er inderdaad nog niet. Dat is onderdeel van de roadmap na de publicatie van IMBOR2022

**Comment by RiX012** [comment]
> 1-vocabulair
> 
> • Ik mis skos import (daarna past te browsen in TBC) • Ik mis iets als: https://.../skos/term a skos:ConceptScheme ; en daarmee ook graph-uri
> 
> • Prefix imborVoc noemen we in nen2660 nen2660-term
> 
> 2-ontology • Ik mis iets als: https://.../skos/term a owl:Ontology ; en daarmee ook graph-uri
> 
> • Check
> 
> Ik zie bij bv: https://data.crow.nl/imbor/def/3a04ed3f-1a4a-462c-a979-0c9a92cc1e42
> 
> m3 maar er werd toch van QUDT gebruik gemaakt?
> 
> Ik mis imports
> 
> 3-Domeinwaarden
> 
> • Ik mis ontology / imports
> 
> 4-addenda

We gaan de benodigde `imports` toevoegen.

**Comment by RiX012** [comment]
@MichelBohms we hebben alles verwerkt in de ReSpec en de turtle bestanden. Indien je er nog eens naar wilt kijken, laat maar weten dan stuur ik ze op.

**Comment by MichelBohms** [comment]
Ik check ff of dit binnen adam-werk kan vallen bij ronald bergs




Michel Böhms
Data Scientist
Unit Buildings, Infrastructure & Maritime


Mobile +31 630381220
E-mail  ***@***.******@***.***>

Location<http://www.tno.nl/locations/DTS>



***@***.***<http://www.tno.nl/>

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.
