### ISSUE TITLE
Reinigende put, is een type bij rioolput, maar ook type gedetailleerd bij inspectieput

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#66]
Reinigende put, is een puttype bij rioolput, maar staat ook als type gedetailleerd onder type inspectieput.

**Comment by RiX012** [comment]
Klopt. Dit is niet correct uit GWSW gehaald. Reinigende put als type gedetailleerd onder type inspectieput gaan we weghalen.

**Comment by JochemMollema** [comment]
Inderdaad een dubbeling, alleen type van Rioolput. Afgehandeld.
