### ISSUE TITLE
EAN-code ook voor meubilair

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#67]
Een EAN-code kan ook gelden voor meubilair. Hier komt deze helaas niet voor, wel bij het Objecttypegroep Apparaat. Graag dus ook toevoegen bij Meubilair in elk geval bij speeltoestel. Mogelijk zijn er meer objectypegroepen waar deze bij hoort.

**Comment by RiX012** [comment]
Goedgekeurd. Doorgevoerd in 2020-08.
