### ISSUE TITLE
Locatie aanduiding

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#68]
Locatie aanduiding, is maar bij een aantal objecttypegroepen/objecttypes aanwezig.
Is daar een reden voor. Bijv..een kast wel, maar een put niet. terwijl dit soort gelijke objecten zijn.
Graag op juiste niveau (Beheerobject?) toevoegen.

**Comment by RiX012** [comment]
In tabel X_ObjecttypesAttributen Locatieaanduiding toegevoegd aan Scheiding, Bouwwerk, Meubilair en Put.
Tabellen aangepast.
