### ISSUE TITLE
Kenmerken bij transportleiding

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#69]
Bij transport leiding staat maar een beperkt aantal kenmerken. Verwacht wordt dat hier dezelfde kenmerken als rioolleiding voorkomen.
Type onderdeel staat bijv. niet bij transportleiding?

**Comment by JochemMollema** [comment]
Bij Transportleiding zijn alle GWSW-attributen opgenomen in IMBOR 2021.
