### ISSUE TITLE
Records uit [X_Objecttypes] zijn rdfs:subClassOf van alle records uit [X_Objecttypegroepen]

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#7]
... uitgezonderd 'Beheerobject';
... en te identificeren d.m.v. de bestaande PK <> FK link in Access.

Objecttypegroepen worden hiermee  de tweede laag in de taxonomie. Dit is wederom voor de overerving van eigenschappen. Momenteel worden de objecttypegroepen ook op deze manier   gebruikt in de IMBOR. Dat wil zeggen, in de User Interface (de formulieren) van IMBOR. De data (tabellen in IMBOR) stelt het anders. Maar omdat de eindgebruiker van IMBOR ons uitgangspunt is, wordt voor deze oplossing gekozen.

**Comment by redmer** [comment]
Het hoofdobject van de ObjecttypeGroep wordt gebruikt als superklasse van de objecten in de groep. Van de Objecttypegroep wordt nog wel de naam en leden geregistreerd, maar als een `skos:Collection`. Het GUID van de groep wordt wel aan het hoofdobject gekoppeld.
