### ISSUE TITLE
eenduidig gebruik BAG_ID

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#70]
BAG-identificatie. Wel bij een bouwwerk en een kast, maar niet bij een apparaat
WISH: BAG_ID toevoegen bij alle relevante objecten.

**Comment by RiX012** [comment]
Goed punt. We gaan oplossen doormiddel van een herclassificatie.

**Comment by RiX012** [comment]
Is BAG niet een extern model en daarmee een mapping op zijn plaats? Als we BAG_ID opnemen zijn er nog wel wat ID's te verzinnen toch?
Andere oplossing is het toevoegen van een 'klasse' BAG objecten, dit zijn dus objecten die een BAG_ID moeten hebben.

**Comment by JochemMollema** [comment]
Alle relevante objecttypen/klassen hebben een bag-identificatie binnen IMBOR
