### ISSUE TITLE
Koppeling tussen domeinwaarden 

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#72]
Graag koppelingsmogelijkheden tussen domeinwaarden aanbrengen
Bijv. bij Vorm, hier zijn  geen 'bovenliggende domeinwaarden'. Nu kan je bij elke vorm, alle vormen gebruiken en dit is niet conform GWSW. Sommige vormen gelden voor een buis, andere voor een overstortdrempel.

**Comment by RiX012** [comment]
Juiste constatering, dit komt bij meer zaken voor (o.a. Materialen). Hier gaan we een oplossing voor uitwerken en voorleggen aan de community.

**Comment by JochemMollema** [comment]
Domeinwaarden zijn per objecttype zichtbaar in de nieuwe versie van IMBOR.
