### ISSUE TITLE
Status (functioneren) IMGEo en GWSW niet samenvoegen

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#73]
Status functioneren uit GWSW is samengevoegd met stastus uit IMGEO
Deze begrippen hebben een andere betekenis en kunnen daarom niet worden samengevoegd

**Comment by RiX012** [comment]
Dit gaan we uitzoeken, een oplossing uitwerken en voorleggen en de community.

**Comment by JochemMollema** [comment]
IMBOR-team: de statussen van GWSW en IMBOR worden wel gelijk getrokken.
Bestaand --> In gebruik
Ontwerp --> In ontwerp
Aanleg --> In aanleg
