### ISSUE TITLE
Vermogen van het object (kast) icm fases

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#74]
Het vermogen van een kast is een attribuut zo ook het aantal fases. hoe daar dan mee om te gaan?
VRAAG hoe wordt omgegaan met verschillende vermogens per fase

**Comment by RiX012** [comment]
Gaan we voorleggen aan community.

**Comment by JochemMollema** [comment]
Vermogen per fase kan niet geregistreerd worden. Attribuut fase is hernoemd in aantal fases.
