### ISSUE TITLE
Attributen dubbel (in zowel objecttypegroep als object)

### ISSUE THREAD

**Issue by fzantea** [Stichting-CROW/imbor#77]
Bij de volgende objecten is geconstateerd dat het attribuut op object niveau ook op objecttypegroep niveau voorkomt. 

AANSLUITVOORZIENING | DIAMETER
ARMATUUR | PLAATSINGSDATUM
KADEMUUR | TYPEFUNDERING
LAMP | ONDERDEELVAN
ONDERDEEL | OPPERVLAKTE
POMP | SERIENUMMER
RECLAMEBORD | PLAATSINGSDATUM
RIOOLPUT | TYPEONDERDEEL
STROOK | OBJECTNUMMER
VERKEERSLANTAARN | PLAATSINGSDATUM
WEGMARKERING | KLEUR

Bij deze analyse zijn de X_... tabellen als bron toegepast.

**Comment by RiX012** [comment]
Het gaat op dit moment om :
Objecttype-AttribuutID
Aansluitvoorziening-Diameter
Aansluitvoorziening-Plaatsingsdatum
Armatuur-Plaatsingsdatum
Drijflijn--Type
Duiker--TypeOnderdeel
Kademuur-TypeFundering
Lamp--OnderdeelVan
Lamp--Voltage
Lamp--Plaatsingsdatum
Nutsaansluiting-Plaatsingsdatum
Onderdeel-Oppervlakte
Pomp--Serienummer
Reclamebord-Plaatsingsdatum
Rioolleiding-TypeOnderdeel
Rioolput-TypeOnderdeel
Strook--Objectnummer
SUFWEGKORVerhardingsobject-Oppervlakte
SUFWEGKORVerhardingsobject-Type
SUFWEGKORVerhardingsobject-WegtypeBestaand
SUFWEGKORVerhardingsobject-BGTFysiekVoorkomen
Verkeerslantaarn-Plaatsingsdatum
Wegmarkering-Kleur



Aanpassingen:
Aansluitvoorziening: In tabel X_ObjecttypesAttributen Diameter en Plaatsingsdatum op vervallen gezet. Tabel aangepast
Armatuur: In tabel X_ObjecttypesAttributen Plaatsingsdatum op vervallen gezet. Tabel aangepast
Drijflijn: Dit kunnen andere types zijn, dus geen aanpassing.
Duiker: In tabel X_ObjecttypesAttributen TypeOnderdeel op vervallen gezet.
Kademuur: In tabel X_ObjecttypesAttributen TypeFundering op vervallen gezet. Tabel aangepast inclusief relatie
Lamp: In tabel X_ObjecttypesAttributen Voltage, OnderdeelVan en Plaatsingsdatum op vervallen gezet. Tabel aangepast
Nutsaansluiting: In tabel X_ObjecttypesAttributen Plaatsingsdatum op vervallen gezet. Tabel aangepast
Onderdeel: In tabel X_ObjecttypesAttributen Oppervlakte op vervallen gezet. Veld stond niet meer in de tabel
Pomp: In tabel X_ObjecttypesAttributen Serienummer op vervallen gezet. Tabel aangepast
Reclamebord: In tabel X_ObjecttypesAttributen Plaatsingsdatum op vervallen gezet. Tabel aangepast
Rioolleiding: Was al vervallen
Rioolput: In tabel X_ObjecttypesAttributen TypeOnderdeel op vervallen gezet.
Strook: Was al vervallen
Verkeerslantaarn: In tabel X_ObjecttypesAttributen Plaatsingsdatum op vervallen gezet. Tabel aangepast
Wegmarkering: In tabel X_ObjecttypesAttributen Kleur op vervallen gezet. Tabel aangepast inclusief relatie



De SUFWEGKOR tabellen zijn overgeslagen.



Resultaat:
Objecttype-AttribuutID-WijzigingStatusID-StatusGroep
Aansluitvoorziening-Diameter-Vervallen-Goedgekeurd
Aansluitvoorziening-Plaatsingsdatum-Vervallen-Goedgekeurd
Armatuur-Plaatsingsdatum-Vervallen-Goedgekeurd
Drijflijn--Type--Goedgekeurd-Goedgekeurd
Duiker--TypeOnderdeel-Vervallen-Goedgekeurd
Kademuur-TypeFundering-Vervallen-Goedgekeurd
Lamp--OnderdeelVan-Vervallen-Goedgekeurd
Lamp--Plaatsingsdatum-Vervallen-Goedgekeurd
Lamp--Voltage-Vervallen-Goedgekeurd
Nutsaansluiting-Plaatsingsdatum-Vervallen-Goedgekeurd
Onderdeel-Oppervlakte-Vervallen-Goedgekeurd
Pomp--Serienummer-Vervallen-Goedgekeurd
Reclamebord-Plaatsingsdatum-Vervallen-Goedgekeurd
Rioolleiding-TypeOnderdeel-Vervallen-Goedgekeurd
Rioolput-TypeOnderdeel-Vervallen-Goedgekeurd
Strook--Objectnummer-Vervallen-Vervallen
SUFWEGKORVerhardingsobject-Oppervlakte-Goedgekeurd-Goedgekeurd
SUFWEGKORVerhardingsobject-Type-Goedgekeurd-Goedgekeurd
SUFWEGKORVerhardingsobject-BGTFysiekVoorkomen-Goedgekeurd-Goedgekeurd
SUFWEGKORVerhardingsobject-WegtypeBestaand-Goedgekeurd-Goedgekeurd
Verkeerslantaarn-Plaatsingsdatum-Vervallen-Goedgekeurd
Wegmarkering-Kleur--Vervallen-Goedgekeurd
