### ISSUE TITLE
Toegang tot de IMBOR gegevens via een REST-API

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#78]
De gegevens in IMBOR zijn waardevol voor areaalbeheerders in alle soorten en maten. Maar een Linked Data-turtlebestand is lang niet voor iedereen te begrijpen. Daarom zou, op basis van de data, een API gebouwd kunnen worden die de besloten gegevens beschikbaar stelt voor programmeurs (van afnemers) die niet bekend zijn met Linked Data.

Daarbij moeten we de aanbevelingen voor API's van [Geonovum][2] en [DIS Geo][1] in acht nemen. We moeten daarbij oppassen voor "API's zijn de nieuwe silo's".

[1]: https://docs.geostandaarden.nl/api/API-Strategie/
[2]: https://www.geonovum.nl/themas/kennisplatform-apis

Relevant hierbij is dat een goede API de toepassing van Linked Data bijna transparant maakt: er zouden geen SPARQL SELECT-antwoorden terug hoeven te komen, er horen meer labels dan URIs in de API-response te staan. Dan sluit deze toegang tot IMBOR beter aan op de verwachtingen van een doorsnee (programmeur van een) afnemer.

Een aantal verwachtingen:

- Toont alle objecttypen, attributen en vastewaardelijsten
- ... zowel als lijst (_alle groenvoorzieningen_), als los (_toon sluis_)
- ... met steeds de naam, identifier, relevante eigenschappen, gerelateerde objecten/attributen
- Kan zoeken naar vrije tekst
- Bevordert, zoals REST API's gebruikelijk zijn, in stappen doorzoeken van het informatiemodel ( vergelijkbaar met: _vakdisciplines/groen/objecttypen/boom/types/hegOpStam_)
- Kan zowel door mensen (html) als computers (json, ttl) gebruikt worden.

De huidige 'API' voldoet niet aan deze verwachtingen: het staat alleen vaste zoekvragen toe, is niet hierarchisch en slaat de gestructureerde informatie plat voor gebruik.

**Comment by redmer** [comment]
In https://github.com/Stichting-CROW/imbor_rest heb ik een aanzet gemaakt van het laatste idee:

1. De API-response is in JSON(-LD) en verbergt de Linked Data-URIs zo veel mogelijk

Het bouwt voort op https://github.com/NielsHoffmann/imbor_rest, waarin al een API-beschrijving conform OAS3 is opgenomen. 
Dat is een van de aanbevelingen voor API's.

**Comment by ElisabethKloren** [comment]
Zie ook de OpenAPI specification van Forum voor standaardisatie, die is bedoeld voor overheden
`[https://www.forumstandaardisatie.nl/domein/rest-apis](https://www.forumstandaardisatie.nl/domein/rest-apis)`

**Comment by ElisabethKloren** [comment]
Marinus mailt me dit: De term REST API voor de site sparql.crow.nl zorgt hier voor spraakverwarring. Op sparql.crow.nl staat (net als op apps.gwsw.nl) eigenlijk alleen een interface, geen “application programming” interface.

De OpenAPI specificatie OAS 3.0 is de standaard als er (in vervolg op de praktijkoefening) een REST-API wordt gedefinieerd.

**Comment by RiX012** [comment]
Goed dat Marinus dat zegt. Daar moeten we dan ook helder in zijn. Moeten we alleen nog wel een goede term hebben hoe we het dan wel noemen.

**Comment by RiX012** [comment]
Inmiddels is de nieuwe versie van de Webapp sparql.crow.nl/ldp gereleased, inclusief REST-API
