### ISSUE TITLE
Aansluiting GWSW - IMBOR, vraag over "kast"

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#79]
In het overleg met de softwareleveranciers werd het volgende voorbeeld genoemd over aansluiting GWSW - IMBOR:
in GWSW zit een kast, met een beperkt aantal attributen.
in IMBOR, voor verlichting, zitten in een kast véél meer soorten attributen

Checkvraag 1: kunnen we dit voorbeeld terugvinden?
Checkvraag 2: hebben we nu IMBOR-attributen weggelaten uit de linked data versie, omdat die aan een GWSW object zaten?
Checkvraag 3: missen we in de linked data versie attributen uit GWSW, die toch ook bij een IMBOR kast gevraagd worden?

Grotere vraag: hoe gaan we hiermee om qua aansluiting op elkaar, kunnen we GWSW en IMBOR op "objecttype" scheiden, of moeten we soms hetzelfde object erkennen, maar op één of ander manier aangeven dat deze binnen de IMBOR-context meer eigenschappen heeft dan in de GWSW context (maar ook de GWSW-eigenschappen horen erbij?

Welke smaken zijn er qua op elkaar afstemmen, wat zijn voors en tegens in gewone mensentaal?

**Comment by RiX012** [comment]
In de volgende versie van IMBOR gaan we de zaken meer uiteenrafelen. De herkomst van alle objecttypen en attributen gaan we koppelen aan de bronnen. De afstemming tussen de verschillende modellen en de afwegingen daarin worden in de volgende versie verder uitgewerkt.
