### ISSUE TITLE
Drain

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#81]
Het type bij de Drain is niet volledig als we kijken naar het GWSW.
Graag de lijst met 
![2020-06-10 13_55_16-GWSW - Drain](https://user-images.githubusercontent.com/40396592/84265295-ee17db00-ab22-11ea-862c-1368e8e707c6.png)
![2020-06-10 13_55_52-frmIMBOR_Drain](https://user-images.githubusercontent.com/40396592/84265345-ff60e780-ab22-11ea-93c2-48a4a2d630b2.png)

type uitbreiden.

**Comment by JochemMollema** [comment]
De relaties tussen drain en andere objecttypen worden conform GWSW in IMBOR via semantische relaties vastgelegd.
