### ISSUE TITLE
Versiebeheer IMBOR - 2020-07

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#82]
De patch op IMBOR wordt uitgebracht, waarbij de Access publicatie en de linked data publicatie dezelfde versieaanduiding krijgen: 2020-07. Graag deze als zodanig verspreiden binnen de experimenten en pilots.

**Comment by RiX012** [comment]
Waar het nu naar laatste inzichten dus 2020-08 wordt

**Comment by ElisabethKloren** [comment]
@HarroVerhoeven is al duidelijk welke versienaam de patch krijgt? IMBOR 2020-08?

**Comment by HarroVerhoeven** [comment]
Jazeker @ElisabethKloren! De patch moet deze maand verschijnen en heet dan IMBOR 2020-08.
