### ISSUE TITLE
Vraag Prov. Utrecht, faunaduiker versus faunatunnel klein?

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#83]
Binnengekomen bij mij, vanuit Provincie UtrechtWat is het verschil tussen een faunaduiker en een faunatunnel klein? Als je afgaat op de definitie is hier geen verschil aanwezig, dus wat kies je dan?

**Comment by wjtmollema** [comment]
**Probleem**
`Faunaduiker` : "Faunaduiker (droog): Een droge doorgang onder of over lijnvormige infrastructurele werken. Doel: opheffen van infrastructurele barrières en de migratie van kleine tot middelgrote fauna mogelijk maken tussen of binnen leefgebieden en populaties. Kleine zoogdieren zoals muizen, konijnen, marterachtigen, egels en medegebruik door kleinere niet-zoogdieren."

`Faunatunnel klein` : "Opheffen van infrastructurele barrières en de migratie van kleine tot middelgrote fauna mogelijk maken tussen of binnen leefgebieden en populaties."

Afgaand op de definities ontstaat er inderdaad verwarring, omdat de doelstellingen van het gebruik van beide termen overeenkomen. Dit is op te lossen door de definitie van beide termen aan te passen, zodat ze het semantische verschil tussen de objecttypes `Duiker` en `Tunnel` reflecteren. 

**Oplossing**
Beschouw de volgende definities, waarbij voor `Tunnel` de tweede zin van de definitie buiten beschouwing gelaten moet worden:
`Duiker`  :  "Kunstwerk voor de waterhuishouding, bestaande uit een kokervormige constructie aangebracht onder een weg of spoorweg of in een dam."

`Tunnel` : "Een tunnel is een kunstmatig aangelegde onderdoorgang om tussen twee punten transport, passage of communicatie mogelijk te maken. Doorgaans is de tunnel langer dan 300 meter."

Dit maakt duidelijk dat Duikers betrekking hebben op waterhuishouding, maar Tunnels niet. Een Faunaduiker is als zodanig een Duiker die voor faunadoeleinden wordt ingezet (zie ook deze definitie van [Waterschap Hunze en Aa's](https://kennis.hunzeenaas.nl/index.php/Id-6716bfc0-bc4b-4216-ae45-c600299bc5f2)). Een faunatunnel is daarmee een onderdoorgang die niet letterlijk bestaat uit een duikerbuis. 

**Conclusie**
Derhalve worden de volgende gewijzigde definities voorgesteld, zodat het duidelijk is dat een `Faunaduiker` letterlijk bestaat uit een duikerbuis en een `Faunatunnel klein` in essentie een onderdoorgang is.

`Faunaduiker` : "Een droge doorgang onder of over lijnvormige infrastructurele werken die bestaat uit een duikerbuis die voor het opheffen van infrastructurele barrières en de migratie van kleine tot middelgrote fauna mogelijk maken tussen of binnen leefgebieden en populaties bedoeld is. De faunaduiker is geschikt voor kleine zoogdieren zoals muizen, konijnen, marterachtigen, egels en voor medegebruik door kleinere niet-zoogdieren."

`Faunatunnel klein` : "Een onderdoorgang die als doel het opheffen van infrastructurele barrières en het mogelijk maken van de migratie van kleine tot middelgrote fauna tussen of binnen leefgebieden en populaties heeft."

`Faunatunnel groot` : "Een onderdoorgang die als doel het opheffen van infrastructurele barrières en het mogelijk maken van de migratie van middelgrote tot grote fauna tussen of binnen leefgebieden en populaties heeft."

**Comment by RiX012** [comment]
Klinkt prima. Wordt de '...buis' ook nog apart geregistreerd? Zodat er wellicht een semantische relatie moet zijn?

**Comment by wjtmollema** [comment]
Nee, de `Faunaduiker` is letterlijk een duikerbuis, waarbij ik het woord 'duikerbuis' gebruik om `Duiker` niet aan te roepen, want dat is ook letterlijk een duikerbuis, maar dan in de zin van de bovenstaande definitie van `Duiker`.

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
