### ISSUE TITLE
Vraag Prov. Utrecht, viaduct versus fly-over

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#84]
Vraag vanuit provincie Utrecht - Wat is het verschil tussen een viaduct en een flyover? Aan de hand van de definitie kwamen wij er niet uit

**Comment by JochemMollema** [comment]
Definitie aangepast in IMBOR 2020-08.

Definitie Viaduct aangescherpt.

Een viaduct is een onderdeel van een ongelijkvloerse kruising van twee (geplande) (spoor)wegen of een kruising van een weg met ondergrondse leidingen. Een viaduct is feitelijk niet veel anders dan een vaste brug, hoewel met een viaduct geen waterweg wordt gekruist. De ruimte onder een viaduct is in geval van aanwezigheid van pijlers verdeeld in zogenaamde velden. Elke ruimte tussen pijlers c.q. tussen een landhoofd en een pijler is gedefinieerd als een veld.

3 types kunnen bij een viaduct onderscheiden worden:
- Liggerbrug
- Dalviaduct
- Maaiveldviaduct

Attribuut Type toegevoegd aan Viaduct (X_ObjecttypeAttributen, IMBOR_Viaduct).
Domeiwaarden toegevoegd aan REF_Type, X_AttributenDomeinwaarden

Definitie flyover aangescherpt:

Een fly-over of flyover is een verbindingsweg, aangelegd als viaduct over andere wegen heen, teneinde een aansluiting ongelijkvloers te maken, waarbij vaak de boogstraal groot wordt gehouden voor de doorstroming. Flyovers worden onderscheiden van reguliere viaducten en zijn doorgaans voor snelverkeer. Op drukke knooppunten zijn vaak flyovers voorhanden.
