### ISSUE TITLE
Vraag Prov. Utrecht: tunnel versus onderdoorgang

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#85]
Vraag vanuit provincie Utrecht: Wat is het verschil tussen een tunnel; en een onderdoorgang? Aan de hand van de definitie kwamen wij er niet uit

**Comment by JochemMollema** [comment]
Aangepast in IMBOR versie 2020-08

Definitie tunnel gewijzigd in:

Een tunnel is een kunstmatig aangelegde onderdoorgang om tussen twee punten transport, passage of communicatie mogelijk te maken. Doorgaans is de tunnel langer dan 300 meter.

Definitie onderdoorgang gewijzigd in: 

Een onderdoorgang is in feite een tunnel met geringe afmetingen in lengte en breedte. In tegenstelling tot de gangbare definitie van een tunnel, wordt een onderdoorgang meestal niet onder een watergang, maar onder een spoor- of verkeersweg aangelegd. Korte ongelijkvloerse verbinding die bestemd is voor wegverkeer onder een weg of spoorweg door. De lengte van de onderdoorgang is korter dan 300 meter.
