### ISSUE TITLE
Object Kunstwerk (ObjecttypeID 414) in Vakdiscipline "Bomen" (VakdisciplineID 23)

### ISSUE THREAD

**Issue by LuukWijnholts** [Stichting-CROW/imbor#86]
In de Access is het object Kunstwerk onderdeel van de Vakdiscipline Bomen. Dit is overgenomen in de IMBOR LD. 

groep:V23 (Bomen) member: imbor:OBB414 (Kunstwerk)

Ik denk dat dit object niet tot deze vakdiscpline behoort, maar dat dit Bouwwerk dient te zijn.

**Comment by JochemMollema** [comment]
In tabel X_VakdisciplinesObjecttypes Kunstwerk voor vakdiscipline Bomen op vervallen gezet.
