### ISSUE TITLE
Antea Group | Prio: Nee | J16 Objecttype Planten - type bodembedekkers

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#860]
OPMERKING:
Dit beplantingstype staat op de verkeerde plek

ARGUMENTATIE:
conform de genoemde defintie van dit beplantingstype en de onderliggende definities bij type gedetailleerd worden hier heesterbeplatingen bedoeld. Deze horen bij struiken en niet bij planten.

OPLOSSING:
Oplossing type bodembedekkers en bijbehorende typen gedetaileerd (3x) onderbrengen bij objecttype heesters/struiken

(Eventuele bijbehorende afbeelding is bij CROW beschikbaar)

**Comment by JochemMollema** [comment]
Oplossinsgvoorstel wordt overgenomen en de bodembedekkers worden naar struiken verhuisd.
