### ISSUE TITLE
Antea Group | Prio: Nee | J20 Ecologie

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#861]
OPMERKING:
mist objecttype tuunwal

ARGUMENTATIE:
Is landschapselement met ecologische waarde net als houtwal

OPLOSSING:
toevoegen objecttype tuunwal aan vakdiscipline ecologie

(Eventuele bijbehorende afbeelding is bij CROW beschikbaar)

**Comment by JochemMollema** [comment]
Tuunwal is de aan de vakdiscipline Ecologie toegevoegd.
