### ISSUE TITLE
Antea Group | Prio: Nee | J21 Vakdiscipline Spelen

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#862]
OPMERKING:
Waarom zijn hier zoveel objecttypen gekoppeld?

ARGUMENTATIE:
Er is veel overlap tussen de disciplines dat werkt verwarrend en heeft geen meerwaarde.

OPLOSSING:
Alleen de voor spelen unieke objecttypen hier koppelen, de overige kan via gebruiksfunctie of functioneel gebied oid.
Voorstel unieke objecttypen zie bijlage

(Eventuele bijbehorende afbeelding is bij CROW beschikbaar)

**Comment by JochemMollema** [comment]
Omdat bij Spelen net als bij Sport voor een speelterrein alle vaak voorkomende objecttypen geregistreerd kunnen worden. Het is een zoekingang en geen regel, het is aan de leverancier en de gebruiker om te bepalen welke objecttypen binnen een vakdiscipline gebruikt worden.
