### ISSUE TITLE
IS Tiny Forest toegevoegd aan IMBOR?

### ISSUE THREAD

**Issue by stefanleeuwerik** [Stichting-CROW/imbor#864]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**

**Beschrijf de oplossing die je voor je ziet**
Een beknopte en heldere beschrijving van je wilt zien gebeuren.

**Wat voor alternatieven heb je overwogen?*
Een beknopte en heldere beschrijving van alternatieve oplossingen die je hebt overwegen.

**Meer context**
Voeg andere context of bijvoorbeeld schermfoto's toe. Denk eraan, deze melding is openbaar.

**Comment by RiX012** [comment]
Dit punt wordt bij ingebracht bij een inhoudelijke werkgroep zodra deze geformeerd zijn.

**Comment by wjtmollema** [comment]
`Tiny forest` is sinds IMBOR 2022 onderdeel van de enumeratietypes `BosGebruiksfunctie` en `BosplantsoenGebruiksfunctie`.
