### ISSUE TITLE
relatie boom met armatuur onduidelijk

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#865]
Bij de objecttype boom is er een relatie met een armatuur opgenomen. Deze is voor mij niet duidelijk.

Mogelijk een test geweest om te zien hoe dit in het model wordt weergegeven.
![relatie objecttype boom-armatuur](https://user-images.githubusercontent.com/40396592/148901349-a7cd5765-a097-49c5-a17a-547d604032f6.jpg)

**Comment by JochemMollema** [comment]
Gaat om de aanwezigheid van feestverlichting in de boom, dit is een type van een armatuur.
