### ISSUE TITLE
Waarom staat Type: Skatevoorziening Onder Objecttype: Speeltoestel?

### ISSUE THREAD

**Issue by WisseDQ** [Stichting-CROW/imbor#866]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Waarom staat Type: Skatevoorziening Onder Objecttype: Speeltoestel en niet onder Objecttype: Sporttoestel?
Eeen skatevoorziening lijkt mij eerder sport als speel gerelateerd.

**Beschrijf de oplossing die je voor je ziet**
Type: Skatevoorziening en onderliggende verschijningen verplaatsen naar Objecttype: Sporttoestel

**Wat voor alternatieven heb je overwogen?*

**Meer context**

**Comment by RiX012** [comment]
Dit punt wordt bij ingebracht bij een inhoudelijke werkgroep zodra deze geformeerd zijn.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- `Skatevoorziening` vervalt bij `SpeeltoestelType` en wordt toegevoegd bij `SporttoestelType`;
- `Bank zonder tranny` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Bench` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Curb` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Curved Grind Rail` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Dubbele rail` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Flat Bank` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Fly box` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Fun box` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Half Pipe` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Handrailbox` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Hip` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Hubba` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Jump Ramp` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Ledge` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Midi Ramp` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Mini Ramp` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Pyramid` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Quarter bank` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Quarter ramp` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Quarterpipe` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Rail` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Ramp` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Roll-In` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Spine` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Vault rails` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Volcano` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Wall Ride` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`;
- `Wally` vervalt bij `SpeeltoestelTypeGedetailleerd` en wordt toegevoegd bij `SporttoestelTypeGedetailleerd`.

**Comment by RiX012** [comment]
Prima wat mij betreft om dit zo te verwerken
