### ISSUE TITLE
Relaties tussen Geo-object, Fysiek object en RuimtelijkGebied

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#869]
Opmerking van @NielsHoffmann  gekregen.

- FysiekObject is nu een subklasse van Geo-object, terwijl de NEN3610 en NEN2660-2 dit andersom zien. Dus dit moet aangepast.
- RuimtelijkGebied moet ook een subklasse van FysiekObject zijn. Dit kan 'versimpeld' worden door bullit 1 en dan RuimtelijkeGebied een subklasse te laten zijn van Geo-object

**Comment by JochemMollema** [comment]
Opgelost.

Toegevoegd Superklasse Object
Kinderen FysiekObject en Informatieobject

Ouder FysiekObject
Kinderen Materie, ReeelObject, RuimtelijkGebied, Geo-object

Ouder Geo-object
Kinderen Reeel object, Virtueel gebied, Topologisch element
