### ISSUE TITLE
Beheerplan IMBOR: toevoegen rol financiers KPP en FFL

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#871]
Suggestie:

Rol: Opdrachtgever. Het Fonds Fysieke Leefomgeving en het Kennis Platform Provincies zijn opdrachtgever van het IMBOR

Taak: De fondsen geven opdracht om het beheer uit te voeren aan de beheerder, CROW.
Taak: De fondsen geven stellen de Stuurgroep samen 
Taak: De fondsen benoemen de voorzitter van de Stuurgroep

Rol: Financier (indirect) Het Fonds Fysieke Leefomgeving en het Kennis Platform Provincies signaleren welke ontwikkelingen nodig zijn binnen de sector (de klantvraag) en financieren de uitwerking van deze ontwikkeling.

Taak: Beoordelen van projectvoorstellen voor ontwikkelingen van IMBOR, te financieren door het Kennis Platform Provincies en het Fonds Fysieke Leefomgeving.

**Comment by EJvandekamp** [comment]
Tekst volledig verwijderd.
