### ISSUE TITLE
Enumeratie en xsd:boolean lopen door elkaar heen. Domeinwaarden Ja/Nee/Onbekend

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#874]
Komt mede voort uit #749 

In de EnumeratieType en Domeinwaarden tabel wordt heel vaak de combinatie Ja/Nee/Onbekend gebruikt. Terwijl deze in de Attributen tabel als "Enumeratie" en xsd:boolean aangemerkt staat. 

We gaan nu al deze domeinwaarden laten vervallen en het daarmee alleen xsd:boolean laten. @JochemMollema Het TypeAttribuut 'Enumeratie' moet daarmee ook vervallen.

**Comment by JochemMollema** [comment]
Opgelost, bij alle boolean-attributen vervalt het enumeratietype.
