### ISSUE TITLE
Amsterdam: graag bij eigenaar en beheerder in de vaste lijst Landelijke organisatie opnemen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#876]
Amsterdam: graag bij eigenaar en beheerder in de vaste lijst Landelijke organisatie opnemen. En dan bij eigenaar en beheerder gedetailleerd ProRail (en andere organisaties)

**Comment by wjtmollema** [comment]
**Verwerking**
De term 'Landelijke organisatie' is toegevoegd. 'Landelijke organisatie' is toegevoegd aan de enumeratietypes 'BeheerdObjectEigenaar' en 'BeheerdObjectBeheerder.' De domeinwaarde 'ProRail' is verplaatst van de enumeratietypes 'BeheerdObjectEigenaar' en 'BeheerdObjectBeheerder' naar de enumeratietypes 'BeheerdObjectEigenaarGedetailleerd' en 'BeheerdObjectBeheerderGedetailleerd.'

**Motivatie**
De toevoeging van 'Landelijke organisatie' zorgt voor een beter functioneren van de attributen 'eigenaar gedetailleerd' en 'beheerder gedetailleerd.'
