### ISSUE TITLE
DG groep: 1 op n relatie van onderhoudsplichtigen:  Dit zou ons inziens helemaal geen kenmerk van een object moeten zijn, maar een kenmerk van een maatregel. 

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#877]
1 op n relatie van onderhoudsplichtigen:  Dit zou ons inziens helemaal geen kenmerk van een object moeten zijn, maar een kenmerk van een maatregel. Andersoms: een assetobject heeft meerdere onderhoudsmaatregelen welke door verschillende onderhoudsplichtigen worden uitgevoerd. Het registreren van een onderhoudsplichtige in 1 op 1 of 1 op n aan het object klopt ons inziens dus niet.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Het registreren van meerdere `onderhoudsplichtige`n op het niveau van een `ObjectType` is niet in tegenspraak met het registreren van `onderhoudsplichtige`n op het niveau van een maatregel. Het registreren van meerdere `onderhoudsplichtige`n op het niveau van een `ObjectType` heeft een administratief nut dat losstaat van het uitzetten van concrete maatregelen bij een of meer partijen. Het is namelijk ook mogelijk dat de `onderhoudsplichtige` voor bepaalde maatregelen weer andere partijen contracteert. Het gaat, in samenhang met `beheerder` en `eigenaar` bij `onderhoudsplichtige` om het registreren van de taakverdeling binnen organisaties m.b.t. een `ObjectType`.
