### ISSUE TITLE
DG Groep: Waarom worden in het gehele verhaal de voorgesteld BOR attributen voor aanvullende elementen in het BGT-BOR berichtenverkeer nog meegenomen?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#879]
Waarom worden in het gehele verhaal de voorgesteld BOR attributen voor aanvullende elementen in het BGT-BOR berichtenverkeer nog meegenomen? Dit gaat toch nooit gebruikt worden en scherpt ook hier weer verwarring met andere typeringen.

**Comment by wjtmollema** [comment]
Ten behoeve van overzichtelijkheid stel ik voor deze issue te sluiten en definitief af te handelen in #991.
