### ISSUE TITLE
Amsterdam: voeg de put waarin een ondergrondse container zit als objecttype Containerput toe.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#880]
Amsterdam: voeg de put waarin een ondergrondse container zit als objecttype Containerput toe.

**Comment by wjtmollema** [comment]
`Voorgestelde verwerking`
Een `Containerput` is een ondergronds object en kan als zodanig toegevoegd worden als `subKlasseVan` de klasse `Put`. 

**Motivatie**
Een ander voorbeeld van een `Put` die niet tot de ondergrondse infrastructuur behoort (zoals `Rioolput`) om de bovenstaande verwerking te onderbouwen kan gegeven worden, namelijk de `Fauna-inspectieput`. Een modellering als `Straatmeubilair` zoals bij `Vlaggenmastput` (zie #1028 ) lijkt hier een verkeerde optie, omdat de `Containerput` tot dieper in de ondergrond reikt en daarom de attributen van de klasse `Put` goed zou kunnen gebruiken.

**Comment by wjtmollema** [comment]
**Herziening**
Voorstel om dit `ObjectType`, #1028 en #1008 samen te voegen tot een `ObjectType` `Ombouw`, met als relevante attributen `boven- of ondergronds` en `is open` (voorstel nieuw attribuut).
