### ISSUE TITLE
Amsterdam: hoe kun je een afvalaanbiedlocatie of stortlocatie registreren?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#881]
Amsterdam: hoe kun je een afvalaanbiedlocatie of stortlocatie registreren?

**Comment by wjtmollema** [comment]
**Constatering**
Op het eerste gezicht lijk het objecttype `Verzamelplaats` aan de voorbeelden van 'afvalaanbiedlocatie' en 'stortlocatie' te voldoen. `Verzamelplaats` kent namelijk de volgende waarden voor `type`:
- `Inzamelpunt`: "Locatie waar specifiek afval ingezameld wordt, bijvoorbeeld door inlevering."
- `Opslagplaats`: "Terrein met eventueel verschillende soorten verharding, bedoeld voor de opslag van materialen of producten in de open lucht."

**Voorgestelde verwerking**
`Inzamelpunt` lijkt de lading te dekken van 'afvalaanbiedlocatie'. 

`Opslagplaats` komt echter niet volledig overeen met de betekenis van 'stortlocatie'. Hiervoor kan voorgesteld worden om `Stortlocatie` toe te voegen aan `VerzamelplaatsTypeGedetailleerd` (een enumeratietype dat zelf ook toegevoegd moet worden) met als bovenliggende domeinwaarde `Opslagplaats`.
