### ISSUE TITLE
Container - types zijn overlappend

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#882]
Bij de containers lopen de types en de positie door elkaar. Meerdere types kunnen gelijk van toepassing zijn.

**Comment by wjtmollema** [comment]
**Constatering**
De types zijn niet langer overlappend. Er is sprake van mogelijke overlap tussen `boven- of ondergronds` en de inhoud van de definities van de types. Dit is een toepassingsvoorbeeld waarbij het onwenselijk is het model aan te passen. Het kan ondervangen worden met een business rule in een registratiesysteem.
