### ISSUE TITLE
IMBOR Modelleerregel Termen & Definities

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#884]
### Termen

- Binnen IMBOR wordt _alles_ geschreven als **enkelvoud**, tenzij het een groep betreft
  - BIjvoorbeeld de vakdisciplines betreffen 'Wegen' en 'Kunstwerken', niet 'Weg' of 'Kunstwerk'

### Definities

- Een definitie bestaat uit de genus + differentia (ofwel de categorie en de onderscheidende kenmerken). 
  - _Lichtmast: Een mast met een lichtbron_ of _Mast die als lichtbron functioneert_
- Hiermee is meteen een zwakke hiërarchie geborgd. 
  - Mast kan nu als _broader_ dan Lichtmast aangemerkt worden.
- Het onderwerp wordt niet herhaald
   - NIET: _Een lichtmast is een mast met een lichtbron_

[Definities.pdf](https://github.com/Stichting-CROW/imbor-2021/files/7822852/Definities.pdf)

**Comment by wjtmollema** [comment]
**Analyse**
In het kader van de bovengenoemde eis voor definities...

> Het onderwerp wordt niet herhaald

...zijn de definities uit de werkversie van IMBOR geanalyseerd en waar nodig aangepast. Het bijgevoegde Excellijst bevat de resultaten van de analyse- en wijzigingsactie. 1632 van de 8601 termen zijn in overtreding van deze modelleerregel, wat de hoge urgentie voor het uitvoeren van deze actie onderbouwd. De resultaten zijn onderverdeeld in de volgende vijf categorieën die een bepaalde vorm van wijziging of handhaving van de term omvatten:

1. _Wijziging categorie 1:_ (1560 gevallen) De definitie van de term bevat de term zelf en is derhalve aangepast. Er is een _was_- en een _wordt_-situatie van de definitie opgenomen.
2. _Wijziging categorie 2:_ (21 gevallen) De definitie van de term bevat de term zelf, maar de term komt voor in een toelichtende zin. De toelichtende zin is verplaatst naar het veld `Toelichting` en de definitie is derhalve aangepast. Er is een _was_- en een _wordt_-situatie van de definitie opgenomen, alsmede een _was_- en een _wordt_-situatie van de toelichting.
3. _Handhaving categorie 1:_ (33 gevallen) De definitie van de term bevat de term zelf, maar de definitie is ontleend aan een ander (informatie)model vanwege diens afstemming met IMBOR of uit een bepaalde Nederlandse overheidsregeling. De termen komen uit het GWSW, het IMKL, de SOR, de BGT, het IMGeo, de NEN 3610 en het Handboek Bomen en het Binnenvaartpolitiereglement.
4. _Handhaving categorie 2:_ (12 gevallen) De definitie van de term bevat de term zelf, maar de term kan niet gedefinieerd worden zonder de tekenreeks waar de term uit bestaat te gebruiken. Bijvoorbeeld `A` heeft als definitie: `Ampère.`
5. _Handhaving categorie 3_: (16 gevallen) De definitie van de term bevat de term zelf, maar het betreft een `Vakdiscipline`, waarbij de concessie wordt gedaan dat bijv. de term `Bomen` gedefinieerd mag worden met behulp van het woord 'bomen'.

Het definitief doorvoeren van de 1581 wijzigingen en het ongewijzigd laten van de andere 51 termen is in afwachting van accordering door het IMBOR-team.
[20230426_GitHub_#884.xlsx](https://github.com/Stichting-CROW/imbor/files/11331255/20230426_GitHub_.884.xlsx)

**Comment by RiX012** [comment]
Uitstekend werk. Ik zie hier alleen maar voordelen aan. Dus wat mij mij betreft doorvoeren.
