### ISSUE TITLE
GWSW 1.5.2/1.6 Mapping

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#887]
Jochem: 28-09-2021:

**GWSW Basis 1.6 en IMBOR 2021**

Alle fysieke objecten en een deel van de ruimtes worden in IMBOR 2021 opgenomen.

1. Aansluiting --> als Rioolaansluiting toegevoegd binnen de nieuwe klasse Samengestelde rioleringsobjecten
Types toegevoegd
Type gedetailleerd toegevoegd
Geen verdere specifieke attributen

2. Apparatuur
2.1
- Elektrakast hernoemd in Elektriciteitskast
++ Centrale voedingskast als type van Elektriciteitskast toegevoegd
- Rioolkast is synoniem van Besturingskast, Rioolkast hernoemd in Besturingkast

2.2 Meetinstrumenten
- Relatie met Meetpunt via semantische relatie 
- Meetpunt als objecttype toegevoegd.
Om een meetpunt te kunnen klassificeren is de onderstaande klassenstructuur toegevoegd.

Onder de klasse Geo-object
- Topologisch object
-- Edge
o Deelineoriëntatie
o Kabeloriëntatie
-- Gebiedsoriëntatie - kan in IMBOR met GM_Surface opgelost worden.
-- Representatie fysiek object
o --> objecten die hieronder vallen opgenomen in IMBOR
-- Vertex
o --> objecten die hieronder vallen opgenomen in IMBOR

Voor het objecttype Knooppunt wordt de Engelse term Node gekozen, vanwege mogelijke verwarring met het verkeersknooppunt.

Attribuut Meetpunt-identificatie komt te vervallen. Wordt via semnatische relaties opgelost. De relatie met Meetpunt wordt geregistreerd bij:

Meetbuis
Debietmeter
Detector
Drukmeter
GMS-sensor
Kwaliteitssensor
Lichtsensor
Luchtkwaliteitssensor
Zichtmeter
Overstortmeter
Camera
Referentiemicrofoon
Regenmeter
Telpaal
Waterniveaumeter
Weegpunt
Weerstation
Wifi-antenne
Windmeter
Peilbuis

3. Bouwwerk
- Algemeen relatie met topologisch element Bouwwerkoriëntatie
- Adresgegevens: via openbare ruimte, huisnummer en locatieaanduiding

3.1 Grindkoffer
- Attributen Bergend oppervlak, Bergend vermogen, Infiltrerend oppervlak, Infiltrerend vermogen toegevoegd

3.2 Infiltratiebassin
- Attribuut Bergend oppervlak toegevoegd

3.3 Gras- en kruidachtigen/Infiltratieveld
- Attributen Bergend oppervlak, Infiltrerend oppervlak, Infiltrerend vermogen en Porositeit toegevoegd --> gras- en kruidachtigen kan als infiltratieveld gebruikt worden.
- Infiltratieveld als domeinwaarde toegevoegd bij groenfunctie

3.4 Zuiveringsreservoir
- IBA verder gedetailleerd en hiervoor type gedetailleerd en type extra gedetailleerd toegevoegd.

3.5 Spoorlijn als waterstaatkundig kunstwerk toegevoegd (zelfde categorie als dijklichaam) onder de werknaam Spoordijk.

4. Constructieonderdelen
Geen opmerkingen of wijzigingen wel nieuwe relaties.

5. Kabels
Geen opmerkingen of wijzigingen wel nieuwe relaties.

6. Leidingen
- attribuut thema imkl hernoemd in WIBON thema
- SDR-waarde toegevoegd aan klasse Holle leiding

6.1 Open leidingen: Goot
- Lijngoot toegevoegd aan IMBOR, GWSW maakt duidelijk onderscheid tussen molgoot en lijngoot.
- Objecttype Lijnafwatering laten vervallen. 4 objecttypes op het zelfde niveau
++ Lijngoot
++ Molgoot
++ Taludgoot
++ Verholen goot
De open leidingen zijn op basis van een groter belang voor Riolering verhuist van Weginrichtingsobjecten naar Holle leidingen.
- Attribuut profiel open leiding toegevoegd aan lijngoot, Molgoot, Taludgoot, Verholen goot
- Attribuut afvoerend oppervlak toegevoegd aan lijngoot, Molgoot, Taludgoot, Verholen goot

6.2 Duiker
- attribuut profiel leiding toegevoegd

6.3 Rioolleiding
- attribuut profiel leiding toegevoegd
- attribuut lateraal debiet toegevoegd
- attribuut aantal woningen toegevoegd
- attribuut afvoerend oppervlak toegevoegd
- attribuut lateraal afvoerend oppervlak toegevoegd

6.4 Transportleiding
- attribuut profiel leiding toegevoegd

7 Putten
Adresgegevens --> openbare ruimte + locatieaanduiding

7.1 Rioolput
- attribuut lateraal debiet toegevoegd
- attribuut afvoerend oppervlak toegevoegd
- attribuut aantal woningen toegevoegd
- attribuut lateraal afvoerend oppervlak toegevoegd

7.2 Kolk
- attribuut type reiniging toegevoegd incl. enumeratielijst

8. Stelsel
Stelsels als objecttype toegevoegd. Dit betekent dat het attribuut type stelsel komt te vervallen en dat de relatie tussen objecttype en stelsel via semantische relaties gelegd wordt.

Vanwege de grote verschillen tussen de stelsels zijn de volgende stelsel als objecttype aan IMBOR toegevoegd.
- Drainagestelsel
- Duikerstelsel
- Grondwatermeetnet
- Infiltratiestelsel
- Rioolstelsel
- Transportstelsel

Drainagestelsel
- types toegevoegd
++ Bouwblokdrainage
++ Privédrainage
++ Riooldrainage
++ Sport- en speldrainage
++ Verzameldrainage

Rioolstelsel
++ Hybride systeem als type gedetailleerd van Mechanisch rioolstelsel

9. Systeem
Objecttypes toegevoegd binnen de "klasse" Systeem
- Afvalwatersysteem
++ attribuut type toegevoegd
- Gescheiden systeem
++ attribuut type toegevoegd
- Grondwatersysteem
- Meetinrichting
- Oppervlaktewatersysteem
++ attribuut type toegevoegd
- Regelinrichting

10. Water

10.1 Watervlakte

Bij vijver type gedetailleerd Bluswatervijver toegevoegd

10.2 Watergang
- attribuut profiel open leiding toegevoegd

11. Ruimte

11.1 Compartiment
- attribuut lateraal debiet toegevoegd
- attribuut afvoerend oppervlak toegevoegd
- attribuut aantal woningen toegevoegd
- attribuut lateraal afvoerend oppervlak toegevoegd

12. Semantische relaties
1e ronde relaties is in bulk toegevoegd. Per objecttype moeten de relaties nog langsgelopen worden.

13. Github-meldingen Riolering verwerkt.

553
Steenwolkoffer en Zandkoffer als objecttypen toegevoegd.

423
Type bewerking als attribuut bij klasse Put verwijderd, komt ook niet in GWSW voor. Bij Kolk gaat het om type reiniging.

389
Type gedetailleerd van Pompput: Luchtinjectie-unit toegevoegd.

386
Type Wikkelbuis relining als type van Lining toegevoegd.

377
Onderscheid gemaakt tussen rioolgemalen en andere gemalen. Bij Rioolgemaal types gedetailleerd conform GWSW.

309
Oppervlakte als attribuut toegevoegd aan de klasse Put.

284
Dit kan via het informatieobject inwinning geregistreerd worden. Hierbij geldt een 0 op n relatie, waardoor de verandering in de tijd ook vastgelegd kan worden voor elk attribuut, dus ook voor de maaiveldhoogte.
Aan het informatieobject inwinning-informatie is het attribuut domeinwaarde toegevoegd.

121
Dakafvoer is geen onderdeel van IMBOR, bespreken met Rioned

Bespreken:

1. Aansluiting, Stelsel en Systeem zijn samengestelde objecten die binnen IMBOR binnen IMBOR als virtuele ruimte gemodelleerd zijn.
2. Geen adresgegevens bij waterobjecten
3. Spoordijk i.p.v. Spoorlijn
4. Vervuilingsgraad bij leiding niet overgenomen, dit is een inspectiegegeven.
5. Wel of geen WIBON-thema bij de open leidingen? Nu niet in IMBOR
6. Is verder opsplitsen van rioolleiding en transportleiding gewenst? Wel nog attributen die van types afhankelijk zijn.
7. IMBOR heeft meer waarden voor de collectie Datacommunicatie
8. Laten vervallen van attribuut Type stelsel?
9. Ontbrekende definities: bijvoorbeeld voor meetinrichting
10. Hoe omn te gaan met stedelijk water (zie taxonomie oppervlaktewater)
11. Indeling gemalen bespreken
12. Volgeschuimd ook bij andere objecten dan leidingen?
13. Dakafvoer is geen onderdeel van IMBOR, bespreken met Rioned

Mapping IMBOR en GWSW bijgewerkt met bespreekpunten voor Rioned.

Match IMBOR-GWSW

1. Bij Putdeksel geen Putdeksel met instroomvoorziening meer in GWSW basis
2. Elektronische component vs Electronisch component
3. Aansluiting Slot is niet 1 op 1
4. Geen match op kunststof leiding
5. Roostergoot synoniem van lijngoot
6. Geen match op stalen leiding

**Comment by RiX012** [comment]
Dit wordt opgepakt in de GWSW - IMBOR mapping die volledig hierzien wordt.

**Comment by wjtmollema** [comment]
@RiX012 Het lijkt me goed om dit mee te nemen als onderdeel van de inhoudelijke as van het afstemmingsoverleg tussen CROW en RIONED over IMBOR/GWSW 2.0

**Comment by RiX012** [comment]
Buiten IMBOR geplaatst en daarom in het project 'Linksets' gezet als `in progress`. Dit is een wel major onderdeel voor de 2024 release

**Comment by RiX012** [comment]
#1356 lost dit grotendeels op
