### ISSUE TITLE
IMBOR 2020-07 release gebruiken om scheiding Functioneel en Fysiek te in IMBOR-LD te implementeren 

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#89]
Impact/revisit van:
#5 #6 #27 

Vanuit meerdere kanten (o.a. Gemeente Amsterdam, Provincie Gelderland, IMBOR) werd aangegeven dat de beslissingen om alles `bs:PhysicalObject` te maken herzien moest worden. Onze keuze om alles op te nemen als PhysicalObject is altijd al een hottopic geweest. Zowel vanuit de IMBOR community, als vanuit de LD gebruikers. Dit onderscheidt hebben we het dus ook al heel vaak over gehad. En veel mensen verwachten ook dat dit in de volgende versie geregeld zou moeten zijn. Met name Gelderland en de gemeente Amsterdam vragen hier om. Gelderland omdat dit onderscheidt in hun OTL reeds aanwezig is en anders geen goede mapping kan doen. De gemeente Amsterdam omdat ze willen beginnen met het ondersteunen van SE (waar dit uiteraard voor nodig is). Onze argumentatie toentertijd was dat wij enerzijds niet wisten wat het onderscheidt (semantisch) is en anderzijds dat we niet niet goed uit de data kan halen. Voor dat eerste punt willen we dus met de IMBOR community gaan zitten, voor het twee punt heeft IMBOR (Access) al de nodige aanpassingen gemaakt. Het is tevens de meest logische uitbreiding van ons metamodel. Nu zitten er (onterecht) zaken als PhysicalObject in die de meeste gebruikers niet zullen herkennen.

De semantiek tussen Fysiek en Functioneel wordt in een issue van de NTA8035 beschreven onder FunctionalPhysicalObject en MaterializedPhysicalObject. Daarnaast is @NielsHoffmann van mening dat er een verschil in inzicht en opvatting tussen ‘fysiek’ en ‘functioneel’ in de geo-wereld en de se-wereld. (en bij voorbaat excuses als het onzin blijkt te zijn…). Daarnaast attendeert @NielsHoffmann ons op het hoofdlijnenrapport van de SOR:  In het denkraam voor de samenhangende objectenregistratie zijn de objecttypen dus gecategoriseerd naar: Fysieke objecttypen, Functionele objecttypen, Registratieve objecttypen.

Binnen IMBOR-LD voorzagen we deze ingewikkelde discussie vandaar dat deze niet is meegenomen in de eerste versie. Nu we hier wel mee aan de slag willen gaan we ons baseren op de IMBOR community. Deze is hierin leidend. @ElisabethKloren is in overleg met @HarroVerhoeven en @JochemMollema om hier een eenduidig antwoord op te krijgen. Hierna zullen we de issue updaten met de beslissing.

**Comment by ElisabethKloren** [comment]
Antwoord van Geonovum gekregen:

NEN3610
Er wordt gewerkt aan een update van NEN3610. De planning is dat die in september ter consultatie gaat. 
•	In dat kader wordt er over een herindeling van objecttypen nagedacht. Bijgevoegd plaatje geeft daarbij de laatste inzichten weer waarbij ook een scheiding in Reëele (fysieke) en Virtuele (functionele en andere) objecten te zien is.
•	Er wordt op dit niveau ook overlegd met experts van NEN2660 en NTA8035.
•	Er vindt hierbij ook overleg plaats met onder meer vertegenwoordigers van DisGeo om tot een gezamenlijk beeld te komen

DisGeo
Er wordt gewerkt aan een uitwerking van het hoofdlijnenrapport (https://docs.geostandaarden.nl/disgeo/hiso/) via een groot aantal themawerkgroepen. De planning is dat dit in september rond is
•	In dit kader worden een aantal denklijnen uitgezet en uitgewerkt, maar nog niet gemodelleerd. Dat start stapsgewijs in de zomer.
•	Hier is wel voor de richting gekozen om fysieke, functionele en administratieve objecttypen te scheiden.  Hierbij worden de kaders van NEN3610 als uitgangspunt gehanteerd.

**Comment by ElisabethKloren** [comment]
@JochemMollema  klopt het dat in IMBOR ook dit onderscheid zit tussen fysieke, functionele en administratieve objecttypen, net als in NEN 3610? En hoe kunnen wij dat onderscheid zien bij het transformeren?

**Comment by RiX012** [comment]
Ik ben dit het helemaal met @NielsHoffmann eens. Maar ben wel nog benieuwd wat de intenties in IMBOR zijn geweest.

**Comment by RiX012** [comment]
> 
> 
> Ik ben dit het helemaal met @NielsHoffmann eens. Maar ben wel nog benieuwd wat de intenties in IMBOR zijn geweest.

Voorlopig lijkt dit goed genoeg om de implementatie van IMBOR te ondersteunen. Er is nu meer inzicht in de semantiek achter de IMBOR keuzes. Deze wordt uitgewerkt en zal in een volgende versie van IMBOR uitgebracht worden. Dan zal er ook meer aansluiting bij de NEN2767-4 en NEN2660 gepresenteerd worden.
