### ISSUE TITLE
NEN2660-2 modellering voor informatieobjecten. 

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#890]
Een aantal concepten zijn nu verkeerd gemodelleerd omdat we uit de NEN2660-2 ons wilde limiteren tot FysiekObject en InformatieObject. Deze zijn nu `InformatieObject` maar betreffen waarschijnlijk raakvlakken. Dit gaan we uitzoeken in 2022. Het betreffen in ieder geval:

- Opening kunstwerk
- Sluis doorvaart
- Rand groenobject
- Rand verhardingsobject

**Comment by RiX012** [comment]
@wjtmollema Hier moeten we het nog eens uitgebreid over hebben.

**Comment by RiX012** [comment]
> * Rand groenobject
> 
> * Rand verhardingsobject

Deze laten we vervallen omdat dit eigenlijk dynamische gegevens betreffen.

**Comment by RiX012** [comment]
> * Opening kunstwerk
> 
> * Sluis doorvaart

Omdat dit zo'n niche betreft, laten we deze voorlopig zo. Het modelleren als raakvlakken gaat voor nu te ver.

**Comment by GreenpointAdviesPN** [comment]
> > * Rand groenobject
> > * Rand verhardingsobject
> 
> Deze laten we vervallen omdat dit eigenlijk dynamische gegevens betreffen.

Je stelt dat dit dynamisch is, omdat het uit GIS te halen is? Dat is ontologisch misschien een goede reden om het informatieobject af te schieten. Echter, in het gebruik is dit een handig informatieobject. Al zal de lengte dan middels GIS bepaald worden, dit wordt meestal periodiek gedaan en behoefd dan een opslag. M.n. omdat dit best bewerkelijke GIS-berekeningen zijn.

**Comment by GreenpointAdviesPN** [comment]
Na discussie met collega komen we tot inzicht dat jullie gelijk hebben. Dit is data die niet voor iedereen op dezelfde manier geïnterpreteerd kan worden. Voor de een is een rand tussen gras en heesters wel een (relevante) rand groenobject, voor de ander niet. Dit hoort in een beheer discipline thuis en daarmee niet per sé in IMBOR. Zou je dit behouden, dan zou ook expliciet bepaald moeten worden wat een groenobject is en wat niet en dat is niet voor iedereen hetzelfde. Klopt het wat ik zeg of komen jullie toch tot andere inzichten?

**Comment by RiX012** [comment]
Dank voor de weloverwogen reactie @GreenpointAdviesPN. Het inzicht dat ten grondslag ligt aan de conclusie om dit als dynamisch gegeven te beschouwen is niet zozeer de dubbelzinnigheid van of een object een 'groenobject' is (want dat is immers een IMBOR-klasse en dus welbepaald). Het gaat juist om het automatisch gegenereerde karakter van de randen en hun volledige afhankelijkheid van de geometrie van IMBOR-objecttypes; dit maakt het onduidelijk hoe het bestaan van de randen zich verhoudt tot de grenzen van verschillende objectgeometrieën. Volgens de NEN 2660-2 zou dit gemodelleerd moeten worden als `Raakvlak`, maar het gebruik van een `InformatieObject` is hiervoor een misplaatste, naast het gegeven dat volgens de voorgaande interpretatie `Rand verhardingsobject` en `Rand groenobject` te dynamisch zijn voor de scope van IMBOR

**Comment by wjtmollema** [comment]
> > * Rand groenobject
> > * Rand verhardingsobject
> 
> Deze laten we vervallen omdat dit eigenlijk dynamische gegevens betreffen.

Deze actie is uitgevoerd.
