### ISSUE TITLE
Veeg frequentie (verhardingsobject - constructielagen en randen)  moet zijn suggestielijst

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#90]
In de acces db 2020-01 is de veegfrequentie opgenomen als vrije invoer, moet zijn suggestielijst

**Comment by JochemMollema** [comment]
Aangepast in versie 2020-08

**Comment by JochemMollema** [comment]
Afgehandeld in versie 2020-08.

Groet,

Jochem

Van: Harro Verhoeven <notifications@github.com>
Verzonden: donderdag 10 september 2020 12:02
Aan: Stichting-CROW/imbor <imbor@noreply.github.com>
CC: Jochem Mollema <jochem@inarea.nl>; Assign <assign@noreply.github.com>
Onderwerp: Re: [Stichting-CROW/imbor] Veeg frequentie (verhardingsobject - constructielagen en randen) moet zijn suggestielijst (#90)


Assigned #90<https://github.com/Stichting-CROW/imbor/issues/90> to @JochemMollema<https://github.com/JochemMollema>.

-
