### ISSUE TITLE
Rest-API Roosendaal en toegang voor opdracthnemer die toegang nodig heeft tot IMBOR

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#91]
Toegang tot de rest-API wordt niet alleen afgeschermd door sleutels voor het linked data platform, maar ook met abonnement op de kennisbank (?) - daardoor kan een opdrachtnemer van een Roosendaal de rest-API niet gebruiken. Moeten wij dit op zo'n manier afschermen, kunnen wij hier een oplossing voor bedenken? Dit zal vaker voorkomen, de provincies laten vaak een ander bureau voor zich werken om IMBOR te implenteren, een OTL op te stellen enzovoorts.

**Comment by RiX012** [comment]
We hebben hier voorlopig een oplossing voor om 'technische' mensen zoals in dit geval van een bureau. Een gratis abbo te geven waarmee ze toegang krijgen. 
Voor de lange termijn is hier nog geen solide oplossing voor. 
Dit is dezelfde kwestie als bij Provincie Utrecht speelt.

**Comment by RiX012** [comment]
Niet meer van toepassing vanwege IMBOR2022 (was issue voor IMBOR-LD 2020-08
