### ISSUE TITLE
Dubbeling van objecttypen onder Ongeclassificeerd object (Bord, Bak, Groenobject e.d.)

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#92]
Onder Hulpobject->Ongeclassificeerd object staat een lijst met objecttypen die ook als Beheerobject voorkomen.
o.a. Bord (OBB513) en Bord(OBC696). 
Volgens mij is Bord(OB696) dus niet echt een 'ongeclassificeerd object' het is alleen niet geclassificeerd tot op het detailniveau bij (OBB513)
En het levert daarbij problemen op met het opzoeken van eigenschappen op basis van Label, je krijgt dan namelijk allemaal dubbelingen omdat je zowel de eigenschappen van Bord (OBB513) als Bord(OBC696) krijgt.

Voorstel: Deze objecttypen onder Ongeclassificeerd object weghalen en de mogelijkheid bieden om een object niet specifieker te classificeren dan Bord(OBB513)

**Comment by RiX012** [comment]
In de LD versie is dit inderdaad niet wenselijk. Het is echter een 1-op-1 vertaling van de Access versie. Omdat deze vooralsnog leidend is kan deze nu nog niet opgepakt worden. Dit moet dus een inhoudelijk issue worden in de 2021-01 versie.
