### ISSUE TITLE
Weginrichtingsobject (415) onderdeel van de Vakdiscipline Bomen in tabel en niet in formulier Access

### ISSUE THREAD

**Issue by LuukWijnholts** [Stichting-CROW/imbor#93]
In de tabel X_VakdisciplinesObjecttype in de Access is het object Weginrichtingsobject (415) onderdeel van de Vakdiscipline Bomen. Dit is overgenomen in de IMBOR LD. In het formulier Vakdisciplines Bomen van de Acces komt deze niet voor. 

groep:V23 (Bomen) member: imbor:OBB415 (Weginrichtingsobject)

Ik denk dat dit object, samen met het vroegere object Boomspiegel niet meer onder de Vakdiscipline Bomen dient te vallen. Boomspiegel is van object verplaats naar eigenschap in de laatste versie.

**Comment by JochemMollema** [comment]
Deze melding is in versie 2020-08 afgehandeld.

Groet,

Jochem

Van: Harro Verhoeven <notifications@github.com>
Verzonden: donderdag 10 september 2020 11:55
Aan: Stichting-CROW/imbor <imbor@noreply.github.com>
CC: Jochem Mollema <jochem@inarea.nl>; Assign <assign@noreply.github.com>
Onderwerp: Re: [Stichting-CROW/imbor] Weginrichtingsobject (415) onderdeel van de Vakdiscipline Bomen in tabel en niet in formulier Access (#93)


Assigned #93<https://github.com/Stichting-CROW/imbor/issues/93> to @JochemMollema<https://github.com/JochemMollema>.
