### ISSUE TITLE
Actualisatie toelichting op LinkedData

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/imbor#936]
Is dit document nog actueel: https://docs.crow.nl/imbor/imbor-ld/
En onderdeel van de documentatie van IMBOR?

Geef eens een samenvatting, is dit document: "een toelichting op IMBOR in linkedData en de samenhang met NEN 2660-2"?

Of zou het onderdeel moeten zijn van deze technische documentatie? https://docs.crow.nl/imbor/techdoc/#imbor-in-linkeddata

**Comment by RiX012** [comment]
Deze hoort bij IMBOR2020-08, daar staat hij ook onder:
https://docs.crow.nl/#sectie-imbor

Ik zal dat in de ReSpec meer toelichten
