### ISSUE TITLE
Waarom zijn er zo veel eigenschappen als AnnotationProperty getypeerd?

### ISSUE THREAD

**Issue by NielsHoffmann** [Stichting-CROW/imbor#94]
Er is een behoorlijke lijst van eigenschappen als AnnotationProperty getypeerd. In de respec staat er heel kort over dat als het een 'eenheidsloze' eigenschap is, dat het dan een AnnotationProperty wordt, maar die redenering kan ik niet helemaal volgen.

Er zijn ook een hele serie eigenschappen niet nader getypeerd dan Property. Dat zou dan een betere oplossing zijn?
Een AnnotationProperty zou je volgens mij alleen willen gebruiken om je klasse te 'annoteren' (oftewel metadata over de klasse mee te geven. bv een imbor versie, of een bron verwijzing oid) 

Ik loop er tegenaan in de poging onze OTL te mappen naar IMBOR waarbij ik bijvoorbeeld wegvaknummer wil mappen en daarbij een DatatypeProperty uit onze OTL gelijk wil maken aan een AnnotationProperty in IMBOR...

**Comment by RiX012** [comment]
See also #87 

We laten de owl:Data / Annotation / ObjectProperty weg kunnen laten uit de data. Dit scheelt met mappen naar andere ontologieen (je maakt het generieker). Nadeel: Protege enzo interpreteert het niet lekker. We zouden dan wel weer de OWL properties op kunnen nemen als SHACL construct.  Voor de nieuwe release 2020-07 laten we de OWL properties er uit en wordt alles rdf:property. We gaan op basis van feedback die daarna komt kijken of dit handig is.
