### ISSUE TITLE
Goedkeuringsprocedure

### ISSUE THREAD

**Issue by EJvandekamp** [Stichting-CROW/imbor#943]
De goedkeuringsprocedure moet nog verder worden aangescherpt. Duidelijk gemaakt moet worden wie waar verantwoordelijk voor is.

**Comment by JHLJoosten** [comment]
@EJvandekamp, Volgens mij is die wel duidelijk maar moet deze nog worden geformaliseerd en inderdaad met man en paard worden genoemd.

**Comment by JHLJoosten** [comment]
In overleg met Evert Jan. Opgelost
