### ISSUE TITLE
Hoofdstukindeling H5 verdwenen uit inhoudsopgave en zijbalk

### ISSUE THREAD

**Issue by EJvandekamp** [Stichting-CROW/imbor#945]
Ik heb wat wijzigingen doorgevoerd in H5 en zijn verschillende paragrafen uit de dit hoofdstuk verdwenen uit de inhoudsopgave en in de zij balk. Hoe kan ik dit herstellen?

**Comment by ElisabethKloren** [comment]
hij doet 't weer (over een kwartier)
