### ISSUE TITLE
Aanscherpen relaties LigtIN, HoortBIJ en OnderdeelVAN

### ISSUE THREAD

**Issue by HarroVerhoeven** [Stichting-CROW/imbor#95]
In IMBOR worden nu 3 attributen gebruiken om de objecten aan elkaar te relateren:
•	LigtIN
•	HoortBIJ
•	OnderdeelVAN
Af en toe is het best lastig om te bepalen welke van deze relaties toegepast moet worden. Kunnen wij dit misschien aanscherpen m.b.v. de NTA 8035?

**Comment by RiX012** [comment]
Heel fijn dat deze boven komt Harro. Dit is precies wat lastig is als 'de semantiek' niet duidelijk is. Er zijn twee manieren om dit aan te pakken, maar beiden beginnen met: achterhalen wat er bedoelt is toen twee objecten aan elkaar gerelateerd werden. Dus onafhankelijk van welke relatie jullie gebruikt hebben. Als we dat weten dan kunnen we  1) kijken of er standaard is (zoals de NTA bv) die een overeenkomstige relatie heeft en/of 2) een IMBOR definitie aan een relatie geven. Daarna zetten we een modelleerregel op zodat iedereen die deze relatie zal gaan leggen/gebruiken dat op dezelfde manier doet.

**Comment by JochemMollema** [comment]
IMBOR-team: dit wordt uitgewerkt via een nieuw onderdeel binnen IMBOR, de semantische relaties.
