### ISSUE TITLE
Almelo: type Smart drainput bij drainageput

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#954]
Toevoegen type Smart drainput bij drainageput

**Comment by JochemMollema** [comment]
Staat nog niet in GWSW, eerst bespreken met Rioned

**Comment by MarinusVonhof** [comment]
Dit aanpassingsvoorstel is bij RIONED geregistreerd onder nr 1237.
Op 2 november 2023 volgt beoordeling door de werkgroep GWSW-Basis en daarna volgt publicatie van de uitslag op https://data.gwsw.nl/ .
