### ISSUE TITLE
Almelo: verbeterd vuilwaterstelsel kan niet geregistreerd worden.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#955]
Verbeterd vuilwaterstelsel kan niet geregistreerd worden.

**Comment by JochemMollema** [comment]
Staat nog niet in GWSW Basis, bespreken met Rioned

**Comment by MarinusVonhof** [comment]
Dit aanpassingsvoorstel is bij RIONED geregistreerd onder nr 1238.
Op 2 november 2023 volgt beoordeling door de werkgroep GWSW-Basis en daarna volgt publicatie van de uitslag op https://data.gwsw.nl/ .
