### ISSUE TITLE
Utrecht: bij verkeerslantaarn het attribuut knipperen toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#962]
bij verkeerslantaarn het attribuut knipperen toevoegen

**Comment by JochemMollema** [comment]
Knipperen als boolean toegevoegd aan Verkeerslantaarn.

**Comment by wjtmollema** [comment]
De gemeente Utrecht mistte voor de registratie van het objecttype Verkeerslantaarn een gestandaardiseerd gegeven waarmee vastgelegd kan worden of een Verkeerslantaarn in een knipperstand gezet kan worden, bijvoorbeeld wanneer ze defect of in onderhoud zijn.

**Comment by RiX012** [comment]
Ah, ok. Als dat duidelijk wordt uit de definitie dan is het prima. Het label 'AanwezigheidKnipperstand' had me wellicht meer op weg geholpen :)
