### ISSUE TITLE
Groenobject soortnaam / rand beheer

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#97]
![2020-07-23 14_15_41-frmIMBOR_Groenobject](https://user-images.githubusercontent.com/40396592/88285389-47148a80-ccef-11ea-8094-1a96b81ca395.png)

1.Bij de soortnaam kun je een hoeveelheid opnemen. Hierbij is de eenheid altijd een percentage van het oppervlak. 
Hierdoor komt het veld eenheid eigenlijk te vervallen, als het % teken als waarde achter Hoeveelheid wordt opgenomen.

2. Randen > Beheer 
Uit het model is niet terug te halen dat het een boolean is, aan de voorkant wel.

**Comment by redmer** [comment]
Bedankt voor je melding. We gaan ermee aan de slag.

**Comment by JochemMollema** [comment]
Je kunt hier ook kiezen voor een andere eenheid voor het registreren van de hoeveelheid.
Bij de rand is Beheer als Boolean-veld terug te vinden.
