### ISSUE TITLE
Activiteiten ombouwen tot echte functies binnen de NEN2660-2

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#970]
Herziening #891 

Bij de afronding van IMBOR2022 constateerden we nog één semantische kwestie. Het gaat om de Functies die een object/systeem uitvoert. In IMBOR declareren we dus een lijst van mogelijke relaties tussen fysieke objecten en activiteiten (voert uit). Dit zijn voor de assetmanagers ‘functies’ die het object kan uitvoeren. In het beheersysteem kiezen ze er dus één of meerdere van. 
 Maar wat zijn functies nu in de IMBOR ontologie? We hebben zenu als subclass van nen2660:Activity.  Check bij NEN2660-2
_Antwoord Michel Bohms: Subclass van Activity EN van FunctionalEntity; “ Functie’ die dit al doet hebben we nog niet gedefinieerd; zou je in otl kunnen doen._

Kortom:
- Nieuwe klasse `Functie`. Met de definitie: _"Een activiteit die uitgevoerd wordt door een object, wiens externe gedrag bijdraagt aan gestelde doelen door één of meerdere technische entiteiten."_
- Deze heeft als parents: `Activiteit` (nen2660:Activity) en `FunctioneleEntiteit` (nen2660:FunctionalEntity)
- Alle huidige subklassen van `Activiteit` worden direct subklasse van `Functie`
- Op deze `Functie` wordt ook het attribuut `hoofdfunctie` geïntroduceerd. Met de definitie: "Aanduiding of het de belangrijkste uit te voeren activiteit van het object betreft.". Het datatype is `xsd:boolean`
- Alle relaties blijven hetzelfde
- IMBOR startscherm in AccesDB moet aangepast worden.

**Comment by JochemMollema** [comment]
Voorgestelde aanpassingen zijn doorgevoerd.
