### ISSUE TITLE
TypeAfsluiting = Deur is dubbel met Kunstwerk heeft deel Deur

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#971]
Wat te doen met TypeAfsluiting = Deur bij een Kunstwerk?

Wegens de introductie van het `Deur` als objecttype is deze dubbel. Bekeken moet worden of het voor andere `TypeAfsluiting` geldt.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
Het laten fungeren van `ObjectType`n als domeinwaarde is ongewenst in een attribuut waarin in principe als domeinwaarden alleen termen van de collectie `Domeinwaarde` benodigd zijn (viz. het verschil tussen `standplaats`, `grondsoortnaam` etc. en `type afsluiting`). 

De term voor het `ObjectType` `Deur` zou weer gewijzigd kunnen worden naar `Toegangsdeur`. In de definitie en de enumeratietypes voor `Deur` wordt overigens nog steeds gesproken over `Toegangsdeur`. Stel dat `Deur` als term behouden blijft, dan moeten in ieder geval de definities voor `Deur` en de bijbehorende enumeratietypes gewijzigd worden.

Zoals @RiX012 aangeeft in de issue zelf, wijst dit op een breder probleem. Een analyse van de domeinen in termen van de collecties `ObjectType` en `Domeinwaarde` levert de volgende intersectie op. Tussen parentheses is weergegeven waar de term als `Domeinwaarde` voorkomt.

- Baan voor vliegverkeer (`Verharding :: gebruiksfunctie`)
- Deur (`type afsluiting`)
- Fietspad (`Verharding :: gebruiksfunctie`)
- Gemeente (`eigenaar`, `beheerder`)
- Inrit (`Verharding :: gebruiksfunctie`)
- Loopdek (`Verharding :: gebruiksfunctie`)
- Molgoot (`Verharding :: gebruiksfunctie`)
- Overweg (`Verharding :: gebruiksfunctie` en `type` van het `ObjectType` `Kruispunt` **!**)
- Parkeergarage (`Verblijfsobject :: feitelijk gebruik gedetailleerd`)
- Parkeervoorziening (`Verharding :: gebruiksfunctie`)
- Plantenbak (`Plantenbak :: soort plantenbak`)
- Provincie (`eigenaar`, `beheerder`)
- Radar (`Verkeerstelling :: meetinstrument`)
- Rijbaan (`Verharding :: gebruiksfunctie`)
- Spoorbaan (`Verharding :: gebruiksfunctie`)
- Trap (`Verharding :: gebruiksfunctie`)
- Uitkijktoren (`Speeltoestel :: type extra gedetailleerd`)
- Veiligheidsregio (`eigenaar`, `beheerder`)
- Verkeersdrempel (`gebruiksfunctie`)
- Verkeerseiland (`gebruiksfunctie`)
- Vlonder (`Boom :: boomvoorziening`)
- Voetpad (`Verharding :: gebruiksfunctie`)
- Waterschap (`eigenaar`, `beheerder`)
- Zwembad (`Verblijfsobject :: feitelijk gebruik gedetailleerd`)

Als zodanig levert dit negen verschillende gevallen op:
1. `gebruiksfunctie`: Deze overlap is intentioneel gemodelleerd;
2. `eigenaar`, `beheerder`: Deze overlap is intentioneel gemodelleerd;
3. `type afsluiting`: Deze overlap is problematisch, want onnodig en moet worden weggewerkt m.b.v. een wijzigingsvoorstel;
4. `Speeltoestel :: type extra gedetailleerd`: Deze overlap is problematisch, want onnodig en moet worden weggewerkt m.b.v. een wijzigingsvoorstel;
5. `type` van het `ObjectType` `Kruispunt`: Deze overlap is problematisch, want onnodig en moet worden weggewerkt m.b.v. een wijzigingsvoorstel;
6. `Boom :: boomvoorziening`: Voor de kwestie `boomvoorziening`, zie de separate bespreking in #579 ;
7. `Verblijfsobject :: feitelijk gebruik gedetailleerd`: Dit is veroorzaakt door de afstemming met de SOR, dit kan intentioneel zijn gemodelleerd;
8. `Verkeerstelling :: meetinstrument`: Deze overlap is problematisch, want onnodig en moet worden weggewerkt m.b.v. een wijzigingsvoorstel;
9. `Plantenbak :: soort plantenbak`: Deze overlap is problematisch, want onnodig en moet worden weggewerkt m.b.v. een wijzigingsvoorstel;

**Comment by wjtmollema** [comment]
**Corollarium**
Voor ieder van de negen gevallen wordt in dit bericht een wijzigingsvoorstel gedaan. 

1. `gebruiksfunctie`: Deze overlap is intentioneel gemodelleerd. Er kan gekeken worden naar een modelleringsconstructie waarbij binnen `gebruiksfunctie` zowel `ObjectType`n als `Domeinwaarde`n worden toegestaan. Dit zou tot een reductie leiden van 13 overvloedige domeinwaarden omdat hun rol vervuld zou worden door de semantisch equivalente `ObjectType`n. 
2. `eigenaar`, `beheerder`: Deze overlap is intentioneel gemodelleerd; Er kan gekeken worden naar een modelleringsconstructie waarbij binnen `gebruiksfunctie` zowel `ObjectType`n als `Domeinwaarde`n worden toegestaan. Dit zou tot een reductie leiden van 4 overvloedige domeinwaarden omdat hun rol vervuld zou worden door de semantisch equivalente `ObjectType`n. 
3. `type afsluiting :: Deur`: Zie het voorstel in het bovenstaande bericht. 
4. `Speeltoestel :: type extra gedetailleerd`: Het voorstel luidt om de `Domeinwaarde` van `Speeltoestel` te wijzigen naar `Speeluitkijktoren` of naar `Frame klimtoestel met uitkijktoren`.
5. `type` van het `ObjectType` `Kruispunt`: Of het `type` `Overweg` moet komen te vervallen, of het `ObjectType` `Overweg`. De definities komen bij beoordeling op het hetzelfde neer.
6. `Boom :: boomvoorziening`: Voor de kwestie `boomvoorziening`, zie de separate bespreking in #579 ;
7. `Verblijfsobject :: feitelijk gebruik gedetailleerd`: De problematische termen zijn `Zwembad` en `Parkeergarage`. 
- Voor `Zwembad` geldt dat er een andere intersectie is, namelijk met `Sportterrein :: type :: Open lucht zwembad`. Er kan gekozen worden voor het hernoemen van de term `ObjectType` `Zwembad` naar `Open lucht zwembad` en het laten vervallen van `Sportterrein :: type :: Open lucht zwembad`. Met `Verblijfsobject :: feitelijk gebruik gedetailleerd :: Zwembad` wordt immers een 'zwemhal' met alle bijbehorende voorzieningen bedoeld, terwijl met `ObjectType` `Zwembad` op de constructie wordt geduid die in de openbare ruimte ligt.
- Voor `Parkeergarage` kan er gekozen worden voor het laten vervallen van `Verblijfsobject :: feitelijk gebruik gedetailleerd :: Parkeergarage` en de projectie van de SOR naar IMBOR op het `ObjectType` `Parkeergarage` te laten vallen.
9. `Verkeerstelling :: meetinstrument`: Er kan gekeken worden naar een modelleringsconstructie waarbij binnen `gebruiksfunctie` zowel `ObjectType`n als `Domeinwaarde`n worden toegestaan. Anderzijds kan de `Domeinwaarde` `Radar` voor `VerkeerstellingMeetinstrument` aangepast worden naar `Radarmeting`. Dit zou de dubbeling ook wegwerken.
10. `Plantenbak :: soort plantenbak`: Er kan gekeken worden naar een modelleringsconstructie waarbij binnen `gebruiksfunctie` zowel `ObjectType`n als `Domeinwaarde`n worden toegestaan. De definitie van `Domeinwaarde` `Plantenbak` luidt: "Plantenbak in de vorm van een rechthoekige bak." Een substituut hiervoor zou daardoor de term `Rechthoekige plantenbak` kunnen zijn.

**Comment by wjtmollema** [comment]
**Addendum**
De constateringen en voorstellen die zijn omschreven in de bovenstaande berichten zijn onderdeel van een bredere discussie omtrent het formuleren van modelleringsregels voor uitbreidingen aan en wijzigingen van IMBOR. Sommige van de geïdentificeerde conflicten, zoals het gebruiken van `ObjectType`n als domeinwaarden of het gebruiken van `Objecttype`n als `gebruiksfunctie` of `Activiteit`, vragen om de verheldering van de principes en stelregels die het modelleren conform NEN 2660-2 en NEN 3610 met zich meebrengen. Deze gevallen zullen ook als zodanig geadresseerd worden.

Voor de niet-principiële conflicten, zoals de terminologisch oplosbare gevallen, zullen de bovenstaande voorstellen geaccordeerd moeten worden.

**Comment by RiX012** [comment]
@wjtmollema volgende keer bespreken

**Comment by RiX012** [comment]
We gaan hier modelleren conform de NEN2660-2. Dit zal het uitgangspunt voor IMBOR2024 worden en daarmee is deze issue binnen scope om compliant te worden met de NEN2660-2.

**Comment by wjtmollema** [comment]
Om eindelijk tot een oplossing te komen voor deze gevallen, zijn de oplossingsrichtingen opnieuw op een rij gezet, waarbij de conformiteit van de oplossing aan de NEN2660-2 is beoordeeld.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


ID | Naam | Oplossing | Conform NEN2660-2
-- | -- | -- | --
1 | gebruiksfunctie: overlap   objecttypen/domeinwaarden | Gebruiksfuncties hernoemen zodat overlap met objecttypes verdwijnt | Nee, deze domeinwaarden moeten als Functies uitgewerkt gaan worden, zie #878.
2 | eigenaar, beheerder:   overlap objecttypen/domeinwaarden | Gemeente, Provincie, Veiligheidsregio en Waterschap zijn zowel objecttype als domeinwaarde. Als enige uitzondering handhaven? Wellicht onnodig na de hermodellering van beheerder en eigenaar, zie #1258  | Ja
3 | type afsluiting: overlap objecttypen/domeinwaarden | Domeinwaarde Deur wijzigen naar Toegangsdeur | Ja
4 | Speeltoestel :: type extra gedetailleerd | Domeinwaarde Uitkijktoren wijzigen naar Speeluitkijktoren | Ja
5 | Kruispunt :: type | Domeinwaarde Overweg laten vervallen | Ja
6 | Boomvoorziening | Niet langer van toepassing | Ja
7 | Verblijfsobject: Zwembad en Parkeergarage | Objecttype Zwembad --> Open lucht zwembad. Sportterrein :: type ::   Zwembad laten vervallen. | Ja
8 | Verkeerstelling   :: meetinstrument | Moet in principe vervallen omdat het dynamische gegevens betreft | Ja
9 | Plantenbak :: soort plantenbak | Domeinwaarde Plantenbak wijzigen in Rechthoekige plantenbak | Ja



</body>

</html>

**Comment by RiX012** [comment]
Ok mooie oplossingen. 

- Bij nummer 1 komen we wel uit als we ze gaan hernoemen en opschonen. 
- Nummer 2 moet inderdaad opgelost worden door #1258. Dan kunnen ze verdwijnen. 
- Bij 3 moet dan ook de definitie aangepast worden. 
- Bij 9, wat als er dan een ovale is?

**Comment by RiX012** [comment]
Issue kan worden doorgevoerd en afgerond. Behalve onderstaand item. Dit wordt opgelost met #878 

> 1 	gebruiksfunctie: overlap objecttypen/domeinwaarden 	Gebruiksfuncties hernoemen zodat overlap met objecttypes verdwijnt 	Nee, deze domeinwaarden moeten als Functies uitgewerkt gaan worden, zie #878.

**Comment by wjtmollema** [comment]
Verwerkt zoals voorgesteld. Voor punt 8 wordt een ander impact 2 issue aangemaakt om deze modellering te borgen
