### ISSUE TITLE
Spatie aan het eind van activiteit 'Afvoeren hemelwater naar de ondergrond '

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#972]
De activiteit "Afvoeren hemelwater naar de ondergrond " bevat een spatie aan het eind. Het hoort te zijn: "Afvoeren hemelwater naar de ondergrond"

**Comment by GreenpointAdviesPN** [comment]
Ook activiteit "Overbruggen groot niveauverschil " bevat een spatie aan het eind.

**Comment by wjtmollema** [comment]
**Verwerking**
De spatie is verwijderd.

**Motivatie**
Melder wees terecht op de aanwezigheid van een overbodige spatie als laatste teken van de term.
