### ISSUE TITLE
Materiaaltype "Geopolymeer"

### ISSUE THREAD

**Issue by GreenpointAdviesPN** [Stichting-CROW/imbor#973]
Ik kom bij een klant een vorig jaar aangelegde rioolbuis tegen die van "Geopolymeer" gemaakt is. Via internet lees ik dat dit een vrij nieuw materiaal is in de rioolwereld. Kan dit materiaal toegevoegd worden aan de materie-lijst en gekoppeld worden aan i.i.g. klasse 'Rioolleiding'?

**Comment by wjtmollema** [comment]
**Verwerking**
'Geopolymeer' is als term van de collectie 'Materie' toegevoegd.

**Motivatie**
De melder heeft een materiesoort aangedragen die een waardevolle toevoeging is.
