### ISSUE TITLE
Provincie Gelderland: ANWB-mast moet NBD-mast zijn.

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#974]
Provincie Gelderland: ANWB-mast moet NBD-mast zijn.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
De term `ANWB-mast` wordt aangepast naar `NBd-mast` aangezien de definities hetzelfde zijn. De Nationale Bewegwijzeringsdienst is sinds 2015 volledig verantwoordelijk voor de nationale bewegwijzering. Feitelijk was de opname van de term `ANWB-mast` die de werkelijke masten representeerde tijdens haar inceptie in IMBOR een _misnomer_ en had het toentertijd al `NBd-mast` moeten zijn. Echter, in het alledaags taalgebruik wordt er nog gesproken over `ANWB-mast`, vanwege de herinnering aan de soms nog door de ANWB geplaatste en in het verleden beheerde masten. Daarom is het voorstel om aansluitend op de terminologische wijziging `ANWB-mast` als `synoniem` van `NBd-mast` op te nemen.
