### ISSUE TITLE
Provincie Gelderland: codes toevoegen voor synchronisatie met het centraal haltebestand

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#975]
Provincie Gelderland: codes toevoegen voor synchronisatie met het centraal haltebestand.

Onderstaand de juiste benamingen van de beide code velden die in het Centraal Halte Bestand (CHB) worden bijgehouden. De codes die in de kaders vermeld staan zijn de codes zoals ik deze vanuit het CHB heb overgenomen in GISIB.

Attributen toevoegen bij Halteplaats:
- quaycode CHB, schrijfwijze NL:Q:Nummer
- stopplacecode CHB schrijfwijze NL:S:Nummer

**Comment by wjtmollema** [comment]
**Verwerking**
Het attribuut 'stopplacecode' is toegevoegd aan imborVoc_Termen en imborKern_Attributen. Toegevoegd aan de klasse 'Halteplaats' in imborKern_K_KlassenAttributen.
 Het attribuut 'quaycode' is toegevoegd aan imborVoc_Termen en imborKern_Attributen. Toegevoegd aan de klasse 'Halteplaats' in imborKern_K_KlassenAttributen.

**Motivatie**
De attributen vormen een waardevolle toevoeging voor de klasse 'Halteplaats' omdat ze de connectie van het objecttype 'Halteplaats' met het CHB consolideren.
