### ISSUE TITLE
Utrecht: hoe kunnen werfkelders en werfmuren (historische objecten) verwerkt worden?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#976]
Utrecht: hoe kunnen werfkelders en werfmuren (historische objecten) verwerkt worden?

**Comment by wjtmollema** [comment]
**Constatering**
In de praktijk heeft men gekozen voor een modellering van de in de gemeentelijke data voorkomende `Werftrap` en `Werfmuur` als bestaande `ObjectType`n.
- `Werftrap`: `ObjectType` `Toegangstrap`; `objectnaam :: Werftrap`; `Monument-informatie :: type monument :: Gemeentelijk monument`;
- `Werfmuur`: `ObjectType` `Kademuur`; `objectnaam :: Werfmuur`; `Monument-informatie :: type monument :: Gemeentelijk monument`.

De generieke oplossing voor 'historische' objecten die hier is toegepast, is:
1. _Kies voor het `ObjectType` met de grootste semantische overeenkomst_;
2. _Registreer de historische benaming onder `objectnaam` t.b.v. van vindbaarheid binnen de gemeente_
3. _Stel de monumentale waarde veilig m.b.v. het `InformatieObject` `Monument-informatie` door het juiste `type monument` te koppelen._

Er moet echter beoordeeld worden of deze oplossingsrichting toereikend is voor alle mogelijke historische objecten.

**Comment by wjtmollema** [comment]
**Addendum**
Het gebruik van `objectnaam` is het misbruiken van dit attribuut t.b.v. informatie die eigenlijk binnen `Monument-informatie` zou moeten worden ondergebracht. Het formele wijzigingsvoorstel is daarom als volgt:
- Het toevoegen van een attribuut `type monument gedetailleerd` van het attribuuttype `Referentie` om specifieke benamingen te kunnen registreren voor monumenten, zoals `Werftrap`, `Werfmuur` en `Werfkelder`.
