### ISSUE TITLE
Almelo: bij sportveld ook Klootschietbaan opnemen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#977]
Almelo: bij sportveld ook Klootschietbaan opnemen

**Comment by wjtmollema** [comment]
**Verwerking**
'Klootschietbaan' is opgenomen  in imborVoc_Termen en in imborKern_EnumeratiesDomeinwaarden toegekend aan 'SportveldType.'

**Motivatie**
In IMBOR 2022 ontbrak deze typering. De gemeente Almelo en andere gemeenten in de provincie Overijssel vormen praktijkvoorbeelden voor de toepassing van sportvelden t.b.v. klootschieten.
