### ISSUE TITLE
Sliedrecht: kan de vaste lijst van het attrbuut groenstructuur uitgebreid worden?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#979]
Kan de vaste lijst van het attribuut groenstructuur uitgebreid worden met de volgende waarden: hoofdgroen, wijkgroen en buurtgroen

**Comment by wjtmollema** [comment]
In samenwerking met de gemeente Utrecht is er nagedacht over de mogelijke uitbreiding van de enumeratietypes van dit attribuut. 

Hieronder het resultaat dat als input kan dienen voor verdere uitwerking van deze issue. Onderdeel van het voorstel is de toevoeging van het attribuut `groenstructuur gedetailleerd`.
-  `groenstructuur :: Onderdeel ecologische structuur`
1. `groenstructuur gedetailleerd :: Natuurontwikkelingsgebied`
2. `groenstructuur gedetailleerd :: Natuurterrein` (andere aanduiding `Kerngebied`, omdat dit al een objecttype is)
3.  `groenstructuur gedetailleerd :: Ecologische verbindingszone`

-  `groenstructuur :: Onderdeel landschappelijke groenstructuur`
1. `groenstructuur gedetailleerd :: Dijkbeplanting`
2. `groenstructuur gedetailleerd :: Beekbegeleiding`
3. `groenstructuur gedetailleerd :: Singel`
4. `groenstructuur gedetailleerd :: Koeienbocht`
5. `groenstructuur gedetailleerd :: Erfbeplanting`

- `groenstructuur :: Onderdeel stedelijke groenstructuur`
1. `groenstructuur gedetailleerd :: Hoofdgroen`
2. `groenstructuur gedetailleerd :: Buurtgroen`
3. `groenstructuur gedetailleerd :: Wijkgroen`

**Comment by JochemMollema** [comment]
Na overleg is bepaald dat de bestaande indeling gehandhaaft blijft en dat met behulp van semantisce relaties een extra detaillering aangebracht kan worden.

**Comment by JochemMollema** [comment]
@RiX012 deze issue kan gesloten worden.
