### ISSUE TITLE
Attribuut definitie groenobject niet uitgeschreven

### ISSUE THREAD

**Issue by ernst63** [Stichting-CROW/imbor#98]
![2020-07-23 14_22_50-frmIMBOR_Verhardingsobject](https://user-images.githubusercontent.com/40396592/88285906-2bf64a80-ccf0-11ea-85e9-fc61ff24231c.png)
![2020-07-23 14_22_21-frmIMBOR_Groenobject](https://user-images.githubusercontent.com/40396592/88285923-3284c200-ccf0-11ea-8377-d2cd750219c5.png)

In tegenstelling tot bij het verhardingsobject zijn de attribuutwaarden-velden wel uitgeschreven. Voor Groen objecten dit ook graag realiseren en verder waar dit van toepassing is. Wellicht goed om de benaming van het tabblad ook uniform te maken.
Zie ook Soort constructielaag (bij groenobject)  en Constructielaagsoort (verhardingsobject)
Daarnaast is ook attribuut Knipoppervlak aan de voorkant niet gelijk aan de attribuutdefinitie ( knipoppervlakte)

**Comment by JochemMollema** [comment]
Definitie   groenobject aangepast, attribuut groenobject is vervallen. Koppeling tussen groenobject en onderdeel wordt via semantische relaties opgelost.
--
