### ISSUE TITLE
Unafact: aansluiting bij GWSW Gemalen, heroverwegen Gemalen opdelen in veschillende objecttypen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#980]
Aansluiting bij GWSW Gemalen, heroverwegen Gemalen opdelen in veschillende objecttypen

**Comment by wjtmollema** [comment]
@RiX012 Volgens mij wordt dit opgelost met de aankomende afstemming tussen IMBOR en GWSW 2.0 en kan deze issue gesloten worden.
