### ISSUE TITLE
Opname van Terras als objecttype

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#981]
Opname van Terras als objecttype binnen klasse Urbane beheerzone

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- Het toevoegen van het `ObjectType` `Terras` als `subKlasseVan` `Urbane beheerzone`;
- het toevoegen van het attribuut `bor-type` aan de klasse `Terras`.

**Motivatie**
- Er is gemeentelijk belang bij het registreren van terrasgrenzen. Tevens bevat NLCS al symbologie voor een `TERRAS`.
