### ISSUE TITLE
Incorrecte vertegenwoordiging RWS in bijlage2.md

### ISSUE THREAD

**Issue by mickbaggen** [Stichting-CROW/imbor#982]
In het document imbor/tree/master/docs/beheerplan/hoofdstukken/bijlage2.md wordt L. Heres (Rijkswaterstaat Data-ICT-Dienst) genoemd als lid van de stuurgroep, peildatum 16-03-2022. 

Dit is echter niet correct: Luc Heres is een (zeer gewaardeerde) oud-RWS-collega, die bij mijn weten inderdaad lid geweest van deze stuurgroep, maar die al een kleine twee jaar met pensioen is gegaan. En de RWS Data-ICT-Dienst bestaat al niet meer sinds 2013: dat is inmiddels de Dienst Centrale Informatievoorziening (CIV) geworden.

Voorstel: L. Heres als actueel lid namens RWS verwijderen uit bijlage 2.

**Comment by EJvandekamp** [comment]
@mickbaggen, dank voor het doorgeven. Naar aanleiding van je voorstel heb ik L. Heres namens RWS verwijderd uit bijlage 2 van het beheerplan IMBOR.
