### ISSUE TITLE
Amsterdam: Registratie van een Plantaarn: combinatie van een lichtmast en een groenobject

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#984]
Registratie van een Plantaarn: combinatie van een lichtmast en een groenobject

**Comment by WisseDQ** [comment]
Deze zou ik apart houden. Als lichtmast en klimplant registreren.

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- Onveranderd laten van `ObjectType` `Paal :: type :: Lichtmast`
- Onveranderd laten van `ObjectType` `Klimplant`
- Optie 1 (`Plantaarn` als zelfstandig `ObjectType`): het toevoegen van een `ObjectType` `Plantaarn` waarvoor geldt: `Paal :: heeftDeel :: Plantaarn` en `Klimplant :: isVerbondenMet :: Plantaarn` 
- Optie 2 (`Plantaarn` als `type` van `Paal`): `Plantaarn` als domeinwaarde toevoegen aan het enumeratietype `PaalType`
- Optie 3 (`Plantaarn` als domeinwaarde van `voetconstructie`): `Plantaarn` als domeinwaarde toevoegen aan het enumeratietype `PaalVoetconstructie`.

**Motivatie**
Kijkend naar de constructie van een `Plantaarn` is er sprake van drie objecten: (1) `Lichtmast`; (2) `Klimplant`; en (3) de stalen cilinder waartegen de `Klimplant` groeit. Voor optie (1) valt in te brengen dat de stalen cilinder beschouwd kan worden als zelfstandig object, dat niet gelijkstaat aan zowel de `Lichtmast` of de `Klimplant`. Voor optie (2) daarentegen kan als argument ingebracht worden dat het ongewenst is om de stalen cilinder als zelfstandig object te registreren omdat het vanuit het perspectief van het beheren van de `Plantaarn` voldoende zou kunnen zijn om over gegevens ven de `Lichtmast` en de `Klimplant` te beschikken. Ten gunste van optie (3) kan tot slot gesteld worden dat `Plantaarn` geen goed `type` van `Paal` is, omdat het daar onduidelijk schept over of de `Plantaarn` van toepassing is bij een `Lichtmast` of een `Verkeerslichtmast` (etc.). Omdat de `Plantaarn` op de voet van de `Paal` in de grond wordt bevestigd, is er gekozen voor de suggestie `Paal :: voetconstructie :: Plantaarn`.

**Comment by wjtmollema** [comment]
**Addendum**
Er is gekozen voor Optie 1. Dit heeft de volgende wijzigingen tot gevolg:
- `Plantaarn` wordt als zelfstandig `ObjectType` toegevoegd als `subKlasseVan` `Straatmeubilair`;
- Het voorkomen van een `Plantaarn` is de stalen cilindervormige kokerconstructie. `Plantaarn` is als zodanig onderscheiden van `Paal` en `Klimplant`;
- De relaties met `Paal` en `Klimplant` kunnen m.b.v. semantische relaties gelegd worden, zoals wordt uitgewerkt in het bovenstaande bericht.
