### ISSUE TITLE
Amsterdam BMIDMS: hoe kan een slaghek geregistreerd worden in IMBOR?

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#986]
Registratie Slaghek

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
De WikiWoordenboek-definitie van 'slaghek' is: "Hek dat door schuine stand vanzelf dichtklapt na openen." Er is zeer weinig informatie te vinden over hoe een slaghek er uit zou moeten zien. Qua definitie is een `Klaphek` ook een slaghek; echter zouden ook `Draaihek` (naar binnen toe draaiend slaghek) en `Schuifhek` (slaghek met schuif) hieronder kunnen vallen.
