### ISSUE TITLE
Waardenlijst type reiniging moet vaste lijst (enumeratie) zijn en geen suggestielijst (referentie)

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#989]
Waardenlijst type reiniging moet vaste lijst (enumeratie) zijn en geen suggestielijst (referentie)

**Comment by JochemMollema** [comment]
Waardenlijst type reiniging moet vaste lijst (enumeratie) zijn en geen suggestielijst (referentie)

**Comment by wjtmollema** [comment]
**Verwerking**
De waardenlijst van het attribuut 'type reiniging' is aangepast van referentietype naar enumeratietype.

**Motivatie**
De melding betreft een fout die aanwezig was in de publicatieversie van IMBOR 2022. De fout is gerectificeerd.
