### ISSUE TITLE
Viersoorten Koffers onder klasse kunstwerk

### ISSUE THREAD

**Issue by WisseProgresity** [Stichting-CROW/imbor#990]
**Is dit verzoek gerelateerd aan een probleem? Beschrijf die hier a.u.b.**
Onder Klasse kunstwerk staan vier Objecttypen met Koffer:
Grindkoffer
Lavakoffer
Steenwolkoffer
Zandkoffer

Is het niet beter om deze een niveau omlaag te plaatsen naar Type. En inplaats daarvan het Objecttype 'Koffer' te hanteren?

**Beschrijf de oplossing die je voor je ziet**
Verplaatsen naar Type.

**Wat voor alternatieven heb je overwogen?*
Nee

**Meer context**

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking** (kan als input fungeren voor een werkgroep)
Kijkend naar de definities van `Zandkoffer`, `Lavakoffer` en `Steenwolkoffer` (die allen de vorm hebben van "Een constructie gevuld met **X** waar regenwater de tijd krijgt om langzaam in de bodem opgenomen te worden.") is dit een zinnige suggestie. De definitie van `Grindkoffer` wijkt af maar slaat op hetzelfde principe (een constructie gevuld met een bepaald materiaal ten behoeve van de infiltratie van regenwater). 

De `ObjectTypen` zijn onderdeel van IMBOR 2022 vanwege de afstemming met GWSW. In GWSW zijn er echter geen definities gegeven van de  `ObjectTypen`, maar voor alle vier geldt dat `Heeft supertype: Infiltratiereservoir` binnen GWSW. Deze gemeenschappelijke superklasse maakt dat er in IMBOR ook voor een superklasse is gekozen (namelijk: `Kunstwerk`). Als zodanig kan bevonden worden dat de 'koffers' genoeg gemeen hebben om tot een `type` van een en hetzelfde `ObjectType` `Koffer` (`subKlasseVan` `Kunstwerk`) te behoren.

**Comment by JochemMollema** [comment]
Koffers zijn onder de nieuwe klasse reservoir ondergebracht, met reservoir als subklasse van Constructie.\

@RiX012 deze issue kan gesloten worden.

**Comment by RiX012** [comment]
@JochemMollema . `Reservoir`  zit nu onder `Bouwwerk` terwijl hierboven `Constructie` staat.

**Comment by JochemMollema** [comment]
We volgen hier de indeling die GWSW aanhoudt en hier is de bovenliggende voor de klasse Reservoir de  klasse Bouwwerk en niet Kunstwerk.

**Comment by RiX012** [comment]
> Koffers zijn onder de nieuwe klasse reservoir ondergebracht, met reservoir als subklasse van Constructie.\

Ok, dan geldt deze comment dus niet
