### ISSUE TITLE
QUDT URI zijn verkeerd

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#992]
In de tabel `refModel_Attributen` moet de kolom `URI` gewijzigd worden van gegevenstype Hyperlink naar `Lange tekst`.

Daarna moet uit alle QUDT URI's `/2.1` gehaald worden. Zodat deze hetzelfde is als bij Temperature

**Comment by JochemMollema** [comment]
aangepast

**Comment by RiX012** [comment]
Sorry Jochem, ik heb je verkeerd geinformeerd. Er moeten helemaal geen hastags staan. Dus in de aangepaste URI's moeten de hekjes allemaal er af.

**Comment by RiX012** [comment]
Fixed
