### ISSUE TITLE
Spelfout in tekenreeks

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/imbor#993]
URL: https://data.crow.nl/imbor/term/9c6de4ef-d45b-49d3-ad73-e2b2d5d3e2e3
GUID term: 9c6de4ef-d45b-49d3-ad73-e2b2d5d3e2e3

> IP-adres
> Internet Protocol adres: een unieke tekstenreeks voor elk apparaat op een netwerk.

"tekstenreeks" moet "tekenreeks" zijn.

**Comment by wjtmollema** [comment]
**Verwerking**
In de definitie van de term 'IP-adres' is het woord "tekstenreeks" gewijzigd naar "tekenreeks."

**Motivatie**
De melder wees terecht op een fout in de definitie. De fout is gerectificeerd.
