### ISSUE TITLE
Duiker heeft niet de klasse Holle leiding gekregen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#994]
Duiker heeft niet de klasse Holle leiding gekregen

**Comment by wjtmollema** [comment]
**Verwerking**
De klasse 'Duiker' is ondergebracht bij de klasse 'Holle leiding' in imborKern_K_KlassenChildParent en imborKern_Klassenindeling.

**Motivatie**
In de publicatieversie van IMBOR 2022 was der klasse 'Duiker' onterecht niet ingedeeld als kind van de klasse 'Holle leiding.' O.a. de gemeenten Almelo en Utrecht zijn praktijkvoorbeelden waar dit is opgemerkt.
