### ISSUE TITLE
Verschijningsvormen van een zebrapad (waaronder het regenboogpad) niet meer in IMBOR te vinden bij de wegmarkeringen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#995]
Verschijningsvormen van een zebrapad (waaronder het regenboogpad) niet meer in IMBOR te vinden bij de wegmarkeringen

**Comment by wjtmollema** [comment]
**Verwerking**
De term 'Regenboogzebrapad’ is  toegevoegd aan imborVocTermen en is als domeinwaarde aan het enumeratietype 'WegmarkeringMarkeringToepassing' toegevoegd.
De term ‘Zebrapad’ is toegevoegd aan imborVocTermen en gedefinieerd en is als domeinwaarde aan het enumeratietype 'WegmarkeringMarkeringToepassing' toegevoegd.

**Motivatie**
Regenboogzebrapaden en zebrapaden zijn onderscheiden maar veelvoorkomende toepassingen van Wegmarkeringen. Als zodanig is de toevoeging van deze domeinwaarden een waardevolle uitbreiding.
