### ISSUE TITLE
Raalte: graag Gereedschaprek als nieuw objecttype toevoegen

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#996]
Raalte: graag Gereedschaprek als nieuw objecttype toevoegen

**Comment by JochemMollema** [comment]
![20181130_134057_resized](https://user-images.githubusercontent.com/33116640/172042717-b757f43d-6bb7-4f9f-bafe-cc36ba5c1d9c.jpg)

**Comment by wjtmollema** [comment]
**Voorgestelde verwerking**
- Het toevoegen van het `ObjectType` `Gereedschapsrek` als `subKlasseVan` de klasse `Straatmeubilair`.

Er zijn voor de klasse `Gereedschapsrek` geen onderscheidende attributen voorgesteld. Ogenschijnlijk lijkt dit ook niet benodigd.
