### ISSUE TITLE
NEN3610 netwerk model toepassen voor topologie

### ISSUE THREAD

**Issue by RiX012** [Stichting-CROW/imbor#997]
Topologie is nu een beetje 'weggemoffeld' in IMBOR2022. De nieuwe NEN3610 heeft hier een uitwerken voor (8.5). Deze zouden we hier moeten toepassen.

**Comment by RiX012** [comment]
In de nieuwe versie van IMBOR gaan we het netwerkmodel van NEN3610 introduceren, hiervoor moeten we:

1. Herzien plek van topologische element (wellicht naast Reëel en Virtueel)
2. NEN3610 Netwerk::Node en Netwerk::Link als classes introduceren
3. Klassen hieronder introduceren als (zowel Links en Nodes) imbor:WegNode, imbor:WaterNode, imbor:RioolNode, etc. 
4. Edge en Link uit GWSW zijn dan te mappen op NEN3610 Link en Node
5. Overige onderdelen van wat nu topologische elementen zijn dan 'mappen' op die klassen

**Comment by RiX012** [comment]
Verwerken zoals voorgesteld. Maar ook voorleggen aan de softwareleveranciers.

**Comment by wjtmollema** [comment]
Wordt verwerkt zoals voorgesteld in https://github.com/Stichting-CROW/imbor/issues/997#issuecomment-1475937479. De issue blijft openstaan in afwachting van de volgende zaken:
1. Validatie door vertegenwoordigers van NEN 3610;
2. Afstemming met vertegenwoordigers van GWSW;
3. Feedback van softwareleveranciers;

**Comment by wjtmollema** [comment]
Na gesprek met @RiX012 vandaag is de indeling van verschijningsvormen van de `Topologische elementen` de volgende. Er wordt nader onderzocht wat de verdieping kan zijn voor `WegNode`, `WegLink` en `WaterNode`, `WaterLink`. Kandidaten hiervoor zijn `Wegas,` `Wegknoop` en `Waterloopas` etc.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Thomas/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Klasse1 | Klasse2 | ObjectType | type | type   gedetailleerd | type extra   gedetailleerd
-- | -- | -- | -- | -- | --
Topologisch   element | Netwerk::Link | RioleringLink | Buitengrens |   |  
Topologisch element | Netwerk::Link | RioleringLink | Deellineroriëntatie |   |  
Topologisch element | Netwerk::Link | RioleringLink | Kabeloriëntatie |   |  
Topologisch element | Netwerk::Link | RioleringLink | Verbinding | Leidingoriëntatie |  
Topologisch element | Netwerk::Link | RioleringLink | Verbinding | Onderdeeloriëntatie |  
Topologisch element | Netwerk::Link | WaterLink |   |   |  
Topologisch element | Netwerk::Link | WegLink |   |   |  
Topologisch element | Netwerk::Node | RioleringNode | Aansluitpunt | Lozingspunt | Lozingspunt   bodem
Topologisch element | Netwerk::Node | RioleringNode | Aansluitpunt | Lozingspunt | Lozingspunt   oppervlaktewater
Topologisch element | Netwerk::Node | RioleringNode | Aansluitpunt | Overnamepunt |  
Topologisch element | Netwerk::Node | RioleringNode | Aansluitpunt | Perceelaansluitpunt |  
Topologisch element | Netwerk::Node | RioleringNode | Aansluitpunt | Uitlaat   (punt) |  
Topologisch element | Netwerk::Node | RioleringNode | Appendage-oriëntatie |   |  
Topologisch element | Netwerk::Node | RioleringNode | Beginpunt   leiding |   |  
Topologisch element | Netwerk::Node | RioleringNode | Beginpunt   onderdeel |   |  
Topologisch element | Netwerk::Node | RioleringNode | Bouwwerkoriëntatie |   |  
Topologisch element | Netwerk::Node | RioleringNode | Compartimentoriëntatie |   |  
Topologisch element | Netwerk::Node | RioleringNode | Dekseloriëntatie |   |  
Topologisch element | Netwerk::Node | RioleringNode | Eindpunt   leiding |   |  
Topologisch element | Netwerk::Node | RioleringNode | Eindpunt   onderdeel |   |  
Topologisch element | Netwerk::Node | RioleringNode | Hulpstukoriëntatie |   |  
Topologisch element | Netwerk::Node | RioleringNode | Injectiepunt |   |  
Topologisch element | Netwerk::Node | RioleringNode | Maaiveldoriëntatie |   |  
Topologisch element | Netwerk::Node | RioleringNode | Meetpunt | Grondwatermeetpunt |  
Topologisch element | Netwerk::Node | RioleringNode | Meetpunt | Monsternamepunt |  
Topologisch element | Netwerk::Node | RioleringNode | Putoriëntatie |   |  
Topologisch element | Netwerk::Node | WaterNode |   |   |  
Topologisch element | Netwerk::Node | WegNode |   |   |  
Topologisch element | Representatie   fysiek object | Gebiedsoriëntatie |   |   |  
Topologisch element | Representatie   fysiek object | Hydraulisch   rioleringsmodel |   |   |  
Topologisch element | Representatie   fysiek object | Rioolstreng |   |   |  
Topologisch element | Representatie   fysiek object | Uitlaat |   |   |  



</body>

</html>

**Comment by wjtmollema** [comment]
**Corollarium**
Dit bericht presenteert mogelijke kandidaten uit `imbor:ObjectType` als typeringen voor `WegNode`, `WegLink`, `WaterNode` en `WaterLink`. Elke nominatie wordt voorzien van een _motivatie_. Nader overleg is benodigd om te bepalen of de voormalig `imwv:ObjectType`n (Aansluiting, Knooppunt, etc.) ook gemodelleerd zouden moeten worden als `Netwerk::Link` en `Netwerk::Node`.

**`WegNode`**
- `Wegknoop`
- `Spoorwegknoop`

**`WegLink`**
- `Wegas`
- `Spooras`

**`WaterNode`**
- ?

**`WaterLink`**
- `Waterloopas`:

**`Netwerk::Link`**
- `Profiellijn`

Dit bericht is onderhevig aan **werk in uitvoering**.

**Comment by wjtmollema** [comment]
**Addendum**
Een verificatiegesprek met de vertegenwoordigers van NEN 3610 (Paul Janssen en Wilko Quak) heeft uitgewezen dat op het niveau van de klassenovererving deze uitwerking op de goede weg is. Echter bleek wel dat omdat de NEN 3610 INSPIRE klassen letterlijk overneemt, dit feitelijk geen volwaardig onderdeel is van het NEN 3610 semantisch model. Dit betekent dat IMBOR, net zoals de NEN 3610 dat doet, facetten van het INSPIRE netwerkmodel concreet moet implementeren.

Dit betekent in ieder geval dat de volgende INSPIRE-klassen benodigd zijn:

- `NetworkElement`, met tenminste als eigenschappen `InspireId`/`identificatie`, `beginLifespanVersion` en `endLifespanVersion` , met als subklassen:

1. `Node`: met tenminste als eigenschappen `geometry`, `heeft 0 tot N spokeStarts` en `heeft 0 tot N spokeEnds` 
2. `Link`: met tenminste als eigenschappen  `geometry`, `fictitious`, `heeft 0 tot 1 startNodes` en `heeft 0 tot 1 endNodes` 

- `Network`: met tenminste als eigenschappen `objectnaam` en `bestaat uit 1 of meer NetworkElements`


Daarnaast moet dit in samenhang beoordeeld worden met de uitwerkingssuggestie voor de decompositie van een Wegennetwerk zoals die terug te vinden is in de NEN 2660-2. Zie onderstaande voorbeeld:
![image](https://github.com/Stichting-CROW/imbor/assets/90725038/d100168b-55b7-4ff6-8ce0-996e136dbcaa)

**Comment by RiX012** [comment]
Alles overwogen lijkt onderstaande (in diagram) het beste te passen. 
- In groen staat de invulling hoe GWSW2.0 het gedaan heeft. Dit moet besproken worden.
- `imbor:WegLink` en ` imbor:WegNode` zijn twee (voorbeeld) uitwerkingen. Alle topologische elementen uit [issuecomment-1500300563](https://github.com/Stichting-CROW/imbor/issues/997#issuecomment-1500300563) worden zulke specialisaties.
- De relaties (behalve `nen2660:isConnectedTo`) moeten worden opgenomen in de IMBOR beheeromgeving, maar zijn directe implementaties van de [INSPIRE RDF Vocabulary -- DRAFT](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies/blob/master/net/net.ttl) 

![IMBOR-Netwerkmodel drawio](https://github.com/Stichting-CROW/imbor/assets/56293445/51fb577f-588e-49e8-967a-6644eda3f672)

**Comment by MarinusVonhof** [comment]
Lijkt voor GWSW / IMBOR SW ook goed te passen:
<pre>
gwsw:Knooppunt rdfs:subClassOf net:Node . # het topologische element bij putten, uitlaatpunt, ...
gwsw:Verbinding rdfs:subClassOf net:Link . # het topologische element (met begin en eind) bij leidingen, pompen, ...
</pre>

Zie ook de praktijkvoorbeelden in query-vorm (GWSW 1.n), die worden toegepast voor hydraulische berekeningen:

**De knooppunten / nodes:**
https://github.com/StichtingRIONED/gwsw_queries/blob/main/apps/Hyd/Hyd_Knooppunt.rq

**De verbindingen / links:** (leidingen, doorlaten, pompen, wanden)
https://github.com/StichtingRIONED/gwsw_queries/blob/main/apps/Hyd/Hyd_Leiding.rq
https://github.com/StichtingRIONED/gwsw_queries/blob/main/apps/Hyd/Hyd_Doorlaat.rq

**Comment by wjtmollema** [comment]
In principe is het de bedoeling om deze issue eindelijk af te ronden. Wat volgens mij nog dient te gebeuren qua modeluitbreiden is het invoeren van de relevante INSPIRE-attributen voor `Network`, `Node` en `Link` (zie https://github.com/Stichting-CROW/imbor/issues/997#issuecomment-1611038893):

- `Node`: `geometrie`, `spokeStarts`, `spokeEnds`.
- `Link`: `geometrie`, `fictitious`, `startNodes`, `endNodes`.
- `Network`: `objectnaam`.

Voor de attributen `spokeStarts`, `spokeEnds`,  `startNodes` en `endNodes` kunnen ook semantische relaties worden gebruikt: subklasses van `is verbonden met`: `heeft als beginpunt` en `heeft als eindpunt`. Wellicht is dat meet NEN2660-2-proof. Wat denk jij @RiX012?

**Comment by wjtmollema** [comment]
IMBOR adopteert het INSPIRE-netwerkmodel vanwege het integratieadvies van de NEN 3610. Hierbij wordt gekozen voor en integratie waarvan de complexiteit minimaal is. In IMBOR worden alleen voor Water, Wegen en Riolering netwerkobjecten geïntroduceerd. Om deze reden worden de volgende klassen toegevoegd: `Netwerk::Node, Netwerk::Link, RioleringNode, RioleringLink, WaterNode, WaterLink en WegNode, WegLink`. GWSW zorgt voorde invulling van het attributenprofiel van RioleringNode en RioleringLink, in lijn met de huidige uitwerking van de klasse `Topologisch element`. Om `Netwerk::Node` met `Netwerk::Link` te kunnen verbinden, zijn de INSPIRE-eigenschappen	‘`spokeStart`’ en ‘`spokeEnd`’ overgenomen. Deze topologische relaties verbinden de subklassen van Links en Nodes, maar kunnen geen subklasse gemaakt worden van ‘`isVerbondenMet`’ omdat deze relatie een restrictie van `FysiekObject` tot` FysiekObject` heeft in de NEN2660-2. De multipliciteit van beide relaties wordt overgenomen uit de NEN 3610 appendix: 0-N. De overige algemene attributen die worden toegevoegd zijn ‘`geometrie`’ en (alleen voor Netwerk::Link) ‘`fictitious`’.

**Comment by wjtmollema** [comment]
Er wordt verzocht om deze issue, na een controle, te sluiten

**Comment by RiX012** [comment]
> 1. Wijzigingen lijken me goed, maar de modellering van `startNode` en `endNode` als subklassen van `nen2660:hasPart` roept wel een vraag op: Is dat semantisch correct? Als ik de definities in dezelfde relatie plaats, d.w.z. : 'The links that leave the node.'/The links that enter the node' --> 'A decomposition (hasPart) relation between concrete concepts.', kom ik tot de conclusie van niet. Een eigenschap die twee topologische objecten verbindt is niet een specifiekere vorm van een algemene decompositierelatie. Bedoel je in je bericht soms `nen2660:isConnectedTo`?

Nee. (Helaas) kan de `nen2660:isConnectedTo` alleen maar tussen FysiekeObjecten gelegd worden. De `nen2660:hasPart` zit hoger en geldt ook voor `nen2660:InformationObject`. Ik ben met je eens dat de semantiek te wensen overlaat. Maar ik zie wel dat hij 1) in te passen is, 2) in lijn is met GWSW en 3) het beste is wat we op dit moment hebben. 


> 2. Subpropertyrelatie aanmaken kan zeker, als we imborKern_Klassenindeling aanpassen. We kunnen ook een imborKern_Klassenindeling aanmaken voor eigenschappen, met het oog op de kwestie van de 'supereigenschappen', die ook relaties tussen eigenschappen betreft die ergens gemodelleerd moeten worden.

Ja we moeten inderdaad een variant van imborKern_Klassenindeling voor eigenschappen.

**Comment by wjtmollema** [comment]
Bespreekpunt: URI's van INSPIRE zijn op dit moment onbekend.

**Comment by wjtmollema** [comment]
imborKern_Hiërarchie en imborKern_HiërarchieElement vervangen vanaf nu imborKern_Klassenindeling en imborKern_Klassen.

Gecheckt moet worden of de module ParentsAndChilds nu ook nog naar behoren werkt. 

Push volgt.

**Comment by RiX012** [comment]
> Bespreekpunt: URI's van INSPIRE zijn op dit moment onbekend.

URI's hieruit herbruiken vooralsnog: https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies/blob/7dde22fde631409957a445f97af5868299f2330e/net/net.ttl#L60

**Comment by wjtmollema** [comment]
@RiX012 Een ding behoeft nog implementatie en dat is `Network`. 

Heb jij op basis van https://github.com/Stichting-CROW/imbor/issues/997#issuecomment-1620441226 hiervoor een voorschrift?

**Comment by RiX012** [comment]
> Thanks, maar dit werkt slechts gedeeltelijk., want net:Link.endNode en net:Link.startNode hebben daar geen URI. Mapping beperken tot net:Link en net:Node?

Dat is toch:
`http://inspire.ec.europa.eu/ont/net#Link.endNode`
`http://inspire.ec.europa.eu/ont/net#Link.startNode`
en 
`http://inspire.ec.europa.eu/ont/net#Link`
`http://inspire.ec.europa.eu/ont/net#Node`



> @RiX012 Een ding behoeft nog implementatie en dat is `Network`.
> 
> Heb jij op basis van [#997 (comment)](https://github.com/Stichting-CROW/imbor/issues/997#issuecomment-1620441226) hiervoor een voorschrift?

NetwerkNode en NetwerkLink zijn onderdelen, dus `nen2660:hasPart` (Networkelements) van een Netwerk

**Comment by wjtmollema** [comment]
Actie: controle door @RiX012 en daarna definitief afsluiten.

**Comment by RiX012** [comment]
- NEN3610:2022 hoofdstuk 8.5
- Nieuwe semantische relatie
- Aantal klassen worden ergens anders onder gehangen
- Scheiding tussen Fysiek, Ruimtelijk en Topologisch

Mogelijke impact:

- Leverancier zal de NEN3610:2022 moeten implementeren
- Meer samenhang met andere NEN3610 modellen
