### ISSUE TITLE
Minimale dataset wegbeheersystematiek: voeglengte alleen bij betonverharding

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#998]
Minimale dataset wegbeheersystematiek: voeglengte alleen bij betonverharding

**Comment by wjtmollema** [comment]
**Verwerking**
Het attribuut 'lengte van voegen' is voor de objecttypes 'Kunststofverharding,' 'Halfverharding,' 'Onverhard,' 'Asfaltverharding' en 'Elementenverharding' verwijderd uit het overzicht met de minimale dataset voor de Wegbeheersystematiek 2019.

**Motivatie**
De melding betreft een fout in de publicatieversie van IMBOR 2022. Het attribuut 'lengte van voegen' is niet van toepassing voor de klassen Kunststofverharding,' 'Halfverharding,' 'Onverhard,' 'Asfaltverharding' en 'Elementenverharding.' De fout is gerectificeerd.
