### ISSUE TITLE
Gebiedstypes: lijst aanvullen met waarden die voor andere doeleinden dan de CROW systematiek gebruikt worden

### ISSUE THREAD

**Issue by JochemMollema** [Stichting-CROW/imbor#999]
Gebiedstypes: lijst aanvullen met waarden die voor andere doeleinden dan de CROW systematiek gebruikt worden

**Comment by wjtmollema** [comment]
Dit is een oplossing in lijn met de inmiddels vervallen modelleringsmethode. Er wordt om toestemming verzocht deze issue te sluiten.
